import pytest

from taxi_sm_monitor.api import youscan


@pytest.mark.config(YOUSCAN_TO_STARTRACK_ENABLED=True)
@pytest.mark.parametrize(
    'data',
    (
        # Пост
        {
            'author': {
                'avatarUrl': 'https://userapi.com/PSplRx50_7I.jpg?ava=1',
                'name': 'Таксопарк РВК',
                'nickname': 'taxoparkrbk',
                'subscribers': 1205,
                'url': 'http://vk.com/club185605318',
            },
            'channel': {
                'avatarUrl': 'https://userapi.com/PSplRx50_7I.jpg?ava=1',
                'name': 'Таксопарк РВК',
                'nickname': 'taxoparkrbk',
                'subscribers': 1205,
                'url': 'http://vk.com/club185605318',
            },
            'comments': 0,
            'country': 'ru',
            'discussionId': '-185605318_50',
            'engagement': 0,
            'imageUrl': 'https://userapi.com//a657/SOIK8ZU-fHg.jpg',
            'language': 'rus',
            'likes': 0,
            'mentionId': 42095240,
            'postId': '-185605318_50',
            'postType': 'post',
            'published': '2019-10-14T20:57:19Z',
            'reposts': 0,
            'resourceType': 'social',
            'sentiment': 'neutral',
            'sourceName': 'vk.com',
            'spam': False,
            'text': 'Подключение <b>водителей</b> к <b>таксометру</b> сервиса',
            'themeId': 83499,
            'themeName': 'Yandex.Taxi Водители',
            'topicId': 83499,
            'topicName': 'Yandex.Taxi Водители',
            'topicGroup': 'taxi',
            'url': 'https://vk.com/wall-185605318_50',
        },
        # Репост
        {
            'author': {
                'avatarUrl': 'https://userapi.com/1E9_2MhghRk.jpg?ava=1',
                'name': 'Не дорогая обувь, СПб- Ленсоветовский',
                'subscribers': 740,
                'url': 'http://vk.com/club112889249',
            },
            'channel': {
                'avatarUrl': 'https://userapi.com/75163/1E9_2MhghRk.jpg?ava=1',
                'name': 'Не дорогая обувь, СПб- Ленсоветовский',
                'subscribers': 740,
                'url': 'http://vk.com/club112889249',
            },
            'city': 'Санкт-Петербург',
            'comments': 0,
            'country': 'ru',
            'discussionId': '-112889249_6790',
            'engagement': 0,
            'imageUrl': 'https://userapi.com/1ea755/R7qM7ZIVISc.jpg',
            'language': 'rus',
            'likes': 0,
            'mentionId': 10486558,
            'parentPostId': '-31639826_20263',
            'postId': '-112889249_6790',
            'postType': 'repost',
            'published': '2019-10-14T20:52:57Z',
            'region': 'Санкт-Петербург',
            'reposts': 0,
            'resourceType': 'social',
            'sentiment': 'neutral',
            'sourceName': 'vk.com',
            'spam': False,
            'text': 'Пpиглaшаем oтвeтcтвенныx водитeлей для paботы в такси.🚕',
            'themeId': 83499,
            'themeName': 'Yandex.Taxi Водители',
            'topicId': 83499,
            'topicName': 'Yandex.Taxi Водители',
            'topicGroup': 'taxi',
            'url': 'https://vk.com/wall-112889249_6790',
        },
        # Дополненый репост
        {
            'author': {
                'avatarUrl': 'https://userapi.com/UWQXkmXQWfE.jpg?ava=1',
                'name': 'Михаил Янтарный',
                'nickname': 'mishan1',
                'subscribers': 390,
                'url': 'http://vk.com/id548966252',
            },
            'channel': {
                'avatarUrl': 'https://userapi.com/UWQXkmXQWfE.jpg?ava=1',
                'name': 'Михаил Янтарный',
                'nickname': 'mishan1',
                'subscribers': 390,
                'url': 'http://vk.com/id548966252',
            },
            'city': 'Калининград',
            'comments': 0,
            'country': 'ru',
            'discussionId': '548966252_117',
            'engagement': 1,
            'imageUrl': 'https://userapi.com/tl0Ws4Pilyw.jpg',
            'language': 'rus',
            'likes': 1,
            'mentionId': 3500374732,
            'parentPostId': '-183877134_55',
            'postId': '548966252_117',
            'postType': 'extendedRepost',
            'published': '2019-10-14T18:26:49Z',
            'region': 'Калининградская область',
            'reposts': 0,
            'resourceType': 'social',
            'sentiment': 'neutral',
            'sourceName': 'vk.com',
            'spam': False,
            'text': 'Ставим ❤️, подписываемся на мой YouTube канал',
            'themeId': 83499,
            'themeName': 'Yandex.Taxi Водители',
            'topicId': 83499,
            'topicName': 'Yandex.Taxi Водители',
            'topicGroup': 'taxi',
            'url': 'https://vk.com/wall548966252_117',
        },
        # Комментарий
        {
            'author': {
                'avatarUrl': 'https://userapi.com/fpcuYGNuCOM.jpg?ava=1',
                'name': 'Наталья Копылова',
                'subscribers': 529,
                'url': 'http://vk.com/id232262635',
            },
            'channel': {
                'avatarUrl': 'https://userapi.com/b7RK-kzR7VM.jpg?ava=1',
                'name': 'Плохая Покупка | Город Орел',
                'nickname': 'bad_57',
                'subscribers': 60034,
                'url': 'http://vk.com/club86168582',
            },
            'city': 'Орёл',
            'country': 'ru',
            'discussionId': '-86168582_839156',
            'engagement': 0,
            'language': 'rus',
            'likes': 0,
            'mentionId': 1314691101,
            'parentPostId': '-86168582_839156',
            'postId': '-86168582_839238',
            'postType': 'comment',
            'published': '2019-10-14T20:59:41Z',
            'region': 'Орловская область',
            'resourceType': 'social',
            'sentiment': 'neutral',
            'sourceName': 'vk.com',
            'spam': False,
            'text': 'Не знаю, постоянно пользуюсь этим такси',
            'themeId': 83499,
            'themeName': 'Yandex.Taxi Водители',
            'title': '<b>Яндекс</b> <b>такси</b>. <b>Водитель</b> отказался',
            'topicId': 83499,
            'topicName': 'Yandex.Taxi Водители',
            'topicGroup': 'taxi',
            'url': 'https://vk.com/wall-86168582_839156?reply=839238',
        },
        # Комментарий к реплаю
        {
            'city': 'Орёл',
            'country': 'ru',
            'discussionId': '-86168582_839156',
            'engagement': 0,
            'language': 'rus',
            'likes': 0,
            'mentionId': 1314691101,
            'parentPostId': '-86168582_839156',
            'postId': '-86168582_839238',
            'postType': 'replyComment',
            'published': '2019-10-14T20:59:41Z',
            'region': 'Орловская область',
            'resourceType': 'social',
            'sentiment': 'neutral',
            'sourceName': 'vk.com',
            'spam': False,
            'text': 'Не знаю, постоянно пользуюсь этим такси',
            'themeId': 83499,
            'themeName': 'Yandex.Taxi Водители',
            'title': '<b>Яндекс</b> <b>такси</b>. <b>Водитель</b> отказался',
            'topicId': 83499,
            'topicName': 'Yandex.Taxi Водители',
            'topicGroup': 'taxi',
            'url': 'https://vk.com/wall-86168582_839156?reply=839238',
        },
    ),
)
async def test_validate_mention_success(taxi_sm_monitor_app_stq, data: dict):
    assert taxi_sm_monitor_app_stq.ticket_manager.validate_mention(data)


@pytest.mark.parametrize(
    'data',
    (
        {},
        {
            'mentionId': 42095240,
            'published': '2019-10-14T20:57:19Z',
            'resourceType': 'social',
            'topicId': 83499,
            'topicName': 'Yandex.Taxi Водители',
            'topicGroup': 'taxi',
            'url': 'https://vk.com/wall-185605318_50',
        },
        {
            'mentionId': 42095240,
            'postType': 'post',
            'published': 'undefined',
            'resourceType': 'social',
            'spam': False,
            'topicId': 83499,
            'topicName': 'Yandex.Taxi Водители',
            'topicGroup': 'eats',
            'url': 'https://vk.com/wall-185605318_50',
        },
    ),
)
async def test_validate_mention_error(taxi_sm_monitor_app_stq, data: dict):
    with pytest.raises(youscan.MentionValidationError):
        taxi_sm_monitor_app_stq.ticket_manager.validate_mention(data)
