import os


TUS_OAUTH_TOKEN_FOR_TESTS = os.environ.get('TUS_OAUTH_TOKEN_FOR_TESTS', 'AQAD-qJSJqGKAAAcfveD_uD2rk95s-uDHkXGAU0')
LOGIN_FOR_OAUTH_TOKEN = 'gladnik'

TUS_OAUTH_TOKEN_FOR_USER_WITH_NO_ACCESS_TO_DEFAULT_CONSUMER = os.environ.get(
    'TUS_OAUTH_TOKEN_FOR_USER_WITH_NO_ACCESS_TO_DEFAULT_CONSUMER', ''
)
TUS_ENVIRONMENT_FOR_TESTS = 'PROD'
PASSPORT_ENVIRONMENT_FOR_TESTS = 'TEST'

DEFAULT_TUS_CONSUMER_FOR_TESTS = 'kopusha'
NON_DEFAULT_TUS_CONSUMER_FOR_TESTS = 'tus-tests-other'
TUS_HOST_FOR_TESTS = 'tus.yandex-team.ru'
