// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	madm "a.yandex-team.ru/portal/avocado/libs/utils/madm/v2"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Arg is an autogenerated mock type for the Arg type
type Arg struct {
	mock.Mock
}

// Execute provides a mock function with given fields: c
func (_m *Arg) Execute(c *madm.ArgsConfig) {
	_m.Called(c)
}

// NewArg creates a new instance of Arg. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewArg(t testing.TB) *Arg {
	mock := &Arg{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
