// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BytesParser is an autogenerated mock type for the BytesParser type
type BytesParser struct {
	mock.Mock
}

// ParseMADMBytes provides a mock function with given fields: b
func (_m *BytesParser) ParseMADMBytes(b []byte) error {
	ret := _m.Called(b)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
