// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "a.yandex-team.ru/portal/avocado/libs/utils/base/models"
	mock "github.com/stretchr/testify/mock"
)

// cspGetter is an autogenerated mock type for the cspGetter type
type cspGetter struct {
	mock.Mock
}

// GetCSP provides a mock function with given fields:
func (_m *cspGetter) GetCSP() models.CSP {
	ret := _m.Called()

	var r0 models.CSP
	if rf, ok := ret.Get(0).(func() models.CSP); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.CSP)
	}

	return r0
}

type mockConstructorTestingTnewCspGetter interface {
	mock.TestingT
	Cleanup(func())
}

// newCspGetter creates a new instance of cspGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newCspGetter(t mockConstructorTestingTnewCspGetter) *cspGetter {
	mock := &cspGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
