// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	models "a.yandex-team.ru/portal/avocado/libs/utils/base/models"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// geoGetter is an autogenerated mock type for the geoGetter type
type geoGetter struct {
	mock.Mock
}

// GetGeo provides a mock function with given fields:
func (_m *geoGetter) GetGeo() models.Geo {
	ret := _m.Called()

	var r0 models.Geo
	if rf, ok := ret.Get(0).(func() models.Geo); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Geo)
	}

	return r0
}

// newGeoGetter creates a new instance of geoGetter. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func newGeoGetter(t testing.TB) *geoGetter {
	mock := &geoGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
