// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	geobase "a.yandex-team.ru/library/go/yandex/geobase"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// geoBase is an autogenerated mock type for the geoBase type
type geoBase struct {
	mock.Mock
}

// GetParentsIDsDef provides a mock function with given fields: id
func (_m *geoBase) GetParentsIDsDef(id geobase.ID) ([]geobase.ID, error) {
	ret := _m.Called(id)

	var r0 []geobase.ID
	if rf, ok := ret.Get(0).(func(geobase.ID) []geobase.ID); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]geobase.ID)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(geobase.ID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newGeoBase creates a new instance of geoBase. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func newGeoBase(t testing.TB) *geoBase {
	mock := &geoBase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
