// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	models "a.yandex-team.ru/portal/avocado/libs/utils/base/models"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// localeGetter is an autogenerated mock type for the localeGetter type
type localeGetter struct {
	mock.Mock
}

// GetLocale provides a mock function with given fields:
func (_m *localeGetter) GetLocale() models.Locale {
	ret := _m.Called()

	var r0 models.Locale
	if rf, ok := ret.Get(0).(func() models.Locale); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Locale)
	}

	return r0
}

// newLocaleGetter creates a new instance of localeGetter. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func newLocaleGetter(t testing.TB) *localeGetter {
	mock := &localeGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
