// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	morda_data "a.yandex-team.ru/portal/avocado/proto/morda_data"
	mock "github.com/stretchr/testify/mock"
)

// LocaleKeeper is an autogenerated mock type for the LocaleKeeper type
type LocaleKeeper struct {
	mock.Mock
}

// GetLocale provides a mock function with given fields:
func (_m *LocaleKeeper) GetLocale() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLocaleIfUpdated provides a mock function with given fields:
func (_m *LocaleKeeper) GetLocaleIfUpdated() *morda_data.Lang {
	ret := _m.Called()

	var r0 *morda_data.Lang
	if rf, ok := ret.Get(0).(func() *morda_data.Lang); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*morda_data.Lang)
		}
	}

	return r0
}
