// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	log3 "a.yandex-team.ru/portal/avocado/libs/utils/log3"
	mock "github.com/stretchr/testify/mock"
)

// Log3Getter is an autogenerated mock type for the Log3Getter type
type Log3Getter struct {
	mock.Mock
}

// GetLogger provides a mock function with given fields:
func (_m *Log3Getter) GetLogger() log3.LoggerAlterable {
	ret := _m.Called()

	var r0 log3.LoggerAlterable
	if rf, ok := ret.Get(0).(func() log3.LoggerAlterable); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log3.LoggerAlterable)
		}
	}

	return r0
}
