// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	exports "a.yandex-team.ru/portal/avocado/morda-go/pkg/exports"
	mock "github.com/stretchr/testify/mock"
)

// madmOptionsGetter is an autogenerated mock type for the madmOptionsGetter type
type madmOptionsGetter struct {
	mock.Mock
}

// GetMadmOptions provides a mock function with given fields:
func (_m *madmOptionsGetter) GetMadmOptions() exports.Options {
	ret := _m.Called()

	var r0 exports.Options
	if rf, ok := ret.Get(0).(func() exports.Options); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(exports.Options)
	}

	return r0
}

type mockConstructorTestingTnewMadmOptionsGetter interface {
	mock.TestingT
	Cleanup(func())
}

// newMadmOptionsGetter creates a new instance of madmOptionsGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMadmOptionsGetter(t mockConstructorTestingTnewMadmOptionsGetter) *madmOptionsGetter {
	mock := &madmOptionsGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
