// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	models "a.yandex-team.ru/portal/avocado/libs/utils/base/models"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// madmContentGetter is an autogenerated mock type for the madmContentGetter type
type madmContentGetter struct {
	mock.Mock
}

// GetMadmContent provides a mock function with given fields:
func (_m *madmContentGetter) GetMadmContent() models.MadmContent {
	ret := _m.Called()

	var r0 models.MadmContent
	if rf, ok := ret.Get(0).(func() models.MadmContent); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.MadmContent)
	}

	return r0
}

// newMadmContentGetter creates a new instance of madmContentGetter. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func newMadmContentGetter(t testing.TB) *madmContentGetter {
	mock := &madmContentGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
