// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "a.yandex-team.ru/portal/avocado/libs/utils/base/models"
	mock "github.com/stretchr/testify/mock"
)

// mordaContentGetter is an autogenerated mock type for the mordaContentGetter type
type mordaContentGetter struct {
	mock.Mock
}

// GetMordaContent provides a mock function with given fields:
func (_m *mordaContentGetter) GetMordaContent() models.MordaContent {
	ret := _m.Called()

	var r0 models.MordaContent
	if rf, ok := ret.Get(0).(func() models.MordaContent); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.MordaContent)
	}

	return r0
}

type mockConstructorTestingTnewMordaContentGetter interface {
	mock.TestingT
	Cleanup(func())
}

// newMordaContentGetter creates a new instance of mordaContentGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMordaContentGetter(t mockConstructorTestingTnewMordaContentGetter) *mordaContentGetter {
	mock := &mordaContentGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
