// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	its "a.yandex-team.ru/portal/avocado/morda-go/pkg/its"
	mock "github.com/stretchr/testify/mock"
)

// OptionsGetter is an autogenerated mock type for the OptionsGetter type
type OptionsGetter struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *OptionsGetter) Get() its.Options {
	ret := _m.Called()

	var r0 its.Options
	if rf, ok := ret.Get(0).(func() its.Options); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(its.Options)
	}

	return r0
}
