// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// OptionsKeeper is an autogenerated mock type for the OptionsKeeper type
type OptionsKeeper struct {
	mock.Mock
}

// GetData provides a mock function with given fields:
func (_m *OptionsKeeper) GetData() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// NewOptionsKeeper creates a new instance of OptionsKeeper. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewOptionsKeeper(t testing.TB) *OptionsKeeper {
	mock := &OptionsKeeper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
