// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "a.yandex-team.ru/portal/avocado/libs/utils/base/models"
	mock "github.com/stretchr/testify/mock"
)

// originRequestGetter is an autogenerated mock type for the originRequestGetter type
type originRequestGetter struct {
	mock.Mock
}

// GetOriginRequest provides a mock function with given fields:
func (_m *originRequestGetter) GetOriginRequest() (*models.OriginRequest, error) {
	ret := _m.Called()

	var r0 *models.OriginRequest
	if rf, ok := ret.Get(0).(func() *models.OriginRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OriginRequest)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewOriginRequestGetter interface {
	mock.TestingT
	Cleanup(func())
}

// newOriginRequestGetter creates a new instance of originRequestGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newOriginRequestGetter(t mockConstructorTestingTnewOriginRequestGetter) *originRequestGetter {
	mock := &originRequestGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
