// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	log3 "a.yandex-team.ru/portal/avocado/libs/utils/log3"
	exports "a.yandex-team.ru/portal/avocado/morda-go/pkg/exports"

	mock "github.com/stretchr/testify/mock"

	models "a.yandex-team.ru/portal/avocado/libs/utils/base/models"
)

// SuperBase is an autogenerated mock type for the SuperBase type
type SuperBase struct {
	mock.Mock
}

// CleanABFlags provides a mock function with given fields:
func (_m *SuperBase) CleanABFlags() {
	_m.Called()
}

// CleanLocale provides a mock function with given fields:
func (_m *SuperBase) CleanLocale() {
	_m.Called()
}

// CleanMordaZone provides a mock function with given fields:
func (_m *SuperBase) CleanMordaZone() {
	_m.Called()
}

// CleanTime provides a mock function with given fields:
func (_m *SuperBase) CleanTime() {
	_m.Called()
}

// ForceABFlags provides a mock function with given fields: _a0
func (_m *SuperBase) ForceABFlags(_a0 models.ABFlags) {
	_m.Called(_a0)
}

// ForceAuth provides a mock function with given fields: _a0
func (_m *SuperBase) ForceAuth(_a0 models.Auth) {
	_m.Called(_a0)
}

// ForceBigB provides a mock function with given fields: _a0
func (_m *SuperBase) ForceBigB(_a0 models.BigB) {
	_m.Called(_a0)
}

// ForceClid provides a mock function with given fields: _a0
func (_m *SuperBase) ForceClid(_a0 models.Clid) {
	_m.Called(_a0)
}

// ForceDevice provides a mock function with given fields: _a0
func (_m *SuperBase) ForceDevice(_a0 models.Device) {
	_m.Called(_a0)
}

// ForceGeo provides a mock function with given fields: _a0
func (_m *SuperBase) ForceGeo(_a0 models.Geo) {
	_m.Called(_a0)
}

// ForceLocale provides a mock function with given fields: _a0
func (_m *SuperBase) ForceLocale(_a0 models.Locale) {
	_m.Called(_a0)
}

// ForceMordaContent provides a mock function with given fields: _a0
func (_m *SuperBase) ForceMordaContent(_a0 models.MordaContent) {
	_m.Called(_a0)
}

// ForceMordaZone provides a mock function with given fields: _a0
func (_m *SuperBase) ForceMordaZone(_a0 models.MordaZone) {
	_m.Called(_a0)
}

// ForceYabs provides a mock function with given fields: _a0
func (_m *SuperBase) ForceYabs(_a0 models.Yabs) {
	_m.Called(_a0)
}

// ForceYandexUID provides a mock function with given fields: _a0
func (_m *SuperBase) ForceYandexUID(_a0 string) {
	_m.Called(_a0)
}

// GetAADB provides a mock function with given fields:
func (_m *SuperBase) GetAADB() models.AADB {
	ret := _m.Called()

	var r0 models.AADB
	if rf, ok := ret.Get(0).(func() models.AADB); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.AADB)
	}

	return r0
}

// GetAppInfo provides a mock function with given fields:
func (_m *SuperBase) GetAppInfo() models.AppInfo {
	ret := _m.Called()

	var r0 models.AppInfo
	if rf, ok := ret.Get(0).(func() models.AppInfo); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.AppInfo)
	}

	return r0
}

// GetAuth provides a mock function with given fields:
func (_m *SuperBase) GetAuth() models.Auth {
	ret := _m.Called()

	var r0 models.Auth
	if rf, ok := ret.Get(0).(func() models.Auth); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Auth)
	}

	return r0
}

// GetAuthOrErr provides a mock function with given fields:
func (_m *SuperBase) GetAuthOrErr() (models.Auth, error) {
	ret := _m.Called()

	var r0 models.Auth
	if rf, ok := ret.Get(0).(func() models.Auth); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Auth)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBigB provides a mock function with given fields:
func (_m *SuperBase) GetBigB() models.BigB {
	ret := _m.Called()

	var r0 models.BigB
	if rf, ok := ret.Get(0).(func() models.BigB); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.BigB)
	}

	return r0
}

// GetBigBOrErr provides a mock function with given fields:
func (_m *SuperBase) GetBigBOrErr() (models.BigB, error) {
	ret := _m.Called()

	var r0 models.BigB
	if rf, ok := ret.Get(0).(func() models.BigB); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.BigB)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCSP provides a mock function with given fields:
func (_m *SuperBase) GetCSP() models.CSP {
	ret := _m.Called()

	var r0 models.CSP
	if rf, ok := ret.Get(0).(func() models.CSP); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.CSP)
	}

	return r0
}

// GetClid provides a mock function with given fields:
func (_m *SuperBase) GetClid() models.Clid {
	ret := _m.Called()

	var r0 models.Clid
	if rf, ok := ret.Get(0).(func() models.Clid); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Clid)
	}

	return r0
}

// GetCookie provides a mock function with given fields:
func (_m *SuperBase) GetCookie() models.Cookie {
	ret := _m.Called()

	var r0 models.Cookie
	if rf, ok := ret.Get(0).(func() models.Cookie); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Cookie)
	}

	return r0
}

// GetDevice provides a mock function with given fields:
func (_m *SuperBase) GetDevice() models.Device {
	ret := _m.Called()

	var r0 models.Device
	if rf, ok := ret.Get(0).(func() models.Device); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Device)
	}

	return r0
}

// GetDeviceOrErr provides a mock function with given fields:
func (_m *SuperBase) GetDeviceOrErr() (models.Device, error) {
	ret := _m.Called()

	var r0 models.Device
	if rf, ok := ret.Get(0).(func() models.Device); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Device)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFlags provides a mock function with given fields:
func (_m *SuperBase) GetFlags() models.ABFlags {
	ret := _m.Called()

	var r0 models.ABFlags
	if rf, ok := ret.Get(0).(func() models.ABFlags); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.ABFlags)
	}

	return r0
}

// GetFlagsOrErr provides a mock function with given fields:
func (_m *SuperBase) GetFlagsOrErr() (models.ABFlags, error) {
	ret := _m.Called()

	var r0 models.ABFlags
	if rf, ok := ret.Get(0).(func() models.ABFlags); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.ABFlags)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGeo provides a mock function with given fields:
func (_m *SuperBase) GetGeo() models.Geo {
	ret := _m.Called()

	var r0 models.Geo
	if rf, ok := ret.Get(0).(func() models.Geo); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Geo)
	}

	return r0
}

// GetGeoOrErr provides a mock function with given fields:
func (_m *SuperBase) GetGeoOrErr() (models.Geo, error) {
	ret := _m.Called()

	var r0 models.Geo
	if rf, ok := ret.Get(0).(func() models.Geo); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Geo)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLocale provides a mock function with given fields:
func (_m *SuperBase) GetLocale() models.Locale {
	ret := _m.Called()

	var r0 models.Locale
	if rf, ok := ret.Get(0).(func() models.Locale); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Locale)
	}

	return r0
}

// GetLogger provides a mock function with given fields:
func (_m *SuperBase) GetLogger() log3.LoggerAlterable {
	ret := _m.Called()

	var r0 log3.LoggerAlterable
	if rf, ok := ret.Get(0).(func() log3.LoggerAlterable); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log3.LoggerAlterable)
		}
	}

	return r0
}

// GetMadmContent provides a mock function with given fields:
func (_m *SuperBase) GetMadmContent() models.MadmContent {
	ret := _m.Called()

	var r0 models.MadmContent
	if rf, ok := ret.Get(0).(func() models.MadmContent); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.MadmContent)
	}

	return r0
}

// GetMadmOptions provides a mock function with given fields:
func (_m *SuperBase) GetMadmOptions() exports.Options {
	ret := _m.Called()

	var r0 exports.Options
	if rf, ok := ret.Get(0).(func() exports.Options); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(exports.Options)
	}

	return r0
}

// GetMordaContent provides a mock function with given fields:
func (_m *SuperBase) GetMordaContent() models.MordaContent {
	ret := _m.Called()

	var r0 models.MordaContent
	if rf, ok := ret.Get(0).(func() models.MordaContent); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.MordaContent)
	}

	return r0
}

// GetMordaZone provides a mock function with given fields:
func (_m *SuperBase) GetMordaZone() models.MordaZone {
	ret := _m.Called()

	var r0 models.MordaZone
	if rf, ok := ret.Get(0).(func() models.MordaZone); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.MordaZone)
	}

	return r0
}

// GetOriginRequest provides a mock function with given fields:
func (_m *SuperBase) GetOriginRequest() (*models.OriginRequest, error) {
	ret := _m.Called()

	var r0 *models.OriginRequest
	if rf, ok := ret.Get(0).(func() *models.OriginRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OriginRequest)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRequest provides a mock function with given fields:
func (_m *SuperBase) GetRequest() models.Request {
	ret := _m.Called()

	var r0 models.Request
	if rf, ok := ret.Get(0).(func() models.Request); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Request)
	}

	return r0
}

// GetTime provides a mock function with given fields:
func (_m *SuperBase) GetTime() *models.TimeData {
	ret := _m.Called()

	var r0 *models.TimeData
	if rf, ok := ret.Get(0).(func() *models.TimeData); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TimeData)
		}
	}

	return r0
}

// GetYaCookies provides a mock function with given fields:
func (_m *SuperBase) GetYaCookies() models.YaCookies {
	ret := _m.Called()

	var r0 models.YaCookies
	if rf, ok := ret.Get(0).(func() models.YaCookies); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.YaCookies)
	}

	return r0
}

// GetYaCookiesOrErr provides a mock function with given fields:
func (_m *SuperBase) GetYaCookiesOrErr() (models.YaCookies, error) {
	ret := _m.Called()

	var r0 models.YaCookies
	if rf, ok := ret.Get(0).(func() models.YaCookies); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.YaCookies)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetYabs provides a mock function with given fields:
func (_m *SuperBase) GetYabs() models.Yabs {
	ret := _m.Called()

	var r0 models.Yabs
	if rf, ok := ret.Get(0).(func() models.Yabs); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Yabs)
	}

	return r0
}

// GetYabsOrErr provides a mock function with given fields:
func (_m *SuperBase) GetYabsOrErr() (models.Yabs, error) {
	ret := _m.Called()

	var r0 models.Yabs
	if rf, ok := ret.Get(0).(func() models.Yabs); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Yabs)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsSID669ByAuth provides a mock function with given fields:
func (_m *SuperBase) IsSID669ByAuth() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetIsStaffLogin provides a mock function with given fields:
func (_m *SuperBase) SetIsStaffLogin() {
	_m.Called()
}

// SyncTime provides a mock function with given fields: _a0
func (_m *SuperBase) SyncTime(_a0 int64) {
	_m.Called(_a0)
}

// WarmCache provides a mock function with given fields:
func (_m *SuperBase) WarmCache() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewSuperBase interface {
	mock.TestingT
	Cleanup(func())
}

// NewSuperBase creates a new instance of SuperBase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSuperBase(t mockConstructorTestingTNewSuperBase) *SuperBase {
	mock := &SuperBase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
