// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	madm "a.yandex-team.ru/portal/avocado/libs/utils/madm"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// WeatherSettings is an autogenerated mock type for the WeatherSettings type
type WeatherSettings struct {
	mock.Mock
}

// GetByWeatherType provides a mock function with given fields: weatherType
func (_m *WeatherSettings) GetByWeatherType(weatherType string) *madm.WeatherSettingsEntry {
	ret := _m.Called(weatherType)

	var r0 *madm.WeatherSettingsEntry
	if rf, ok := ret.Get(0).(func(string) *madm.WeatherSettingsEntry); ok {
		r0 = rf(weatherType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*madm.WeatherSettingsEntry)
		}
	}

	return r0
}

// NewWeatherSettings creates a new instance of WeatherSettings. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewWeatherSettings(t testing.TB) *WeatherSettings {
	mock := &WeatherSettings{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
