INSERT INTO "document_templator"."template_groups" (id,
                                                    name,
                                                    description,
                                                    parent_id)
VALUES ('000000000000000000000001',
        'main',
        NULL,
        NULL),
       ('000000000000000000000002',
        'sub main',
        'description sub main',
        '000000000000000000000001'),
       ('000000000000000000000003',
        'sub sub main',
        'description sub sub main',
        '000000000000000000000002'),
       ('000000000000000000000004',
        'sub sub main with document',
        'description sub sub main with document',
        '000000000000000000000002');

INSERT INTO "document_templator"."dynamic_document_groups" (id,
                                                            name,
                                                            description,
                                                            parent_id)
VALUES ('000000000000000000000001',
        'main',
        NULL,
        NULL),
       ('000000000000000000000002',
        'sub main',
        'description sub main',
        '000000000000000000000001'),
       ('000000000000000000000003',
        'sub sub main',
        'description sub sub main',
        '000000000000000000000002'),
       ('000000000000000000000004',
        'sub sub main with document',
        'description sub sub main with document',
        '000000000000000000000002');

INSERT INTO "document_templator"."templates" (id,
                                              version,
                                              dependencies,
                                              base_template_id,
                                              name,
                                              description,
                                              group_id,
                                              css_style,
                                              created_by,
                                              created_at,
                                              modified_by,
                                              modified_at,
                                              params,
                                              param_settings,
                                              items,
                                              item_settings,
                                              requests,
                                              request_settings,
                                              enumerators)
VALUES ('000000000000000000000101',
        1,
        NULL,
        NULL,
        'main template',
        'main template',
        '000000000000000000000004',
        NULL,
        'robot',
        '2018-07-01T00:00:00+03:00',
        'robot',
        '2018-07-01T01:00:00+03:00',
        '[]'::JSONB,
        '[]'::JSONB,
        NULL,
        '[]'::JSONB,
        '[]'::JSONB,
        '[]'::JSONB,
        '[]'::JSONB);

INSERT INTO "document_templator"."templates" (id,
                                              version,
                                              dependencies,
                                              base_template_id,
                                              name,
                                              description,
                                              group_id,
                                              css_style,
                                              created_by,
                                              created_at,
                                              modified_by,
                                              modified_at,
                                              params,
                                              param_settings,
                                              items,
                                              item_settings,
                                              requests,
                                              request_settings,
                                              enumerators)
VALUES ('5ff4901c583745e089e55be1',
        1,
        NULL,
        NULL,
        'template',
        'template',
        NULL,
        NULL,
        'robot',
        '2019-12-01T01:00:00+03:00',
        'robot',
        '2019-12-01T01:00:00+03:00',
        '[]'::JSONB,
        '[]',
        '[]'::JSONB,
        '[]'::JSONB,
        '[]'::JSONB,
        '[]',
        NULL);


INSERT INTO "document_templator"."dynamic_documents" (created_by,
                                                      created_at,
                                                      description,
                                                      generated_text,
                                                      is_valid,
                                                      modified_by,
                                                      modified_at,
                                                      name,
                                                      params,
                                                      persistent_id,
                                                      group_id,
                                                      version,
                                                      removed,
                                                      requests_params,
                                                      template_id)
VALUES ('venimaster',
        '2018-07-01T00:00:00+03:00',
        'some text',
        'some generated text',
        True,
        'russhakirov',
        '2018-07-01T01:00:00+03:00',
        'test',
        '[
          {
            "name": "dynamic document parameter1",
            "value": "dynamic document parameter1 value"
          },
          {
            "name": "dynamic document parameter2",
            "value": 1
          }
        ]'::JSONB,
        '000000000000000000000101',
        '000000000000000000000004',
        0,
        True,
        '[]',
        '5ff4901c583745e089e55be1');
