INSERT INTO crm_admin.segment(
    id,
    yql_shared_url,
    yt_table,
    extra_columns,
    aggregate_info,
    mode,
    control,
    created_at,
    updated_at,
    deleted_at,
    applied_targets
) VALUES (
    10,
    '',
    'home/taxi/testing/features/crm-admin/segments/testing/cmp_8511_seg',
    null,
    '{"size": 2015, "policy": {}, "filtered": 107, "distribution": [{"city": "Обнинск", "locales": [{"name": "ru", "value": 2015, "unique_drivers": 1723}]}], "targets_stat": [{"label": "global_control_drivers", "filtered": 107}], "global_control": 94, "unique_drivers": 1723, "global_control_unique_drivers": 87}',
    'Filter',
    10.00,
    '2022-06-16 16:49:50.142973',
    '2022-06-16 18:09:15.358028',
    null,
    '[{"id": 1, "label": "global_control_drivers", "is_active": true, "const_salt": "driver_salt_1", "current_period": {"current_control": {"key": "unique_driver_id", "salt": "RandomHash20200311", "mechanism": "murmur", "control_percentage": 5}, "inverted_period_selection": false, "previous_control_saved_percentage": 0}}]'
)
;

INSERT INTO crm_admin.campaign (
    id,
    name,
    specification,
    entity_type,
    trend,
    kind,
    subkind,
    discount,
    state,
    owner_name,
    ticket,
    ticket_status,
    settings,
    creative,
    segment_id,
    test_users,
    global_control,
    com_politic,
    tasks,
    created_at,
    updated_at,
    deleted_at,
    extra_data,
    planned_start_date,
    efficiency,
    is_regular,
    regular_start_time,
    regular_stop_time,
    efficiency_start_time,
    efficiency_stop_time,
    is_active,
    schedule,
    salt,
    extra_data_path,
    error_description,
    error_code,
    qs_major_version,
    extra_data_key,
    motivation_methods,
    root_id,
    parent_id,
    child_id,
    version_state,
    is_communications_limited,
    communications_limit,
    target_metrics,
    segment_stats_status
) VALUES (
    1,
    'Test campaign 1',
    'Тест',
    'Driver',
    'tariff_and_money',
    'tariff_in_city',
    'econom',
    true,
    'SEGMENT_FINISHED',
    'leemurus',
    'CRMTESTSERVICEC-3203',
    'Открыт',
    '[{"value": ["br_russia"], "fieldId": "country"}, {"value": ["br_obninsk"], "fieldId": "node_id"}, {"value": [], "fieldId": "city_exclude"}, {"value": ["driver"], "fieldId": "executor_type"}, {"value": "taximeter", "fieldId": "app"}, {"value": 90, "fieldId": "communicated_days"}, {"value": "exclude", "fieldId": "newcomer"}]',
    'CRMTEST-2419',
    10,
    '{}',
    true,
    false,
    '{}',
    '2022-06-16 16:49:15.936353',
    '2022-06-16 18:09:15.372117',
    null,
    null,
    null,
    false,
    true,
    '2022-06-16 16:49:05.138000',
    '2023-06-01 16:49:10.138000',
    null,
    null,
    null,
    '0 12 * * *',
    '__campaign_8511__',
    null,
    null,
    null,
    0,
    null,
    '{}',
    1,
    null,
    null,
    'DRAFT',
    null,
    null,
    '{sh_28}',
    '{"state": "COMPUTED", "updated_at": "2022-06-16T21:09:15.372103+03:00"}'
)
;
