\set role testsuite
\ir ../../../postgresql/crm_admin/migrations/V1__initial.sql
\ir ../../../postgresql/crm_admin/migrations/V3__nirvana.sql
\ir ../../../postgresql/crm_admin/migrations/V4__group.sql
\ir ../../../postgresql/crm_admin/migrations/V5__trigger_campaign.sql
\ir ../../../postgresql/crm_admin/migrations/V6__trigger_campaign_column.sql
\ir ../../../postgresql/crm_admin/migrations/V7__campaing_add_extra_data.sql
\ir ../../../postgresql/crm_admin/migrations/V8__trigger_campaign_state.sql
\ir ../../../postgresql/crm_admin/migrations/V9__geo_hierarchy.sql
\ir ../../../postgresql/crm_admin/migrations/V10__uploaded_csv.sql
\ir ../../../postgresql/crm_admin/migrations/V11__trigger_campaign_type_col.sql
\ir ../../../postgresql/crm_admin/migrations/V12__planned_campaing_start_date.sql
\ir ../../../postgresql/crm_admin/migrations/V13__trigger_campaign_global_control.sql
\ir ../../../postgresql/crm_admin/migrations/V15__sending.sql
\ir ../../../postgresql/crm_admin/migrations/V16__sending_send_at.sql
\ir ../../../postgresql/crm_admin/migrations/V18__campaign_results.sql
\ir ../../../postgresql/crm_admin/migrations/V19__dict_ticket_statuses.sql
\ir ../../../postgresql/crm_admin/migrations/V20__operations.sql
\ir ../../../postgresql/crm_admin/migrations/V23__campaign_efficiency_column.sql
\ir ../../../postgresql/crm_admin/migrations/V22__quicksegment.sql
\ir ../../../postgresql/crm_admin/migrations/V25__regular_campaigns.sql
\ir ../../../postgresql/crm_admin/migrations/V26__group_stats.sql
\ir ../../../postgresql/crm_admin/migrations/V27__campaign_types_dict.sql
\ir ../../../postgresql/crm_admin/migrations/V28__active_regular.sql
\ir ../../../postgresql/crm_admin/migrations/V29__group_prepared_at.sql
\ir ../../../postgresql/crm_admin/migrations/V30__campaign_efficiency_period.sql
\ir ../../../postgresql/crm_admin/migrations/V31__resolution.sql
\ir ../../../postgresql/crm_admin/migrations/V32__campaign_index.sql
\ir ../../../postgresql/crm_admin/migrations/V33__regular_campaign_schedule.sql
\ir ../../../postgresql/crm_admin/migrations/V34__regular_campaign_runs.sql
\ir ../../../postgresql/crm_admin/migrations/V35__sending_start_id.sql
\ir ../../../postgresql/crm_admin/migrations/V36__regular_sending_stats.sql
\ir ../../../postgresql/crm_admin/migrations/V37__alter_operations.sql
\ir ../../../postgresql/crm_admin/migrations/V38__chained_operations.sql
\ir ../../../postgresql/crm_admin/migrations/V39__segment_index.sql
\ir ../../../postgresql/crm_admin/migrations/V40__alter_geo_hierarchy.sql
\ir ../../../postgresql/crm_admin/migrations/V41__campaign_extra_data_path.sql
\ir ../../../postgresql/crm_admin/migrations/V42__pushed__resolutions.sql
\ir ../../../postgresql/crm_admin/migrations/V43__salt_control_group.sql
\ir ../../../postgresql/crm_admin/migrations/V44__campaign_error_code.sql
\ir ../../../postgresql/crm_admin/migrations/V45__quicksegment_schema_version2.sql
\ir ../../../postgresql/crm_admin/migrations/V46__campaign_schema_version.sql
\ir ../../../postgresql/crm_admin/migrations/V47__campaign_motivation_method.sql
\ir ../../../postgresql/crm_admin/migrations/V49__sending_foreigh_key.sql
\ir ../../../postgresql/crm_admin/migrations/V51__sending_errors.sql
\ir ../../../postgresql/crm_admin/migrations/V65__operation_retry_count.sql
\ir ../../../postgresql/crm_admin/migrations/V48__campaign_log_error_codes.sql
\ir ../../../postgresql/crm_admin/migrations/V50__campaign_extra_data_key.sql
\ir ../../../postgresql/crm_admin/migrations/V52__campaign_motivation_method.sql
\ir ../../../postgresql/crm_admin/migrations/V53__group_state_log.sql
\ir ../../../postgresql/crm_admin/migrations/V54__creative.sql
\ir ../../../postgresql/crm_admin/migrations/V55__group_v2.sql
\ir ../../../postgresql/crm_admin/migrations/V57__group_v2_updated_at_index.sql
\ir ../../../postgresql/crm_admin/migrations/V60__group_not_null_updated_at.sql
\ir ../../../postgresql/crm_admin/migrations/V56__identifiers_for_connectivity.sql
\ir ../../../postgresql/crm_admin/migrations/V71__version_info_on_delete_set_null.sql
\ir ../../../postgresql/crm_admin/migrations/V61__creative_constr_updated_at.sql
\ir ../../../postgresql/crm_admin/migrations/V69__draft_applying.sql
\ir ../../../postgresql/crm_admin/migrations/V58__drop_audience_fkey.sql
\ir ../../../postgresql/crm_admin/migrations/V59__campaign_errors.sql
\ir ../../../postgresql/crm_admin/migrations/V62__sending_errors_code.sql
\ir ../../../postgresql/crm_admin/migrations/V67__group_v2_promocode.sql
\ir ../../../postgresql/crm_admin/migrations/V72__group_v2_user_tags.sql
\ir ../../../postgresql/crm_admin/migrations/V76__timezone_flags.sql
\ir ../../../postgresql/crm_admin/migrations/V63__stop_regular_campaigns.sql
\ir ../../../postgresql/crm_admin/migrations/V64__campaign_comm_limit.sql
\ir ../../../postgresql/crm_admin/migrations/V73__targets.sql
\ir ../../../postgresql/crm_admin/migrations/V74__campaign_target_connection.sql
\ir ../../../postgresql/crm_admin/migrations/V81__period_deleted_at.sql
\ir ../../../postgresql/crm_admin/migrations/V66__group_state_log_v2.sql
\ir ../../../postgresql/crm_admin/migrations/V77__applied_targets.sql
\ir ../../../postgresql/crm_admin/migrations/V80__group_action.sql
\ir ../../../postgresql/crm_admin/migrations/V84__constr_for_group_action.sql
\ir ../../../postgresql/crm_admin/migrations/V79__target_label_constraint.sql
\ir ../../../postgresql/crm_admin/migrations/V70__diff_flags.sql
\ir ../../../postgresql/crm_admin/migrations/V75__target_metrics.sql
