\ir ../../../postgresql/supportai/migrations/V01__initial.sql
\ir ../../../postgresql/supportai/migrations/V02__add_states_table.sql
\ir ../../../postgresql/supportai/migrations/V03__user_visits.sql
\ir ../../../postgresql/supportai/migrations/V04__move_config_from_admin.sql
\ir ../../../postgresql/supportai/migrations/V05__state_ttl.sql
\ir ../../../postgresql/supportai/migrations/V06__dms_support.sql
\ir ../../../postgresql/supportai/migrations/V07__drop_scenario_useless_fields.sql
\ir ../../../postgresql/supportai/migrations/V08__create_config_indexes.sql
\ir ../../../postgresql/supportai/migrations/V09__version_percentage.sql
\ir ../../../postgresql/supportai/migrations/V10__percentage_last_version.sql
\ir ../../../postgresql/supportai/migrations/V11__policy_actions_order.sql
\ir ../../../postgresql/supportai/migrations/V12__entities.sql
\ir ../../../postgresql/supportai/migrations/V13__drop_feature_old_fields.sql
\ir ../../../postgresql/supportai/migrations/V14__debug.sql
\ir ../../../postgresql/supportai/migrations/V15__add_is_calculated_feature.sql
\ir ../../../postgresql/supportai/migrations/V16__NONTRANSACTIONAL_states_index.sql
\ir ../../../postgresql/supportai/migrations/V17__NONTRANSACTIONAL_debug_index.sql
\ir ../../../postgresql/supportai/migrations/V18__explicit_topic_rule.sql
\ir ../../../postgresql/supportai/migrations/V19__model_topics.sql
\ir ../../../postgresql/supportai/migrations/V20__model_topics_insert.sql
\ir ../../../postgresql/supportai/migrations/V21__drop_thresholds.sql
\ir ../../../postgresql/supportai/migrations/V22__scenario_graph.sql
\ir ../../../postgresql/supportai/migrations/V23__feature_suggestions.sql
\ir ../../../postgresql/supportai/migrations/V24__add_valid_scenario_graph.sql
\ir ../../../postgresql/supportai/migrations/V25__blackbox.sql
\ir ../../../postgresql/supportai/migrations/V26__topics_graph.sql
\ir ../../../postgresql/supportai/migrations/V27__nlu_features.sql
\ir ../../../postgresql/supportai/migrations/V28__graph_node_counter.sql
\ir ../../../postgresql/supportai/migrations/V29__graph_constraint.sql
\ir ../../../postgresql/supportai/migrations/V30__graph_validation.sql
\ir ../../../postgresql/supportai/migrations/V31__worker_heartbeats.sql
\ir ../../../postgresql/supportai/migrations/V32__graph_node_tags.sql
\ir ../../../postgresql/supportai/migrations/V33__voice_topics.sql
\ir ../../../postgresql/supportai/migrations/V34__not_null_graph_topic.sql
\ir ../../../postgresql/supportai/migrations/V35__graph_updated_at.sql
\ir ../../../postgresql/supportai/migrations/V36__topic_on_delete.sql
\ir ../../../postgresql/supportai/migrations/V37__version_error.sql
\ir ../../../postgresql/supportai/migrations/V38__scenario_graph_rules_and_folders.sql
\ir ../../../postgresql/supportai/migrations/V39__NONTRANSACTIONAL_add_greeting_type.sql
