INSERT INTO storage.places (
    id,
    created_at,
    updated_at,
    slug,
    enabled,
    name,
    revision,
    type,
    business,
    launched_at,
    payment_methods,
    gallery,
    brand,
    address,
    country,
    categories,
    quick_filters,
    wizard_quick_filters,
    region,
    location,
    price_category,
    assembly_cost,
    rating,
    extra_info,
    features,
    timing,
    sorting,
    working_intervals,
    allowed_couriers_types)
VALUES
(55, NOW(), NOW(), 'coffee_boy_novodmitrovskaya_2k6', true, 'Название55', 1,
    'native', 'restaurant', '2021-01-29T14:50:12.017363+00:00',
    ARRAY['cash', 'payture', 'apple_pay','taxi']::storage.place_payment_method[], ARRAY[]::storage.place_gallery[],
    (5,'brand_slug5','brand_name5', 'aspect_fit')::storage.place_brand_v2, ('city','short')::storage.place_address,
    (1,'name','code',('RUB','₽')::storage.place_country_currency)::storage.place_country,
    ARRAY[]::storage.place_category[], ARRAY[]::storage.place_quick_filter[],
    ARRAY[]::storage.place_quick_filter[], (1,'{1,2}'::bigint[],'UTC','name')::storage.place_region,
    point(55.766491,37.622333), (1,'name',0.5)::storage.place_price_category, 123,
    '{"shown":4.685, "users":4.685, "admin":1.0, "count":200}', '{}',
    '{"fast_food": true, "ignore_surge": false, "supports_preordering": false}',
    '{"preparation": 300, "extra_preparation": 300, "average_preparation": 300}',
    '{"popular": 1, "weight": 1, "wizard": 1}',
    ARRAY[(NOW() - interval '5 hours', NOW() + interval '5 hours')::storage.working_interval]::storage.working_interval[],
    ARRAY[]::storage.delivery_zone_couriers_type[]),
(1, NOW(), NOW(), 'azbuka_vkusa', true, 'Азбука Вкуса', 1,
    'native', 'restaurant', '2021-01-29T14:50:12.017363+00:00',
    ARRAY['cash', 'payture', 'apple_pay','taxi']::storage.place_payment_method[], ARRAY[]::storage.place_gallery[],
    (1,'brand_slug1','brand_name1', 'aspect_fit')::storage.place_brand_v2, ('city','short')::storage.place_address,
    (1,'name','code',('RUB','₽')::storage.place_country_currency)::storage.place_country,
    ARRAY[]::storage.place_category[], ARRAY[]::storage.place_quick_filter[],
    ARRAY[]::storage.place_quick_filter[], (1,'{1,2}'::bigint[],'UTC','name')::storage.place_region,
    point(37.622333, 55.766491), (1,'name',0.5)::storage.place_price_category, 123,
    '{"shown":4.685, "users":4.685, "admin":1.0, "count":200}', '{}',
    '{"fast_food": true, "ignore_surge": false, "supports_preordering": false}',
    '{"preparation": 300, "extra_preparation": 300, "average_preparation": 300}',
    '{"popular": 1, "weight": 1, "wizard": 1}',
    ARRAY[(NOW() - interval '5 hours', NOW() + interval '5 hours')::storage.working_interval]::storage.working_interval[],
    ARRAY[]::storage.delivery_zone_couriers_type[]),
(2, NOW(), NOW(), 'retail_shop', true, 'Retail Shop Test', 1,
    'native', 'shop', '2022-04-29T14:50:12.017363+00:00',
    ARRAY['cash', 'payture', 'apple_pay','taxi']::storage.place_payment_method[], ARRAY[]::storage.place_gallery[],
    (1,'brand_slug2','brand_name2', 'aspect_fit')::storage.place_brand_v2, ('city','short')::storage.place_address,
    (1,'name','code',('RUB','₽')::storage.place_country_currency)::storage.place_country,
    ARRAY[]::storage.place_category[], ARRAY[]::storage.place_quick_filter[],
    ARRAY[]::storage.place_quick_filter[], (1,'{1,2}'::bigint[],'UTC','name')::storage.place_region,
    point(37.622333, 55.766491), (1,'name',0.5)::storage.place_price_category, 123,
    '{"shown":4.685, "users":4.685, "admin":1.0, "count":200}', '{}',
    '{"fast_food": true, "ignore_surge": false, "supports_preordering": false}',
    '{"preparation": 300, "extra_preparation": 300, "average_preparation": 300}',
    '{"popular": 1, "weight": 1, "wizard": 1}',
    ARRAY[(NOW() - interval '5 hours', NOW() + interval '5 hours')::storage.working_interval]::storage.working_interval[],
    ARRAY[]::storage.delivery_zone_couriers_type[]);

INSERT INTO storage.delivery_zones(
    id,
    source,
    external_id,
    place_id,
    couriers_zone_id,
    name,
    created_at,
    updated_at,
    revision,
    enabled,
    couriers_type,
    shipping_type,
    delivery_conditions,
    market_avg_time,
    arrival_time,
    working_intervals,
    polygons)
VALUES
(1, 'eats_core', '1', 1, 1, 'test_delivery_zone', NOW(), NOW(), 200, true,
    'pedestrian', 'delivery',
    ARRAY[(100,200)::storage.delivery_zone_delivery_condition]::storage.delivery_zone_delivery_condition[], 10, 10,
    ARRAY[(NOW() - interval '5 hours', NOW() + interval '5 hours')::storage.working_interval]::storage.working_interval[],
    '{"((37.510243,55.806466),(37.703824,55.806466),(37.703824,55.715214),(37.510243,55.715214))"}'),
(2, 'eats_core', '2', 2, 1, 'test_delivery_zone', NOW(), NOW(), 200, true,
    'pedestrian', 'delivery',
    ARRAY[(100,200)::storage.delivery_zone_delivery_condition]::storage.delivery_zone_delivery_condition[], 10, 10,
    ARRAY[(NOW() - interval '5 hours', NOW() + interval '5 hours')::storage.working_interval]::storage.working_interval[],
    '{"((37.510243,55.806466),(37.703824,55.806466),(37.703824,55.715214),(37.510243,55.715214))"}');
