HEADER = {'Accept-Language': 'ru', 'X-Remote-IP': '127.0.0.1'}
VIP_TYPE = 'slivki'

EXPECTED_ORDER_HISTORY_VALUES = [
    [
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'payment_status_change',
            'event_data': {
                'payment_operation_info': {
                    'type': 'create',
                    'status': 'requested',
                    'id': '1',
                },
            },
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'status_change',
            'event_data': {'status': 'reserving'},
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'state_change',
            'event_data': {'state': {'wms_reserve_status': 'success'}},
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'state_change',
            'event_data': {'state': {'hold_money_status': 'success'}},
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'payment_status_change',
            'event_data': {
                'payment_operation_info': {
                    'type': 'create',
                    'status': 'success',
                    'id': '123',
                },
            },
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'status_change',
            'event_data': {'status': 'reserved'},
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'admin_action',
            'event_data': {
                'admin_action': {
                    'type': 'correct',
                    'admin_info': {'x_ya_login': 'super_admin_777'},
                    'status': 'success',
                },
            },
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'order_correcting_status',
            'event_data': {
                'correcting_info': {
                    'status': 'correcting_checked',
                    'result': 'success',
                    'correcting_items': [
                        {'item_id': 'some_item_id', 'quantity': '3'},
                    ],
                    'correcting_type': 'remove',
                },
            },
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'status_change',
            'event_data': {'status': 'assembling'},
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'dispatch_status_change',
            'event_data': {'dispatch_status': 'created'},
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'dispatch_status_change',
            'event_data': {'dispatch_status': 'accepted'},
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'state_change',
            'event_data': {'state': {'assembling_status': 'assembled'}},
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'state_change',
            'event_data': {'state': {'close_money_status': 'success'}},
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'status_change',
            'event_data': {'status': 'assembled'},
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'status_change',
            'event_data': {'status': 'delivering'},
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'dispatch_status_change',
            'event_data': {'dispatch_status': 'accepted'},
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'status_change',
            'event_data': {'status': 'pending_cancel'},
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'status_change',
            'event_data': {'status': 'closed'},
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'items_refund',
            'event_data': {
                'refund_info': {
                    'type': 'partial',
                    'refunded_items': [
                        {'item_id': 'some_random_item', 'quantity': '100500'},
                    ],
                },
            },
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'admin_action',
            'event_data': {
                'admin_action': {
                    'type': 'partial_refund',
                    'admin_info': {'x_ya_login': 'super_admin_777'},
                },
            },
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'admin_action',
            'event_data': {
                'admin_action': {
                    'type': 'promocode',
                    'admin_info': {'x_ya_login': 'super_admin_777'},
                    'status': 'fail',
                },
            },
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'create_cashback',
            'event_data': {
                'cashback_info': {
                    'compensation_id': 'a2ace908-5d18-4764-8593-192a1b535514',
                    'compensation_source': 'admin_compensation',
                    'compensation_value': 120,
                    'status': 'success',
                },
            },
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'wms_pause',
            'event_data': {
                'wms_pause_info': {'type': 'pause', 'delay': '120'},
            },
        },
        {
            'ts': '2022-01-25T13:25:37.328882+00:00',
            'event_type': 'wms_pause',
            'event_data': {'wms_pause_info': {'type': 'resume'}},
        },
    ],
]

ADMIN_INFO_STATUSES = [
    (
        'canceled',
        None,
        None,
        'success',
        'success',
        None,
        None,
        'pickuped',
        'order_canceled',
    ),
    (
        'closed',
        'delivering',
        'success',
        'success',
        'success',
        'assembled',
        'delivering',
        'pickuped',
        'order_finished',
    ),
    (
        'delivering',
        'closed',
        'success',
        'success',
        'success',
        'assembled',
        'delivering',
        'ready_for_delivery_confirmation',
        'finishing_in_progress',
    ),
    (
        'closed',
        'closed',
        'success',
        'success',
        'success',
        'assembled',
        'delivering',
        'ready_for_delivery_confirmation',
        'order_finished',
    ),
    (
        'delivering',
        'canceled',
        'success',
        'success',
        'success',
        'assembled',
        'delivering',
        'ready_for_delivery_confirmation',
        'canceling_in_progress',
    ),
    (
        'canceled',
        'canceled',
        'success',
        'success',
        'success',
        'assembled',
        'delivering',
        'ready_for_delivery_confirmation',
        'order_canceled',
    ),
    (
        'delivering',
        None,
        'success',
        'success',
        'success',
        'assembled',
        'delivering',
        'ready_for_delivery_confirmation',
        'performer_arrived_to_client',
    ),
    (
        'delivering',
        None,
        'success',
        'success',
        'success',
        'assembled',
        'delivering',
        'pickuped',
        'performer_took_the_order',
    ),
    (
        'delivering',
        None,
        'success',
        'success',
        'success',
        'assembled',
        'delivering',
        'ready_for_pickup_confirmation',
        'performer_arrived_to_depot',
    ),
    (
        'delivering',
        None,
        'success',
        'success',
        'success',
        'assembled',
        'delivering',
        'performer_found',
        'performer_found',
    ),
    (
        'delivering',
        None,
        'success',
        'success',
        'success',
        'assembled',
        'delivering',
        'performer_draft',
        'performer_lookup',
    ),
    (
        'assembled',
        None,
        'success',
        'success',
        'success',
        'assembled',
        'delivering',
        'accepted',
        'order_assembled',
    ),
    (
        'assembling',
        None,
        'success',
        'success',
        'success',
        None,
        None,
        'accepted',
        'order_assembling_started',
    ),
    (
        'reserving',
        None,
        'success',
        None,
        'success',
        'assembled',
        'delivering',
        'accepted',
        'payment_awaiting',
    ),
    (
        'reserving',
        None,
        'failed',
        'success',
        'success',
        'assembled',
        'delivering',
        'accepted',
        'wms_reservation_failed',
    ),
    (
        'reserving',
        None,
        'success',
        'success',
        'success',
        'assembled',
        'delivering',
        'accepted',
        'payment_success',
    ),
    (
        'reserving',
        None,
        'success',
        'failed',
        'success',
        'assembled',
        'delivering',
        'accepted',
        'payment_failed',
    ),
    (
        'checked_out',
        None,
        'success',
        'success',
        'success',
        'assembled',
        'delivering',
        'accepted',
        'order_created',
    ),
    (
        'canceled',
        None,
        'success',
        'success',
        'failed',
        'assembled',
        'delivering',
        'accepted',
        'payment_failed',
    ),
    (
        'canceled',
        None,
        'success',
        'success',
        'success',
        'failed',
        'delivering',
        'accepted',
        'order_assembling_failed',
    ),
    (
        'canceled',
        None,
        'success',
        'success',
        'success',
        'assembled',
        'failed',
        'accepted',
        'dispatch_failed',
    ),
]

SPECIFIC_ORDER_TIMEZONE = 'Europe/Moscow'

SPECIFIC_ORDER_CARGO_DISPATCH = {
    'batch_claim_ids': [
        '5218f37445de4fa890924f90f1165a95',
        '5920adbc7a0f45489445e938ccfd6367',
    ],
    'batch_order_num': 0,
    'dispatch_in_batch': True,
    'dispatch_delivery_type': 'courier',
}

SPECIFIC_ORDER = {
    'order_id': 'specific_order_id',
    'status': 'delivering',
    'desired_status': 'delivering',
    'client_price': 102,
    'depot_id': '123456',
    'bound_sessions': ['specific_bound_sessions'],
    'session': 'specific_session',
    'yandex_uid': 'specific_yandex_uid',
    'personal_phone_id': 'specific_personal_phone_id',
    'phone_id': 'specific_phone_id',
    'eats_user_id': 'specific_eats_user_id',
    'taxi_user_id': 'specific_taxi_user_id',
    'eats_order_id': 'specific_eats_order_id',
    'cart_id': '32d82a0f-7da0-459c-ba24-12ec11f30c99',
    'cart_version': 119,
    'short_order_id': 'specific_short_order_id',
    'dispatch_start_delivery_ts': '2020-05-25T17:40:45+00:00',
    'location': [10.0, 20.0],
    'grocery_order_status': 'closed',
    'order_history': [],
    'items': [
        {
            'id': '1',
            'product_key': {'id': '1', 'shelf_type': 'store'},
            'price': 10,
            'price_template': f'{str(10)} $SIGN$$CURRENCY$',
            'quantity': 1,
            'title': 'item_title',
            'currency': 'RUB',
            'refunded_quantity': '0',
        },
    ],
    'depot_address': 'depot_address',
    'dispatch_flow': 'grocery_dispatch',
    'courier_name': 'courier_name',
    'order_version': 33,
    'assembling_status': 'assembled',
    'close_money_status': 'success',
    'hold_money_status': 'success',
    'wms_reserve_status': 'success',
    'doorcode': '119kk',
    'doorcode_extra': 'doorcode_extra',
    'doorbell_name': 'doorbell_name',
    'building_name': 'building_name',
    'left_at_door': False,
    'meet_outside': True,
    'no_door_call': True,
    'postal_code': 'SE16 3LR',
    'place_id': 'yamaps...',
    'region_id': 100,
    'floor': '22',
    'flat': '89',
    'house': '12',
    'street': 'specific_street',
    'city': 'specific_city',
    'country': 'speceific_country',
    'app_info': 'specific_app_info',
    'cancel_reason_type': 'failure',
    'cancel_reason_message': 'specific cancel reason message',
    'currency': 'specific_currency',
    'grocery_flow_version': 'grocery_flow_v1',
    'dispatch_id': '1337',
    'dispatch_status': 'created',
    'dispatch_cargo_status': 'performer_draft',
    'dispatch_courier_name': 'specific_courier',
    'dispatch_delivery_eta': 15,
    'dispatch_status_meta': {'cargo_dispatch': SPECIFIC_ORDER_CARGO_DISPATCH},
    'created': '2020-05-25T17:20:45+00:00',
    'updated': '2020-05-25T17:35:45+00:00',
    'status_updated': '2020-05-25T17:43:00+00:00',
    'finished': '2020-05-25T17:43:45+00:00',
    'promocode': 'SOME_PROMOCODE',
    'promocode_valid': True,
    'promocode_sum': 120,
    'entrance': 'entrance-123',
    'comment': 'specific_comment',
    'tips': 1.23,
    'tips_status': 'pending',
    'order_revision': 1,
    'billing_flow': 'grocery_payments',
    'timezone': SPECIFIC_ORDER_TIMEZONE,
    'locale': 'ru',
    'edit_status': 'success',
    'vip_type': VIP_TYPE,
    'push_notification_enabled': True,
    'user_ip': '127.0.0.1',
    'allowed_actions': [
        'promocode',
        'refund',
        'partial_refund',
        'cancel',
        'correct_remove',
        'compensation',
        'edit_address',
    ],
}

SPECIFIC_FEEDBACK = {
    'feedback_status': 'submitted',
    'evaluation': 5,
    'feedback_options': ['Качество продуктов'],
    'feedback_comment': 'Свежая еда',
}
