import { RequestLogEntry } from '@metrika/shared/types/logs';

export const mooa = {
    requestLogs: [
        {
            method: 'GET',
            url:
                'http://localhost:8001/tvm/tickets?dsts=blackbox%2Capi%2CmobmetApi%2CdirectIntApi%2CwebmasterApi',
            requestHeaders: {
                'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
                accept: 'application/json',
                'accept-encoding': 'gzip, deflate',
                host: 'localhost:8001',
            },
            status: 'success',
            statusCode: 200,
            responseHeaders: {
                'content-type': 'application/json',
                'x-content-type-options': 'nosniff',
                'x-ya-tvmtool-data-birthtime': '1592988859',
                date: 'Wed, 24 Jun 2020 08:56:09 GMT',
                'transfer-encoding': 'chunked',
            },
            requestBody: '',
            timings: {
                start: 1592988969912,
                socket: 1592988969913,
                lookup: 1592988969920,
                connect: 1592988969920,
                upload: 1592988969920,
                response: 1592988969947,
                end: 1592988969950,
                phases: {
                    wait: 1,
                    dns: 7,
                    tcp: 0,
                    request: 0,
                    firstByte: 27,
                    download: 3,
                    total: 38,
                },
            },
            responseBodyJSON: {
                api: {
                    ticket: '<hidden>',
                    tvm_id: 2000233,
                },
                blackbox: {
                    ticket: '<hidden>',
                    tvm_id: 239,
                },
                directIntApi: {
                    ticket: '<hidden>',
                    tvm_id: 2000693,
                },
                mobmetApi: {
                    ticket: '<hidden>',
                    tvm_id: 2000335,
                },
                webmasterApi: {
                    ticket: '<hidden>',
                    tvm_id: 2000286,
                },
            },
            type: 'request',
        },
        {
            method: 'GET',
            url:
                'http://blackbox-mimino.yandex.net/blackbox?method=sessionid&format=json&attributes=1008%2C14%2C31%2C34&regname=yes&fields=&getServiceTicket=&multisession=yes&userip=2a02%3A6b8%3Ab081%3A225%3A%3A1%3Ac&host=eduarddyckman.dev.metrika.yandex.ru&dbfields=subscription.login.669&get_user_ticket=yes',
            requestHeaders: {
                'user-agent': 'got/6.7.1 (https://github.com/sindresorhus/got)',
                'accept-encoding': 'gzip,deflate',
                accept: 'application/json',
                host: 'blackbox-mimino.yandex.net',
            },
            status: 'success',
            statusCode: 200,
            responseHeaders: {
                server: 'nginx',
                date: 'Wed, 24 Jun 2020 08:56:09 GMT',
                'content-type': 'application/json',
                'content-length': '1275',
                connection: 'close',
                xrtiq: '0.0002',
                xrtih: '0.0022',
            },
            requestBody: '',
            timings: {
                start: 1592988969954,
                socket: 1592988969956,
                lookup: 1592988969956,
                connect: 1592988969963,
                upload: 1592988969963,
                response: 1592988969973,
                end: 1592988969974,
                phases: {
                    wait: 2,
                    dns: 0,
                    tcp: 7,
                    request: 0,
                    firstByte: 10,
                    download: 1,
                    total: 20,
                },
            },
            responseBodyJSON: {
                status: {
                    value: 'VALID',
                    id: 0,
                },
                error: 'OK',
                age: 225996,
                expires_in: 7550004,
                ttl: '5',
                default_uid: '642600814',
                users: [
                    {
                        id: '642600814',
                        status: {
                            value: 'VALID',
                            id: 0,
                        },
                        uid: {
                            value: '642600814',
                            lite: false,
                            hosted: false,
                        },
                        login: 'yndx-eduarddyckman',
                        have_password: true,
                        have_hint: false,
                        karma: {
                            value: 0,
                        },
                        karma_status: {
                            value: 0,
                        },
                        regname: 'yndx-eduarddyckman',
                        display_name: {
                            name: 'yndx-eduarddyckman',
                            avatar: {
                                default:
                                    '41409/enc-b7351adf7c80b37b86bb9afb8eb5c2fe25a18840c56cc5358bd602d2cb10e4c9',
                                empty: false,
                            },
                        },
                        dbfields: {
                            'subscription.login.669': 'eduarddyckman',
                        },
                        attributes: {
                            '31': 'ru',
                            '34': 'ru',
                            '1008': 'yndx-eduarddyckman',
                        },
                        auth: {
                            password_verification_age: 753404,
                            have_password: true,
                            secure: true,
                            partner_pdd_token: false,
                        },
                    },
                ],
                allow_more_users: true,
                connection_id: 's:1592235565261:FAABAAAAAAAZEoGwuAYCKg:4f',
            },
            type: 'request',
        },
        {
            method: 'GET',
            url:
                'http://mtback01et.yandex.ru:8082/internal/rbac/roles?request_id=14c7ced8-df59-4a47-b5e0-f1828f100bdb',
            requestHeaders: {
                'user-agent': 'metrika-frontend/eduarddyckman',
                'accept-encoding': 'utf-8',
                accept: 'application/json',
                'x-yandex-uid': '642600814',
                host: 'mtback01et.yandex.ru:8082',
            },
            status: 'success',
            statusCode: 200,
            responseHeaders: {
                connection: 'close',
                date: 'Wed, 24 Jun 2020 08:56:09 GMT',
                'set-cookie': [
                    'JSESSIONID=node04rb1xyn87o2kpldl0wtz2meg311727.node0; Path=/',
                ],
                expires: 'Thu, 01 Jan 1970 00:00:00 GMT',
                'content-type': 'application/json;charset=utf-8',
                'x-xss-protection': '1; mode=block',
                'x-frame-options': 'DENY',
                'x-content-type-options': 'nosniff',
                vary: 'Accept-Encoding, User-Agent',
                server: 'Jetty(9.4.19.v20190610)',
            },
            requestBody: '',
            timings: {
                start: 1592988969980,
                socket: 1592988969980,
                lookup: 1592988969982,
                connect: 1592988969990,
                upload: 1592988969990,
                response: 1592988970007,
                end: 1592988970008,
                phases: {
                    wait: 0,
                    dns: 2,
                    tcp: 8,
                    request: 0,
                    firstByte: 17,
                    download: 1,
                    total: 28,
                },
            },
            responseBodyJSON: {
                roles: [
                    'delegate_read',
                    'api_read',
                    'manager',
                    'api_write',
                    'yamanager',
                    'user',
                    'support',
                ],
                _profile: {
                    queries: [],
                    additional: {
                        'frontend-host': 'mtback01et.yandex.ru:8082',
                    },
                    base_time: 1592988969996,
                    request_id: '5653d5f1-872b-4cbe-b4b8-851ae6a6aab8',
                    request_uid: 642600814,
                    total_time: 9,
                    java_time: 9,
                },
            },
            type: 'request',
        },
        {
            method: 'POST',
            url: 'http://geobase-test.qloud.yandex.ru/v1/pinpoint_geolocation?',
            requestHeaders: {
                'user-agent': 'got/6.7.1 (https://github.com/sindresorhus/got)',
                'accept-encoding': 'gzip,deflate',
                accept: 'application/json',
                'content-length': 593,
                host: 'geobase-test.qloud.yandex.ru',
            },
            status: 'success',
            statusCode: 200,
            responseHeaders: {
                server: 'nginx',
                date: 'Wed, 24 Jun 2020 08:56:10 GMT',
                'content-type': 'application/json; charset=utf-8',
                'content-length': '234',
                connection: 'keep-alive',
                'keep-alive': 'timeout=120',
                'x-qloud-router': 'sas9-cd6a29a1747d.qloud-c.yandex.net',
            },
            requestBody:
                '{"x_forwarded_for":"2a02:6b8:b081:225::1:c","x_real_ip":"2a02:6b8:b081:225::1:c","yandex_gid":213,"yp_cookie":"1623771487.cld.1955450#1608683183.szm.2:1440x900:1440x805#1901872518.sad.1585411011:1586512518:3#1901889275.multib.1#1619020291.stltp.serp_bk-map_1_1587484291#1620727000.p_sw.1589190999#1594827485.ygu.1#1592995880.gpauto.55_614033:37_604198:159:1:1592988680#1907595565.udn.cDp5bmR4LWVkdWFyZGR5Y2ttYW4=#1907443820.2fa.1","ys_cookie":"udn.cDp5bmR4LWVkdWFyZGR5Y2ttYW4=#wprid.1592984758161346-1321987751525201404838184-prestable-report-sas-web-yp-5#c_chck.3591520171","is_trusted":true}',
            timings: {
                start: 1592988970010,
                socket: 1592988970011,
                lookup: 1592988970012,
                connect: 1592988970012,
                upload: 1592988970013,
                response: 1592988970020,
                end: 1592988970021,
                phases: {
                    wait: 1,
                    dns: 1,
                    tcp: 0,
                    request: 1,
                    firstByte: 7,
                    download: 1,
                    total: 11,
                },
            },
            responseBodyJSON: {
                region_id: 213,
                region_id_by_ip: 213,
                precision_by_ip: 2,
                suspected_region_id: -1,
                precision: 2,
                point_id: -1,
                should_update_cookie: false,
                gid_is_trusted: false,
                region_id_by_gp: 120580,
                location: {
                    lat: 55.614033,
                    lon: 37.604198,
                },
            },
            type: 'request',
        },
        {
            method: 'GET',
            url: 'http://geobase-test.qloud.yandex.ru/v1/parents?id=213',
            requestHeaders: {
                'user-agent': 'got/6.7.1 (https://github.com/sindresorhus/got)',
                'accept-encoding': 'gzip,deflate',
                accept: 'application/json',
                host: 'geobase-test.qloud.yandex.ru',
            },
            status: 'success',
            statusCode: 200,
            responseHeaders: {
                server: 'nginx',
                date: 'Wed, 24 Jun 2020 08:56:10 GMT',
                'content-type': 'application/json; charset=utf-8',
                'content-length': '25',
                connection: 'keep-alive',
                'keep-alive': 'timeout=120',
                'x-qloud-router': 'sas9-cd6a29a1747d.qloud-c.yandex.net',
            },
            requestBody: '',
            timings: {
                start: 1592988970022,
                socket: 1592988970023,
                lookup: 1592988970023,
                connect: 1592988970023,
                upload: 1592988970023,
                response: 1592988970031,
                end: 1592988970031,
                phases: {
                    wait: 1,
                    dns: 0,
                    tcp: 0,
                    request: 0,
                    firstByte: 8,
                    download: 0,
                    total: 9,
                },
            },
            responseBodyJSON: [213, 1, 3, 225, 10001, 10000],
            type: 'request',
        },
        {
            method: 'POST',
            url: 'http://langdetect-test.qloud.yandex.ru/v0/find',
            requestHeaders: {
                'user-agent': 'got/6.7.1 (https://github.com/sindresorhus/got)',
                'accept-encoding': 'gzip,deflate',
                'content-type': 'application/json',
                accept: 'application/json',
                'content-length': 174,
                host: 'langdetect-test.qloud.yandex.ru',
            },
            status: 'success',
            statusCode: 200,
            responseHeaders: {
                server: 'nginx',
                date: 'Wed, 24 Jun 2020 08:56:10 GMT',
                'content-type': 'application/json',
                'content-length': '42',
                connection: 'keep-alive',
                'keep-alive': 'timeout=120',
                'x-qloud-router': 'sas1-996f174944c1.qloud-c.yandex.net',
            },
            requestBody:
                '{"host":"eduarddyckman.dev.metrika.yandex.ru","cookie":1,"accept_language":"ru,en;q=0.9,es;q=0.8","geo_regions":"213,1,3,225,10001,10000","def_lang":"ru","filter":"ru,en,tr"}',
            timings: {
                start: 1592988970039,
                socket: 1592988970039,
                lookup: 1592988970041,
                connect: 1592988970041,
                upload: 1592988970042,
                response: 1592988970048,
                end: 1592988970049,
                phases: {
                    wait: 0,
                    dns: 2,
                    tcp: 0,
                    request: 1,
                    firstByte: 6,
                    download: 1,
                    total: 10,
                },
            },
            responseBodyJSON: {
                cookie_value: 1,
                name: 'Ru',
                code: 'ru',
            },
            type: 'request',
        },
        {
            method: 'POST',
            url: 'http://uatraits-test.qloud.yandex.ru/v0/detect',
            requestHeaders: {
                'user-agent': 'got/6.7.1 (https://github.com/sindresorhus/got)',
                'accept-encoding': 'gzip,deflate',
                'content-type': 'application/json',
                accept: 'application/json',
                'content-length': 154,
                host: 'uatraits-test.qloud.yandex.ru',
            },
            status: 'success',
            statusCode: 200,
            responseHeaders: {
                server: 'nginx',
                date: 'Wed, 24 Jun 2020 08:56:10 GMT',
                'content-type': 'application/json',
                'content-length': '496',
                connection: 'keep-alive',
                'keep-alive': 'timeout=120',
                'x-qloud-router': 'sas1-bc4496697d2c.qloud-c.yandex.net',
            },
            requestBody:
                '{"User-Agent":"Mozilla/5.0 (Linux; U; Android 4.0; en-us; GT-I9300 Build/IMM76D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"}',
            timings: {
                start: 1592988970050,
                socket: 1592988970051,
                lookup: 1592988970051,
                connect: 1592988970052,
                upload: 1592988970052,
                response: 1592988970061,
                end: 1592988970062,
                phases: {
                    wait: 1,
                    dns: 0,
                    tcp: 1,
                    request: 0,
                    firstByte: 9,
                    download: 1,
                    total: 12,
                },
            },
            responseBodyJSON: {
                isTouch: true,
                isTablet: false,
                isMobile: true,
                postMessageSupport: true,
                isBrowser: true,
                historySupport: true,
                SVGSupport: true,
                OSName: 'Android Ice Cream Sandwich',
                OSFamily: 'Android',
                BrowserBaseVersion: '534.30',
                BrowserEngine: 'WebKit',
                DeviceName: 'Galaxy S III',
                MultiTouch: true,
                BrowserName: 'AndroidBrowser',
                OSVersion: '4.0',
                DeviceVendor: 'SAMSUNG',
                BrowserEngineVersion: '534.30',
                BrowserVersion: '4.0',
                localStorageSupport: true,
                BrowserBase: 'Safari',
                DeviceModel: 'GT-I9300',
            },
            type: 'request',
        },
        {
            executionTime: 8,
            operation: 'findOne',
            collectionName: 'dashboards3',
            queryConditions: { counterId: 51764942 },
            host: 'man-mpobup748puppw9k.db.yandex.net',
            result: null,
            type: 'mongo',
        },
    ],
} as { requestLogs: RequestLogEntry[] };
