# pylint: disable=too-many-arguments,too-many-lines
import json

import pytest

from taxi.stq import client as stq_client

from taxi_protocol import constants
from test_taxi_protocol import plugins as conftest


@pytest.mark.parametrize(
    'headers, url, data, expected_code, expected_result, ',
    [
        (
            {
                'X-Real-IP': '1.1.1.1',
                'X-YaTaxi-UserId': '5ff4901c583745e089e55be4',
            },
            '/4.0/support_chat/v1/regular/add_user_message',
            {
                'id': '5ff4901c583745e089e55be4',
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'text',
            },
            200,
            {},
        ),
        (
            {
                'X-Real-IP': '1.1.1.1',
                'X-YaTaxi-UserId': '5ff4901c583745e089e55be4',
            },
            '/4.0/support_chat/v1/regular/add_user_message',
            {
                'id': '5ff4901c583745e089e55be4',
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'text',
            },
            200,
            {},
        ),
        (
            {
                'X-Real-IP': '1.1.1.1',
                'X-YaTaxi-UserId': '5ff4901c583745e089e55be6',
            },
            '/4.0/support_chat/v1/regular/add_user_message',
            {
                'id': '5ff4901c583745e089e55be4',
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'text',
            },
            406,
            {},
        ),
        (
            {
                'X-Real-IP': '1.1.1.1',
                'X-YaTaxi-UserId': '5ff4901c583745e089e55be4',
            },
            '/4.0/support_chat/v1/regular/add_user_message',
            {
                'id': '5ff4901c583745e089e55be4',
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'csat',
            },
            200,
            {},
        ),
        (
            {
                'X-Real-IP': '1.1.1.1',
                'X-YaTaxi-UserId': '5ff4901c583745e089e55be5',
            },
            '/4.0/support_chat/v1/regular/add_user_message',
            {
                'id': '5ff4901c583745e089e55be5',
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'csat',
            },
            406,
            {},
        ),
        (
            {
                'X-Real-IP': '1.1.1.1',
                'X-YaTaxi-UserId': '5ff4901c583745e089e55be6',
            },
            '/4.0/support_chat/v1/regular/add_user_message',
            {
                'id': '5ff4901c583745e089e55be6',
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'csat',
            },
            406,
            {},
        ),
    ],
)
async def test_add_user_message(
        monkeypatch,
        protocol_client,
        protocol_app,
        mock,
        mock_chat_search,
        mock_chat_add_update,
        mock_get_users,
        headers,
        url,
        data,
        expected_code,
        expected_result,
):
    monkeypatch.setattr(
        protocol_app, 'passport', conftest.MockPassportClient(),
    )

    @mock
    async def _put(*args, **kwargs):
        pass

    monkeypatch.setattr(stq_client, 'put', _put)

    response = await protocol_client.post(
        url, headers=headers, data=json.dumps(data),
    )

    assert response.status == expected_code

    if response.status == 200:

        response = await protocol_client.post(
            url, headers=headers, data=json.dumps(data),
        )

        assert response.status == 406


@pytest.mark.config(LOCALES_SUPPORTED=['ru', 'en', 'he'])
@pytest.mark.parametrize(
    [
        'prefix',
        'chat_type',
        'add_actions',
        'data',
        'params',
        'headers',
        'expected_add_update_call',
        'expected_chat_create_call',
        'expected_code',
        'expected_result',
    ],
    [
        (
            '4.0/support_chat',
            'regular',
            False,
            {
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'text',
                'message_metadata': {
                    'attachments': [{'id': 'id', 'name': 'id.txt'}],
                },
            },
            {},
            {
                'X-Real-IP': '1.1.1.1',
                constants.YANDEX_UID_HEADER: '12',
                'X-YaTaxi-UserId': '5ff4901c583745e089e55be4',
            },
            {
                'headers': None,
                'chat_id': '5ff4901c583745e089e55be4',
                'message_id': '1234567890abcdefghijkl01',
                'message_text': 'Текст сообщения',
                'message_sender_id': '539eb65be7e5b1f53980dfa8',
                'message_sender_role': 'client',
                'message_metadata': {
                    'source': 'chat',
                    'attachments': [
                        {'id': 'id', 'name': 'id.txt', 'source': 'mds'},
                    ],
                },
                'update_metadata': None,
                'include_chat': True,
                'scenario_context': None,
            },
            None,
            200,
            {
                'chat_id': '5ff4901c583745e089e55be4',
                'chat_open': True,
                'chat_visible': True,
                'ask_csat': False,
                'new_messages': 0,
                'messages': [
                    {
                        'id': 'message_id',
                        'type': 'text',
                        'timestamp': '2018-10-20T12:34:56',
                        'body': 'Привет!',
                        'text': 'Привет!',
                        'author': 'user',
                        'metadata': {'created': '2018-10-20T12:34:56'},
                        'sender': {'id': 'client_id', 'role': 'client'},
                    },
                ],
                'participants': [
                    {'id': 'client_id', 'role': 'client'},
                    {
                        'id': 'support_id',
                        'role': 'support',
                        'nickname': 'support_name',
                        'avatar_url': 'support_avatar',
                    },
                ],
                'actions': [],
                'view': {'show_message_input': True},
                'avatar_url': 'support_avatar',
                'support_name': 'support_name',
            },
        ),
        (
            '4.0/support_chat',
            'regular',
            False,
            {
                'scenario_context': {'last_action_id': 'anime22'},
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'message_key': '5',
                'type': 'csat',
            },
            {},
            {
                'X-Real-IP': '1.1.1.1',
                constants.YANDEX_UID_HEADER: '12',
                'X-YaTaxi-UserId': '5ff4901c583745e089e55be4',
            },
            {
                'headers': None,
                'chat_id': '5ff4901c583745e089e55be4',
                'message_id': '1234567890abcdefghijkl01',
                'message_text': 'Текст сообщения',
                'message_sender_id': '539eb65be7e5b1f53980dfa8',
                'message_sender_role': 'client',
                'message_metadata': None,
                'update_metadata': {'csat_value': '5', 'csat_reasons': []},
                'include_chat': True,
                'scenario_context': {'last_action_id': 'anime22'},
            },
            None,
            200,
            {
                'chat_id': '5ff4901c583745e089e55be4',
                'chat_open': True,
                'chat_visible': True,
                'ask_csat': False,
                'new_messages': 0,
                'messages': [
                    {
                        'id': 'message_id',
                        'type': 'text',
                        'timestamp': '2018-10-20T12:34:56',
                        'body': 'Привет!',
                        'text': 'Привет!',
                        'author': 'user',
                        'metadata': {'created': '2018-10-20T12:34:56'},
                        'sender': {'id': 'client_id', 'role': 'client'},
                    },
                ],
                'participants': [
                    {'id': 'client_id', 'role': 'client'},
                    {
                        'id': 'support_id',
                        'role': 'support',
                        'nickname': 'support_name',
                        'avatar_url': 'support_avatar',
                    },
                ],
                'actions': [],
                'view': {'show_message_input': True},
                'avatar_url': 'support_avatar',
                'support_name': 'support_name',
            },
        ),
        (
            '4.0/support_chat',
            'realtime',
            False,
            {
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'csat',
            },
            {},
            {
                'Accept-Language': 'he',
                'X-Real-IP': '1.1.1.1',
                constants.YANDEX_UID_HEADER: '12',
                'X-YaTaxi-UserId': '5ff4901c583745e089e55be4',
            },
            {
                'headers': {'Accept-Language': 'he'},
                'chat_id': '5ff4901c583745e089e55be4',
                'message_id': '1234567890abcdefghijkl01',
                'message_text': 'Текст сообщения',
                'message_sender_id': '12',
                'message_sender_role': 'eats_client',
                'message_metadata': None,
                'update_metadata': {'csat_value': '', 'csat_reasons': []},
                'include_chat': True,
                'scenario_context': None,
            },
            None,
            200,
            {
                'chat_id': '5ff4901c583745e089e55be4',
                'chat_open': True,
                'chat_visible': True,
                'ask_csat': False,
                'new_messages': 0,
                'messages': [
                    {
                        'id': 'message_id',
                        'type': 'text',
                        'timestamp': '2018-10-20T12:34:56',
                        'body': 'Привет!',
                        'text': 'Привет!',
                        'author': 'user',
                        'metadata': {'created': '2018-10-20T12:34:56'},
                        'sender': {'id': 'client_id', 'role': 'client'},
                    },
                ],
                'participants': [
                    {'id': 'client_id', 'role': 'client'},
                    {
                        'id': 'support_id',
                        'role': 'support',
                        'nickname': 'support_name',
                        'avatar_url': 'support_avatar',
                    },
                ],
                'actions': [],
                'view': {'show_message_input': True},
                'avatar_url': 'support_avatar',
                'support_name': 'support_name',
            },
        ),
        (
            '4.0/support_chat',
            'realtime',
            False,
            {
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'text',
                'message_metadata': {
                    'attachments': [{'id': 'id', 'name': 'id.txt'}],
                },
            },
            {},
            {
                'X-Real-IP': '1.1.1.1',
                constants.YANDEX_UID_HEADER: '12',
                'X-YaTaxi-UserId': '5ff4901c583745e089e55be4',
            },
            None,
            {
                'headers': None,
                'owner_id': '12',
                'owner_role': 'eats_client',
                'platform': 'android',
                'message_text': 'Текст сообщения',
                'message_sender_id': '12',
                'message_sender_role': 'eats_client',
                'metadata': {
                    'user_id': '5ff4901c583745e089e55be4',
                    'user_application': 'android',
                    'user_phone': '+79099575227 (специалист по мемам)',
                    'phone_type': 'yandex',
                    'user_phone_id': '539eb65be7e5b1f53980dfa8',
                    'user_uid': '12',
                    'user_locale': 'ru',
                },
                'message_metadata': {
                    'attachments': [
                        {'id': 'id', 'name': 'id.txt', 'source': 'mds'},
                    ],
                },
                'include_history': True,
                'scenario_context': None,
            },
            200,
            {
                'chat_id': '5ff4901c583745e089e55be4',
                'chat_open': True,
                'chat_visible': True,
                'ask_csat': False,
                'new_messages': 0,
                'messages': [
                    {
                        'id': 'message_id',
                        'type': 'text',
                        'timestamp': '2018-10-20T12:34:56',
                        'body': 'Привет!',
                        'text': 'Привет!',
                        'author': 'user',
                        'metadata': {'created': '2018-10-20T12:34:56'},
                        'sender': {'id': 'client_id', 'role': 'client'},
                    },
                ],
                'participants': [
                    {'id': 'client_id', 'role': 'client'},
                    {
                        'id': 'support_id',
                        'role': 'support',
                        'nickname': 'support_name',
                        'avatar_url': 'support_avatar',
                    },
                ],
                'actions': [],
                'view': {'show_message_input': True},
                'avatar_url': 'support_avatar',
                'support_name': 'support_name',
            },
        ),
        (
            '4.0/support_chat',
            'realtime',
            False,
            {
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'text',
                'message_metadata': {'user_country': 'isr'},
            },
            {},
            {
                'X-Real-IP': '1.1.1.1',
                'Accept-Language': 'he',
                constants.YANDEX_UID_HEADER: '12',
                'X-YaTaxi-UserId': '5ff4901c583745e089e55be4',
            },
            None,
            {
                'headers': {'Accept-Language': 'he'},
                'owner_id': '12',
                'owner_role': 'eats_client',
                'platform': 'android',
                'message_text': 'Текст сообщения',
                'message_sender_id': '12',
                'message_sender_role': 'eats_client',
                'metadata': {
                    'user_id': '5ff4901c583745e089e55be4',
                    'user_application': 'android',
                    'user_phone': '+79099575227 (специалист по мемам)',
                    'phone_type': 'yandex',
                    'user_phone_id': '539eb65be7e5b1f53980dfa8',
                    'user_uid': '12',
                    'user_country': 'isr',
                    'user_locale': 'he',
                },
                'message_metadata': {'user_country': 'isr'},
                'include_history': True,
                'scenario_context': None,
            },
            200,
            {
                'chat_id': '5ff4901c583745e089e55be4',
                'chat_open': True,
                'chat_visible': True,
                'ask_csat': False,
                'new_messages': 0,
                'messages': [
                    {
                        'id': 'message_id',
                        'type': 'text',
                        'timestamp': '2018-10-20T12:34:56',
                        'body': 'Привет!',
                        'text': 'Привет!',
                        'author': 'user',
                        'metadata': {'created': '2018-10-20T12:34:56'},
                        'sender': {'id': 'client_id', 'role': 'client'},
                    },
                ],
                'participants': [
                    {'id': 'client_id', 'role': 'client'},
                    {
                        'id': 'support_id',
                        'role': 'support',
                        'nickname': 'support_name',
                        'avatar_url': 'support_avatar',
                    },
                ],
                'actions': [],
                'view': {'show_message_input': True},
                'avatar_url': 'support_avatar',
                'support_name': 'support_name',
            },
        ),
        (
            '4.0/support_chat',
            'regular',
            False,
            {
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'text',
            },
            {},
            {},
            None,
            None,
            400,
            None,
        ),
        (
            '4.0/support_chat',
            'realtime',
            True,
            {
                'scenario_context': {'action_id': 'root_action'},
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'text',
            },
            {'service': 'safety_center'},
            {
                'X-Real-IP': '1.1.1.1',
                constants.YANDEX_UID_HEADER: '12',
                'X-YaTaxi-UserId': '5ff4901c583745e089e55be4',
            },
            None,
            {
                'headers': None,
                'scenario_context': {'action_id': 'root_action'},
                'owner_id': '12',
                'owner_role': 'safety_center_client',
                'platform': 'android',
                'message_text': 'Текст сообщения',
                'message_sender_id': '12',
                'message_sender_role': 'safety_center_client',
                'metadata': {
                    'user_id': '5ff4901c583745e089e55be4',
                    'user_application': 'android',
                    'user_phone': '+79099575227 (специалист по мемам)',
                    'phone_type': 'yandex',
                    'user_phone_id': '539eb65be7e5b1f53980dfa8',
                    'user_uid': '12',
                    'user_locale': 'ru',
                },
                'message_metadata': None,
                'include_history': True,
            },
            200,
            {
                'chat_id': '5ff4901c583745e089e55be4',
                'chat_open': True,
                'chat_visible': True,
                'ask_csat': False,
                'new_messages': 0,
                'messages': [
                    {
                        'id': 'message_id',
                        'type': 'text',
                        'timestamp': '2018-10-20T12:34:56',
                        'body': 'Привет!',
                        'text': 'Привет!',
                        'author': 'user',
                        'metadata': {'created': '2018-10-20T12:34:56'},
                        'sender': {'id': 'client_id', 'role': 'client'},
                    },
                ],
                'participants': [
                    {'id': 'client_id', 'role': 'client'},
                    {
                        'id': 'support_id',
                        'role': 'support',
                        'nickname': 'support_name',
                        'avatar_url': 'support_avatar',
                    },
                ],
                'actions': [
                    {
                        'action_id': 'anime',
                        'content': {
                            'items': [
                                {
                                    'action_id': 'anime1',
                                    'params': {'text': 'Yes'},
                                    'title': 'Yes',
                                    'type': 'text',
                                },
                                {
                                    'action_id': 'anime2',
                                    'params': {'text': 'No'},
                                    'title': 'No',
                                    'type': 'text',
                                },
                            ],
                            'question': 'anime_text',
                        },
                        'type': 'questionary',
                    },
                ],
                'view': {'show_message_input': True},
                'avatar_url': 'support_avatar',
                'support_name': 'support_name',
            },
        ),
        (
            '4.0/support_chat',
            'realtime',
            False,
            {
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'text',
            },
            {'service': 'help_yandex_ru'},
            {'X-Real-IP': '1.1.1.1', constants.YANDEX_UID_HEADER: '12'},
            None,
            {
                'headers': None,
                'owner_id': '12',
                'owner_role': 'help_yandex_client',
                'platform': 'help_yandex',
                'message_text': 'Текст сообщения',
                'message_sender_id': '12',
                'message_sender_role': 'help_yandex_client',
                'metadata': {
                    'user_id': '12',
                    'user_application': 'help_yandex',
                    'user_uid': '12',
                    'user_locale': 'ru',
                },
                'message_metadata': None,
                'include_history': True,
                'scenario_context': None,
            },
            200,
            {
                'chat_id': '5ff4901c583745e089e55be4',
                'chat_open': True,
                'chat_visible': True,
                'ask_csat': False,
                'new_messages': 0,
                'messages': [
                    {
                        'id': 'message_id',
                        'type': 'text',
                        'timestamp': '2018-10-20T12:34:56',
                        'body': 'Привет!',
                        'text': 'Привет!',
                        'author': 'user',
                        'metadata': {'created': '2018-10-20T12:34:56'},
                        'sender': {'id': 'client_id', 'role': 'client'},
                    },
                ],
                'participants': [
                    {'id': 'client_id', 'role': 'client'},
                    {
                        'id': 'support_id',
                        'role': 'support',
                        'nickname': 'support_name',
                        'avatar_url': 'support_avatar',
                    },
                ],
                'actions': [],
                'view': {'show_message_input': True},
                'avatar_url': 'support_avatar',
                'support_name': 'support_name',
            },
        ),
        (
            '4.0/support_chat',
            'realtime',
            False,
            {
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'text',
                'message_metadata': {'lab_id': '123', 'lab_name': 'lab name'},
            },
            {'service': 'labs_admin_yandex_ru'},
            {'X-Real-IP': '1.1.1.1', constants.YANDEX_UID_HEADER: '12'},
            None,
            {
                'headers': None,
                'owner_id': '12',
                'owner_role': 'labs_admin_yandex_client',
                'platform': 'labs_admin_yandex',
                'message_text': 'Текст сообщения',
                'message_sender_id': '12',
                'message_sender_role': 'labs_admin_yandex_client',
                'metadata': {
                    'user_id': '12',
                    'user_application': 'labs_admin_yandex',
                    'user_uid': '12',
                    'lab_id': '123',
                    'lab_name': 'lab name',
                    'user_locale': 'ru',
                },
                'message_metadata': {'lab_id': '123', 'lab_name': 'lab name'},
                'include_history': True,
                'scenario_context': None,
            },
            200,
            {
                'chat_id': '5ff4901c583745e089e55be4',
                'chat_open': True,
                'chat_visible': True,
                'ask_csat': False,
                'new_messages': 0,
                'messages': [
                    {
                        'id': 'message_id',
                        'type': 'text',
                        'timestamp': '2018-10-20T12:34:56',
                        'body': 'Привет!',
                        'text': 'Привет!',
                        'author': 'user',
                        'metadata': {'created': '2018-10-20T12:34:56'},
                        'sender': {'id': 'client_id', 'role': 'client'},
                    },
                ],
                'participants': [
                    {'id': 'client_id', 'role': 'client'},
                    {
                        'id': 'support_id',
                        'role': 'support',
                        'nickname': 'support_name',
                        'avatar_url': 'support_avatar',
                    },
                ],
                'actions': [],
                'view': {'show_message_input': True},
                'avatar_url': 'support_avatar',
                'support_name': 'support_name',
            },
        ),
        (
            'eats/v1/support_chat',
            'realtime',
            False,
            {
                'message_id': 'message_id_72343',
                'message': 'Текст сообщения',
                'type': 'text',
                'message_metadata': {},
            },
            {'service': 'eats_app'},
            {
                'X-Real-IP': '1.1.1.1',
                'X-YaTaxi-User': 'eats_user_id=eats_id_72343',
            },
            None,
            {
                'headers': None,
                'owner_id': 'eats_id_72343',
                'owner_role': 'eats_app_client',
                'platform': 'eats_app',
                'message_text': 'Текст сообщения',
                'message_sender_id': 'eats_id_72343',
                'message_sender_role': 'eats_app_client',
                'metadata': {
                    'user_id': 'eats_id_72343',
                    'eats_user_id': 'eats_id_72343',
                    'user_application': 'eats_app',
                    'user_locale': 'ru',
                },
                'message_metadata': {},
                'include_history': True,
                'scenario_context': None,
            },
            200,
            {
                'chat_id': '5ff4901c583745e089e55be4',
                'chat_open': True,
                'chat_visible': True,
                'ask_csat': False,
                'new_messages': 0,
                'messages': [
                    {
                        'id': 'message_id',
                        'type': 'text',
                        'timestamp': '2018-10-20T12:34:56',
                        'body': 'Привет!',
                        'text': 'Привет!',
                        'author': 'user',
                        'metadata': {'created': '2018-10-20T12:34:56'},
                        'sender': {'id': 'client_id', 'role': 'client'},
                    },
                ],
                'participants': [
                    {'id': 'client_id', 'role': 'client'},
                    {
                        'id': 'support_id',
                        'role': 'support',
                        'nickname': 'support_name',
                        'avatar_url': 'support_avatar',
                    },
                ],
                'actions': [],
                'view': {'show_message_input': True},
                'avatar_url': 'support_avatar',
                'support_name': 'support_name',
            },
        ),
        (
            '4.0/support_chat',
            'regular',
            False,
            {
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'csat',
            },
            {'service': 'drive'},
            {'X-Real-IP': '1.1.1.1', constants.YANDEX_UID_HEADER: '12'},
            {
                'headers': None,
                'chat_id': '5ff4901c583745e089e55be4',
                'message_id': '1234567890abcdefghijkl01',
                'message_text': 'Текст сообщения',
                'message_sender_id': '12',
                'message_sender_role': 'carsharing_client',
                'message_metadata': None,
                'update_metadata': {'csat_value': '', 'csat_reasons': []},
                'include_chat': True,
                'scenario_context': None,
            },
            None,
            200,
            {
                'chat_id': '5ff4901c583745e089e55be4',
                'chat_open': True,
                'chat_visible': True,
                'ask_csat': False,
                'new_messages': 0,
                'messages': [
                    {
                        'id': 'message_id',
                        'type': 'text',
                        'timestamp': '2018-10-20T12:34:56',
                        'body': 'Привет!',
                        'text': 'Привет!',
                        'author': 'user',
                        'metadata': {'created': '2018-10-20T12:34:56'},
                        'sender': {'id': 'client_id', 'role': 'client'},
                    },
                ],
                'participants': [
                    {'id': 'client_id', 'role': 'client'},
                    {
                        'id': 'support_id',
                        'role': 'support',
                        'nickname': 'support_name',
                        'avatar_url': 'support_avatar',
                    },
                ],
                'actions': [],
                'view': {'show_message_input': True},
                'avatar_url': 'support_avatar',
                'support_name': 'support_name',
            },
        ),
        (
            '4.0/support_chat',
            'realtime',
            False,
            {
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'csat',
            },
            {'service': 'scouts'},
            {'X-Real-IP': '1.1.1.1', constants.YANDEX_UID_HEADER: '12'},
            {
                'headers': None,
                'chat_id': '5ff4901c583745e089e55be4',
                'message_id': '1234567890abcdefghijkl01',
                'message_text': 'Текст сообщения',
                'message_sender_id': '12',
                'message_sender_role': 'scouts_client',
                'message_metadata': None,
                'update_metadata': {'csat_value': '', 'csat_reasons': []},
                'include_chat': True,
                'scenario_context': None,
            },
            None,
            200,
            {
                'chat_id': '5ff4901c583745e089e55be4',
                'chat_open': True,
                'chat_visible': True,
                'ask_csat': False,
                'new_messages': 0,
                'messages': [
                    {
                        'id': 'message_id',
                        'type': 'text',
                        'timestamp': '2018-10-20T12:34:56',
                        'body': 'Привет!',
                        'text': 'Привет!',
                        'author': 'user',
                        'metadata': {'created': '2018-10-20T12:34:56'},
                        'sender': {'id': 'client_id', 'role': 'client'},
                    },
                ],
                'participants': [
                    {'id': 'client_id', 'role': 'client'},
                    {
                        'id': 'support_id',
                        'role': 'support',
                        'nickname': 'support_name',
                        'avatar_url': 'support_avatar',
                    },
                ],
                'actions': [],
                'view': {'show_message_input': True},
                'avatar_url': 'support_avatar',
                'support_name': 'support_name',
            },
        ),
        (
            '4.0/support_chat',
            'realtime',
            False,
            {
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'csat',
            },
            {'service': 'lavka_storages'},
            {'X-Real-IP': '1.1.1.1', 'X-Taxi-Storage-Id': '12'},
            {
                'headers': None,
                'chat_id': '5ff4901c583745e089e55be4',
                'message_id': '1234567890abcdefghijkl01',
                'message_text': 'Текст сообщения',
                'message_sender_id': '12',
                'message_sender_role': 'lavka_storages_client',
                'message_metadata': None,
                'update_metadata': {'csat_value': '', 'csat_reasons': []},
                'include_chat': True,
                'scenario_context': None,
            },
            None,
            200,
            {
                'chat_id': '5ff4901c583745e089e55be4',
                'chat_open': True,
                'chat_visible': True,
                'ask_csat': False,
                'new_messages': 0,
                'messages': [
                    {
                        'id': 'message_id',
                        'type': 'text',
                        'timestamp': '2018-10-20T12:34:56',
                        'body': 'Привет!',
                        'text': 'Привет!',
                        'author': 'user',
                        'metadata': {'created': '2018-10-20T12:34:56'},
                        'sender': {'id': 'client_id', 'role': 'client'},
                    },
                ],
                'participants': [
                    {'id': 'client_id', 'role': 'client'},
                    {
                        'id': 'support_id',
                        'role': 'support',
                        'nickname': 'support_name',
                        'avatar_url': 'support_avatar',
                    },
                ],
                'actions': [],
                'view': {'show_message_input': True},
                'avatar_url': 'support_avatar',
                'support_name': 'support_name',
            },
        ),
        (
            'eats/v1/website_support_chat',
            'realtime',
            False,
            {
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'csat',
            },
            {'service': 'website'},
            {'X-Real-IP': '1.1.1.1', 'X-Eats-Session': 'test-session-header'},
            {
                'headers': None,
                'chat_id': '5ff4901c583745e089e55be7',
                'message_id': '1234567890abcdefghijkl01',
                'message_text': 'Текст сообщения',
                'message_sender_id': (
                    '13c726a0440481a6d4208f6d834961400f7c8906'
                ),
                'message_sender_role': 'website_client',
                'message_metadata': None,
                'update_metadata': {'csat_value': '', 'csat_reasons': []},
                'include_chat': True,
                'scenario_context': None,
            },
            None,
            200,
            {
                'chat_id': '5ff4901c583745e089e55be4',
                'chat_open': True,
                'chat_visible': True,
                'ask_csat': False,
                'new_messages': 0,
                'messages': [
                    {
                        'id': 'message_id',
                        'type': 'text',
                        'timestamp': '2018-10-20T12:34:56',
                        'body': 'Привет!',
                        'text': 'Привет!',
                        'author': 'user',
                        'metadata': {'created': '2018-10-20T12:34:56'},
                        'sender': {'id': 'client_id', 'role': 'client'},
                    },
                ],
                'participants': [
                    {'id': 'client_id', 'role': 'client'},
                    {
                        'id': 'support_id',
                        'role': 'support',
                        'nickname': 'support_name',
                        'avatar_url': 'support_avatar',
                    },
                ],
                'actions': [],
                'view': {'show_message_input': True},
                'avatar_url': 'support_avatar',
                'support_name': 'support_name',
            },
        ),
        (
            'eats/v1/restapp_support_chat',
            'realtime',
            False,
            {
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'csat',
            },
            {'service': 'restapp'},
            {'X-Real-IP': '1.1.1.1', 'X-YaEda-PartnerId': '12'},
            {
                'headers': None,
                'chat_id': '5ff4901c583745e089e55be4',
                'message_id': '1234567890abcdefghijkl01',
                'message_text': 'Текст сообщения',
                'message_sender_id': '12',
                'message_sender_role': 'restapp_client',
                'message_metadata': None,
                'update_metadata': {'csat_value': '', 'csat_reasons': []},
                'include_chat': True,
                'scenario_context': None,
            },
            None,
            200,
            {
                'chat_id': '5ff4901c583745e089e55be4',
                'chat_open': True,
                'chat_visible': True,
                'ask_csat': False,
                'new_messages': 0,
                'messages': [
                    {
                        'id': 'message_id',
                        'type': 'text',
                        'timestamp': '2018-10-20T12:34:56',
                        'body': 'Привет!',
                        'text': 'Привет!',
                        'author': 'user',
                        'metadata': {'created': '2018-10-20T12:34:56'},
                        'sender': {'id': 'client_id', 'role': 'client'},
                    },
                ],
                'participants': [
                    {'id': 'client_id', 'role': 'client'},
                    {
                        'id': 'support_id',
                        'role': 'support',
                        'nickname': 'support_name',
                        'avatar_url': 'support_avatar',
                    },
                ],
                'actions': [],
                'view': {'show_message_input': True},
                'avatar_url': 'support_avatar',
                'support_name': 'support_name',
            },
        ),
        (
            'eats/v1/restapp_support_chat',
            'realtime',
            False,
            {
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'text',
                'message_metadata': {'eats_order_id': 'test_eats_order_id'},
            },
            {'service': 'restapp'},
            {'X-Real-IP': '1.1.1.1', 'X-YaEda-PartnerId': '12'},
            None,
            {
                'headers': None,
                'owner_id': '12',
                'owner_role': 'restapp_client',
                'platform': 'restapp',
                'message_text': 'Текст сообщения',
                'message_sender_id': '12',
                'message_sender_role': 'restapp_client',
                'metadata': {
                    'user_id': '12',
                    'user_application': 'restapp',
                    'user_locale': 'ru',
                    'eats_order_id': 'test_eats_order_id',
                    'order_id': 'test_eats_order_id',
                },
                'message_metadata': {
                    'eats_order_id': 'test_eats_order_id',
                    'order_id': 'test_eats_order_id',
                },
                'include_history': True,
                'scenario_context': None,
            },
            200,
            {
                'chat_id': '5ff4901c583745e089e55be4',
                'chat_open': True,
                'chat_visible': True,
                'ask_csat': False,
                'new_messages': 0,
                'messages': [
                    {
                        'id': 'message_id',
                        'type': 'text',
                        'timestamp': '2018-10-20T12:34:56',
                        'body': 'Привет!',
                        'text': 'Привет!',
                        'author': 'user',
                        'metadata': {'created': '2018-10-20T12:34:56'},
                        'sender': {'id': 'client_id', 'role': 'client'},
                    },
                ],
                'participants': [
                    {'id': 'client_id', 'role': 'client'},
                    {
                        'id': 'support_id',
                        'role': 'support',
                        'nickname': 'support_name',
                        'avatar_url': 'support_avatar',
                    },
                ],
                'actions': [],
                'view': {'show_message_input': True},
                'avatar_url': 'support_avatar',
                'support_name': 'support_name',
            },
        ),
        (
            '4.0/support_chat',
            'realtime',
            False,
            {
                'message_id': '1234567890abcdefghijkl01',
                'message': 'Текст сообщения',
                'type': 'csat',
            },
            {'service': 'market'},
            {'X-Real-IP': '1.1.1.1', constants.YANDEX_UID_HEADER: '12'},
            {
                'headers': None,
                'chat_id': '5ff4901c583745e089e55be4',
                'message_id': '1234567890abcdefghijkl01',
                'message_text': 'Текст сообщения',
                'message_sender_id': '12',
                'message_sender_role': 'market_client',
                'message_metadata': None,
                'update_metadata': {'csat_value': '', 'csat_reasons': []},
                'include_chat': True,
                'scenario_context': None,
            },
            None,
            200,
            {
                'chat_id': '5ff4901c583745e089e55be4',
                'chat_open': True,
                'chat_visible': True,
                'ask_csat': False,
                'new_messages': 0,
                'messages': [
                    {
                        'id': 'message_id',
                        'type': 'text',
                        'timestamp': '2018-10-20T12:34:56',
                        'body': 'Привет!',
                        'text': 'Привет!',
                        'author': 'user',
                        'metadata': {'created': '2018-10-20T12:34:56'},
                        'sender': {'id': 'client_id', 'role': 'client'},
                    },
                ],
                'participants': [
                    {'id': 'client_id', 'role': 'client'},
                    {
                        'id': 'support_id',
                        'role': 'support',
                        'nickname': 'support_name',
                        'avatar_url': 'support_avatar',
                    },
                ],
                'actions': [],
                'view': {'show_message_input': True},
                'avatar_url': 'support_avatar',
                'support_name': 'support_name',
            },
        ),
    ],
)
async def test_create_user_message(
        stq,
        mock_chat_create,
        protocol_client,
        protocol_app,
        mock,
        patch,
        mock_chat_search,
        mock_chat_add_update,
        mock_get_users,
        prefix,
        chat_type,
        add_actions,
        data,
        params,
        headers,
        expected_add_update_call,
        expected_chat_create_call,
        expected_code,
        expected_result,
):
    mock_chat_create = mock_chat_create(add_actions)

    @patch('taxi.clients.user_api._get_user_phone_from_db')
    async def _get_user_phone_from_db(*args, **kwargs):
        return {
            'phone': '+79099575227 (специалист по мемам)',
            'type': 'yandex',
        }

    response = await protocol_client.post(
        '/{0}/v1/{1}/add_user_message/'.format(prefix, chat_type),
        headers=headers,
        params=params,
        data=json.dumps(data),
    )

    assert response.status == expected_code
    if expected_code == 200:
        assert (
            stq.user_support_chat_message.has_calls
            or stq.support_chat_create_chatterbox_task.has_calls
        )
    if expected_result is not None:
        assert expected_result == await response.json()
    if expected_add_update_call is None:
        assert not mock_chat_add_update.calls
    else:
        kwargs = mock_chat_add_update.calls[0]['kwargs']
        kwargs.pop('log_extra', None)
        assert expected_add_update_call == kwargs
    if expected_chat_create_call is None:
        assert not mock_chat_create.calls
    else:
        kwargs = mock_chat_create.calls[0]['kwargs']
        kwargs.pop('log_extra', None)
        assert expected_chat_create_call == kwargs
