#!/bin/sh

if [ -n "$1" ]
then
    DIRS="$@"
else
    DIRS="driver-partner taxi* tests tariffs replication"
fi

autopep8 --ignore E701 --in-place -r $DIRS

JSON_FILES=$(find $DIRS -name '*.json')

./tools/json-pp --in-place $JSON_FILES
