#!/bin/bash

export PYTHONPATH=../../uservices/submodules/testsuite


if [ -x .venv/bin/python ]; then
    PYTHON=.venv/bin/python
    . .venv/bin/activate
else
    for binary in $(which taxi-python3 python3.8 python3.7 python3); do
        PYTHON=$binary
        break
    done
fi

if [ "x$PYTHON" = "x" ]; then
   exec >&2
   echo "FATAL: No python binary found, sorry"
   exit 1
fi

exec $PYTHON -m pytest --auto-env  "$@"
