import datetime

import pytest


EXPECTED_ANSWER = {
    'page': 1,
    'total': 9,
    'limit': 30,
    'settings': [
        {
            'supporter_login': 'absent_login',
            'piece': True,
            'shift_finish': '2022-01-02T00:00:00',
            'shift_start': '2022-01-01T00:00:00',
            'in_additional_permitted': True,
            'dis_tickets_off_shift': False,
            'assigned_lines': [],
            'can_choose_from_assigned_lines': True,
            'can_choose_except_assigned_lines': True,
            'max_tickets_per_shift': 0,
            'max_chats_chatterbox': 12,
            'cash': 10.0,
            'block_tickets': True,
            'reason_block_tickets': ['absence'],
            'disable_access_day': '2022-05-31',
        },
        {
            'supporter_login': 'disabled_login',
            'languages': ['ru'],
            'piece': True,
            'shift_finish': '2022-01-02T00:00:00',
            'shift_start': '2022-01-01T00:00:00',
            'in_additional_permitted': True,
            'dis_tickets_off_shift': False,
            'assigned_lines': [],
            'can_choose_from_assigned_lines': True,
            'can_choose_except_assigned_lines': True,
            'max_tickets_per_shift': 0,
            'max_chats_chatterbox': 12,
            'cash': 10.0,
            'block_tickets': False,
            'reason_block_tickets': [],
            'disable_access_day': '2020-05-29',
        },
        {
            'supporter_login': 'login_with_minimum_info',
            'shift_finish': '2022-01-02T00:00:00',
            'shift_start': '2022-01-01T00:00:00',
            'in_additional_permitted': True,
            'piece': True,
            'assigned_lines': [],
            'can_choose_from_assigned_lines': True,
            'can_choose_except_assigned_lines': True,
            'block_tickets': False,
            'reason_block_tickets': [],
        },
        {
            'supporter_login': 'not_compendium_user',
            'assigned_lines': [],
            'block_tickets': False,
            'can_choose_except_assigned_lines': True,
            'can_choose_from_assigned_lines': True,
            'in_additional_permitted': True,
            'piece': True,
            'reason_block_tickets': [],
            'shift_finish': '2022-01-02T00:00:00',
            'shift_start': '2022-01-01T00:00:00',
        },
        {
            'supporter_login': 'not_on_piece_login',
            'languages': ['ru', 'en'],
            'piece': False,
            'shift_finish': '2022-01-02T00:00:00',
            'shift_start': '2022-01-01T00:00:00',
            'in_additional_permitted': True,
            'dis_tickets_off_shift': False,
            'assigned_lines': [],
            'can_choose_from_assigned_lines': True,
            'can_choose_except_assigned_lines': True,
            'max_chats_chatterbox': 12,
            'cash': 10.0,
            'block_tickets': False,
            'reason_block_tickets': [],
            'disable_access_day': '2022-05-31',
        },
        {
            'supporter_login': 'not_use_reserves_login',
            'piece': True,
            'shift_finish': '2022-01-02T00:00:00',
            'shift_start': '2022-01-01T00:00:00',
            'in_additional_permitted': True,
            'dis_tickets_off_shift': False,
            'assigned_lines': [],
            'can_choose_from_assigned_lines': True,
            'can_choose_except_assigned_lines': True,
            'max_chats_chatterbox': 3,
            'cash': -10.0,
            'block_tickets': False,
            'reason_block_tickets': [],
            'disable_access_day': '2022-06-01',
        },
        {
            'supporter_login': 'regular_login',
            'languages': ['ru', 'en'],
            'piece': True,
            'shift_finish': '2022-01-02T00:00:00',
            'shift_start': '2022-01-01T00:00:00',
            'in_additional_permitted': True,
            'dis_tickets_off_shift': False,
            'assigned_lines': ['line_1', 'line_2'],
            'can_choose_from_assigned_lines': True,
            'can_choose_except_assigned_lines': True,
            'max_chats_chatterbox': 12,
            'cash': 12.0,
            'block_tickets': False,
            'reason_block_tickets': [],
            'disable_access_day': '2022-05-31',
        },
        {
            'assigned_lines': [],
            'supporter_login': 'returned_after_dismiss_user',
            'block_tickets': False,
            'can_choose_except_assigned_lines': True,
            'can_choose_from_assigned_lines': True,
            'disable_access_day': '2019-12-27',
            'in_additional_permitted': True,
            'piece': True,
            'reason_block_tickets': [],
            'shift_finish': '2022-01-02T00:00:00',
            'shift_start': '2022-01-01T00:00:00',
        },
        {
            'supporter_login': 'use_reserves_login',
            'piece': True,
            'shift_finish': '2022-01-02T00:00:00',
            'shift_start': '2022-01-01T00:00:00',
            'in_additional_permitted': True,
            'dis_tickets_off_shift': False,
            'assigned_lines': [],
            'can_choose_from_assigned_lines': True,
            'can_choose_except_assigned_lines': True,
            'max_chats_chatterbox': 3,
            'max_tickets_per_shift': 0,
            'cash': -10.0,
            'block_tickets': False,
            'reason_block_tickets': [],
            'disable_access_day': '2022-05-20',
        },
    ],
}


@pytest.mark.now(datetime.datetime(2022, 1, 1).isoformat())
@pytest.mark.config(
    AGENT_PROJECT_SETTINGS={
        'default': {'enable_chatterbox': False},
        'calltaxi': {
            'enable_chatterbox': True,
            'main_permission': 'user_calltaxi',
        },
    },
)
async def test_get_support_settings(
        web_app_client, web_context, mock_picework_reserve_current,
):
    response = await web_app_client.get('/get_support_settings')
    assert response.status == 200

    answer = await response.json()
    assert answer == EXPECTED_ANSWER
