import pytest

TRANSLATE = {
    'not_admin_for': {
        'ru': 'Нет админских прав для: view admin listing goods',
        'en': 'Not admin for: {action}',
    },
    'test_name': {'ru': 'тест-промо', 'en': 'test-promo'},
    '2test_name': {'ru': '2тест-промо', 'en': '2test-promo'},
    '3test_name': {'ru': '3тест-промо', 'en': '3test-promo'},
    '4test_name': {'ru': '4тест-промо', 'en': '4test-promo'},
    'test_attr': {'ru': 'тест-аттр', 'en': 'test-attr'},
    '2test_attr': {'ru': '2тест-аттр', 'en': '2test-attr'},
    '3test_attr': {'ru': '3тест-аттр', 'en': '3test-attr'},
    'test_attr2': {'ru': 'тест-аттр2', 'en': 'test-attr2'},
    '2test_attr2': {'ru': '2тест-аттр2', 'en': '2test-attr2'},
    '3test_attr2': {'ru': '3тест-аттр2', 'en': '3test-attr2'},
    'test_attr3': {'ru': 'тест-аттр3', 'en': 'test-attr3'},
    '2test_attr3': {'ru': '2тест-аттр3', 'en': '2test-attr3'},
    '3test_attr3': {'ru': '3тест-аттр3', 'en': '3test-attr3'},
}

TEST_DATA = '2021-01-01T00:00:00Z'


@pytest.mark.translations(agent=TRANSLATE)
@pytest.mark.parametrize(
    'headers,status,response_content',
    [
        (
            {},
            400,
            {
                'code': 'REQUEST_VALIDATION_ERROR',
                'details': {'reason': 'X-Yandex-Login is required parameter'},
                'message': 'Some parameters are invalid',
            },
        ),
        (
            {'X-Yandex-Login': 'webalex', 'Accept-Language': 'ru-ru'},
            200,
            {
                'ok': False,
                'goods_list': [],
                'message': 'Нет админских прав для: view admin listing goods',
            },
        ),
        (
            {'X-Yandex-Login': 'mikh-vasily', 'Accept-Language': 'ru-ru'},
            200,
            {
                'ok': True,
                'goods_list': [
                    {
                        'id': 1,
                        'categories': [
                            {'id': 'test1', 'name': 'Test'},
                            {'id': 'test2', 'name': 'Test'},
                            {'id': 'test3', 'name': 'Test'},
                        ],
                        'ru_name': 'test_name',
                        'en_name': 'test_name',
                        'type': 'test_type',
                        'created': TEST_DATA,
                        'updated': TEST_DATA,
                        'creator': 'mikh-vasily',
                        'visible': True,
                        'permission': 'read_shop_test_taxi',
                        'ru_description': 'test_description',
                        'en_description': 'test_description',
                        'image_mds_id': 'test_image',
                        'amount': 10,
                        'assortment': [
                            {
                                'id': 1,
                                'goods_id': 1,
                                'created': TEST_DATA,
                                'updated': TEST_DATA,
                                'visible': True,
                                'creator': 'mikh-vasily',
                                'price': 222.33,
                                'ru_attribute': 'test_attr',
                                'en_attribute': 'test_attr',
                                'amount': 2,
                            },
                            {
                                'id': 2,
                                'goods_id': 1,
                                'created': TEST_DATA,
                                'updated': TEST_DATA,
                                'visible': False,
                                'creator': 'mikh-vasily',
                                'price': 333.22,
                                'ru_attribute': 'test_attr2',
                                'en_attribute': 'test_attr2',
                                'amount': 3,
                            },
                            {
                                'id': 3,
                                'goods_id': 1,
                                'created': TEST_DATA,
                                'updated': TEST_DATA,
                                'visible': True,
                                'creator': 'mikh-vasily',
                                'price': 4444.55,
                                'ru_attribute': 'test_attr3',
                                'en_attribute': 'test_attr3',
                                'amount': 5,
                            },
                        ],
                    },
                    {
                        'id': 2,
                        'categories': [
                            {'id': 'test2', 'name': 'Test'},
                            {'id': 'test3', 'name': 'Test'},
                        ],
                        'ru_name': '2test_name',
                        'en_name': '2test_name',
                        'type': '2test_type',
                        'created': TEST_DATA,
                        'updated': TEST_DATA,
                        'creator': 'mikh-vasily',
                        'visible': True,
                        'permission': 'read_shop_test_eda',
                        'ru_description': '2test_description',
                        'en_description': '2test_description',
                        'image_mds_id': '2test_image',
                        'amount': 12,
                        'assortment': [
                            {
                                'id': 4,
                                'goods_id': 2,
                                'created': TEST_DATA,
                                'updated': TEST_DATA,
                                'visible': True,
                                'creator': 'mikh-vasily',
                                'price': 111.33,
                                'ru_attribute': '2test_attr',
                                'en_attribute': '2test_attr',
                                'amount': 7,
                            },
                            {
                                'id': 5,
                                'goods_id': 2,
                                'created': TEST_DATA,
                                'updated': TEST_DATA,
                                'visible': True,
                                'creator': 'mikh-vasily',
                                'price': 311.22,
                                'ru_attribute': '2test_attr2',
                                'en_attribute': '2test_attr2',
                                'amount': 4,
                            },
                            {
                                'id': 6,
                                'goods_id': 2,
                                'created': TEST_DATA,
                                'updated': TEST_DATA,
                                'visible': True,
                                'creator': 'mikh-vasily',
                                'price': 4111.55,
                                'ru_attribute': '2test_attr3',
                                'en_attribute': '2test_attr3',
                                'amount': 1,
                            },
                        ],
                    },
                    {
                        'id': 3,
                        'categories': [],
                        'ru_name': '3test_name',
                        'en_name': '3test_name',
                        'type': '3test_type',
                        'created': TEST_DATA,
                        'updated': TEST_DATA,
                        'creator': 'mikh-vasily',
                        'visible': False,
                        'permission': 'read_shop_test_eda',
                        'ru_description': '3test_description',
                        'en_description': '3test_description',
                        'image_mds_id': '3test_image',
                        'amount': 12,
                        'assortment': [
                            {
                                'id': 7,
                                'goods_id': 3,
                                'created': TEST_DATA,
                                'updated': TEST_DATA,
                                'visible': False,
                                'creator': 'mikh-vasily',
                                'price': 111.33,
                                'ru_attribute': '3test_attr',
                                'en_attribute': '3test_attr',
                                'amount': 7,
                            },
                            {
                                'id': 8,
                                'goods_id': 3,
                                'created': TEST_DATA,
                                'updated': TEST_DATA,
                                'visible': False,
                                'creator': 'mikh-vasily',
                                'price': 311.22,
                                'ru_attribute': '3test_attr2',
                                'en_attribute': '3test_attr2',
                                'amount': 4,
                            },
                            {
                                'id': 9,
                                'goods_id': 3,
                                'created': TEST_DATA,
                                'updated': TEST_DATA,
                                'visible': False,
                                'creator': 'mikh-vasily',
                                'price': 4111.55,
                                'ru_attribute': '3test_attr3',
                                'en_attribute': '3test_attr3',
                                'amount': 1,
                            },
                        ],
                    },
                    {
                        'id': 4,
                        'categories': [],
                        'ru_name': '4test_name',
                        'en_name': '4test_name',
                        'type': '4test_type',
                        'created': TEST_DATA,
                        'updated': TEST_DATA,
                        'creator': 'mikh-vasily',
                        'visible': True,
                        'permission': 'read_shop_test_eda',
                        'ru_description': '4test_description',
                        'en_description': '4test_description',
                        'image_mds_id': '4test_image',
                        'amount': 0,
                        'assortment': [],
                    },
                ],
            },
        ),
    ],
)
async def test_get_list_goods(
        web_app_client, headers, status, response_content,
):
    response = await web_app_client.get(
        '/shop/goods/admin-list', headers=headers,
    )
    assert response.status == status
    content = await response.json()
    assert content == response_content
