INSERT INTO price_modifications.rules
    (rule_id, name, source_code, policy, author, approvals_id, ast, updated, deleted, previous_version_id, startrek_ticket)
  VALUES
    (0, 'one', 'return 11;', 'backend_only', '200ok', 00, 'CR(boarding=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(boarding)),distance=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(distance)),time=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(time)),waiting=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(waiting)),requirements=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(requirements)),transit_waiting=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(transit_waiting)),destination_waiting=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(destination_waiting)))', '2010-03-04 06:00:00', true, null, null),
    (1, 'one', 'return 1;', 'backend_only', '200ok', 11, 'CR(boarding=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(boarding)),distance=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(distance)),time=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(time)),waiting=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(waiting)),requirements=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(requirements)),transit_waiting=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(transit_waiting)),destination_waiting=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(destination_waiting)))', '2010-04-04 06:00:00', false, 0, 'EFFICIENCYDEV-16339'),
    (2, 'two', 'return 2;', 'backend_only', '200ok', 22, 'CR(boarding=B(B(B(2.000000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(boarding)),distance=B(B(B(2.000000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(distance)),time=B(B(B(2.000000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(time)),waiting=B(B(B(2.000000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(waiting)),requirements=B(B(B(2.000000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(requirements)),transit_waiting=B(B(B(2.000000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(transit_waiting)),destination_waiting=B(B(B(2.000000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(destination_waiting)))', '2011-04-04 06:00:00', false, null, null),
    (3, 'three', 'return 3;', 'both_side', '200ok', 33, 'CR(boarding=B(B(B(3.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(boarding)),distance=B(B(B(3.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(distance)),time=B(B(B(3.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(time)),waiting=B(B(B(3.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(waiting)),requirements=B(B(B(3.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(requirements)),transit_waiting=B(B(B(3.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(transit_waiting)),destination_waiting=B(B(B(3.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(destination_waiting)))', '2012-04-04 06:00:00', false, null, null),
    (4, 'four', 'return 4;', 'backend_only', '200ok', 44, 'CR(boarding=B(B(B(4.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(boarding)),distance=B(B(B(4.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(distance)),time=B(B(B(4.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(time)),waiting=B(B(B(4.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(waiting)),requirements=B(B(B(4.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(requirements)),transit_waiting=B(B(B(4.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(transit_waiting)),destination_waiting=B(B(B(4.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(destination_waiting)))', '2013-04-04 06:00:00', false, null, null),
    (5, 'five', 'return 5;', 'taximeter_only', '200ok', 55, 'CR(boarding=B(B(B(5.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(boarding)),distance=B(B(B(5.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(distance)),time=B(B(B(5.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(time)),waiting=B(B(B(5.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(waiting)),requirements=B(B(B(5.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(requirements)),transit_waiting=B(B(B(5.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(transit_waiting)),destination_waiting=B(B(B(5.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(destination_waiting)))', '2014-04-04 06:00:00', false, null, null)
;

INSERT INTO price_modifications.rules_drafts
    (rule_id, name, source_code, policy, author, status, errors, ast, updated, pmv_task_id, approvals_id, evaluate_on_prestable, prestable_evaluation_begin_time, startrek_ticket)
  VALUES
    (6, 'a_draft', 'return 1.1;', 'backend_only', '200ok draft', 'running', NULL, 'CR(boarding=B(B(B(1.10000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(boarding)),distance=B(B(B(1.10000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(distance)),time=B(B(B(1.10000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(time)),waiting=B(B(B(1.10000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(waiting)),requirements=B(B(B(1.10000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(requirements)),transit_waiting=B(B(B(1.10000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(transit_waiting)),destination_waiting=B(B(B(1.10000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(destination_waiting)))', '2014-05-04 06:00:00', 1, 11, true, '2020-05-03 19:10:25+03', null),
    (7, 'one', 'return 2.2;', 'backend_only', '200ok draft', 'failure', 'error message', 'CR(boarding=B(B(B(2.20000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(boarding)),distance=B(B(B(2.20000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(distance)),time=B(B(B(2.20000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(time)),waiting=B(B(B(2.20000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(waiting)),requirements=B(B(B(2.20000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(requirements)),transit_waiting=B(B(B(2.20000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(transit_waiting)),destination_waiting=B(B(B(2.20000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(destination_waiting)))', '2014-06-04 06:00:00', 2, 22, true, null, 'EFFICIENCYDEV-16339'), /* not "one_draft" for test with same names */
    (8, 'two_draft', 'return 3.3;', 'backend_only', '200ok draft', 'running', 'error message', 'CR(boarding=B(B(B(3.30000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(boarding)),distance=B(B(B(3.30000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(distance)),time=B(B(B(3.30000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(time)),waiting=B(B(B(3.30000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(waiting)),requirements=B(B(B(3.30000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(requirements)),transit_waiting=B(B(B(3.30000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(transit_waiting)),destination_waiting=B(B(B(3.30000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(destination_waiting)))', '2014-07-04 06:00:00', 3, 33, true, null, null),
    (9, 'three_draft', 'return 4.4;', 'backend_only', '200ok draft', 'failure', 'error message', 'CR(boarding=B(B(B(4.40000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(boarding)),distance=B(B(B(4.40000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(distance)),time=B(B(B(4.40000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(time)),waiting=B(B(B(4.40000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(waiting)),requirements=B(B(B(4.40000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(requirements)),transit_waiting=B(B(B(4.40000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(transit_waiting)),destination_waiting=B(B(B(4.40000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(destination_waiting)))', '2014-08-04 06:00:00', 4, 44, false, null, null),
    (10, 'four_draft', 'return 5.5;', 'both_side', '200ok draft', 'failure', 'error message', 'CR(boarding=B(B(B(5.50000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(boarding)),distance=B(B(B(5.50000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(distance)),time=B(B(B(5.50000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(time)),waiting=B(B(B(5.50000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(waiting)),requirements=B(B(B(5.50000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(requirements)),transit_waiting=B(B(B(5.50000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(transit_waiting)),destination_waiting=B(B(B(5.50000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(destination_waiting)))', '2014-09-04 06:00:00', 5, 55, false, null, null),
    (11, 'five_draft', 'return 6.6;', 'taximeter_only', '200ok draft', 'failure', 'error message', 'CR(boarding=B(B(B(6.60000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(boarding)),distance=B(B(B(6.60000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(distance)),time=B(B(B(6.60000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(time)),waiting=B(B(B(6.60000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(waiting)),requirements=B(B(B(6.60000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(requirements)),transit_waiting=B(B(B(6.60000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(transit_waiting)),destination_waiting=B(B(B(6.60000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(destination_waiting)))', '2014-10-04 06:00:00', 6, 66, false, null, null)
;


