async def test_autogenerated_datasources(taxi_userver_sample):
    response = await taxi_userver_sample.get('autogen/datasources?baz=bar')
    assert response.status_code == 200
    assert response.json() == {'length': 3}
