insert into payments.payouts(
      amount,
      client_id,
      contract_id,
      currency,
      dry_run,
      firm_id,
      payload,
      payment_processor,
      payment_type,
      person_id,
      source_id,
      source_type
) values
(
      '1500.00',
      '1349515601',
      '3697999',
      'RUB',
      False,
      98765,
      '{"pro_payload": {"pro_category_id": "PAYMENT_ORDER", "pro_order_id": "6d5144addb183c86acee401124cb2c1f"}, "payment_group": "PAYMENT"}'::jsonb,
      'YA_BANK',
      'PAYMENT_ORDER',
      '123',
      '3',
      'TAXI'
),
(
      '1100.00',
      '1349515601',
      '3697999',
      'RUB',
      False,
      98765,
      '{"pro_payload": {"pro_category_id": "PAYMENT_REQUIREMENT", "pro_order_id": "6d5144addb183c86acee401124cb2c1f"}, "payment_group": "REVENUE", "account": "ЛСТ-1234567"}'::jsonb,
      'YA_BANK',
      'PAYMENT_REQUIREMENT',
      '123',
      '4',
      'TAXI'
),
(
      '500.00',
      '1349515601',
      '3697999',
      'RUB',
      False,
      98765,
      '{"pro_payload": {"pro_category_id": "PAYMENT_REQUIREMENT", "pro_order_id": "6d5144addb183c86acee401124cb2c1f"}, "payment_group": "REVENUE"}'::jsonb,
      'YA_BANK',
      'PAYMENT_REQUIREMENT',
      '123',
      '1',
      'TAXI'
);


insert into payments.payout_event_log(
    payout_id,
    status,
    idempotency_key,
    payment_id
) values
(
    1,
    'NEW',
    '1/NEW',
    NULL
),
(
    2,
    'NEW',
    '2/NEW',
    NULL
),
(
    3,
    'NEW',
    '3/NEW',
    NULL
),
(
    3,
    'PROCESSED',
    '3/PROCESSED',
    123456
);
