#!/usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = "Zasimov Alexey"
__email__ = "zasimov-a@yandex-team.ru"

u"""
Создание подложки для виджета.
"""

from wp7desktop.share.wp7.backing import widget_backing


if __name__ == "__main__":
    backing = widget_backing()
    del backing
    backing = widget_backing((1.0, 1.0, 1.0, 0.0))
    del backing
    backing = widget_backing((1.0, 1.0, 0.0))
    del backing
