INSERT INTO callcenter_auth.operators_access
    (yandex_uid, yandex_login, callcenter_id, first_name, last_name, deleted_at, updated_at, state, password, supervisor_login, phone_number, working_domain, operator_id, name_in_telephony)
VALUES
    ('uid1', 'login1', 'cc1', 'name1', 'surname', NULL, '2018-06-22 19:00:00+00'::TIMESTAMPTZ, 'ready', 'DBg+FwQTGD4XBB4WOBoLUg==', 'admin', '+111', 'unit.test', 1000000000, 'tel_name');

INSERT INTO callcenter_auth.current_info
     ( id, last_visited_at, status, metaqueues, updated_at)
VALUES
    ( 1, '2018-06-22 19:00:00+00'::TIMESTAMPTZ,  'connected', '{ru_taxi_disp}', '2018-06-22 19:00:00+00'::TIMESTAMPTZ);

INSERT INTO callcenter_auth.m2m_operators_roles
    (yandex_uid, role)
VALUES
    ('uid1', 'supervisor');
