INSERT INTO callcenter_auth.operators_access
    (yandex_uid, yandex_login, callcenter_id, first_name, last_name, created_at, deleted_at, updated_at, state, password, supervisor_login, phone_number, working_domain, operator_id, staff_login, staff_login_state, mentor_login, employment_date, name_in_telephony)
VALUES
    ('uid1', 'login1', 'cc1', 'name1', 'surname', '2018-06-21 20:00:00+00'::TIMESTAMPTZ, NULL, '2018-06-22 19:00:00+00'::TIMESTAMPTZ, 'ready', 'DBg+FwQTGD4XBB4WOBoLUg==', 'admin@unit.test', '+111', 'unit.test', 1000000000, NULL, 'unverified', NULL, '2018-06-21'::DATE, 'tel_name'),
    ('uid2', 'login2', 'cc1', 'name2', 'surname', '2018-06-21 19:00:00+00'::TIMESTAMPTZ, NULL, '2018-06-22 19:00:00+00'::TIMESTAMPTZ, 'ready', 'DBg+FwQTGD4XBB4WOBoLUg==', 'admin@unit.test', '+111', 'unit.test',  1000000001, 'staff_login2', 'unverified', NULL, '2018-06-21'::DATE, 'tel_name'),
    ('uid3', 'login3', 'cc2', 'name3', 'surname', '2018-06-21 19:00:00+00'::TIMESTAMPTZ, NULL, '2018-06-22 19:00:00+00'::TIMESTAMPTZ,  'ready', 'DBg+FwQTGD4XBB4WOBoLUg==', 'admin@unit.test', '+111', 'unit.test', 1000000002, 'not_staff_login3', 'unverified', NULL, '2018-06-21'::DATE, 'tel_name'),
    ('uid4', 'login4', 'cc1', 'name4', 'surname', '2018-06-21 19:00:00+00'::TIMESTAMPTZ, NULL, '2018-06-22 19:00:00+00'::TIMESTAMPTZ, 'ready', 'DBg+FwQTGD4XBB4WOBoLUg==', 'admin@unit.test', '+111', 'unit.test',  NULL, 'not_staff_login4', 'report_sent', NULL, '2018-06-21'::DATE, 'tel_name'),
    ('uid5', 'login5', 'cc2', 'name5', 'surname', '2018-06-21 20:00:00+00'::TIMESTAMPTZ, NULL, '2018-06-22 19:00:00+00'::TIMESTAMPTZ,  'ready', 'DBg+FwQTGD4XBB4WOBoLUg==', 'admin@unit.test', '+111', 'unit.test',  NULL, NULL, 'unverified', NULL, '2018-06-21'::DATE, 'tel_name'),
    ('uid6', 'staff_login6', 'cc2', 'name6', 'surname', '2018-06-21 19:00:00+00'::TIMESTAMPTZ, NULL, '2018-06-22 19:00:00+00'::TIMESTAMPTZ,'ready', 'DBg+FwQTGD4XBB4WOBoLUg==', 'admin@unit.test', '+111', 'unit.test',   NULL, NULL, 'report_sent', NULL, '2018-06-21'::DATE, 'tel_name'),
    ('uid7', 'staff_login7', 'cc2', 'name7', 'surname', '2018-06-21 19:00:00+00'::TIMESTAMPTZ, NULL, '2018-06-22 19:00:00+00'::TIMESTAMPTZ, 'ready', 'DBg+FwQTGD4XBB4WOBoLUg==', 'admin@unit.test', '+111', 'unit.test',   NULL, 'staff_login7', 'unverified', NULL, '2018-06-21'::DATE, 'tel_name'),
    ('uid8', 'login8', 'cc2', 'name8', 'surname', '2018-06-21 19:00:00+00'::TIMESTAMPTZ, NULL, '2018-06-22 19:00:00+00'::TIMESTAMPTZ, 'ready', 'DBg+FwQTGD4XBB4WOBoLUg==', 'admin@unit.test', '+111', 'unit.test',  NULL, 'staff_login8', 'unverified', NULL, '2018-06-21'::DATE, 'tel_name'),
    ('uid9', 'login9', 'cc2', 'name9', 'surname', '2018-06-21 19:00:00+00'::TIMESTAMPTZ, NULL, '2018-06-22 19:00:00+00'::TIMESTAMPTZ,'ready', 'DBg+FwQTGD4XBB4WOBoLUg==', 'admin@unit.test', '+111', 'unit.test',   NULL, 'staff_login9', 'verified', NULL, '2018-06-21'::DATE, 'tel_name');


INSERT INTO callcenter_auth.current_info
    ( id, last_visited_at, status, metaqueues, updated_at, is_form_opened)
VALUES
    ( 1, '2018-06-22 19:00:00+00'::TIMESTAMPTZ, 'connected', '{ru_taxi_disp}', '2018-06-22 19:00:00+00'::TIMESTAMPTZ, True),
    ( 2, '2018-06-22 19:00:00+00'::TIMESTAMPTZ, 'paused', '{ru_taxi_disp}', '2018-06-22 19:00:00+00'::TIMESTAMPTZ, True),
    ( 3, '2018-06-22 19:00:00+00'::TIMESTAMPTZ, 'disconnected', '{}', '2018-06-22 19:00:00+00'::TIMESTAMPTZ, True);

INSERT INTO callcenter_auth.m2m_operators_roles
    (yandex_uid, role)
VALUES
    ('uid1', 'operator'),
    ('uid2', 'operator'),
    ('uid3', 'operator'),
    ('uid4', 'operator'),
    ('uid5', 'operator'),
    ('uid6', 'operator'),
    ('uid7', 'operator'),
    ('uid8', 'supervisor'),
    ('uid9', 'operator');
