\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.0.1.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.0.2.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.0.3.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.0.4.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.0.5.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.0.6.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.0.7.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.0.8.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.0.9.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.0.10.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.0.11.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.0.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.1.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.2.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.3.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.4.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.5.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.6.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.7.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.8.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.9.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.10.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.11.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.12.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.13.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.14.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.15.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.16.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.17.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.18.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.19.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.1.20.psql
\ir ../../../hiring_candidates/storage/postgresql/schemas/hiring_candidates_0.2.0.psql
