import pytest


@pytest.mark.pgsql(
    'billing_commissions', files=['test_rules_v1_rules_list.sql'],
)
async def test_v1_rules_list(taxi_billing_commissions):
    response = await taxi_billing_commissions.get(
        'v1/rules/list', params={'tariff_zone': 'moscow'},
    )
    assert response.status_code == 200, response.json()
    assert response.json()['items'] == RULES


RULES = [
    {
        'agent_percent': '0.0001',
        'acquiring_percent': '0.0200',
        'begin': '2018-12-31T20:00:00',
        'billable_cancel_distance': 300,
        'branding_discounts': [],
        'callcenter_commission_percent': '0.0000',
        'cancel_percent': '0.0000',
        'end': '2030-01-01T00:00:00',
        'expired_cost': '800.0000',
        'expired_percent': '0.1100',
        'has_fixed_cancel_percent': False,
        'id': 'some_fixed_percent_commission_contract_id_in_future_end',
        'max_order_cost': '6000.0000',
        'min_order_cost': '0.0000',
        'park_cancel_max_td': 600,
        'park_cancel_min_td': 420,
        'payment_type': 'corp',
        'percent': '0.1100',
        'taximeter_payment': '1.0000',
        'type': 'fixed_percent',
        'user_cancel_max_td': 600,
        'user_cancel_min_td': 120,
        'vat': '1.1800',
        'zone': 'moscow',
        #  actions
        'is_editable': True,
        'is_active': True,
        'is_deletable': False,
        'log_count': 0,
        # hiring section
        'hiring': '0.0200',
        'hiring_age': 180,
        'hiring_commercial': '0.0400',
    },
    {
        'acquiring_percent': '0.0000',
        'agent_percent': '0.0001',
        'asymp': '16.0000',
        'begin': '2017-09-12T17:05:00',
        'billable_cancel_distance': 300,
        'branding_discounts': [],
        'callcenter_commission_percent': '0.0000',
        'cancel_percent': '0.0000',
        'cost_norm': '10.7107',
        'end': '2017-12-06T19:20:00',
        'expired_cost': '800.0000',
        'expired_percent': '0.1100',
        'has_fixed_cancel_percent': True,
        'id': 'pool_htan_commission',
        'kc': '0.4000',
        'ks': '2.7000',
        'max_commission_percent': '0.1600',
        'max_diff': '200.0000',
        'max_order_cost': '600.0000',
        'max_rel_profit': '2.4000',
        'min_order_cost': '0.0000',
        'min_rel_profit': '0.7700',
        'numerator': '374.1000',
        'park_cancel_max_td': 600,
        'park_cancel_min_td': 420,
        'payment_type': 'pool',
        'taximeter_payment': '0.0000',
        'type': 'pool_htan',
        'user_cancel_max_td': 600,
        'user_cancel_min_td': 120,
        'vat': '1.1800',
        'zone': 'moscow',
        #  actions
        'is_editable': False,
        'is_active': False,
        'is_deletable': False,
        'log_count': 0,
        # hiring section
        'hiring': '0.0000',
        'hiring_age': 0,
        'hiring_commercial': '0.0000',
    },
    {
        'acquiring_percent': '0.0200',
        'agent_percent': '0.0001',
        'begin': '2017-01-01T00:00:00',
        'billable_cancel_distance': 300,
        'callcenter_commission_percent': '0.0000',
        'end': '2018-01-01T00:00:00',
        'id': 'some_absolute_value_commission_contract_id',
        'branding_discounts': [],
        'max_order_cost': '6000.0000',
        'min_order_cost': '0.0000',
        'park_cancel_max_td': 600,
        'park_cancel_min_td': 420,
        'payment_type': 'cash',
        'tag': 'great_tag',
        'taximeter_payment': '0.0000',
        'type': 'absolute_value',
        'user_cancel_max_td': 600,
        'user_cancel_min_td': 120,
        'vat': '1.1800',
        'zone': 'moscow',
        #  absolute value
        'cancel_commission': '200.0000',
        'commission': '300.0000',
        'expired_commission': '100.0000',
        #  actions
        'is_editable': False,
        'is_active': False,
        'is_deletable': False,
        'log_count': 0,
        # hiring section
        'hiring': '0.0200',
        'hiring_age': 180,
        'hiring_commercial': '0.0400',
    },
    {
        'acquiring_percent': '0.0200',
        'agent_percent': '0.0001',
        'begin': '2016-12-30T20:00:00',
        'end': '2018-01-01T00:00:00',
        'id': 'some_fixed_percent_commission_contract_id',
        'billable_cancel_distance': 300,
        'callcenter_commission_percent': '0.0000',
        'max_order_cost': '6000.0000',
        'min_order_cost': '0.0000',
        'park_cancel_max_td': 600,
        'park_cancel_min_td': 420,
        'payment_type': 'cash',
        'taximeter_payment': '3.9000',
        'type': 'fixed_percent',
        'user_cancel_max_td': 600,
        'user_cancel_min_td': 120,
        'vat': '1.1800',
        'zone': 'moscow',
        #  percent
        'expired_cost': '800.0000',
        'expired_percent': '0.1100',
        'has_fixed_cancel_percent': False,
        'branding_discounts': [],
        'cancel_percent': '0.0000',
        #  fixed_percent
        'percent': '0.1100',
        #  actions
        'is_editable': False,
        'is_active': False,
        'is_deletable': False,
        'log_count': 0,
        # hiring section
        'hiring': '0.0200',
        'hiring_age': 180,
        'hiring_commercial': '0.0400',
    },
    {
        'acquiring_percent': '0.0200',
        'agent_percent': '0.0001',
        'begin': '2016-12-30T20:00:00',
        'billable_cancel_distance': 300,
        'callcenter_commission_percent': '0.0000',
        'id': 'some_fixed_percent_commission_contract_id_with_unlimited_end',
        'tag': 'some_tag',
        'max_order_cost': '6000.0000',
        'min_order_cost': '0.0000',
        'park_cancel_max_td': 600,
        'park_cancel_min_td': 420,
        'payment_type': 'cash',
        'taximeter_payment': '1.0000',
        'type': 'fixed_percent',
        'user_cancel_max_td': 600,
        'user_cancel_min_td': 120,
        'vat': '1.1800',
        'zone': 'moscow',
        #  percent
        'expired_cost': '800.0000',
        'expired_percent': '0.1100',
        'has_fixed_cancel_percent': False,
        'branding_discounts': [],
        'cancel_percent': '0.0000',
        #  fixed_percent
        'percent': '0.1100',
        #  actions
        'is_editable': True,
        'is_active': True,
        'is_deletable': False,
        'log_count': 0,
        # hiring section
        'hiring': '0.0200',
        'hiring_age': 180,
        'hiring_commercial': '0.0400',
    },
    {
        'acquiring_percent': '0.0200',
        'agent_percent': '0.0001',
        'begin': '2016-12-30T20:00:00',
        'billable_cancel_distance': 300,
        'callcenter_commission_percent': '0.0000',
        'end': '2017-12-31T00:00:00',
        'id': 'some_asymptotic_formula_commission_contract_id',
        'tariff_class': 'uberkids',
        'max_order_cost': '6000.0000',
        'min_order_cost': '0.0000',
        'park_cancel_max_td': 600,
        'park_cancel_min_td': 420,
        'payment_type': 'cash',
        'taximeter_payment': '0.0005',
        'type': 'asymptotic_formula',
        'user_cancel_max_td': 600,
        'user_cancel_min_td': 120,
        'vat': '1.1800',
        'zone': 'moscow',
        #  percent
        'expired_cost': '800.0000',
        'expired_percent': '0.1100',
        'has_fixed_cancel_percent': True,
        'branding_discounts': [
            {
                'marketing_level': ['lightbox', 'co_branding', 'sticker'],
                'value': '0.0500',
            },
        ],
        'cancel_percent': '0.1100',
        #  asymptotic formula
        'cost_norm': '-39.3990',
        'max_commission_percent': '0.1630',
        'numerator': '853.8000',
        'asymp': '16.2000',
        #  actions
        'is_editable': False,
        'is_active': False,
        'is_deletable': False,
        'log_count': 0,
        # hiring section
        'hiring': '0.0200',
        'hiring_age': 180,
        'hiring_commercial': '0.0400',
    },
]
