import snmpd_tc

OID_BASE = ".1.3.6.1.4.1.11069.320.531"

OUT1 = [
    {"pref": 49, "kind": "flower", "chain": 0},
    {
        "pref": 49,
        "kind": "flower",
        "chain": 0,
        "options": {
            "handle": 1,
            "indev": "swp49",
            "keys": {"eth_type": "ipv6", "ip_tos": 100, "ip_tos_mask": 252},
            "skip_sw": True,
            "in_hw": True,
            "in_hw_count": 1,
            "actions": [
                {
                    "order": 1,
                    "kind": "skbedit",
                    "priority": ":3",
                    "control_action": {"type": "pipe"},
                    "index": 9,
                    "ref": 1,
                    "bind": 1,
                    "installed": 5267181,
                    "last_used": 8,
                    "stats": {
                        "bytes": 180387370,
                        "packets": 1840685,
                        "drops": 0,
                        "overlimits": 0,
                        "requeues": 0,
                        "sw_bytes": 0,
                        "sw_packets": 0,
                        "hw_bytes": 180387370,
                        "hw_packets": 1840685,
                        "backlog": 0,
                        "qlen": 0,
                    },
                    "used_hw_stats": ["immediate"],
                }
            ],
        },
    },
    {"pref": 50, "kind": "flower", "chain": 0},
    {
        "pref": 50,
        "kind": "flower",
        "chain": 0,
        "options": {
            "handle": 1,
            "indev": "swp50",
            "keys": {"eth_type": "ipv6", "ip_tos": 100, "ip_tos_mask": 252},
            "skip_sw": True,
            "in_hw": True,
            "in_hw_count": 1,
            "actions": [
                {
                    "order": 1,
                    "kind": "skbedit",
                    "priority": ":3",
                    "control_action": {"type": "pipe"},
                    "index": 10,
                    "ref": 1,
                    "bind": 1,
                    "installed": 5267181,
                    "last_used": 1,
                    "stats": {
                        "bytes": 180219328,
                        "packets": 1838936,
                        "drops": 0,
                        "overlimits": 0,
                        "requeues": 0,
                        "sw_bytes": 0,
                        "sw_packets": 0,
                        "hw_bytes": 180219328,
                        "hw_packets": 1838936,
                        "backlog": 0,
                        "qlen": 0,
                    },
                    "used_hw_stats": ["immediate"],
                }
            ],
        },
    },
    {"pref": 49145, "kind": "flower", "chain": 0},
    {
        "pref": 49145,
        "kind": "flower",
        "chain": 0,
        "options": {
            "handle": 1,
            "keys": {"eth_type": "ipv6", "ip_tos": 224, "ip_tos_mask": 224},
            "skip_sw": True,
            "in_hw": True,
            "in_hw_count": 1,
            "actions": [
                {
                    "order": 1,
                    "kind": "skbedit",
                    "priority": ":7",
                    "control_action": {"type": "pipe"},
                    "index": 8,
                    "ref": 1,
                    "bind": 1,
                    "installed": 5267181,
                    "last_used": 0,
                    "stats": {
                        "bytes": 957614760,
                        "packets": 10640164,
                        "drops": 0,
                        "overlimits": 0,
                        "requeues": 0,
                        "sw_bytes": 0,
                        "sw_packets": 0,
                        "hw_bytes": 957614760,
                        "hw_packets": 10640164,
                        "backlog": 0,
                        "qlen": 0,
                    },
                    "used_hw_stats": ["immediate"],
                },
                {
                    "order": 2,
                    "kind": "pedit",
                    "control_action": {"type": "pass"},
                    "nkeys": 1,
                    "index": 8,
                    "ref": 1,
                    "bind": 1,
                    "installed": 5267181,
                    "last_used": 0,
                    "keys": [{"htype": "ipv6", "offset": 0, "cmd": "set", "val": "e000000", "mask": "f03fffff"}],
                    "stats": {
                        "bytes": 957614760,
                        "packets": 10640164,
                        "drops": 0,
                        "overlimits": 0,
                        "requeues": 0,
                        "sw_bytes": 0,
                        "sw_packets": 0,
                        "hw_bytes": 957614760,
                        "hw_packets": 10640164,
                        "backlog": 0,
                        "qlen": 0,
                    },
                    "used_hw_stats": ["immediate"],
                },
            ],
        },
    },
    {"pref": 49146, "kind": "flower", "chain": 0},
    {
        "pref": 49146,
        "kind": "flower",
        "chain": 0,
        "options": {
            "handle": 1,
            "keys": {"eth_type": "ipv6", "ip_tos": 192, "ip_tos_mask": 224},
            "skip_sw": True,
            "in_hw": True,
            "in_hw_count": 1,
            "actions": [
                {
                    "order": 1,
                    "kind": "skbedit",
                    "priority": ":6",
                    "control_action": {"type": "pipe"},
                    "index": 7,
                    "ref": 1,
                    "bind": 1,
                    "installed": 5267181,
                    "last_used": 0,
                    "stats": {
                        "bytes": 1141250740,
                        "packets": 12657462,
                        "drops": 0,
                        "overlimits": 0,
                        "requeues": 0,
                        "sw_bytes": 0,
                        "sw_packets": 0,
                        "hw_bytes": 1141250740,
                        "hw_packets": 12657462,
                        "backlog": 0,
                        "qlen": 0,
                    },
                    "used_hw_stats": ["immediate"],
                },
                {
                    "order": 2,
                    "kind": "pedit",
                    "control_action": {"type": "pass"},
                    "nkeys": 1,
                    "index": 7,
                    "ref": 1,
                    "bind": 1,
                    "installed": 5267181,
                    "last_used": 0,
                    "keys": [{"htype": "ipv6", "offset": 0, "cmd": "set", "val": "c000000", "mask": "f03fffff"}],
                    "stats": {
                        "bytes": 1141250740,
                        "packets": 12657462,
                        "drops": 0,
                        "overlimits": 0,
                        "requeues": 0,
                        "sw_bytes": 0,
                        "sw_packets": 0,
                        "hw_bytes": 1141250740,
                        "hw_packets": 12657462,
                        "backlog": 0,
                        "qlen": 0,
                    },
                    "used_hw_stats": ["immediate"],
                },
            ],
        },
    },
    {"pref": 49147, "kind": "flower", "chain": 0},
    {
        "pref": 49147,
        "kind": "flower",
        "chain": 0,
        "options": {
            "handle": 1,
            "keys": {"eth_type": "ipv6", "ip_tos": 160, "ip_tos_mask": 224},
            "skip_sw": True,
            "in_hw": True,
            "in_hw_count": 1,
            "actions": [
                {
                    "order": 1,
                    "kind": "skbedit",
                    "priority": ":5",
                    "control_action": {"type": "pipe"},
                    "index": 6,
                    "ref": 1,
                    "bind": 1,
                    "installed": 5267181,
                    "last_used": 5267181,
                    "stats": {
                        "bytes": 0,
                        "packets": 0,
                        "drops": 0,
                        "overlimits": 0,
                        "requeues": 0,
                        "backlog": 0,
                        "qlen": 0,
                    },
                    "used_hw_stats": ["immediate"],
                },
                {
                    "order": 2,
                    "kind": "pedit",
                    "control_action": {"type": "pass"},
                    "nkeys": 1,
                    "index": 6,
                    "ref": 1,
                    "bind": 1,
                    "installed": 5267181,
                    "last_used": 5267181,
                    "keys": [{"htype": "ipv6", "offset": 0, "cmd": "set", "val": "a000000", "mask": "f03fffff"}],
                    "stats": {
                        "bytes": 0,
                        "packets": 0,
                        "drops": 0,
                        "overlimits": 0,
                        "requeues": 0,
                        "backlog": 0,
                        "qlen": 0,
                    },
                    "used_hw_stats": ["immediate"],
                },
            ],
        },
    },
    {"pref": 49148, "kind": "flower", "chain": 0},
    {
        "pref": 49148,
        "kind": "flower",
        "chain": 0,
        "options": {
            "handle": 1,
            "keys": {"eth_type": "ipv6", "ip_tos": 128, "ip_tos_mask": 224},
            "skip_sw": True,
            "in_hw": True,
            "in_hw_count": 1,
            "actions": [
                {
                    "order": 1,
                    "kind": "skbedit",
                    "priority": ":4",
                    "control_action": {"type": "pipe"},
                    "index": 5,
                    "ref": 1,
                    "bind": 1,
                    "installed": 5267181,
                    "last_used": 0,
                    "stats": {
                        "bytes": 128319999899114,
                        "packets": 256037861,
                        "drops": 0,
                        "overlimits": 0,
                        "requeues": 0,
                        "sw_bytes": 0,
                        "sw_packets": 0,
                        "hw_bytes": 128319999899114,
                        "hw_packets": 256037861,
                        "backlog": 0,
                        "qlen": 0,
                    },
                    "used_hw_stats": ["immediate"],
                },
                {
                    "order": 2,
                    "kind": "pedit",
                    "control_action": {"type": "pass"},
                    "nkeys": 1,
                    "index": 5,
                    "ref": 1,
                    "bind": 1,
                    "installed": 5267181,
                    "last_used": 0,
                    "keys": [{"htype": "ipv6", "offset": 0, "cmd": "set", "val": "8000000", "mask": "f03fffff"}],
                    "stats": {
                        "bytes": 128319999899114,
                        "packets": 256037861,
                        "drops": 0,
                        "overlimits": 0,
                        "requeues": 0,
                        "sw_bytes": 0,
                        "sw_packets": 0,
                        "hw_bytes": 128319999899114,
                        "hw_packets": 256037861,
                        "backlog": 0,
                        "qlen": 0,
                    },
                    "used_hw_stats": ["immediate"],
                },
            ],
        },
    },
    {"pref": 49149, "kind": "flower", "chain": 0},
    {
        "pref": 49149,
        "kind": "flower",
        "chain": 0,
        "options": {
            "handle": 1,
            "keys": {"eth_type": "ipv6", "ip_tos": 96, "ip_tos_mask": 224},
            "skip_sw": True,
            "in_hw": True,
            "in_hw_count": 1,
            "actions": [
                {
                    "order": 1,
                    "kind": "skbedit",
                    "priority": ":3",
                    "control_action": {"type": "pipe"},
                    "index": 4,
                    "ref": 1,
                    "bind": 1,
                    "installed": 5267181,
                    "last_used": 0,
                    "stats": {
                        "bytes": 187978359424757,
                        "packets": 570285200,
                        "drops": 0,
                        "overlimits": 0,
                        "requeues": 0,
                        "sw_bytes": 0,
                        "sw_packets": 0,
                        "hw_bytes": 187978359424757,
                        "hw_packets": 570285200,
                        "backlog": 0,
                        "qlen": 0,
                    },
                    "used_hw_stats": ["immediate"],
                },
                {
                    "order": 2,
                    "kind": "pedit",
                    "control_action": {"type": "pass"},
                    "nkeys": 1,
                    "index": 4,
                    "ref": 1,
                    "bind": 1,
                    "installed": 5267181,
                    "last_used": 0,
                    "keys": [{"htype": "ipv6", "offset": 0, "cmd": "set", "val": "6000000", "mask": "f03fffff"}],
                    "stats": {
                        "bytes": 187978359424757,
                        "packets": 570285200,
                        "drops": 0,
                        "overlimits": 0,
                        "requeues": 0,
                        "sw_bytes": 0,
                        "sw_packets": 0,
                        "hw_bytes": 187978359424757,
                        "hw_packets": 570285200,
                        "backlog": 0,
                        "qlen": 0,
                    },
                    "used_hw_stats": ["immediate"],
                },
            ],
        },
    },
    {"pref": 49150, "kind": "flower", "chain": 0},
    {
        "pref": 49150,
        "kind": "flower",
        "chain": 0,
        "options": {
            "handle": 1,
            "keys": {"eth_type": "ipv6", "ip_tos": 64, "ip_tos_mask": 224},
            "skip_sw": True,
            "in_hw": True,
            "in_hw_count": 1,
            "actions": [
                {
                    "order": 1,
                    "kind": "skbedit",
                    "priority": ":2",
                    "control_action": {"type": "pipe"},
                    "index": 3,
                    "ref": 1,
                    "bind": 1,
                    "installed": 5267182,
                    "last_used": 0,
                    "stats": {
                        "bytes": 115969158781334,
                        "packets": 1494417436,
                        "drops": 0,
                        "overlimits": 0,
                        "requeues": 0,
                        "sw_bytes": 0,
                        "sw_packets": 0,
                        "hw_bytes": 115969158781334,
                        "hw_packets": 1494417436,
                        "backlog": 0,
                        "qlen": 0,
                    },
                    "used_hw_stats": ["immediate"],
                },
                {
                    "order": 2,
                    "kind": "pedit",
                    "control_action": {"type": "pass"},
                    "nkeys": 1,
                    "index": 3,
                    "ref": 1,
                    "bind": 1,
                    "installed": 5267182,
                    "last_used": 0,
                    "keys": [{"htype": "ipv6", "offset": 0, "cmd": "set", "val": "4000000", "mask": "f03fffff"}],
                    "stats": {
                        "bytes": 115969158781334,
                        "packets": 1494417436,
                        "drops": 0,
                        "overlimits": 0,
                        "requeues": 0,
                        "sw_bytes": 0,
                        "sw_packets": 0,
                        "hw_bytes": 115969158781334,
                        "hw_packets": 1494417436,
                        "backlog": 0,
                        "qlen": 0,
                    },
                    "used_hw_stats": ["immediate"],
                },
            ],
        },
    },
    {"pref": 49151, "kind": "flower", "chain": 0},
    {
        "pref": 49151,
        "kind": "flower",
        "chain": 0,
        "options": {
            "handle": 1,
            "keys": {"eth_type": "ipv6", "ip_tos": 32, "ip_tos_mask": 224},
            "skip_sw": True,
            "in_hw": True,
            "in_hw_count": 1,
            "actions": [
                {
                    "order": 1,
                    "kind": "skbedit",
                    "priority": ":1",
                    "control_action": {"type": "pipe"},
                    "index": 2,
                    "ref": 1,
                    "bind": 1,
                    "installed": 5267182,
                    "last_used": 0,
                    "stats": {
                        "bytes": 160637858774990,
                        "packets": 2976866179,
                        "drops": 0,
                        "overlimits": 0,
                        "requeues": 0,
                        "sw_bytes": 0,
                        "sw_packets": 0,
                        "hw_bytes": 160637858774990,
                        "hw_packets": 2976866179,
                        "backlog": 0,
                        "qlen": 0,
                    },
                    "used_hw_stats": ["immediate"],
                },
                {
                    "order": 2,
                    "kind": "pedit",
                    "control_action": {"type": "pass"},
                    "nkeys": 1,
                    "index": 2,
                    "ref": 1,
                    "bind": 1,
                    "installed": 5267182,
                    "last_used": 0,
                    "keys": [{"htype": "ipv6", "offset": 0, "cmd": "set", "val": "2000000", "mask": "f03fffff"}],
                    "stats": {
                        "bytes": 160637858774990,
                        "packets": 2976866179,
                        "drops": 0,
                        "overlimits": 0,
                        "requeues": 0,
                        "sw_bytes": 0,
                        "sw_packets": 0,
                        "hw_bytes": 160637858774990,
                        "hw_packets": 2976866179,
                        "backlog": 0,
                        "qlen": 0,
                    },
                    "used_hw_stats": ["immediate"],
                },
            ],
        },
    },
    {"pref": 49152, "kind": "flower", "chain": 0},
    {
        "pref": 49152,
        "kind": "flower",
        "chain": 0,
        "options": {
            "handle": 1,
            "keys": {"eth_type": "ipv6", "ip_tos": 0, "ip_tos_mask": 224},
            "skip_sw": True,
            "in_hw": True,
            "in_hw_count": 1,
            "actions": [
                {
                    "order": 1,
                    "kind": "skbedit",
                    "priority": "none",
                    "control_action": {"type": "pipe"},
                    "index": 1,
                    "ref": 1,
                    "bind": 1,
                    "installed": 5267182,
                    "last_used": 0,
                    "stats": {
                        "bytes": 1012512480396,
                        "packets": 159665678,
                        "drops": 0,
                        "overlimits": 0,
                        "requeues": 0,
                        "sw_bytes": 0,
                        "sw_packets": 0,
                        "hw_bytes": 1012512480396,
                        "hw_packets": 159665678,
                        "backlog": 0,
                        "qlen": 0,
                    },
                    "used_hw_stats": ["immediate"],
                },
                {
                    "order": 2,
                    "kind": "pedit",
                    "control_action": {"type": "pass"},
                    "nkeys": 1,
                    "index": 1,
                    "ref": 1,
                    "bind": 1,
                    "installed": 5267182,
                    "last_used": 0,
                    "keys": [{"htype": "ipv6", "offset": 0, "cmd": "set", "val": "0", "mask": "f03fffff"}],
                    "stats": {
                        "bytes": 1012512480396,
                        "packets": 159665678,
                        "drops": 0,
                        "overlimits": 0,
                        "requeues": 0,
                        "sw_bytes": 0,
                        "sw_packets": 0,
                        "hw_bytes": 1012512480396,
                        "hw_packets": 159665678,
                        "backlog": 0,
                        "qlen": 0,
                    },
                    "used_hw_stats": ["immediate"],
                },
            ],
        },
    },
]


def test_parse_tc():
    res = snmpd_tc.SnmpdPass.parse_tc(OUT1)
    assert res == {
        'swp49': {'bytes': 180387370, 'packets': 1840685},
        'swp50': {'bytes': 180219328, 'packets': 1838936},
    }
