import dataclasses
import typing

from unittest import mock
import pytest

from checkist.models import device
from checkist.models import invapi


ETAGS = [device.RawTag(id=tag_id, name="", parent_id=None) for tag_id in [1, 2, 3, 4]]
ITAGS = [device.RawTag(id=tag_id, name="", parent_id=None) for tag_id in [10, 20, 30, 40]]


@pytest.mark.asyncio
@pytest.mark.parametrize("devices_list, device_filter_list, expected_list", (
    (
        [
            {
                "object_id": 1,
                "asset_no": 1000,
                "name": "device1",
                "fqdn": "device1.yndx.net",
                "etags": ETAGS,
                "itags": ITAGS,
                "atags": [],
            },
        ],
        [
            {},
        ],
        [
            {
                "object_id": 1,
                "asset_no": 1000,
                "name": "device1",
                "fqdn": "device1.yndx.net",
                "etags": ETAGS,
                "itags": ITAGS,
                "atags": [],
            },
        ],
    ),
    (
        [
            {
                "object_id": 1,
                "asset_no": 1000,
                "name": "device1",
                "fqdn": "device1.yndx.net",
                "etags": ETAGS,
                "itags": ITAGS,
                "atags": [],
            },
        ],
        [
            {
                "name": "device2",
            },
        ],
        [],
    ),
    (
        [
            {
                "object_id": 1,
                "asset_no": 1000,
                "name": "device1",
                "fqdn": "device1.yndx.net",
                "etags": ETAGS,
                "itags": ITAGS,
                "atags": [],
            },
            {
                "object_id": 3,
                "asset_no": 3000,
                "name": "device3",
                "fqdn": "device3.yndx.net",
                "etags": ETAGS,
                "itags": ITAGS,
                "atags": [],
            },
        ],
        [
            {
                "name": "/device[12]/",
            },
            {
                "name": "/device1.(yndx|yandex).net/",
            },
        ],
        [
            {
                "object_id": 1,
                "asset_no": 1000,
                "name": "device1",
                "fqdn": "device1.yndx.net",
                "etags": ETAGS,
                "itags": ITAGS,
                "atags": [],
            },
        ],
    ),
    (
        [
            {
                "object_id": 1,
                "asset_no": 1000,
                "name": "device1",
                "fqdn": "device1.yndx.net",
                "etags": ETAGS,
                "itags": ITAGS,
                "atags": [],
            },
            {
                "object_id": 3,
                "asset_no": 3000,
                "name": "device3",
                "fqdn": "device3.yndx.net",
                "etags": ETAGS,
                "itags": ITAGS,
                "atags": [],
            },
        ],
        [
            {
                "asset_no": 3000,
            },
        ],
        [
            {
                "object_id": 3,
                "asset_no": 3000,
                "name": "device3",
                "fqdn": "device3.yndx.net",
                "etags": ETAGS,
                "itags": ITAGS,
                "atags": [],
            },
        ],
    ),
    (
        [
            {
                "object_id": 1,
                "asset_no": 1000,
                "name": "device1",
                "fqdn": "device1.yndx.net",
                "etags": ETAGS,
                "itags": ITAGS,
                "atags": [],
            },
        ],
        [
            {
                "tags": [1, 2],
            },
        ],
        [
            {
                "object_id": 1,
                "asset_no": 1000,
                "name": "device1",
                "fqdn": "device1.yndx.net",
                "etags": ETAGS,
                "itags": ITAGS,
                "atags": [],
            },
        ],
    ),
    (
        [
            {
                "object_id": 1,
                "asset_no": 1000,
                "name": "device1",
                "fqdn": "device1.yndx.net",
                "etags": ETAGS,
                "itags": ITAGS,
                "atags": [],
            },
        ],
        [
            {
                "tags": [1, 2, 666],
            },
        ],
        [],
    ),
    (
        [
            {
                "object_id": 1,
                "asset_no": 1000,
                "name": "device1",
                "fqdn": "device1.yndx.net",
                "etags": ETAGS,
                "itags": ITAGS,
                "atags": [],
            },
            {
                "object_id": 2,
                "asset_no": 2000,
                "name": "device2",
                "fqdn": "device2.yndx.net",
                "etags": ETAGS,
                "itags": ITAGS,
                "atags": [],
            },
            {
                "object_id": 3,
                "asset_no": 3000,
                "name": "device3",
                "fqdn": "device3.yndx.net",
                "etags": ETAGS,
                "itags": ITAGS,
                "atags": [],
            },
        ],
        [
            {
                "name": "device1,device3",
            },
            {
                "name": "device1;device3",
            },
            {
                "name": "device1 device3",
            },
            {
                "name": "device1, device3",
            },
            {
                "name": "device1,\t device3",
            },
            {
                "name": "device1, device3.yndx.net",
            },
        ],
        [
            {
                "object_id": 1,
                "asset_no": 1000,
                "name": "device1",
                "fqdn": "device1.yndx.net",
                "etags": ETAGS,
                "itags": ITAGS,
                "atags": [],
            },
            {
                "object_id": 3,
                "asset_no": 3000,
                "name": "device3",
                "fqdn": "device3.yndx.net",
                "etags": ETAGS,
                "itags": ITAGS,
                "atags": [],
            },
        ],
    ),
))
async def test_devices_search(devices_list, device_filter_list, expected_list):
    core = mock.Mock()
    devices = device.Devices(core)
    devices.get_devices = mock.AsyncMock(return_value=[device.Device(**x) for x in devices_list])
    expected = {x["object_id"]: device.Device(**x) for x in expected_list}
    for device_filter in device_filter_list:
        fltr = device.DeviceFilter(**device_filter)
        result = await devices.search(fltr)
        assert result == expected


@pytest.mark.parametrize(
    "invapi_dict, expected_device_dict",
    (
        (
            {
                "id": "21588",
                "name": "ams1-b1",
                "asset_no": "100323600",
                "fqdn": "ams1-b1.yndx.net",
                "etags": [
                    {"id": 69, "tag": "магистральный свитч", "parent_id": 67},
                    {"id": 490, "tag": "Амстердам", "parent_id": 489},
                    {"id": 544, "tag": "Juniper MX", "parent_id": 443},
                    {"id": 850, "tag": "chassis", "parent_id": 842},
                    {"id": 1233, "tag": "regional border", "parent_id": 57},
                    {"id": 1634, "tag": "RE-S-1800x4", "parent_id": 1632},
                    {"id": 1641, "tag": "double RE", "parent_id": 577},
                ],
                "itags": [
                    {"id": 306, "tag": "конюшня NOC", "parent_id": None},
                    {"id": 67, "tag": "свитч", "parent_id": 306},
                    {"id": 279, "tag": "планета Земля", "parent_id": None},
                    {"id": 906, "tag": "Европа", "parent_id": 279},
                    {"id": 489, "tag": "Нидерланды", "parent_id": 906},
                    {"id": 285, "tag": "бестиарий", "parent_id": None},
                    {"id": 862, "tag": "vendor", "parent_id": 285},
                    {"id": 443, "tag": "Juniper", "parent_id": 862},
                    {"id": 842, "tag": "inventory", "parent_id": None},
                    {"id": 66, "tag": "маршрутизатор", "parent_id": 306},
                    {"id": 57, "tag": "border router", "parent_id": 66},
                    {"id": 1631, "tag": "routing engine board", "parent_id": 842},
                    {"id": 1632, "tag": "Juniper routing engine", "parent_id": 1631},
                    {"id": 577, "tag": "flags", "parent_id": None},
                ],
                "atags": [
                    {"tag": "$id_21588"},
                    {"tag": "$typeid_7"},
                    {"tag": "$any_object"},
                    {"tag": "$cn_ams1-b1"},
                    {"tag": "$runs_8021Q"},
                    {"tag": "$8021Q_domain_72"},
                    {"tag": "$8021Q_tpl_295"},
                    {"tag": "$attr_2_927"},
                    {"tag": "$attr_4_88502"},
                    {"tag": "$attr_10000_88694"},
                    {"tag": "$attr_10031_1501"},
                    {"tag": "$rackid_21893"},
                ],
            },
            {
                "object_id": 21588,
                "asset_no": 100323600,
                "atags": [
                    "$id_21588",
                    "$typeid_7",
                    "$any_object",
                    "$cn_ams1-b1",
                    "$runs_8021Q",
                    "$8021Q_domain_72",
                    "$8021Q_tpl_295",
                    "$attr_2_927",
                    "$attr_4_88502",
                    "$attr_10000_88694",
                    "$attr_10031_1501",
                    "$rackid_21893",
                ],
                "dirtiness": None,
                "etags": [
                    {"id": 69, "name": "магистральный свитч", "parent_id": 67},
                    {"id": 490, "name": "Амстердам", "parent_id": 489},
                    {"id": 544, "name": "Juniper MX", "parent_id": 443},
                    {"id": 850, "name": "chassis", "parent_id": 842},
                    {"id": 1233, "name": "regional border", "parent_id": 57},
                    {"id": 1634, "name": "RE-S-1800x4", "parent_id": 1632},
                    {"id": 1641, "name": "double RE", "parent_id": 577},
                ],
                "fqdn": "ams1-b1.yndx.net",
                "itags": [
                    {"id": 306, "name": "конюшня NOC", "parent_id": None},
                    {"id": 67, "name": "свитч", "parent_id": 306},
                    {"id": 279, "name": "планета Земля", "parent_id": None},
                    {"id": 906, "name": "Европа", "parent_id": 279},
                    {"id": 489, "name": "Нидерланды", "parent_id": 906},
                    {"id": 285, "name": "бестиарий", "parent_id": None},
                    {"id": 862, "name": "vendor", "parent_id": 285},
                    {"id": 443, "name": "Juniper", "parent_id": 862},
                    {"id": 842, "name": "inventory", "parent_id": None},
                    {"id": 66, "name": "маршрутизатор", "parent_id": 306},
                    {"id": 57, "name": "border router", "parent_id": 66},
                    {"id": 1631, "name": "routing engine board", "parent_id": 842},
                    {"id": 1632, "name": "Juniper routing engine", "parent_id": 1631},
                    {"id": 577, "name": "flags", "parent_id": None},
                ],
                "name": "ams1-b1",
                "vendor": "juniper",
                "deleted": False,
                "diff_enabled": True,
            },
        ),
        (
            {
                "id": "9223",
                "name": "s2197",
                "asset_no": "397764",
                "fqdn": "s2197.yndx.net",
                "etags": [
                    {"id": 68, "tag": "серверный свитч", "parent_id": 67},
                    {"id": 695, "tag": "Arista", "parent_id": 862},
                    {"id": 783, "tag": "Морозов лаборатория", "parent_id": 251},
                    {"id": 850, "tag": "chassis", "parent_id": 842},
                ],
                "itags": [
                    {"id": 306, "tag": "конюшня NOC", "parent_id": None},
                    {"id": 67, "tag": "свитч", "parent_id": 306},
                    {"id": 285, "tag": "бестиарий", "parent_id": None},
                    {"id": 862, "tag": "vendor", "parent_id": 285},
                    {"id": 279, "tag": "планета Земля", "parent_id": None},
                    {"id": 26, "tag": "Россия", "parent_id": 279},
                    {"id": 27, "tag": "Москва", "parent_id": 26},
                    {"id": 1179, "tag": "Красная Роза", "parent_id": 27},
                    {"id": 112, "tag": "Морозов", "parent_id": 1179},
                    {"id": 251, "tag": "Морозов 4 этаж", "parent_id": 112},
                    {"id": 842, "tag": "inventory", "parent_id": None},
                ],
                "atags": [
                    {"tag": "$id_9223"},
                    {"tag": "$typeid_8"},
                    {"tag": "$any_object"},
                    {"tag": "$cn_s2197"},
                    {"tag": "$runs_8021Q"},
                    {"tag": "$8021Q_domain_10"},
                    {"tag": "$8021Q_tpl_18"},
                    {"tag": "$attr_2_1726"},
                    {"tag": "$attr_4_1675"},
                    {"tag": "$attr_10000_83902"},
                    {"tag": "$attr_10031_1501"},
                    {"tag": "$rackid_9699"},
                ],
            },
            {
                "object_id": 9223,
                "asset_no": 397764,
                "atags": [
                    "$id_9223",
                    "$typeid_8",
                    "$any_object",
                    "$cn_s2197",
                    "$runs_8021Q",
                    "$8021Q_domain_10",
                    "$8021Q_tpl_18",
                    "$attr_2_1726",
                    "$attr_4_1675",
                    "$attr_10000_83902",
                    "$attr_10031_1501",
                    "$rackid_9699",
                ],
                "dirtiness": None,
                "etags": [
                    {"id": 68, "name": "серверный свитч", "parent_id": 67},
                    {"id": 695, "name": "Arista", "parent_id": 862},
                    {"id": 783, "name": "Морозов лаборатория", "parent_id": 251},
                    {"id": 850, "name": "chassis", "parent_id": 842},
                ],
                "fqdn": "s2197.yndx.net",
                "itags": [
                    {"id": 306, "name": "конюшня NOC", "parent_id": None},
                    {"id": 67, "name": "свитч", "parent_id": 306},
                    {"id": 285, "name": "бестиарий", "parent_id": None},
                    {"id": 862, "name": "vendor", "parent_id": 285},
                    {"id": 279, "name": "планета Земля", "parent_id": None},
                    {"id": 26, "name": "Россия", "parent_id": 279},
                    {"id": 27, "name": "Москва", "parent_id": 26},
                    {"id": 1179, "name": "Красная Роза", "parent_id": 27},
                    {"id": 112, "name": "Морозов", "parent_id": 1179},
                    {"id": 251, "name": "Морозов 4 этаж", "parent_id": 112},
                    {"id": 842, "name": "inventory", "parent_id": None},
                ],
                "name": "s2197",
                "vendor": "arista",
                "deleted": False,
                "diff_enabled": True,
            },
        ),
        (
            {
                "id": "29653",
                "name": "admiral-u1",
                "asset_no": "102560924",
                "fqdn": "admiral-u1.yndx.net",
                "etags": [
                    {"id": 13, "tag": "юзерский свитч", "parent_id": 67},
                    {"id": 850, "tag": "chassis", "parent_id": 842},
                    {"id": 1001, "tag": "офисная инфраструктура", "parent_id": 37},
                    {"id": 1360, "tag": "PoE+", "parent_id": 1359},
                    {"id": 1399, "tag": "Cisco 3650", "parent_id": 528},
                    {"id": 1598, "tag": "офис Краснодар Адмирал", "parent_id": 2105},
                ],
                "itags": [
                    {"id": 306, "tag": "конюшня NOC", "parent_id": None},
                    {"id": 67, "tag": "свитч", "parent_id": 306},
                    {"id": 842, "tag": "inventory", "parent_id": None},
                    {"id": 37, "tag": "сервисы", "parent_id": None},
                    {"id": 577, "tag": "flags", "parent_id": None},
                    {"id": 1359, "tag": "PoE", "parent_id": 577},
                    {"id": 285, "tag": "бестиарий", "parent_id": None},
                    {"id": 862, "tag": "vendor", "parent_id": 285},
                    {"id": 526, "tag": "Cisco", "parent_id": 862},
                    {"id": 528, "tag": "Cisco Catalyst", "parent_id": 526},
                    {"id": 279, "tag": "планета Земля", "parent_id": None},
                    {"id": 26, "tag": "Россия", "parent_id": 279},
                    {"id": 2105, "tag": "Краснодар", "parent_id": 26},
                ],
                "atags": [
                    {"tag": "$id_29653"},
                    {"tag": "$typeid_8"},
                    {"tag": "$any_object"},
                    {"tag": "$cn_admiral-u1"},
                    {"tag": "$unmounted"},
                    {"tag": "$runs_8021Q"},
                    {"tag": "$8021Q_domain_129"},
                    {"tag": "$8021Q_tpl_18"},
                    {"tag": "$attr_2_2634"},
                    {"tag": "$attr_4_68301"},
                    {"tag": "$attr_10000_86457"},
                ],
            },
            {
                "object_id": 29653,
                "asset_no": 102560924,
                "atags": [
                    "$id_29653",
                    "$typeid_8",
                    "$any_object",
                    "$cn_admiral-u1",
                    "$unmounted",
                    "$runs_8021Q",
                    "$8021Q_domain_129",
                    "$8021Q_tpl_18",
                    "$attr_2_2634",
                    "$attr_4_68301",
                    "$attr_10000_86457",
                ],
                "dirtiness": None,
                "etags": [
                    {"id": 13, "name": "юзерский свитч", "parent_id": 67},
                    {"id": 850, "name": "chassis", "parent_id": 842},
                    {"id": 1001, "name": "офисная инфраструктура", "parent_id": 37},
                    {"id": 1360, "name": "PoE+", "parent_id": 1359},
                    {"id": 1399, "name": "Cisco 3650", "parent_id": 528},
                    {"id": 1598, "name": "офис Краснодар Адмирал", "parent_id": 2105},
                ],
                "fqdn": "admiral-u1.yndx.net",
                "itags": [
                    {"id": 306, "name": "конюшня NOC", "parent_id": None},
                    {"id": 67, "name": "свитч", "parent_id": 306},
                    {"id": 842, "name": "inventory", "parent_id": None},
                    {"id": 37, "name": "сервисы", "parent_id": None},
                    {"id": 577, "name": "flags", "parent_id": None},
                    {"id": 1359, "name": "PoE", "parent_id": 577},
                    {"id": 285, "name": "бестиарий", "parent_id": None},
                    {"id": 862, "name": "vendor", "parent_id": 285},
                    {"id": 526, "name": "Cisco", "parent_id": 862},
                    {"id": 528, "name": "Cisco Catalyst", "parent_id": 526},
                    {"id": 279, "name": "планета Земля", "parent_id": None},
                    {"id": 26, "name": "Россия", "parent_id": 279},
                    {"id": 2105, "name": "Краснодар", "parent_id": 26},
                ],
                "name": "admiral-u1",
                "vendor": "cisco",
                "deleted": False,
                "diff_enabled": True,
            },
        ),
        (
            {
                "id": "8352",
                "name": "vlainfra-d3",
                "asset_no": "153739",
                "fqdn": "vlainfra-d3.yndx.net",
                "etags": [
                    {"id": 69, "tag": "магистральный свитч", "parent_id": 67},
                    {"id": 448, "tag": "Nexus 5000", "parent_id": 527},
                    {"id": 850, "tag": "chassis", "parent_id": 842},
                    {"id": 1741, "tag": "Владимир-2 КЦ", "parent_id": 1307},
                ],
                "itags": [
                    {"id": 306, "tag": "конюшня NOC", "parent_id": None},
                    {"id": 67, "tag": "свитч", "parent_id": 306},
                    {"id": 285, "tag": "бестиарий", "parent_id": None},
                    {"id": 862, "tag": "vendor", "parent_id": 285},
                    {"id": 526, "tag": "Cisco", "parent_id": 862},
                    {"id": 527, "tag": "Nexus", "parent_id": 526},
                    {"id": 842, "tag": "inventory", "parent_id": None},
                    {"id": 279, "tag": "планета Земля", "parent_id": None},
                    {"id": 26, "tag": "Россия", "parent_id": 279},
                    {"id": 1307, "tag": "Владимир", "parent_id": 26},
                ],
                "atags": [
                    {"tag": "$id_8352"},
                    {"tag": "$typeid_8"},
                    {"tag": "$any_object"},
                    {"tag": "$cn_vlainfra-d3"},
                    {"tag": "$runs_8021Q"},
                    {"tag": "$8021Q_domain_78"},
                    {"tag": "$8021Q_tpl_18"},
                    {"tag": "$attr_2_1412"},
                    {"tag": "$attr_4_83591"},
                    {"tag": "$attr_10000_89550"},
                    {"tag": "$attr_10031_1501"},
                    {"tag": "$rackid_54178"},
                ],
            },
            {
                "object_id": 8352,
                "asset_no": 153739,
                "atags": [
                    "$id_8352",
                    "$typeid_8",
                    "$any_object",
                    "$cn_vlainfra-d3",
                    "$runs_8021Q",
                    "$8021Q_domain_78",
                    "$8021Q_tpl_18",
                    "$attr_2_1412",
                    "$attr_4_83591",
                    "$attr_10000_89550",
                    "$attr_10031_1501",
                    "$rackid_54178",
                ],
                "dirtiness": None,
                "etags": [
                    {"id": 69, "name": "магистральный свитч", "parent_id": 67},
                    {"id": 448, "name": "Nexus 5000", "parent_id": 527},
                    {"id": 850, "name": "chassis", "parent_id": 842},
                    {"id": 1741, "name": "Владимир-2 КЦ", "parent_id": 1307},
                ],
                "fqdn": "vlainfra-d3.yndx.net",
                "itags": [
                    {"id": 306, "name": "конюшня NOC", "parent_id": None},
                    {"id": 67, "name": "свитч", "parent_id": 306},
                    {"id": 285, "name": "бестиарий", "parent_id": None},
                    {"id": 862, "name": "vendor", "parent_id": 285},
                    {"id": 526, "name": "Cisco", "parent_id": 862},
                    {"id": 527, "name": "Nexus", "parent_id": 526},
                    {"id": 842, "name": "inventory", "parent_id": None},
                    {"id": 279, "name": "планета Земля", "parent_id": None},
                    {"id": 26, "name": "Россия", "parent_id": 279},
                    {"id": 1307, "name": "Владимир", "parent_id": 26},
                ],
                "name": "vlainfra-d3",
                "vendor": "nexus",
                "deleted": False,
                "diff_enabled": True,
            },
        ),
        (
            {
                "id": "46347",
                "name": "sas-32z2",
                "asset_no": "106681946",
                "fqdn": "sas-32z2.yndx.net",
                "etags": [
                    {"id": 753, "tag": "Сасово-1 КЦ", "parent_id": 750},
                    {"id": 850, "tag": "chassis", "parent_id": 842},
                    {"id": 1354, "tag": "многодэшка", "parent_id": 873},
                    {"id": 1814, "tag": "cloud_forwarder", "parent_id": 1221},
                    {"id": 1850, "tag": "Nokia", "parent_id": 862},
                    {"id": 1946, "tag": "affects_cloud", "parent_id": 577},
                    {
                        "id": 2033,
                        "tag": "Не подлежит снятию через ЦК",
                        "parent_id": 577,
                    },
                ],
                "itags": [
                    {"id": 279, "tag": "планета Земля", "parent_id": None},
                    {"id": 26, "tag": "Россия", "parent_id": 279},
                    {"id": 697, "tag": "Сасово", "parent_id": 26},
                    {"id": 750, "tag": "Сасово-1", "parent_id": 697},
                    {"id": 842, "tag": "inventory", "parent_id": None},
                    {"id": 306, "tag": "конюшня NOC", "parent_id": None},
                    {"id": 67, "tag": "свитч", "parent_id": 306},
                    {"id": 69, "tag": "магистральный свитч", "parent_id": 67},
                    {"id": 873, "tag": "distrubution с FastBone", "parent_id": 69},
                    {"id": 66, "tag": "маршрутизатор", "parent_id": 306},
                    {"id": 1221, "tag": "datacenter core", "parent_id": 66},
                    {"id": 285, "tag": "бестиарий", "parent_id": None},
                    {"id": 862, "tag": "vendor", "parent_id": 285},
                    {"id": 577, "tag": "flags", "parent_id": None},
                ],
                "atags": [
                    {"tag": "$id_46347"},
                    {"tag": "$typeid_8"},
                    {"tag": "$any_object"},
                    {"tag": "$cn_sas-32z2"},
                    {"tag": "$runs_8021Q"},
                    {"tag": "$8021Q_domain_183"},
                    {"tag": "$8021Q_tpl_296"},
                    {"tag": "$attr_2_86050"},
                    {"tag": "$attr_4_86036"},
                    {"tag": "$attr_10000_89183"},
                    {"tag": "$attr_10031_1501"},
                    {"tag": "$rackid_53031"},
                ],
            },
            {
                "object_id": 46347,
                "asset_no": 106681946,
                "atags": [
                    "$id_46347",
                    "$typeid_8",
                    "$any_object",
                    "$cn_sas-32z2",
                    "$runs_8021Q",
                    "$8021Q_domain_183",
                    "$8021Q_tpl_296",
                    "$attr_2_86050",
                    "$attr_4_86036",
                    "$attr_10000_89183",
                    "$attr_10031_1501",
                    "$rackid_53031",
                ],
                "dirtiness": None,
                "etags": [
                    {"id": 753, "name": "Сасово-1 КЦ", "parent_id": 750},
                    {"id": 850, "name": "chassis", "parent_id": 842},
                    {"id": 1354, "name": "многодэшка", "parent_id": 873},
                    {"id": 1814, "name": "cloud_forwarder", "parent_id": 1221},
                    {"id": 1850, "name": "Nokia", "parent_id": 862},
                    {"id": 1946, "name": "affects_cloud", "parent_id": 577},
                    {
                        "id": 2033,
                        "name": "Не подлежит снятию через ЦК",
                        "parent_id": 577,
                    },
                ],
                "fqdn": "sas-32z2.yndx.net",
                "itags": [
                    {"id": 279, "name": "планета Земля", "parent_id": None},
                    {"id": 26, "name": "Россия", "parent_id": 279},
                    {"id": 697, "name": "Сасово", "parent_id": 26},
                    {"id": 750, "name": "Сасово-1", "parent_id": 697},
                    {"id": 842, "name": "inventory", "parent_id": None},
                    {"id": 306, "name": "конюшня NOC", "parent_id": None},
                    {"id": 67, "name": "свитч", "parent_id": 306},
                    {"id": 69, "name": "магистральный свитч", "parent_id": 67},
                    {"id": 873, "name": "distrubution с FastBone", "parent_id": 69},
                    {"id": 66, "name": "маршрутизатор", "parent_id": 306},
                    {"id": 1221, "name": "datacenter core", "parent_id": 66},
                    {"id": 285, "name": "бестиарий", "parent_id": None},
                    {"id": 862, "name": "vendor", "parent_id": 285},
                    {"id": 577, "name": "flags", "parent_id": None},
                ],
                "name": "sas-32z2",
                "vendor": "nokia",
                "deleted": False,
                "diff_enabled": True,
            },
        ),
        (
            {
                "id": "29321",
                "name": "lab-vla-1s2",
                "asset_no": "101956309",
                "fqdn": "lab-vla-1s2.yndx.net",
                "etags": [
                    {"id": 68, "tag": "серверный свитч", "parent_id": 67},
                    {"id": 850, "tag": "chassis", "parent_id": 842},
                    {"id": 980, "tag": "L3 ToR", "parent_id": 1047},
                    {"id": 1796, "tag": "лаборатория Владимир", "parent_id": 1307},
                    {"id": 1801, "tag": "nonvrf", "parent_id": 577},
                    {"id": 1821, "tag": "FL enabled", "parent_id": 1047},
                    {"id": 2101, "tag": "Mellanox SN2410", "parent_id": 1357},
                ],
                "itags": [
                    {"id": 306, "tag": "конюшня NOC", "parent_id": None},
                    {"id": 67, "tag": "свитч", "parent_id": 306},
                    {"id": 842, "tag": "inventory", "parent_id": None},
                    {"id": 577, "tag": "flags", "parent_id": None},
                    {"id": 1047, "tag": "L3", "parent_id": 577},
                    {"id": 279, "tag": "планета Земля", "parent_id": None},
                    {"id": 26, "tag": "Россия", "parent_id": 279},
                    {"id": 1307, "tag": "Владимир", "parent_id": 26},
                    {"id": 285, "tag": "бестиарий", "parent_id": None},
                    {"id": 862, "tag": "vendor", "parent_id": 285},
                    {"id": 815, "tag": "Mellanox", "parent_id": 862},
                    {"id": 1357, "tag": "Mellanox SN", "parent_id": 815},
                ],
                "atags": [
                    {"tag": "$id_29321"},
                    {"tag": "$typeid_8"},
                    {"tag": "$any_object"},
                    {"tag": "$cn_lab-vla-1s2"},
                    {"tag": "$runs_8021Q"},
                    {"tag": "$8021Q_domain_150"},
                    {"tag": "$8021Q_tpl_211"},
                    {"tag": "$attr_2_2533"},
                    {"tag": "$attr_4_86232"},
                    {"tag": "$attr_10000_89840"},
                    {"tag": "$attr_10031_1501"},
                    {"tag": "$rackid_54469"},
                ],
            },
            {
                "object_id": 29321,
                "asset_no": 101956309,
                "atags": [
                    "$id_29321",
                    "$typeid_8",
                    "$any_object",
                    "$cn_lab-vla-1s2",
                    "$runs_8021Q",
                    "$8021Q_domain_150",
                    "$8021Q_tpl_211",
                    "$attr_2_2533",
                    "$attr_4_86232",
                    "$attr_10000_89840",
                    "$attr_10031_1501",
                    "$rackid_54469",
                ],
                "dirtiness": None,
                "etags": [
                    {"id": 68, "name": "серверный свитч", "parent_id": 67},
                    {"id": 850, "name": "chassis", "parent_id": 842},
                    {"id": 980, "name": "L3 ToR", "parent_id": 1047},
                    {"id": 1796, "name": "лаборатория Владимир", "parent_id": 1307},
                    {"id": 1801, "name": "nonvrf", "parent_id": 577},
                    {"id": 1821, "name": "FL enabled", "parent_id": 1047},
                    {"id": 2101, "name": "Mellanox SN2410", "parent_id": 1357},
                ],
                "fqdn": "lab-vla-1s2.yndx.net",
                "itags": [
                    {"id": 306, "name": "конюшня NOC", "parent_id": None},
                    {"id": 67, "name": "свитч", "parent_id": 306},
                    {"id": 842, "name": "inventory", "parent_id": None},
                    {"id": 577, "name": "flags", "parent_id": None},
                    {"id": 1047, "name": "L3", "parent_id": 577},
                    {"id": 279, "name": "планета Земля", "parent_id": None},
                    {"id": 26, "name": "Россия", "parent_id": 279},
                    {"id": 1307, "name": "Владимир", "parent_id": 26},
                    {"id": 285, "name": "бестиарий", "parent_id": None},
                    {"id": 862, "name": "vendor", "parent_id": 285},
                    {"id": 815, "name": "Mellanox", "parent_id": 862},
                    {"id": 1357, "name": "Mellanox SN", "parent_id": 815},
                ],
                "name": "lab-vla-1s2",
                "vendor": "pc",
                "deleted": False,
                "diff_enabled": True,
            },
        ),
        (
            {
                "id": "22737",
                "name": "red1-wr1",
                "asset_no": "100361772",
                "fqdn": "red1-wr1.yndx.net",
                "etags": [
                    {"id": 66, "tag": "маршрутизатор", "parent_id": 306},
                    {"id": 112, "tag": "Морозов", "parent_id": 1179},
                    {"id": 565, "tag": "спрятан от скриптов", "parent_id": 137},
                    {"id": 580, "tag": "Autonomous WiFi точка", "parent_id": 1041},
                    {"id": 614, "tag": "Out-of-band", "parent_id": 105},
                    {"id": 816, "tag": "Mikrotik", "parent_id": 862},
                ],
                "itags": [
                    {"id": 306, "tag": "конюшня NOC", "parent_id": None},
                    {"id": 279, "tag": "планета Земля", "parent_id": None},
                    {"id": 26, "tag": "Россия", "parent_id": 279},
                    {"id": 27, "tag": "Москва", "parent_id": 26},
                    {"id": 1179, "tag": "Красная Роза", "parent_id": 27},
                    {"id": 577, "tag": "flags", "parent_id": None},
                    {"id": 137, "tag": "в оффлайне", "parent_id": 577},
                    {"id": 1041, "tag": "WiFi точка", "parent_id": 306},
                    {"id": 65, "tag": "сеть NOC", "parent_id": None},
                    {"id": 105, "tag": "управляющая сеть", "parent_id": 65},
                    {"id": 285, "tag": "бестиарий", "parent_id": None},
                    {"id": 862, "tag": "vendor", "parent_id": 285},
                ],
                "atags": [
                    {"tag": "$id_22737"},
                    {"tag": "$typeid_7"},
                    {"tag": "$any_object"},
                    {"tag": "$cn_red1-wr1"},
                    {"tag": "$unmounted"},
                ],
            },
            {
                "object_id": 22737,
                "asset_no": 100361772,
                "atags": [
                    "$id_22737",
                    "$typeid_7",
                    "$any_object",
                    "$cn_red1-wr1",
                    "$unmounted",
                ],
                "deleted": False,
                "diff_enabled": True,
                "dirtiness": None,
                "etags": [
                    {"id": 66, "name": "маршрутизатор", "parent_id": 306},
                    {"id": 112, "name": "Морозов", "parent_id": 1179},
                    {"id": 565, "name": "спрятан от скриптов", "parent_id": 137},
                    {"id": 580, "name": "Autonomous WiFi точка", "parent_id": 1041},
                    {"id": 614, "name": "Out-of-band", "parent_id": 105},
                    {"id": 816, "name": "Mikrotik", "parent_id": 862},
                ],
                "fqdn": "red1-wr1.yndx.net",
                "itags": [
                    {"id": 306, "name": "конюшня NOC", "parent_id": None},
                    {"id": 279, "name": "планета Земля", "parent_id": None},
                    {"id": 26, "name": "Россия", "parent_id": 279},
                    {"id": 27, "name": "Москва", "parent_id": 26},
                    {"id": 1179, "name": "Красная Роза", "parent_id": 27},
                    {"id": 577, "name": "flags", "parent_id": None},
                    {"id": 137, "name": "в оффлайне", "parent_id": 577},
                    {"id": 1041, "name": "WiFi точка", "parent_id": 306},
                    {"id": 65, "name": "сеть NOC", "parent_id": None},
                    {"id": 105, "name": "управляющая сеть", "parent_id": 65},
                    {"id": 285, "name": "бестиарий", "parent_id": None},
                    {"id": 862, "name": "vendor", "parent_id": 285},
                ],
                "name": "red1-wr1",
                "vendor": "routeros",
            },
        ),
        (
            {
                "id": "28591",
                "name": "iva-fw5",
                "asset_no": "900924369",
                "fqdn": "iva-fw5.yndx.net",
                "etags": [
                    {"id": 165, "tag": "Ивантеевка", "parent_id": 26},
                    {"id": 308, "tag": "неисполненный конфиг", "parent_id": 577},
                    {"id": 1278, "tag": "группа Альфа", "parent_id": 510},
                    {"id": 1376, "tag": "E5-2660 v4", "parent_id": 797},
                    {"id": 1428, "tag": "50G router", "parent_id": 577},
                    {"id": 1510, "tag": "Ubuntu 18.04 LTS", "parent_id": 674},
                    {"id": 1544, "tag": "X10", "parent_id": 1541},
                    {"id": 1772, "tag": "YANET", "parent_id": None},
                    {"id": 1920, "tag": "ignore cpu", "parent_id": None},
                    {"id": 1932, "tag": "runs exabgp", "parent_id": 577},
                ],
                "itags": [
                    {"id": 279, "tag": "планета Земля", "parent_id": None},
                    {"id": 26, "tag": "Россия", "parent_id": 279},
                    {"id": 577, "tag": "flags", "parent_id": None},
                    {"id": 306, "tag": "конюшня NOC", "parent_id": None},
                    {"id": 66, "tag": "маршрутизатор", "parent_id": 306},
                    {"id": 121, "tag": "core router", "parent_id": 66},
                    {"id": 510, "tag": "firewall", "parent_id": 121},
                    {"id": 285, "tag": "бестиарий", "parent_id": None},
                    {"id": 566, "tag": "PC", "parent_id": 285},
                    {"id": 1405, "tag": "комплектующие", "parent_id": 566},
                    {"id": 1406, "tag": "CPU", "parent_id": 1405},
                    {"id": 290, "tag": "Intel Xeon", "parent_id": 1406},
                    {"id": 797, "tag": "E5-2660", "parent_id": 290},
                    {"id": 337, "tag": "Linux", "parent_id": 566},
                    {"id": 674, "tag": "Ubuntu", "parent_id": 337},
                    {"id": 1547, "tag": "Motherboard", "parent_id": 1405},
                    {"id": 1541, "tag": "Supermicro MB", "parent_id": 1547},
                ],
                "atags": [
                    {"tag": "$id_28591"},
                    {"tag": "$typeid_4"},
                    {"tag": "$any_object"},
                    {"tag": "$cn_iva-fw5"},
                    {"tag": "$attr_4_88894"},
                    {"tag": "$attr_10000_89616"},
                    {"tag": "$attr_10010_89409"},
                    {"tag": "$rackid_48630"},
                ],
            },
            {
                "object_id": 28591,
                "asset_no": 900924369,
                "atags": [
                    "$id_28591",
                    "$typeid_4",
                    "$any_object",
                    "$cn_iva-fw5",
                    "$attr_4_88894",
                    "$attr_10000_89616",
                    "$attr_10010_89409",
                    "$rackid_48630",
                ],
                "deleted": False,
                "dirtiness": None,
                "etags": [
                    {"id": 165, "name": "Ивантеевка", "parent_id": 26},
                    {"id": 308, "name": "неисполненный конфиг", "parent_id": 577},
                    {"id": 1278, "name": "группа Альфа", "parent_id": 510},
                    {"id": 1376, "name": "E5-2660 v4", "parent_id": 797},
                    {"id": 1428, "name": "50G router", "parent_id": 577},
                    {"id": 1510, "name": "Ubuntu 18.04 LTS", "parent_id": 674},
                    {"id": 1544, "name": "X10", "parent_id": 1541},
                    {"id": 1772, "name": "YANET", "parent_id": None},
                    {"id": 1920, "name": "ignore cpu", "parent_id": None},
                    {"id": 1932, "name": "runs exabgp", "parent_id": 577},
                ],
                "fqdn": "iva-fw5.yndx.net",
                "itags": [
                    {"id": 279, "name": "планета Земля", "parent_id": None},
                    {"id": 26, "name": "Россия", "parent_id": 279},
                    {"id": 577, "name": "flags", "parent_id": None},
                    {"id": 306, "name": "конюшня NOC", "parent_id": None},
                    {"id": 66, "name": "маршрутизатор", "parent_id": 306},
                    {"id": 121, "name": "core router", "parent_id": 66},
                    {"id": 510, "name": "firewall", "parent_id": 121},
                    {"id": 285, "name": "бестиарий", "parent_id": None},
                    {"id": 566, "name": "PC", "parent_id": 285},
                    {"id": 1405, "name": "комплектующие", "parent_id": 566},
                    {"id": 1406, "name": "CPU", "parent_id": 1405},
                    {"id": 290, "name": "Intel Xeon", "parent_id": 1406},
                    {"id": 797, "name": "E5-2660", "parent_id": 290},
                    {"id": 337, "name": "Linux", "parent_id": 566},
                    {"id": 674, "name": "Ubuntu", "parent_id": 337},
                    {"id": 1547, "name": "Motherboard", "parent_id": 1405},
                    {"id": 1541, "name": "Supermicro MB", "parent_id": 1547},
                ],
                "name": "iva-fw5",
                "vendor": "huawei",
                "diff_enabled": True,
            },
        ),
        (
            {
                "id": "58576",
                "name": "cipt-zoom-mmr10",
                "asset_no": None,
                "fqdn": "cipt-zoom-mmr10.yndx.net",
                "etags": [
                    {"id": 452, "tag": "Мытищи-6", "parent_id": 392},
                    {"id": 1518, "tag": "Conference bridge", "parent_id": 166},
                    {"id": 1799, "tag": "no backup", "parent_id": 577},
                    {"id": 1875, "tag": "Zoom", "parent_id": 862},
                    {"id": 1902, "tag": "CentOS 7", "parent_id": 1901},
                ],
                "itags": [
                    {"id": 279, "tag": "планета Земля", "parent_id": None},
                    {"id": 26, "tag": "Россия", "parent_id": 279},
                    {"id": 392, "tag": "Мытищи", "parent_id": 26},
                    {"id": 306, "tag": "конюшня NOC", "parent_id": None},
                    {"id": 660, "tag": "телефония", "parent_id": 306},
                    {"id": 135, "tag": "телефонный сервер", "parent_id": 660},
                    {"id": 166, "tag": "сервер видеоконференций", "parent_id": 135},
                    {"id": 577, "tag": "flags", "parent_id": None},
                    {"id": 285, "tag": "бестиарий", "parent_id": None},
                    {"id": 862, "tag": "vendor", "parent_id": 285},
                    {"id": 566, "tag": "PC", "parent_id": 285},
                    {"id": 337, "tag": "Linux", "parent_id": 566},
                    {"id": 1901, "tag": "CentOS", "parent_id": 337},
                ],
                "atags": [
                    {"tag": "$id_58576"},
                    {"tag": "$typeid_1504"},
                    {"tag": "$any_object"},
                    {"tag": "$cn_cipt-zoom-mmr10"},
                    {"tag": "$portless"},
                    {"tag": "$no_asset_tag"},
                    {"tag": "$containerid_56858"},
                ],
            },
            {
                "object_id": 58576,
                "asset_no": None,
                "atags": [
                    "$id_58576",
                    "$typeid_1504",
                    "$any_object",
                    "$cn_cipt-zoom-mmr10",
                    "$portless",
                    "$no_asset_tag",
                    "$containerid_56858",
                ],
                "deleted": False,
                "diff_enabled": True,
                "dirtiness": None,
                "etags": [
                    {"id": 452, "name": "Мытищи-6", "parent_id": 392},
                    {"id": 1518, "name": "Conference bridge", "parent_id": 166},
                    {"id": 1799, "name": "no backup", "parent_id": 577},
                    {"id": 1875, "name": "Zoom", "parent_id": 862},
                    {"id": 1902, "name": "CentOS 7", "parent_id": 1901},
                ],
                "fqdn": "cipt-zoom-mmr10.yndx.net",
                "itags": [
                    {"id": 279, "name": "планета Земля", "parent_id": None},
                    {"id": 26, "name": "Россия", "parent_id": 279},
                    {"id": 392, "name": "Мытищи", "parent_id": 26},
                    {"id": 306, "name": "конюшня NOC", "parent_id": None},
                    {"id": 660, "name": "телефония", "parent_id": 306},
                    {"id": 135, "name": "телефонный сервер", "parent_id": 660},
                    {"id": 166, "name": "сервер видеоконференций", "parent_id": 135},
                    {"id": 577, "name": "flags", "parent_id": None},
                    {"id": 285, "name": "бестиарий", "parent_id": None},
                    {"id": 862, "name": "vendor", "parent_id": 285},
                    {"id": 566, "name": "PC", "parent_id": 285},
                    {"id": 337, "name": "Linux", "parent_id": 566},
                    {"id": 1901, "name": "CentOS", "parent_id": 337},
                ],
                "name": "cipt-zoom-mmr10",
                "vendor": "zoom",
            },
        ),
    ),
)
def test_from_rt_object(
    invapi_dict: typing.Dict[str, typing.Any],
    expected_device_dict: typing.Dict[str, typing.Any],
):
    inv_object = invapi.Object(
        id=invapi_dict["id"],
        name=invapi_dict["name"],
        asset_no=invapi_dict["asset_no"],
        fqdn=invapi_dict["fqdn"],
        etags=[invapi.Tag(**x) for x in invapi_dict["etags"]],
        itags=[invapi.Tag(**x) for x in invapi_dict["itags"]],
        atags=[invapi.Tag(**x) for x in invapi_dict["atags"]],
    )
    result_device = device.Device.from_rt_object(inv_object, {int(inv_object.id)})
    assert dataclasses.asdict(result_device) == expected_device_dict
