from copy import deepcopy

from nile.processing.record import Record

APPMETRICA = dict(
    utc_event_dttm='2019-08-01 10:00:01',
    event_id='1234567890',
    app_platform_name='android',
    os_version_code='1.2.3',
    device_id='123asdf123',
    event_type='EVENT_CLIENT',
    event_name='abcder',
    event_value={},
    appmetrica_uuid='123asdf123',
    appmetrica_device_id='123asdf123',
    app_version_code='12345',
    user_lat=1.1,
    user_lon=2.2,
    destination_lat=11.11,
    destination_lon=22.22,
    device_manufacturer='AAA',
    device_model='A10',
    device_type='PHONE',
    battery_level=100,
    app='Lavka',
    user_id='1234',
    yandex_uid='abc123',
    adv_id='123',
    order_id=None,
    confirmed_flg=False,
    is_background_flg=False,
    delivery_type='eda_courier',
    region_id=123,
    place_city_name='Мурино',
    lavka_city_name='Санкт-Петербург',
    delivery_cost=None,
    offer_id=None,
    personal_phone_id='123',
    layout_id='123',
    appmetrica_user_locale='ruRU',
    autologin_successfully_finished='false',
    zone_mode=None,
    parcel_market_flg=None,
    active_parcel_ids=None,
    page_name=None,
    total_viewed_items=None,
)

LAVKA_APPSESSION_ATTRIBUTES = dict(
    utc_session_start_dttm='2019-08-01 10:00:01',
    utc_session_end_dttm='2019-08-01 11:30:01',
    appsession_id='9a8f8892b9016797405c5b3a4181818f',
    app_platform_name='android',
    first_app_version_code='12345',
    last_app_version_code='12345',
    event_id_list=['1234567890', '1234567891'],
    os_version_code='1.2.4',
    break_reason='timeout',
    duration_sec=1800,
    appmetrica_uuid='123asdf124',
    appmetrica_device_id='123asdf124',
    user_lat=1.1,
    user_lon=2.2,
    destination_lat=11.11,
    destination_lon=22.22,
    destination_diff_m=0.0,
    device_manufacturer_name='AAA',
    device_model_name='A10',
    device_type_name='PHONE',
    battery_level_pcnt=100,
    battery_level_diff_pcnt=0,
    eda_device_id='123asdf123',
    user_id_list=['1234'],
    yandex_uid_list=['abc123'],
    advert_id='123',
    is_checkout_succeeded_flg=False,
    is_background_flg=False,
    order_id_paid_list=None,
    order_id_created_list=None,
    is_menu_opened_flg=False,
    is_cart_updated_flg=False,
    is_cart_opened_flg=False,
    is_checkout_opened_flg=False,
    has_important_event_flg=False,
    delivery_type='eda_courier',
    is_category_list_opened_flg=False,
    session_app_list=['Lavka'],
    order_paid_from_app_list=None,
    place_id_list=None,
    surge_val_list=None,
    region_id=123,
    detail_city_name='Мурино',
    agg_city_name='Санкт-Петербург',
    utc_first_menu_opened_dttm=None,
    utc_last_menu_opened_dttm=None,
    utc_first_cart_updated_dttm=None,
    utc_last_cart_updated_dttm=None,
    utc_first_cart_opened_dttm=None,
    utc_last_cart_opened_dttm=None,
    utc_first_checkout_opened_dttm=None,
    utc_last_checkout_opened_dttm=None,
    utc_first_category_list_opened_dttm=None,
    utc_last_category_list_opened_dttm=None,
    utc_first_checkout_succeeded_dttm=None,
    utc_last_checkout_succeeded_dttm=None,
    delivery_cost_list=None,
    offer_id_list=None,
    search_opened_flg=False,
    utc_first_search_opened_dttm=None,
    utc_last_search_opened_dttm=None,
    search_succeeded_flg=False,
    utc_first_search_succeeded_dttm=None,
    utc_last_search_succeeded_dttm=None,
    phone_pd_id='123',
    layout_id='123',
    appmetrica_user_locale_code='ruRU',
    utc_first_login_shown_dttm=None,
    utc_last_login_shown_dttm=None,
    is_registered_flg=False,
    utc_registered_dttm=None,
    is_login_shown_flg=False,
    login_type_id=0,
    zone_mode_list=None,
    checkout_attempt_flg=False,
    utc_first_checkout_attempt_dttm=None,
    utc_last_checkout_attempt_dttm=None,
    onboarding_opened_flg=False,
    utc_first_onboarding_opened_dttm=None,
    utc_last_onboarding_opened_dttm=None,
    parcel_market_flg=False,
    lavka_item_viewed_flg=False,
    lavka_na_popup_shown_flg=False,
    misclick_flg=False
)


def create_default_record(default_args):
    def _record(**kwargs):
        attributes = deepcopy(default_args)
        attributes.update(**kwargs)
        return Record(**attributes)
    return _record


lavka_appmetrica_record = create_default_record(APPMETRICA)
lavka_appsession_record = create_default_record(LAVKA_APPSESSION_ATTRIBUTES)

