INSERT INTO "taxi_db_postgres_atlas_backend"."full_geo_hierarchy" (
    node_id,
    root_node_id,
    node_type,
    parent_node_id,
    population_group,
    name_ru,
    name_en,
    tariff_zone,
    direct_flg
)
VALUES
    ('op_russia', 'op_root', 'country', 'op_root', null, 'Россия', 'Russia', 'moscow', false),
    ('br_tsentralnyj_fo', 'br_root', 'node', 'br_russia', null, 'Центральный ФО', 'Central Federal District', 'moscow', false),
    ('br_moscow_adm', 'op_root', 'node', 'br_moscow', 'RU_MSC', 'Москва (адм)', 'Moscow (adm)', 'moscow', true),
    ('br_moscow_adm', 'fi_root', 'node', 'br_moscow', 'RU_MSC', 'Москва (адм)', 'Moscow (adm)', 'moscow', true),
    ('br_moscow_adm', 'br_root', 'node', 'br_moscow', 'RU_MSC', 'Москва (адм)', 'Moscow (adm)', 'moscow', true),
    ('op_moscow_and_mr', 'op_root', 'node', 'op_russia', 'RU_MSC', 'Москва и МО', 'Moscow and Moscow region', 'moscow', false),
    ('fi_russia_macro', 'fi_root', 'node', 'fi_root', null, 'Россия (Макро)', 'Russia (Macro)', 'moscow', false),
    ('op_root', 'op_root', 'root', null, null, 'Операционная иерархия', 'Operational hierarchy', 'moscow', false),
    ('op_ci', 'op_root', 'node', 'op_root', null, 'CI', 'CI', 'moscow', false),
    ('fi_root', 'fi_root', 'root', null, null, 'Финансовые регионы', 'Financial Regions', 'moscow', false),
    ('op_ci_citymobil', 'op_root', 'node', 'op_ci', null, 'Ситимобил', 'Citymobil', 'moscow', false),
    ('br_root', 'br_root', 'root', null, null, 'Базовая иерархия', 'Basic Hierarchy', 'moscow', false),
    ('br_moscow', 'op_root', 'agglomeration', 'op_moscow_and_mr', 'RU_MSC', 'Москва', 'Moscow', 'moscow', false),
    ('br_moscow', 'fi_root', 'agglomeration', 'fi_moscow_and_mr', 'RU_MSC', 'Москва', 'Moscow', 'moscow', false),
    ('br_moscow', 'br_root', 'agglomeration', 'br_moskovskaja_obl', 'RU_MSC', 'Москва', 'Moscow', 'moscow', false),
    ('br_moskovskaja_obl', 'br_root', 'node', 'br_tsentralnyj_fo', 'RU_MSC', 'Московская область', 'Moscow Region', 'moscow', false),
    ('fi_moscow_and_mr', 'fi_root', 'node', 'fi_russia', 'RU_MSC', 'Москва и МО', 'Moscow and Moscow region', 'moscow', false),
    ('fi_russia', 'fi_root', 'country', 'fi_russia_macro', null, 'Россия', 'Russia', 'moscow', false),
    ('br_russia', 'br_root', 'country', 'br_root', null, 'Россия', 'Russia', 'moscow', false),
    ('fi_moscow_and_mr', 'fi_root', 'node', 'fi_russia', 'RU_MSC', 'Москва и МО', 'Moscow and Moscow region', 'himki', false),
    ('op_russia', 'op_root', 'country', 'op_root', null, 'Россия', 'Russia', 'himki', false),
    ('op_ci_citymobil', 'op_root', 'node', 'op_ci', null, 'Ситимобил', 'Citymobil', 'himki', false),
    ('br_root', 'br_root', 'root', null, null, 'Базовая иерархия', 'Basic Hierarchy', 'himki', false),
    ('br_moskovskaja_obl', 'br_root', 'node', 'br_tsentralnyj_fo', 'RU_MSC', 'Московская область', 'Moscow Region', 'himki', false),
    ('br_tsentralnyj_fo', 'br_root', 'node', 'br_russia', null, 'Центральный ФО', 'Central Federal District', 'himki', false),
    ('fi_root', 'fi_root', 'root', null, null, 'Финансовые регионы', 'Financial Regions', 'himki', false),
    ('fi_russia', 'fi_root', 'country', 'fi_russia_macro', null, 'Россия', 'Russia', 'himki', false),
    ('br_moscow_near_region', 'op_root', 'node', 'br_moscow', 'RU_MSC', 'Москва (ближнее МО)', 'Moscow (Near Region)', 'himki', false),
    ('br_moscow_near_region', 'fi_root', 'node', 'br_moscow', 'RU_MSC', 'Москва (ближнее МО)', 'Moscow (Near Region)', 'himki', false),
    ('br_moscow_near_region', 'br_root', 'node', 'br_moscow', 'RU_MSC', 'Москва (ближнее МО)', 'Moscow (Near Region)', 'himki', false),
    ('op_ci', 'op_root', 'node', 'op_root', null, 'CI', 'CI', 'himki', false),
    ('fi_russia_macro', 'fi_root', 'node', 'fi_root', null, 'Россия (Макро)', 'Russia (Macro)', 'himki', false),
    ('op_moscow_and_mr', 'op_root', 'node', 'op_russia', 'RU_MSC', 'Москва и МО', 'Moscow and Moscow region', 'himki', false),
    ('op_root', 'op_root', 'root', null, null, 'Операционная иерархия', 'Operational hierarchy', 'himki', false),
    ('op_moscow_region', 'op_root', 'node', 'op_russia', 'RU_MSC', 'Московская область', 'Moscow region', 'himki', false),
    ('br_moscow', 'fi_root', 'agglomeration', 'fi_moscow_and_mr', 'RU_MSC', 'Москва', 'Moscow', 'himki', false),
    ('br_moscow', 'br_root', 'agglomeration', 'br_moskovskaja_obl', 'RU_MSC', 'Москва', 'Moscow', 'himki', false),
    ('br_moscow', 'op_root', 'agglomeration', 'op_moscow_and_mr', 'RU_MSC', 'Москва', 'Moscow', 'himki', false),
    ('br_russia', 'br_root', 'country', 'br_root', null, 'Россия', 'Russia', 'himki', false),
    ('br_khimki', 'fi_root', 'node', 'br_moscow_near_region', 'RU_MSC', 'Химки', 'Khimki', 'himki', true),
    ('br_khimki', 'br_root', 'node', 'br_moscow_near_region', 'RU_MSC', 'Химки', 'Khimki', 'himki', true),
    ('br_khimki', 'op_root', 'node', 'br_moscow_near_region', 'RU_MSC', 'Химки', 'Khimki', 'himki', true),
    ('fi_root', 'fi_root', 'root', null, null, 'Финансовые регионы', 'Financial Regions', 'voronezh', false),
    ('op_ci_citymobil', 'op_root', 'node', 'op_ci', null, 'Ситимобил', 'Citymobil', 'voronezh', false),
    ('fi_ru_1mp', 'fi_root', 'node', 'fi_russia', 'RU_1M+', 'RU_1M+', 'RU_1M+', 'voronezh', false),
    ('op_center', 'op_root', 'node', 'op_russia', null, 'Центр', 'Center', 'voronezh', false),
    ('fi_russia', 'fi_root', 'country', 'fi_russia_macro', null, 'Россия', 'Russia', 'voronezh', false),
    ('br_root', 'br_root', 'root', null, null, 'Базовая иерархия', 'Basic Hierarchy', 'voronezh', false),
    ('br_tsentralnyj_fo', 'br_root', 'node', 'br_russia', null, 'Центральный ФО', 'Central Federal District', 'voronezh', false),
    ('op_ci_didi_wave3_large', 'op_root', 'node', 'op_ci_didi_wave3', null, 'DiDi wave 3 large', 'DiDi wave 3 large', 'voronezh', false),
    ('op_ci_didi_wave3', 'op_root', 'node', 'op_ci_didi', null, 'DiDi wave 3', 'DiDi wave 3', 'voronezh', false),
    ('op_ci_didi', 'op_root', 'node', 'op_ci', null, 'DiDi', 'DiDi', 'voronezh', false),
    ('br_voronezhskaja_obl', 'br_root', 'node', 'br_tsentralnyj_fo', null, 'Воронежская область', 'Voronezh Region', 'voronezh', false),
    ('br_russia', 'br_root', 'country', 'br_root', null, 'Россия', 'Russia', 'voronezh', false),
    ('br_voronezh', 'br_root', 'agglomeration', 'br_voronezhskaja_obl', 'RU_1M+', 'Воронеж', 'Voronezh', 'voronezh', true),
    ('br_voronezh', 'fi_root', 'agglomeration', 'fi_ru_1mp', 'RU_1M+', 'Воронеж', 'Voronezh', 'voronezh', true),
    ('br_voronezh', 'op_root', 'agglomeration', 'op_center', 'RU_1M+', 'Воронеж', 'Voronezh', 'voronezh', true),
    ('op_root', 'op_root', 'root', null, null, 'Операционная иерархия', 'Operational hierarchy', 'voronezh', false),
    ('fi_russia_macro', 'fi_root', 'node', 'fi_root', null, 'Россия (Макро)', 'Russia (Macro)', 'voronezh', false),
    ('op_ci', 'op_root', 'node', 'op_root', null, 'CI', 'CI', 'voronezh', false),
    ('op_russia', 'op_root', 'country', 'op_root', null, 'Россия', 'Russia', 'voronezh', false);
