CREATE TABLE IF NOT EXISTS "taxi_db_postgres_atlas_backend"."tariff_hierarchy"
(
    node_id TEXT PRIMARY KEY,
    tariff_class_code TEXT NOT NULL,
    root_node_id TEXT NOT NULL,
    node_type TEXT NOT NULL,
    name_en TEXT NOT NULL,
    name_ru TEXT NOT NULL,
    tariff_zone TEXT NOT NULL,
    parent_node_id TEXT,
    is_deleted BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (root_node_id)
        REFERENCES "taxi_db_postgres_atlas_backend"."tariff_hierarchy" (node_id),
    FOREIGN KEY (parent_node_id)
        REFERENCES "taxi_db_postgres_atlas_backend"."tariff_hierarchy" (node_id)
);

CREATE INDEX IF NOT EXISTS tariff_hierarchy_selection_key
    ON "taxi_db_postgres_atlas_backend"."tariff_hierarchy"
        (tariff_zone, root_node_id, is_deleted);

INSERT INTO "taxi_db_postgres_atlas_backend"."tariff_hierarchy"
(
    node_id,
    tariff_class_code,
    root_node_id,
    node_type,
    name_en,
    name_ru,
    tariff_zone,
    parent_node_id
)
VALUES
    ('br_root_moscow', 'Basic', 'br_root_moscow', 'root', 'Basic', 'Базовая', 'moscow', NULL),
    ('br_Business_moscow', 'Business', 'br_root_moscow', 'group', 'Business', 'Business', 'moscow', 'br_root_moscow'),
    ('br_MQC_moscow', 'MQC', 'br_root_moscow', 'group', 'MQC', 'MQC', 'moscow', 'br_root_moscow'),
    ('br_uberblack_UberBlack_UberBlack_moscow', 'uberblack', 'br_root_moscow', 'node', 'UberBlack', 'UberBlack', 'moscow', 'br_Business_moscow'),
    ('fi_root_moscow', 'Financial', 'fi_root_moscow', 'root', 'Financial', 'Финансовая', 'moscow', NULL),
    ('fi_Business_moscow', 'Business', 'fi_root_moscow', 'group', 'Business', 'Business', 'moscow', 'fi_root_moscow'),
    ('fi_uberblack_UberBlack_UberBlack_moscow', 'uberblack', 'fi_root_moscow', 'node', 'UberBlack', 'UberBlack', 'moscow', 'fi_Business_moscow'),
    ('op_root_moscow', 'Operational', 'op_root_moscow', 'root', 'Operational', 'Операционная', 'moscow', NULL),
    ('op_Ultima_moscow', 'Ultima', 'op_root_moscow', 'group', 'Ultima', 'Ultima', 'moscow', 'op_root_moscow'),
    ('op_uberblack_UberBlack_UberBlack_moscow', 'uberblack', 'op_root_moscow', 'node', 'UberBlack', 'UberBlack', 'moscow', 'op_Ultima_moscow'),
    ('sp_root_moscow', 'Support', 'sp_root_moscow', 'root', 'Support', 'Иерархия службы поддержки', 'moscow', NULL),
    ('sp_Premium_moscow', 'Premium', 'sp_root_moscow', 'group', 'Premium', 'Premium', 'moscow', 'sp_root_moscow'),
    ('sp_uberblack_UberBlack_UberBlack_moscow', 'uberblack', 'sp_root_moscow', 'node', 'UberBlack', 'UberBlack', 'moscow', 'sp_Premium_moscow'),
    ('br_vip_Business_Business_moscow', 'vip', 'br_root_moscow', 'node', 'Business', 'Business', 'moscow', 'br_Business_moscow'),
    ('fi_vip_Business_Business_moscow', 'vip', 'fi_root_moscow', 'node', 'Business', 'Business', 'moscow', 'fi_Business_moscow'),
    ('op_vip_Business_Business_moscow', 'vip', 'op_root_moscow', 'node', 'Business', 'Business', 'moscow', 'op_Ultima_moscow'),
    ('sp_vip_Business_Business_moscow', 'vip', 'sp_root_moscow', 'node', 'Business', 'Business', 'moscow', 'sp_Premium_moscow'),
    ('br_Cargo_moscow', 'Cargo', 'br_root_moscow', 'group', 'Cargo', 'Cargo', 'moscow', 'br_root_moscow'),
    ('br_cargo_Cargo_Грузовой_moscow', 'cargo', 'br_root_moscow', 'node', 'Cargo', 'Грузовой', 'moscow', 'br_Cargo_moscow'),
    ('fi_New_Businesses_moscow', 'New Businesses', 'fi_root_moscow', 'group', 'New Businesses', 'New Businesses', 'moscow', 'fi_root_moscow'),
    ('fi_cargo_Cargo_Грузовой_moscow', 'cargo', 'fi_root_moscow', 'node', 'Cargo', 'Грузовой', 'moscow', 'fi_New_Businesses_moscow'),
    ('op_Logistics_moscow', 'Logistics', 'op_root_moscow', 'group', 'Logistics', 'Logistics', 'moscow', 'op_root_moscow'),
    ('op_cargo_Cargo_Грузовой_moscow', 'cargo', 'op_root_moscow', 'node', 'Cargo', 'Грузовой', 'moscow', 'op_Logistics_moscow'),
    ('sp_Logistics_moscow', 'Logistics', 'sp_root_moscow', 'group', 'Logistics', 'Logistics', 'moscow', 'sp_root_moscow'),
    ('sp_cargo_Cargo_Грузовой_moscow', 'cargo', 'sp_root_moscow', 'node', 'Cargo', 'Грузовой', 'moscow', 'sp_Logistics_moscow'),
    ('br_cargocorp_Cargo_(Corporate)_Грузовой_(Корпоративный)_moscow', 'cargocorp', 'br_root_moscow', 'node', 'Cargo (Corporate)', 'Грузовой (Корпоративный)', 'moscow', 'br_Cargo_moscow'),
    ('fi_cargocorp_Cargo_(Corporate)_Грузовой_(Корпоративный)_moscow', 'cargocorp', 'fi_root_moscow', 'node', 'Cargo (Corporate)', 'Грузовой (Корпоративный)', 'moscow', 'fi_New_Businesses_moscow'),
    ('op_cargocorp_Cargo_(Corporate)_Грузовой_(Корпоративный)_moscow', 'cargocorp', 'op_root_moscow', 'node', 'Cargo (Corporate)', 'Грузовой (Корпоративный)', 'moscow', 'op_Logistics_moscow'),
    ('sp_cargocorp_Cargo_(Corporate)_Грузовой_(Корпоративный)_moscow', 'cargocorp', 'sp_root_moscow', 'node', 'Cargo (Corporate)', 'Грузовой (Корпоративный)', 'moscow', 'sp_Logistics_moscow'),
    ('br_Combo_moscow', 'Combo', 'br_root_moscow', 'group', 'Combo', 'Combo', 'moscow', 'br_root_moscow'),
    ('br_pool_Combo_Комбо_moscow', 'pool', 'br_root_moscow', 'node', 'Combo', 'Комбо', 'moscow', 'br_Combo_moscow'),
    ('fi_Economy_moscow', 'Economy', 'fi_root_moscow', 'group', 'Economy', 'Economy', 'moscow', 'fi_root_moscow'),
    ('fi_pool_Combo_Комбо_moscow', 'pool', 'fi_root_moscow', 'node', 'Combo', 'Комбо', 'moscow', 'fi_Economy_moscow'),
    ('op_Econom_moscow', 'Econom', 'op_root_moscow', 'group', 'Econom', 'Econom', 'moscow', 'op_root_moscow'),
    ('op_pool_Combo_Комбо_moscow', 'pool', 'op_root_moscow', 'node', 'Combo', 'Комбо', 'moscow', 'op_Econom_moscow'),
    ('sp_Mass_moscow', 'Mass', 'sp_root_moscow', 'group', 'Mass', 'Mass', 'moscow', 'sp_root_moscow'),
    ('sp_pool_Combo_Комбо_moscow', 'pool', 'sp_root_moscow', 'node', 'Combo', 'Комбо', 'moscow', 'sp_Mass_moscow'),
    ('br_Comfort_moscow', 'Comfort', 'br_root_moscow', 'group', 'Comfort', 'Comfort', 'moscow', 'br_root_moscow'),
    ('br_business_Comfort_Комфорт_moscow', 'business', 'br_root_moscow', 'node', 'Comfort', 'Комфорт', 'moscow', 'br_Comfort_moscow'),
    ('fi_Comfort_moscow', 'Comfort', 'fi_root_moscow', 'group', 'Comfort', 'Comfort', 'moscow', 'fi_root_moscow'),
    ('fi_business_Comfort_Комфорт_moscow', 'business', 'fi_root_moscow', 'node', 'Comfort', 'Комфорт', 'moscow', 'fi_Comfort_moscow'),
    ('op_Comfort_moscow', 'Comfort', 'op_root_moscow', 'group', 'Comfort', 'Comfort', 'moscow', 'op_root_moscow'),
    ('op_business_Comfort_Комфорт_moscow', 'business', 'op_root_moscow', 'node', 'Comfort', 'Комфорт', 'moscow', 'op_Comfort_moscow'),
    ('sp_business_Comfort_Комфорт_moscow', 'business', 'sp_root_moscow', 'node', 'Comfort', 'Комфорт', 'moscow', 'sp_Mass_moscow'),
    ('br_uberselect_UberSelect_UberSelect_moscow', 'uberselect', 'br_root_moscow', 'node', 'UberSelect', 'UberSelect', 'moscow', 'br_Comfort_moscow'),
    ('fi_uberselect_UberSelect_UberSelect_moscow', 'uberselect', 'fi_root_moscow', 'node', 'UberSelect', 'UberSelect', 'moscow', 'fi_Comfort_moscow'),
    ('op_uberselect_UberSelect_UberSelect_moscow', 'uberselect', 'op_root_moscow', 'node', 'UberSelect', 'UberSelect', 'moscow', 'op_Comfort_moscow'),
    ('sp_uberselect_UberSelect_UberSelect_moscow', 'uberselect', 'sp_root_moscow', 'node', 'UberSelect', 'UberSelect', 'moscow', 'sp_Mass_moscow'),
    ('br_vezetbusiness_Comfort_Vezet_Комфорт_Везет_moscow', 'vezetbusiness', 'br_root_moscow', 'node', 'Comfort Vezet', 'Комфорт Везет', 'moscow', 'br_Comfort_moscow'),
    ('fi_vezetbusiness_Comfort_Vezet_Комфорт_Везет_moscow', 'vezetbusiness', 'fi_root_moscow', 'node', 'Comfort Vezet', 'Комфорт Везет', 'moscow', 'fi_Comfort_moscow'),
    ('op_vezetbusiness_Comfort_Vezet_Комфорт_Везет_moscow', 'vezetbusiness', 'op_root_moscow', 'node', 'Comfort Vezet', 'Комфорт Везет', 'moscow', 'op_Comfort_moscow'),
    ('sp_vezetbusiness_Comfort_Vezet_Комфорт_Везет_moscow', 'vezetbusiness', 'sp_root_moscow', 'node', 'Comfort Vezet', 'Комфорт Везет', 'moscow', 'sp_Mass_moscow'),
    ('br_Comfort+_moscow', 'Comfort+', 'br_root_moscow', 'group', 'Comfort+', 'Comfort+', 'moscow', 'br_root_moscow'),
    ('br_comfortplus_Comfort+_Комфорт+_moscow', 'comfortplus', 'br_root_moscow', 'node', 'Comfort+', 'Комфорт+', 'moscow', 'br_Comfort+_moscow'),
    ('fi_comfortplus_Comfort+_Комфорт+_moscow', 'comfortplus', 'fi_root_moscow', 'node', 'Comfort+', 'Комфорт+', 'moscow', 'fi_Comfort_moscow'),
    ('op_comfortplus_Comfort+_Комфорт+_moscow', 'comfortplus', 'op_root_moscow', 'node', 'Comfort+', 'Комфорт+', 'moscow', 'op_Comfort_moscow'),
    ('sp_comfortplus_Comfort+_Комфорт+_moscow', 'comfortplus', 'sp_root_moscow', 'node', 'Comfort+', 'Комфорт+', 'moscow', 'sp_Mass_moscow'),
    ('br_uberselectplus_UberSelect+_UberSelect+_moscow', 'uberselectplus', 'br_root_moscow', 'node', 'UberSelect+', 'UberSelect+', 'moscow', 'br_Comfort+_moscow'),
    ('fi_uberselectplus_UberSelect+_UberSelect+_moscow', 'uberselectplus', 'fi_root_moscow', 'node', 'UberSelect+', 'UberSelect+', 'moscow', 'fi_Comfort_moscow'),
    ('op_uberselectplus_UberSelect+_UberSelect+_moscow', 'uberselectplus', 'op_root_moscow', 'node', 'UberSelect+', 'UberSelect+', 'moscow', 'op_Comfort_moscow'),
    ('sp_uberselectplus_UberSelect+_UberSelect+_moscow', 'uberselectplus', 'sp_root_moscow', 'node', 'UberSelect+', 'UberSelect+', 'moscow', 'sp_Mass_moscow'),
    ('br_Courier_moscow', 'Courier', 'br_root_moscow', 'group', 'Courier', 'Courier', 'moscow', 'br_root_moscow'),
    ('br_courier_Courier_Курьер_moscow', 'courier', 'br_root_moscow', 'node', 'Courier', 'Курьер', 'moscow', 'br_Courier_moscow'),
    ('fi_courier_Courier_Курьер_moscow', 'courier', 'fi_root_moscow', 'node', 'Courier', 'Курьер', 'moscow', 'fi_New_Businesses_moscow'),
    ('op_courier_Courier_Курьер_moscow', 'courier', 'op_root_moscow', 'node', 'Courier', 'Курьер', 'moscow', 'op_Logistics_moscow'),
    ('sp_courier_Courier_Курьер_moscow', 'courier', 'sp_root_moscow', 'node', 'Courier', 'Курьер', 'moscow', 'sp_Logistics_moscow'),
    ('br_eda_Eats_Еда_moscow', 'eda', 'br_root_moscow', 'node', 'Eats', 'Еда', 'moscow', 'br_Courier_moscow'),
    ('fi_eda_Eats_Еда_moscow', 'eda', 'fi_root_moscow', 'node', 'Eats', 'Еда', 'moscow', 'fi_New_Businesses_moscow'),
    ('op_eda_Eats_Еда_moscow', 'eda', 'op_root_moscow', 'node', 'Eats', 'Еда', 'moscow', 'op_Logistics_moscow'),
    ('sp_eda_Eats_Еда_moscow', 'eda', 'sp_root_moscow', 'node', 'Eats', 'Еда', 'moscow', 'sp_Logistics_moscow'),
    ('br_lavka_Lavka_Лавка_moscow', 'lavka', 'br_root_moscow', 'node', 'Lavka', 'Лавка', 'moscow', 'br_Courier_moscow'),
    ('fi_lavka_Lavka_Лавка_moscow', 'lavka', 'fi_root_moscow', 'node', 'Lavka', 'Лавка', 'moscow', 'fi_New_Businesses_moscow'),
    ('op_lavka_Lavka_Лавка_moscow', 'lavka', 'op_root_moscow', 'node', 'Lavka', 'Лавка', 'moscow', 'op_Logistics_moscow'),
    ('sp_lavka_Lavka_Лавка_moscow', 'lavka', 'sp_root_moscow', 'node', 'Lavka', 'Лавка', 'moscow', 'sp_Logistics_moscow'),
    ('br_Cruise_moscow', 'Cruise', 'br_root_moscow', 'group', 'Cruise', 'Cruise', 'moscow', 'br_root_moscow'),
    ('br_premium_van_Cruise_Cruise_moscow', 'premium_van', 'br_root_moscow', 'node', 'Cruise', 'Cruise', 'moscow', 'br_Cruise_moscow'),
    ('fi_premium_van_Cruise_Cruise_moscow', 'premium_van', 'fi_root_moscow', 'node', 'Cruise', 'Cruise', 'moscow', 'fi_Business_moscow'),
    ('op_premium_van_Cruise_Cruise_moscow', 'premium_van', 'op_root_moscow', 'node', 'Cruise', 'Cruise', 'moscow', 'op_Ultima_moscow'),
    ('sp_premium_van_Cruise_Cruise_moscow', 'premium_van', 'sp_root_moscow', 'node', 'Cruise', 'Cruise', 'moscow', 'sp_Premium_moscow'),
    ('br_Delivery_moscow', 'Delivery', 'br_root_moscow', 'group', 'Delivery', 'Delivery', 'moscow', 'br_root_moscow'),
    ('br_express_Delivery_Доставка_moscow', 'express', 'br_root_moscow', 'node', 'Delivery', 'Доставка', 'moscow', 'br_Delivery_moscow'),
    ('fi_express_Delivery_Доставка_moscow', 'express', 'fi_root_moscow', 'node', 'Delivery', 'Доставка', 'moscow', 'fi_New_Businesses_moscow'),
    ('op_express_Delivery_Доставка_moscow', 'express', 'op_root_moscow', 'node', 'Delivery', 'Доставка', 'moscow', 'op_Logistics_moscow'),
    ('sp_express_Delivery_Доставка_moscow', 'express', 'sp_root_moscow', 'node', 'Delivery', 'Доставка', 'moscow', 'sp_Logistics_moscow'),
    ('br_night_Night_Повышенная_доставка_moscow', 'night', 'br_root_moscow', 'node', 'Night', 'Повышенная доставка', 'moscow', 'br_Delivery_moscow'),
    ('fi_night_Night_Повышенная_доставка_moscow', 'night', 'fi_root_moscow', 'node', 'Night', 'Повышенная доставка', 'moscow', 'fi_New_Businesses_moscow'),
    ('op_night_Night_Повышенная_доставка_moscow', 'night', 'op_root_moscow', 'node', 'Night', 'Повышенная доставка', 'moscow', 'op_Logistics_moscow'),
    ('sp_night_Night_Повышенная_доставка_moscow', 'night', 'sp_root_moscow', 'node', 'Night', 'Повышенная доставка', 'moscow', 'sp_Logistics_moscow'),
    ('br_ubernight_Uber_Delivery_Uber_Доставка_moscow', 'ubernight', 'br_root_moscow', 'node', 'Uber Delivery', 'Uber Доставка', 'moscow', 'br_Delivery_moscow'),
    ('fi_ubernight_Uber_Delivery_Uber_Доставка_moscow', 'ubernight', 'fi_root_moscow', 'node', 'Uber Delivery', 'Uber Доставка', 'moscow', 'fi_New_Businesses_moscow'),
    ('op_ubernight_Uber_Delivery_Uber_Доставка_moscow', 'ubernight', 'op_root_moscow', 'node', 'Uber Delivery', 'Uber Доставка', 'moscow', 'op_Logistics_moscow'),
    ('sp_ubernight_Uber_Delivery_Uber_Доставка_moscow', 'ubernight', 'sp_root_moscow', 'node', 'Uber Delivery', 'Uber Доставка', 'moscow', 'sp_Logistics_moscow'),
    ('br_Demostand_moscow', 'Demostand', 'br_root_moscow', 'group', 'Demostand', 'Demostand', 'moscow', 'br_root_moscow'),
    ('br_demostand_Demostand_Стэнд_moscow', 'demostand', 'br_root_moscow', 'node', 'Demostand', 'Стэнд', 'moscow', 'br_Demostand_moscow'),
    ('fi_Other_moscow', 'Other', 'fi_root_moscow', 'group', 'Other', 'Other', 'moscow', 'fi_root_moscow'),
    ('fi_demostand_Demostand_Стэнд_moscow', 'demostand', 'fi_root_moscow', 'node', 'Demostand', 'Стэнд', 'moscow', 'fi_Other_moscow'),
    ('op_Other_moscow', 'Other', 'op_root_moscow', 'group', 'Other', 'Other', 'moscow', 'op_root_moscow'),
    ('op_demostand_Demostand_Стэнд_moscow', 'demostand', 'op_root_moscow', 'node', 'Demostand', 'Стэнд', 'moscow', 'op_Other_moscow'),
    ('sp_demostand_Demostand_Стэнд_moscow', 'demostand', 'sp_root_moscow', 'node', 'Demostand', 'Стэнд', 'moscow', 'sp_Mass_moscow'),
    ('br_Driver_moscow', 'Driver', 'br_root_moscow', 'group', 'Driver', 'Driver', 'moscow', 'br_root_moscow'),
    ('br_personal_driver_Driver_Driver_moscow', 'personal_driver', 'br_root_moscow', 'node', 'Driver', 'Driver', 'moscow', 'br_Driver_moscow'),
    ('fi_personal_driver_Driver_Driver_moscow', 'personal_driver', 'fi_root_moscow', 'node', 'Driver', 'Driver', 'moscow', 'fi_Business_moscow'),
    ('op_personal_driver_Driver_Driver_moscow', 'personal_driver', 'op_root_moscow', 'node', 'Driver', 'Driver', 'moscow', 'op_Ultima_moscow'),
    ('sp_personal_driver_Driver_Driver_moscow', 'personal_driver', 'sp_root_moscow', 'node', 'Driver', 'Driver', 'moscow', 'sp_Premium_moscow'),
    ('br_Econom_moscow', 'Econom', 'br_root_moscow', 'group', 'Econom', 'Econom', 'moscow', 'br_root_moscow'),
    ('br_econom_Econom_Эконом_moscow', 'econom', 'br_root_moscow', 'node', 'Econom', 'Эконом', 'moscow', 'br_Econom_moscow'),
    ('fi_econom_Econom_Эконом_moscow', 'econom', 'fi_root_moscow', 'node', 'Econom', 'Эконом', 'moscow', 'fi_Economy_moscow'),
    ('op_econom_Econom_Эконом_moscow', 'econom', 'op_root_moscow', 'node', 'Econom', 'Эконом', 'moscow', 'op_Econom_moscow'),
    ('sp_econom_Econom_Эконом_moscow', 'econom', 'sp_root_moscow', 'node', 'Econom', 'Эконом', 'moscow', 'sp_Mass_moscow'),
    ('br_mkk_antifraud_Call_center_tariff_(Econom)_Тариф_КЦ_(Эконом)_moscow', 'mkk_antifraud', 'br_root_moscow', 'node', 'Call center tariff (Econom)', 'Тариф КЦ (Эконом)', 'moscow', 'br_Econom_moscow'),
    ('fi_mkk_antifraud_Call_center_tariff_(Econom)_Тариф_КЦ_(Эконом)_moscow', 'mkk_antifraud', 'fi_root_moscow', 'node', 'Call center tariff (Econom)', 'Тариф КЦ (Эконом)', 'moscow', 'fi_Economy_moscow'),
    ('op_mkk_antifraud_Call_center_tariff_(Econom)_Тариф_КЦ_(Эконом)_moscow', 'mkk_antifraud', 'op_root_moscow', 'node', 'Call center tariff (Econom)', 'Тариф КЦ (Эконом)', 'moscow', 'op_Econom_moscow'),
    ('sp_mkk_antifraud_Call_center_tariff_(Econom)_Тариф_КЦ_(Эконом)_moscow', 'mkk_antifraud', 'sp_root_moscow', 'node', 'Call center tariff (Econom)', 'Тариф КЦ (Эконом)', 'moscow', 'sp_Mass_moscow'),
    ('br_uberx_UberX_UberX_moscow', 'uberx', 'br_root_moscow', 'node', 'UberX', 'UberX', 'moscow', 'br_Econom_moscow'),
    ('fi_uberx_UberX_UberX_moscow', 'uberx', 'fi_root_moscow', 'node', 'UberX', 'UberX', 'moscow', 'fi_Economy_moscow'),
    ('op_uberx_UberX_UberX_moscow', 'uberx', 'op_root_moscow', 'node', 'UberX', 'UberX', 'moscow', 'op_Econom_moscow'),
    ('sp_uberx_UberX_UberX_moscow', 'uberx', 'sp_root_moscow', 'node', 'UberX', 'UberX', 'moscow', 'sp_Mass_moscow'),
    ('br_vezeteconom_Econom_Vezet_Эконом_Везет_moscow', 'vezeteconom', 'br_root_moscow', 'node', 'Econom Vezet', 'Эконом Везет', 'moscow', 'br_Econom_moscow'),
    ('fi_vezeteconom_Econom_Vezet_Эконом_Везет_moscow', 'vezeteconom', 'fi_root_moscow', 'node', 'Econom Vezet', 'Эконом Везет', 'moscow', 'fi_Economy_moscow'),
    ('op_vezeteconom_Econom_Vezet_Эконом_Везет_moscow', 'vezeteconom', 'op_root_moscow', 'node', 'Econom Vezet', 'Эконом Везет', 'moscow', 'op_Econom_moscow'),
    ('sp_vezeteconom_Econom_Vezet_Эконом_Везет_moscow', 'vezeteconom', 'sp_root_moscow', 'node', 'Econom Vezet', 'Эконом Везет', 'moscow', 'sp_Mass_moscow'),
    ('br_Elite_moscow', 'Elite', 'br_root_moscow', 'group', 'Elite', 'Elite', 'moscow', 'br_root_moscow'),
    ('br_maybach_Elite_Elite_moscow', 'maybach', 'br_root_moscow', 'node', 'Elite', 'Elite', 'moscow', 'br_Elite_moscow'),
    ('fi_maybach_Elite_Elite_moscow', 'maybach', 'fi_root_moscow', 'node', 'Elite', 'Elite', 'moscow', 'fi_Business_moscow'),
    ('op_maybach_Elite_Elite_moscow', 'maybach', 'op_root_moscow', 'node', 'Elite', 'Elite', 'moscow', 'op_Ultima_moscow'),
    ('sp_maybach_Elite_Elite_moscow', 'maybach', 'sp_root_moscow', 'node', 'Elite', 'Elite', 'moscow', 'sp_Premium_moscow'),
    ('br_Kids_moscow', 'Kids', 'br_root_moscow', 'group', 'Kids', 'Kids', 'moscow', 'br_root_moscow'),
    ('br_child_tariff_Kids_Детский_moscow', 'child_tariff', 'br_root_moscow', 'node', 'Kids', 'Детский', 'moscow', 'br_Kids_moscow'),
    ('fi_Functional_moscow', 'Functional', 'fi_root_moscow', 'group', 'Functional', 'Functional', 'moscow', 'fi_root_moscow'),
    ('fi_child_tariff_Kids_Детский_moscow', 'child_tariff', 'fi_root_moscow', 'node', 'Kids', 'Детский', 'moscow', 'fi_Functional_moscow'),
    ('op_Child_moscow', 'Child', 'op_root_moscow', 'group', 'Child', 'Child', 'moscow', 'op_root_moscow'),
    ('op_child_tariff_Kids_Детский_moscow', 'child_tariff', 'op_root_moscow', 'node', 'Kids', 'Детский', 'moscow', 'op_Child_moscow'),
    ('sp_Functional_moscow', 'Functional', 'sp_root_moscow', 'group', 'Functional', 'Functional', 'moscow', 'sp_root_moscow'),
    ('sp_child_tariff_Kids_Детский_moscow', 'child_tariff', 'sp_root_moscow', 'node', 'Kids', 'Детский', 'moscow', 'sp_Functional_moscow'),
    ('br_uberkids_UberKids_UberKids_moscow', 'uberkids', 'br_root_moscow', 'node', 'UberKids', 'UberKids', 'moscow', 'br_Kids_moscow'),
    ('fi_uberkids_UberKids_UberKids_moscow', 'uberkids', 'fi_root_moscow', 'node', 'UberKids', 'UberKids', 'moscow', 'fi_Functional_moscow'),
    ('op_uberkids_UberKids_UberKids_moscow', 'uberkids', 'op_root_moscow', 'node', 'UberKids', 'UberKids', 'moscow', 'op_Child_moscow'),
    ('sp_uberkids_UberKids_UberKids_moscow', 'uberkids', 'sp_root_moscow', 'node', 'UberKids', 'UberKids', 'moscow', 'sp_Functional_moscow'),
    ('br_Minivan_moscow', 'Minivan', 'br_root_moscow', 'group', 'Minivan', 'Minivan', 'moscow', 'br_root_moscow'),
    ('br_minivan_Minivan_Минивен_moscow', 'minivan', 'br_root_moscow', 'node', 'Minivan', 'Минивен', 'moscow', 'br_Minivan_moscow'),
    ('fi_minivan_Minivan_Минивен_moscow', 'minivan', 'fi_root_moscow', 'node', 'Minivan', 'Минивен', 'moscow', 'fi_Functional_moscow'),
    ('op_Minivan_moscow', 'Minivan', 'op_root_moscow', 'group', 'Minivan', 'Minivan', 'moscow', 'op_root_moscow'),
    ('op_minivan_Minivan_Минивен_moscow', 'minivan', 'op_root_moscow', 'node', 'Minivan', 'Минивен', 'moscow', 'op_Minivan_moscow'),
    ('sp_minivan_Minivan_Минивен_moscow', 'minivan', 'sp_root_moscow', 'node', 'Minivan', 'Минивен', 'moscow', 'sp_Functional_moscow'),
    ('br_ubervan_UberVan_UberVan_moscow', 'ubervan', 'br_root_moscow', 'node', 'UberVan', 'UberVan', 'moscow', 'br_Minivan_moscow'),
    ('fi_ubervan_UberVan_UberVan_moscow', 'ubervan', 'fi_root_moscow', 'node', 'UberVan', 'UberVan', 'moscow', 'fi_Functional_moscow'),
    ('op_ubervan_UberVan_UberVan_moscow', 'ubervan', 'op_root_moscow', 'node', 'UberVan', 'UberVan', 'moscow', 'op_Minivan_moscow'),
    ('sp_ubervan_UberVan_UberVan_moscow', 'ubervan', 'sp_root_moscow', 'node', 'UberVan', 'UberVan', 'moscow', 'sp_Functional_moscow'),
    ('br_mkk_MQC_МКК_moscow', 'mkk', 'br_root_moscow', 'node', 'MQC', 'МКК', 'moscow', 'br_MQC_moscow'),
    ('fi_mkk_MQC_МКК_moscow', 'mkk', 'fi_root_moscow', 'node', 'MQC', 'МКК', 'moscow', 'fi_Other_moscow'),
    ('op_mkk_MQC_МКК_moscow', 'mkk', 'op_root_moscow', 'node', 'MQC', 'МКК', 'moscow', 'op_Other_moscow'),
    ('sp_Other_moscow', 'Other', 'sp_root_moscow', 'group', 'Other', 'Other', 'moscow', 'sp_root_moscow'),
    ('sp_mkk_MQC_МКК_moscow', 'mkk', 'sp_root_moscow', 'node', 'MQC', 'МКК', 'moscow', 'sp_Other_moscow'),
    ('br_Perseus_moscow', 'Perseus', 'br_root_moscow', 'group', 'Perseus', 'Perseus', 'moscow', 'br_root_moscow'),
    ('br_premium_suv_Help_Adult_Помощь_взрослым_moscow', 'premium_suv', 'br_root_moscow', 'node', 'Help Adult', 'Помощь взрослым', 'moscow', 'br_Perseus_moscow'),
    ('fi_premium_suv_Help_Adult_Помощь_взрослым_moscow', 'premium_suv', 'fi_root_moscow', 'node', 'Help Adult', 'Помощь взрослым', 'moscow', 'fi_Other_moscow'),
    ('op_premium_suv_Help_Adult_Помощь_взрослым_moscow', 'premium_suv', 'op_root_moscow', 'node', 'Help Adult', 'Помощь взрослым', 'moscow', 'op_Other_moscow'),
    ('sp_premium_suv_Help_Adult_Помощь_взрослым_moscow', 'premium_suv', 'sp_root_moscow', 'node', 'Help Adult', 'Помощь взрослым', 'moscow', 'sp_Mass_moscow'),
    ('br_promo_Medic_Медик_moscow', 'promo', 'br_root_moscow', 'node', 'Medic', 'Медик', 'moscow', 'br_Perseus_moscow'),
    ('fi_promo_Medic_Медик_moscow', 'promo', 'fi_root_moscow', 'node', 'Medic', 'Медик', 'moscow', 'fi_Other_moscow'),
    ('op_promo_Medic_Медик_moscow', 'promo', 'op_root_moscow', 'node', 'Medic', 'Медик', 'moscow', 'op_Other_moscow'),
    ('sp_promo_Medic_Медик_moscow', 'promo', 'sp_root_moscow', 'node', 'Medic', 'Медик', 'moscow', 'sp_Mass_moscow'),
    ('br_suv_Help_Kids_Помощь_детям_moscow', 'suv', 'br_root_moscow', 'node', 'Help Kids', 'Помощь детям', 'moscow', 'br_Perseus_moscow'),
    ('fi_suv_Help_Kids_Помощь_детям_moscow', 'suv', 'fi_root_moscow', 'node', 'Help Kids', 'Помощь детям', 'moscow', 'fi_Other_moscow'),
    ('op_suv_Help_Kids_Помощь_детям_moscow', 'suv', 'op_root_moscow', 'node', 'Help Kids', 'Помощь детям', 'moscow', 'op_Other_moscow'),
    ('sp_suv_Help_Kids_Помощь_детям_moscow', 'suv', 'sp_root_moscow', 'node', 'Help Kids', 'Помощь детям', 'moscow', 'sp_Mass_moscow'),
    ('br_Premier_moscow', 'Premier', 'br_root_moscow', 'group', 'Premier', 'Premier', 'moscow', 'br_root_moscow'),
    ('br_uberlux_UberLux_UberLux_moscow', 'uberlux', 'br_root_moscow', 'node', 'UberLux', 'UberLux', 'moscow', 'br_Premier_moscow'),
    ('fi_uberlux_UberLux_UberLux_moscow', 'uberlux', 'fi_root_moscow', 'node', 'UberLux', 'UberLux', 'moscow', 'fi_Business_moscow'),
    ('op_uberlux_UberLux_UberLux_moscow', 'uberlux', 'op_root_moscow', 'node', 'UberLux', 'UberLux', 'moscow', 'op_Ultima_moscow'),
    ('sp_uberlux_UberLux_UberLux_moscow', 'uberlux', 'sp_root_moscow', 'node', 'UberLux', 'UberLux', 'moscow', 'sp_Premium_moscow'),
    ('br_ultimate_Premier_Premier_moscow', 'ultimate', 'br_root_moscow', 'node', 'Premier', 'Premier', 'moscow', 'br_Premier_moscow'),
    ('fi_ultimate_Premier_Premier_moscow', 'ultimate', 'fi_root_moscow', 'node', 'Premier', 'Premier', 'moscow', 'fi_Business_moscow'),
    ('op_ultimate_Premier_Premier_moscow', 'ultimate', 'op_root_moscow', 'node', 'Premier', 'Premier', 'moscow', 'op_Ultima_moscow'),
    ('sp_ultimate_Premier_Premier_moscow', 'ultimate', 'sp_root_moscow', 'node', 'Premier', 'Premier', 'moscow', 'sp_Premium_moscow'),
    ('br_Premium_Assistant_moscow', 'Premium Assistant', 'br_root_moscow', 'group', 'Premium Assistant', 'Premium Assistant', 'moscow', 'br_root_moscow'),
    ('br_start_Premium_Assistant_Premium_Assistant_moscow', 'start', 'br_root_moscow', 'node', 'Premium Assistant', 'Premium Assistant', 'moscow', 'br_Premium_Assistant_moscow'),
    ('fi_start_Premium_Assistant_Premium_Assistant_moscow', 'start', 'fi_root_moscow', 'node', 'Premium Assistant', 'Premium Assistant', 'moscow', 'fi_New_Businesses_moscow'),
    ('op_start_Premium_Assistant_Premium_Assistant_moscow', 'start', 'op_root_moscow', 'node', 'Premium Assistant', 'Premium Assistant', 'moscow', 'op_Logistics_moscow'),
    ('sp_start_Premium_Assistant_Premium_Assistant_moscow', 'start', 'sp_root_moscow', 'node', 'Premium Assistant', 'Premium Assistant', 'moscow', 'sp_Premium_moscow'),
    ('br_Scooters_moscow', 'Scooters', 'br_root_moscow', 'group', 'Scooters', 'Scooters', 'moscow', 'br_root_moscow'),
    ('br_scooters_Scooters_Самокаты_moscow', 'scooters', 'br_root_moscow', 'node', 'Scooters', 'Самокаты', 'moscow', 'br_Scooters_moscow'),
    ('fi_Scooters_moscow', 'Scooters', 'fi_root_moscow', 'group', 'Scooters', 'Scooters', 'moscow', 'fi_root_moscow'),
    ('fi_scooters_Scooters_Самокаты_moscow', 'scooters', 'fi_root_moscow', 'node', 'Scooters', 'Самокаты', 'moscow', 'fi_Scooters_moscow'),
    ('op_Scooters_moscow', 'Scooters', 'op_root_moscow', 'group', 'Scooters', 'Scooters', 'moscow', 'op_root_moscow'),
    ('op_scooters_Scooters_Самокаты_moscow', 'scooters', 'op_root_moscow', 'node', 'Scooters', 'Самокаты', 'moscow', 'op_Scooters_moscow'),
    ('sp_Scooters_moscow', 'Scooters', 'sp_root_moscow', 'group', 'Scooters', 'Scooters', 'moscow', 'sp_root_moscow'),
    ('sp_scooters_Scooters_Самокаты_moscow', 'scooters', 'sp_root_moscow', 'node', 'Scooters', 'Самокаты', 'moscow', 'sp_Scooters_moscow'),
    ('br_SDC_moscow', 'SDC', 'br_root_moscow', 'group', 'SDC', 'SDC', 'moscow', 'br_root_moscow'),
    ('br_selfdriving_SDC_Беспилотник_moscow', 'selfdriving', 'br_root_moscow', 'node', 'SDC', 'Беспилотник', 'moscow', 'br_SDC_moscow'),
    ('fi_selfdriving_SDC_Беспилотник_moscow', 'selfdriving', 'fi_root_moscow', 'node', 'SDC', 'Беспилотник', 'moscow', 'fi_Functional_moscow'),
    ('op_SDC_moscow', 'SDC', 'op_root_moscow', 'group', 'SDC', 'SDC', 'moscow', 'op_root_moscow'),
    ('op_selfdriving_SDC_Беспилотник_moscow', 'selfdriving', 'op_root_moscow', 'node', 'SDC', 'Беспилотник', 'moscow', 'op_SDC_moscow'),
    ('sp_selfdriving_SDC_Беспилотник_moscow', 'selfdriving', 'sp_root_moscow', 'node', 'SDC', 'Беспилотник', 'moscow', 'sp_Functional_moscow'),
    ('br_Shuttle_moscow', 'Shuttle', 'br_root_moscow', 'group', 'Shuttle', 'Shuttle', 'moscow', 'br_root_moscow'),
    ('br_shuttle_Shuttle_Шаттл_moscow', 'shuttle', 'br_root_moscow', 'node', 'Shuttle', 'Шаттл', 'moscow', 'br_Shuttle_moscow'),
    ('fi_shuttle_Shuttle_Шаттл_moscow', 'shuttle', 'fi_root_moscow', 'node', 'Shuttle', 'Шаттл', 'moscow', 'fi_Functional_moscow'),
    ('op_shuttle_Shuttle_Шаттл_moscow', 'shuttle', 'op_root_moscow', 'node', 'Shuttle', 'Шаттл', 'moscow', 'op_Minivan_moscow'),
    ('sp_shuttle_Shuttle_Шаттл_moscow', 'shuttle', 'sp_root_moscow', 'node', 'Shuttle', 'Шаттл', 'moscow', 'sp_Functional_moscow'),
    ('br_Special_moscow', 'Special', 'br_root_moscow', 'group', 'Special', 'Special', 'moscow', 'br_root_moscow'),
    ('br_universal_Special_Специальный_moscow', 'universal', 'br_root_moscow', 'node', 'Special', 'Специальный', 'moscow', 'br_Special_moscow'),
    ('fi_universal_Special_Специальный_moscow', 'universal', 'fi_root_moscow', 'node', 'Special', 'Специальный', 'moscow', 'fi_Functional_moscow'),
    ('op_Other_Functional_moscow', 'Other Functional', 'op_root_moscow', 'group', 'Other Functional', 'Other Functional', 'moscow', 'op_root_moscow'),
    ('op_universal_Special_Специальный_moscow', 'universal', 'op_root_moscow', 'node', 'Special', 'Специальный', 'moscow', 'op_Other_Functional_moscow'),
    ('sp_universal_Special_Специальный_moscow', 'universal', 'sp_root_moscow', 'node', 'Special', 'Специальный', 'moscow', 'sp_Functional_moscow'),
    ('br_Start_moscow', 'Start', 'br_root_moscow', 'group', 'Start', 'Start', 'moscow', 'br_root_moscow'),
    ('br_uberstart_UberStart_UberStart_moscow', 'uberstart', 'br_root_moscow', 'node', 'UberStart', 'UberStart', 'moscow', 'br_Start_moscow'),
    ('fi_uberstart_UberStart_UberStart_moscow', 'uberstart', 'fi_root_moscow', 'node', 'UberStart', 'UberStart', 'moscow', 'fi_Economy_moscow'),
    ('op_uberstart_UberStart_UberStart_moscow', 'uberstart', 'op_root_moscow', 'node', 'UberStart', 'UberStart', 'moscow', 'op_Econom_moscow'),
    ('sp_uberstart_UberStart_UberStart_moscow', 'uberstart', 'sp_root_moscow', 'node', 'UberStart', 'UberStart', 'moscow', 'sp_Mass_moscow'),
    ('br_root_voronezh', 'Basic', 'br_root_voronezh', 'root', 'Basic', 'Базовая', 'voronezh', NULL),
    ('br_Cargo_voronezh', 'Cargo', 'br_root_voronezh', 'group', 'Cargo', 'Cargo', 'voronezh', 'br_root_voronezh'),
    ('br_cargo_Cargo_Грузовой_voronezh', 'cargo', 'br_root_voronezh', 'node', 'Cargo', 'Грузовой', 'voronezh', 'br_Cargo_voronezh'),
    ('fi_root_voronezh', 'Financial', 'fi_root_voronezh', 'root', 'Financial', 'Финансовая', 'voronezh', NULL),
    ('fi_New_Businesses_voronezh', 'New Businesses', 'fi_root_voronezh', 'group', 'New Businesses', 'New Businesses', 'voronezh', 'fi_root_voronezh'),
    ('fi_cargo_Cargo_Грузовой_voronezh', 'cargo', 'fi_root_voronezh', 'node', 'Cargo', 'Грузовой', 'voronezh', 'fi_New_Businesses_voronezh'),
    ('op_root_voronezh', 'Operational', 'op_root_voronezh', 'root', 'Operational', 'Операционная', 'voronezh', NULL),
    ('op_Logistics_voronezh', 'Logistics', 'op_root_voronezh', 'group', 'Logistics', 'Logistics', 'voronezh', 'op_root_voronezh'),
    ('op_cargo_Cargo_Грузовой_voronezh', 'cargo', 'op_root_voronezh', 'node', 'Cargo', 'Грузовой', 'voronezh', 'op_Logistics_voronezh'),
    ('sp_root_voronezh', 'Support', 'sp_root_voronezh', 'root', 'Support', 'Иерархия службы поддержки', 'voronezh', NULL),
    ('sp_Logistics_voronezh', 'Logistics', 'sp_root_voronezh', 'group', 'Logistics', 'Logistics', 'voronezh', 'sp_root_voronezh'),
    ('sp_cargo_Cargo_Грузовой_voronezh', 'cargo', 'sp_root_voronezh', 'node', 'Cargo', 'Грузовой', 'voronezh', 'sp_Logistics_voronezh'),
    ('br_cargocorp_Cargo_(Corporate)_Грузовой_(Корпоративный)_voronezh', 'cargocorp', 'br_root_voronezh', 'node', 'Cargo (Corporate)', 'Грузовой (Корпоративный)', 'voronezh', 'br_Cargo_voronezh'),
    ('fi_cargocorp_Cargo_(Corporate)_Грузовой_(Корпоративный)_voronezh', 'cargocorp', 'fi_root_voronezh', 'node', 'Cargo (Corporate)', 'Грузовой (Корпоративный)', 'voronezh', 'fi_New_Businesses_voronezh'),
    ('op_cargocorp_Cargo_(Corporate)_Грузовой_(Корпоративный)_voronezh', 'cargocorp', 'op_root_voronezh', 'node', 'Cargo (Corporate)', 'Грузовой (Корпоративный)', 'voronezh', 'op_Logistics_voronezh'),
    ('sp_cargocorp_Cargo_(Corporate)_Грузовой_(Корпоративный)_voronezh', 'cargocorp', 'sp_root_voronezh', 'node', 'Cargo (Corporate)', 'Грузовой (Корпоративный)', 'voronezh', 'sp_Logistics_voronezh'),
    ('br_Combo_voronezh', 'Combo', 'br_root_voronezh', 'group', 'Combo', 'Combo', 'voronezh', 'br_root_voronezh'),
    ('br_pool_Combo_Комбо_voronezh', 'pool', 'br_root_voronezh', 'node', 'Combo', 'Комбо', 'voronezh', 'br_Combo_voronezh'),
    ('fi_Economy_voronezh', 'Economy', 'fi_root_voronezh', 'group', 'Economy', 'Economy', 'voronezh', 'fi_root_voronezh'),
    ('fi_pool_Combo_Комбо_voronezh', 'pool', 'fi_root_voronezh', 'node', 'Combo', 'Комбо', 'voronezh', 'fi_Economy_voronezh'),
    ('op_Econom_voronezh', 'Econom', 'op_root_voronezh', 'group', 'Econom', 'Econom', 'voronezh', 'op_root_voronezh'),
    ('op_pool_Combo_Комбо_voronezh', 'pool', 'op_root_voronezh', 'node', 'Combo', 'Комбо', 'voronezh', 'op_Econom_voronezh'),
    ('sp_Mass_voronezh', 'Mass', 'sp_root_voronezh', 'group', 'Mass', 'Mass', 'voronezh', 'sp_root_voronezh'),
    ('sp_pool_Combo_Комбо_voronezh', 'pool', 'sp_root_voronezh', 'node', 'Combo', 'Комбо', 'voronezh', 'sp_Mass_voronezh'),
    ('br_Comfort_voronezh', 'Comfort', 'br_root_voronezh', 'group', 'Comfort', 'Comfort', 'voronezh', 'br_root_voronezh'),
    ('br_business_Comfort_Комфорт_voronezh', 'business', 'br_root_voronezh', 'node', 'Comfort', 'Комфорт', 'voronezh', 'br_Comfort_voronezh'),
    ('fi_Comfort_voronezh', 'Comfort', 'fi_root_voronezh', 'group', 'Comfort', 'Comfort', 'voronezh', 'fi_root_voronezh'),
    ('fi_business_Comfort_Комфорт_voronezh', 'business', 'fi_root_voronezh', 'node', 'Comfort', 'Комфорт', 'voronezh', 'fi_Comfort_voronezh'),
    ('op_Comfort_voronezh', 'Comfort', 'op_root_voronezh', 'group', 'Comfort', 'Comfort', 'voronezh', 'op_root_voronezh'),
    ('op_business_Comfort_Комфорт_voronezh', 'business', 'op_root_voronezh', 'node', 'Comfort', 'Комфорт', 'voronezh', 'op_Comfort_voronezh'),
    ('sp_business_Comfort_Комфорт_voronezh', 'business', 'sp_root_voronezh', 'node', 'Comfort', 'Комфорт', 'voronezh', 'sp_Mass_voronezh'),
    ('br_uberselect_UberSelect_UberSelect_voronezh', 'uberselect', 'br_root_voronezh', 'node', 'UberSelect', 'UberSelect', 'voronezh', 'br_Comfort_voronezh'),
    ('fi_uberselect_UberSelect_UberSelect_voronezh', 'uberselect', 'fi_root_voronezh', 'node', 'UberSelect', 'UberSelect', 'voronezh', 'fi_Comfort_voronezh'),
    ('op_uberselect_UberSelect_UberSelect_voronezh', 'uberselect', 'op_root_voronezh', 'node', 'UberSelect', 'UberSelect', 'voronezh', 'op_Comfort_voronezh'),
    ('sp_uberselect_UberSelect_UberSelect_voronezh', 'uberselect', 'sp_root_voronezh', 'node', 'UberSelect', 'UberSelect', 'voronezh', 'sp_Mass_voronezh'),
    ('br_vezetbusiness_Comfort_Vezet_Комфорт_Везет_voronezh', 'vezetbusiness', 'br_root_voronezh', 'node', 'Comfort Vezet', 'Комфорт Везет', 'voronezh', 'br_Comfort_voronezh'),
    ('fi_vezetbusiness_Comfort_Vezet_Комфорт_Везет_voronezh', 'vezetbusiness', 'fi_root_voronezh', 'node', 'Comfort Vezet', 'Комфорт Везет', 'voronezh', 'fi_Comfort_voronezh'),
    ('op_vezetbusiness_Comfort_Vezet_Комфорт_Везет_voronezh', 'vezetbusiness', 'op_root_voronezh', 'node', 'Comfort Vezet', 'Комфорт Везет', 'voronezh', 'op_Comfort_voronezh'),
    ('sp_vezetbusiness_Comfort_Vezet_Комфорт_Везет_voronezh', 'vezetbusiness', 'sp_root_voronezh', 'node', 'Comfort Vezet', 'Комфорт Везет', 'voronezh', 'sp_Mass_voronezh'),
    ('br_Comfort+_voronezh', 'Comfort+', 'br_root_voronezh', 'group', 'Comfort+', 'Comfort+', 'voronezh', 'br_root_voronezh'),
    ('br_comfortplus_Comfort+_Комфорт+_voronezh', 'comfortplus', 'br_root_voronezh', 'node', 'Comfort+', 'Комфорт+', 'voronezh', 'br_Comfort+_voronezh'),
    ('fi_comfortplus_Comfort+_Комфорт+_voronezh', 'comfortplus', 'fi_root_voronezh', 'node', 'Comfort+', 'Комфорт+', 'voronezh', 'fi_Comfort_voronezh'),
    ('op_comfortplus_Comfort+_Комфорт+_voronezh', 'comfortplus', 'op_root_voronezh', 'node', 'Comfort+', 'Комфорт+', 'voronezh', 'op_Comfort_voronezh'),
    ('sp_comfortplus_Comfort+_Комфорт+_voronezh', 'comfortplus', 'sp_root_voronezh', 'node', 'Comfort+', 'Комфорт+', 'voronezh', 'sp_Mass_voronezh'),
    ('br_uberselectplus_UberSelect+_UberSelect+_voronezh', 'uberselectplus', 'br_root_voronezh', 'node', 'UberSelect+', 'UberSelect+', 'voronezh', 'br_Comfort+_voronezh'),
    ('fi_uberselectplus_UberSelect+_UberSelect+_voronezh', 'uberselectplus', 'fi_root_voronezh', 'node', 'UberSelect+', 'UberSelect+', 'voronezh', 'fi_Comfort_voronezh'),
    ('op_uberselectplus_UberSelect+_UberSelect+_voronezh', 'uberselectplus', 'op_root_voronezh', 'node', 'UberSelect+', 'UberSelect+', 'voronezh', 'op_Comfort_voronezh'),
    ('sp_uberselectplus_UberSelect+_UberSelect+_voronezh', 'uberselectplus', 'sp_root_voronezh', 'node', 'UberSelect+', 'UberSelect+', 'voronezh', 'sp_Mass_voronezh'),
    ('br_Courier_voronezh', 'Courier', 'br_root_voronezh', 'group', 'Courier', 'Courier', 'voronezh', 'br_root_voronezh'),
    ('br_courier_Courier_Курьер_voronezh', 'courier', 'br_root_voronezh', 'node', 'Courier', 'Курьер', 'voronezh', 'br_Courier_voronezh'),
    ('fi_courier_Courier_Курьер_voronezh', 'courier', 'fi_root_voronezh', 'node', 'Courier', 'Курьер', 'voronezh', 'fi_New_Businesses_voronezh'),
    ('op_courier_Courier_Курьер_voronezh', 'courier', 'op_root_voronezh', 'node', 'Courier', 'Курьер', 'voronezh', 'op_Logistics_voronezh'),
    ('sp_courier_Courier_Курьер_voronezh', 'courier', 'sp_root_voronezh', 'node', 'Courier', 'Курьер', 'voronezh', 'sp_Logistics_voronezh'),
    ('br_Delivery_voronezh', 'Delivery', 'br_root_voronezh', 'group', 'Delivery', 'Delivery', 'voronezh', 'br_root_voronezh'),
    ('br_express_Delivery_Доставка_voronezh', 'express', 'br_root_voronezh', 'node', 'Delivery', 'Доставка', 'voronezh', 'br_Delivery_voronezh'),
    ('fi_express_Delivery_Доставка_voronezh', 'express', 'fi_root_voronezh', 'node', 'Delivery', 'Доставка', 'voronezh', 'fi_New_Businesses_voronezh'),
    ('op_express_Delivery_Доставка_voronezh', 'express', 'op_root_voronezh', 'node', 'Delivery', 'Доставка', 'voronezh', 'op_Logistics_voronezh'),
    ('sp_express_Delivery_Доставка_voronezh', 'express', 'sp_root_voronezh', 'node', 'Delivery', 'Доставка', 'voronezh', 'sp_Logistics_voronezh'),
    ('br_ubernight_Uber_Delivery_Uber_Доставка_voronezh', 'ubernight', 'br_root_voronezh', 'node', 'Uber Delivery', 'Uber Доставка', 'voronezh', 'br_Delivery_voronezh'),
    ('fi_ubernight_Uber_Delivery_Uber_Доставка_voronezh', 'ubernight', 'fi_root_voronezh', 'node', 'Uber Delivery', 'Uber Доставка', 'voronezh', 'fi_New_Businesses_voronezh'),
    ('op_ubernight_Uber_Delivery_Uber_Доставка_voronezh', 'ubernight', 'op_root_voronezh', 'node', 'Uber Delivery', 'Uber Доставка', 'voronezh', 'op_Logistics_voronezh'),
    ('sp_ubernight_Uber_Delivery_Uber_Доставка_voronezh', 'ubernight', 'sp_root_voronezh', 'node', 'Uber Delivery', 'Uber Доставка', 'voronezh', 'sp_Logistics_voronezh'),
    ('br_Econom_voronezh', 'Econom', 'br_root_voronezh', 'group', 'Econom', 'Econom', 'voronezh', 'br_root_voronezh'),
    ('br_econom_Econom_Эконом_voronezh', 'econom', 'br_root_voronezh', 'node', 'Econom', 'Эконом', 'voronezh', 'br_Econom_voronezh'),
    ('fi_econom_Econom_Эконом_voronezh', 'econom', 'fi_root_voronezh', 'node', 'Econom', 'Эконом', 'voronezh', 'fi_Economy_voronezh'),
    ('op_econom_Econom_Эконом_voronezh', 'econom', 'op_root_voronezh', 'node', 'Econom', 'Эконом', 'voronezh', 'op_Econom_voronezh'),
    ('sp_econom_Econom_Эконом_voronezh', 'econom', 'sp_root_voronezh', 'node', 'Econom', 'Эконом', 'voronezh', 'sp_Mass_voronezh'),
    ('br_mkk_antifraud_Call_center_tariff_(Econom)_Тариф_КЦ_(Эконом)_voronezh', 'mkk_antifraud', 'br_root_voronezh', 'node', 'Call center tariff (Econom)', 'Тариф КЦ (Эконом)', 'voronezh', 'br_Econom_voronezh'),
    ('fi_mkk_antifraud_Call_center_tariff_(Econom)_Тариф_КЦ_(Эконом)_voronezh', 'mkk_antifraud', 'fi_root_voronezh', 'node', 'Call center tariff (Econom)', 'Тариф КЦ (Эконом)', 'voronezh', 'fi_Economy_voronezh'),
    ('op_mkk_antifraud_Call_center_tariff_(Econom)_Тариф_КЦ_(Эконом)_voronezh', 'mkk_antifraud', 'op_root_voronezh', 'node', 'Call center tariff (Econom)', 'Тариф КЦ (Эконом)', 'voronezh', 'op_Econom_voronezh'),
    ('sp_mkk_antifraud_Call_center_tariff_(Econom)_Тариф_КЦ_(Эконом)_voronezh', 'mkk_antifraud', 'sp_root_voronezh', 'node', 'Call center tariff (Econom)', 'Тариф КЦ (Эконом)', 'voronezh', 'sp_Mass_voronezh'),
    ('br_uberx_UberX_UberX_voronezh', 'uberx', 'br_root_voronezh', 'node', 'UberX', 'UberX', 'voronezh', 'br_Econom_voronezh'),
    ('fi_uberx_UberX_UberX_voronezh', 'uberx', 'fi_root_voronezh', 'node', 'UberX', 'UberX', 'voronezh', 'fi_Economy_voronezh'),
    ('op_uberx_UberX_UberX_voronezh', 'uberx', 'op_root_voronezh', 'node', 'UberX', 'UberX', 'voronezh', 'op_Econom_voronezh'),
    ('sp_uberx_UberX_UberX_voronezh', 'uberx', 'sp_root_voronezh', 'node', 'UberX', 'UberX', 'voronezh', 'sp_Mass_voronezh'),
    ('br_vezeteconom_Econom_Vezet_Эконом_Везет_voronezh', 'vezeteconom', 'br_root_voronezh', 'node', 'Econom Vezet', 'Эконом Везет', 'voronezh', 'br_Econom_voronezh'),
    ('fi_vezeteconom_Econom_Vezet_Эконом_Везет_voronezh', 'vezeteconom', 'fi_root_voronezh', 'node', 'Econom Vezet', 'Эконом Везет', 'voronezh', 'fi_Economy_voronezh'),
    ('br_root_vyksa_district', 'Basic', 'br_root_vyksa_district', 'root', 'Basic', 'Базовая', 'vyksa_district', NULL),
    ('op_vezeteconom_Econom_Vezet_Эконом_Везет_voronezh', 'vezeteconom', 'op_root_voronezh', 'node', 'Econom Vezet', 'Эконом Везет', 'voronezh', 'op_Econom_voronezh'),
    ('sp_vezeteconom_Econom_Vezet_Эконом_Везет_voronezh', 'vezeteconom', 'sp_root_voronezh', 'node', 'Econom Vezet', 'Эконом Везет', 'voronezh', 'sp_Mass_voronezh'),
    ('br_Kids_voronezh', 'Kids', 'br_root_voronezh', 'group', 'Kids', 'Kids', 'voronezh', 'br_root_voronezh'),
    ('br_child_tariff_Kids_Детский_voronezh', 'child_tariff', 'br_root_voronezh', 'node', 'Kids', 'Детский', 'voronezh', 'br_Kids_voronezh'),
    ('fi_Functional_voronezh', 'Functional', 'fi_root_voronezh', 'group', 'Functional', 'Functional', 'voronezh', 'fi_root_voronezh'),
    ('fi_child_tariff_Kids_Детский_voronezh', 'child_tariff', 'fi_root_voronezh', 'node', 'Kids', 'Детский', 'voronezh', 'fi_Functional_voronezh'),
    ('op_Child_voronezh', 'Child', 'op_root_voronezh', 'group', 'Child', 'Child', 'voronezh', 'op_root_voronezh'),
    ('op_child_tariff_Kids_Детский_voronezh', 'child_tariff', 'op_root_voronezh', 'node', 'Kids', 'Детский', 'voronezh', 'op_Child_voronezh'),
    ('sp_Functional_voronezh', 'Functional', 'sp_root_voronezh', 'group', 'Functional', 'Functional', 'voronezh', 'sp_root_voronezh'),
    ('sp_child_tariff_Kids_Детский_voronezh', 'child_tariff', 'sp_root_voronezh', 'node', 'Kids', 'Детский', 'voronezh', 'sp_Functional_voronezh'),
    ('br_uberkids_UberKids_UberKids_voronezh', 'uberkids', 'br_root_voronezh', 'node', 'UberKids', 'UberKids', 'voronezh', 'br_Kids_voronezh'),
    ('fi_uberkids_UberKids_UberKids_voronezh', 'uberkids', 'fi_root_voronezh', 'node', 'UberKids', 'UberKids', 'voronezh', 'fi_Functional_voronezh'),
    ('op_uberkids_UberKids_UberKids_voronezh', 'uberkids', 'op_root_voronezh', 'node', 'UberKids', 'UberKids', 'voronezh', 'op_Child_voronezh'),
    ('sp_uberkids_UberKids_UberKids_voronezh', 'uberkids', 'sp_root_voronezh', 'node', 'UberKids', 'UberKids', 'voronezh', 'sp_Functional_voronezh'),
    ('br_Perseus_voronezh', 'Perseus', 'br_root_voronezh', 'group', 'Perseus', 'Perseus', 'voronezh', 'br_root_voronezh'),
    ('br_night_Help_Помощь:_волонтёры_voronezh', 'night', 'br_root_voronezh', 'node', 'Help', 'Помощь: волонтёры', 'voronezh', 'br_Perseus_voronezh'),
    ('fi_Other_voronezh', 'Other', 'fi_root_voronezh', 'group', 'Other', 'Other', 'voronezh', 'fi_root_voronezh'),
    ('fi_night_Help_Помощь:_волонтёры_voronezh', 'night', 'fi_root_voronezh', 'node', 'Help', 'Помощь: волонтёры', 'voronezh', 'fi_Other_voronezh'),
    ('op_Other_voronezh', 'Other', 'op_root_voronezh', 'group', 'Other', 'Other', 'voronezh', 'op_root_voronezh'),
    ('op_night_Help_Помощь:_волонтёры_voronezh', 'night', 'op_root_voronezh', 'node', 'Help', 'Помощь: волонтёры', 'voronezh', 'op_Other_voronezh'),
    ('sp_night_Help_Помощь:_волонтёры_voronezh', 'night', 'sp_root_voronezh', 'node', 'Help', 'Помощь: волонтёры', 'voronezh', 'sp_Mass_voronezh'),
    ('br_premium_suv_Help_Adult_Помощь_взрослым_voronezh', 'premium_suv', 'br_root_voronezh', 'node', 'Help Adult', 'Помощь взрослым', 'voronezh', 'br_Perseus_voronezh'),
    ('fi_premium_suv_Help_Adult_Помощь_взрослым_voronezh', 'premium_suv', 'fi_root_voronezh', 'node', 'Help Adult', 'Помощь взрослым', 'voronezh', 'fi_Other_voronezh'),
    ('op_premium_suv_Help_Adult_Помощь_взрослым_voronezh', 'premium_suv', 'op_root_voronezh', 'node', 'Help Adult', 'Помощь взрослым', 'voronezh', 'op_Other_voronezh'),
    ('sp_premium_suv_Help_Adult_Помощь_взрослым_voronezh', 'premium_suv', 'sp_root_voronezh', 'node', 'Help Adult', 'Помощь взрослым', 'voronezh', 'sp_Mass_voronezh'),
    ('br_promo_Medic_Медик_voronezh', 'promo', 'br_root_voronezh', 'node', 'Medic', 'Медик', 'voronezh', 'br_Perseus_voronezh'),
    ('fi_promo_Medic_Медик_voronezh', 'promo', 'fi_root_voronezh', 'node', 'Medic', 'Медик', 'voronezh', 'fi_Other_voronezh'),
    ('op_promo_Medic_Медик_voronezh', 'promo', 'op_root_voronezh', 'node', 'Medic', 'Медик', 'voronezh', 'op_Other_voronezh'),
    ('sp_promo_Medic_Медик_voronezh', 'promo', 'sp_root_voronezh', 'node', 'Medic', 'Медик', 'voronezh', 'sp_Mass_voronezh'),
    ('br_suv_Help_Kids_Помощь_детям_voronezh', 'suv', 'br_root_voronezh', 'node', 'Help Kids', 'Помощь детям', 'voronezh', 'br_Perseus_voronezh'),
    ('fi_suv_Help_Kids_Помощь_детям_voronezh', 'suv', 'fi_root_voronezh', 'node', 'Help Kids', 'Помощь детям', 'voronezh', 'fi_Other_voronezh'),
    ('op_suv_Help_Kids_Помощь_детям_voronezh', 'suv', 'op_root_voronezh', 'node', 'Help Kids', 'Помощь детям', 'voronezh', 'op_Other_voronezh'),
    ('sp_suv_Help_Kids_Помощь_детям_voronezh', 'suv', 'sp_root_voronezh', 'node', 'Help Kids', 'Помощь детям', 'voronezh', 'sp_Mass_voronezh'),
    ('br_Special_voronezh', 'Special', 'br_root_voronezh', 'group', 'Special', 'Special', 'voronezh', 'br_root_voronezh'),
    ('br_universal_Special_Специальный_voronezh', 'universal', 'br_root_voronezh', 'node', 'Special', 'Специальный', 'voronezh', 'br_Special_voronezh'),
    ('fi_universal_Special_Специальный_voronezh', 'universal', 'fi_root_voronezh', 'node', 'Special', 'Специальный', 'voronezh', 'fi_Functional_voronezh'),
    ('op_Other_Functional_voronezh', 'Other Functional', 'op_root_voronezh', 'group', 'Other Functional', 'Other Functional', 'voronezh', 'op_root_voronezh'),
    ('op_universal_Special_Специальный_voronezh', 'universal', 'op_root_voronezh', 'node', 'Special', 'Специальный', 'voronezh', 'op_Other_Functional_voronezh'),
    ('sp_universal_Special_Специальный_voronezh', 'universal', 'sp_root_voronezh', 'node', 'Special', 'Специальный', 'voronezh', 'sp_Functional_voronezh'),
    ('br_root_voronezh_region', 'Basic', 'br_root_voronezh_region', 'root', 'Basic', 'Базовая', 'voronezh_region', NULL),
    ('br_Econom_voronezh_region', 'Econom', 'br_root_voronezh_region', 'group', 'Econom', 'Econom', 'voronezh_region', 'br_root_voronezh_region'),
    ('br_econom_Econom_Эконом_voronezh_region', 'econom', 'br_root_voronezh_region', 'node', 'Econom', 'Эконом', 'voronezh_region', 'br_Econom_voronezh_region'),
    ('fi_root_voronezh_region', 'Financial', 'fi_root_voronezh_region', 'root', 'Financial', 'Финансовая', 'voronezh_region', NULL),
    ('fi_Economy_voronezh_region', 'Economy', 'fi_root_voronezh_region', 'group', 'Economy', 'Economy', 'voronezh_region', 'fi_root_voronezh_region'),
    ('fi_econom_Econom_Эконом_voronezh_region', 'econom', 'fi_root_voronezh_region', 'node', 'Econom', 'Эконом', 'voronezh_region', 'fi_Economy_voronezh_region'),
    ('op_root_voronezh_region', 'Operational', 'op_root_voronezh_region', 'root', 'Operational', 'Операционная', 'voronezh_region', NULL),
    ('op_Econom_voronezh_region', 'Econom', 'op_root_voronezh_region', 'group', 'Econom', 'Econom', 'voronezh_region', 'op_root_voronezh_region'),
    ('op_econom_Econom_Эконом_voronezh_region', 'econom', 'op_root_voronezh_region', 'node', 'Econom', 'Эконом', 'voronezh_region', 'op_Econom_voronezh_region'),
    ('sp_root_voronezh_region', 'Support', 'sp_root_voronezh_region', 'root', 'Support', 'Иерархия службы поддержки', 'voronezh_region', NULL),
    ('sp_Mass_voronezh_region', 'Mass', 'sp_root_voronezh_region', 'group', 'Mass', 'Mass', 'voronezh_region', 'sp_root_voronezh_region'),
    ('sp_econom_Econom_Эконом_voronezh_region', 'econom', 'sp_root_voronezh_region', 'node', 'Econom', 'Эконом', 'voronezh_region', 'sp_Mass_voronezh_region'),
    ('br_uberx_UberX_UberX_voronezh_region', 'uberx', 'br_root_voronezh_region', 'node', 'UberX', 'UberX', 'voronezh_region', 'br_Econom_voronezh_region'),
    ('fi_uberx_UberX_UberX_voronezh_region', 'uberx', 'fi_root_voronezh_region', 'node', 'UberX', 'UberX', 'voronezh_region', 'fi_Economy_voronezh_region'),
    ('op_uberx_UberX_UberX_voronezh_region', 'uberx', 'op_root_voronezh_region', 'node', 'UberX', 'UberX', 'voronezh_region', 'op_Econom_voronezh_region'),
    ('sp_uberx_UberX_UberX_voronezh_region', 'uberx', 'sp_root_voronezh_region', 'node', 'UberX', 'UberX', 'voronezh_region', 'sp_Mass_voronezh_region'),
    ('br_vezeteconom_Econom_Vezet_Эконом_Везет_voronezh_region', 'vezeteconom', 'br_root_voronezh_region', 'node', 'Econom Vezet', 'Эконом Везет', 'voronezh_region', 'br_Econom_voronezh_region'),
    ('fi_vezeteconom_Econom_Vezet_Эконом_Везет_voronezh_region', 'vezeteconom', 'fi_root_voronezh_region', 'node', 'Econom Vezet', 'Эконом Везет', 'voronezh_region', 'fi_Economy_voronezh_region'),
    ('op_vezeteconom_Econom_Vezet_Эконом_Везет_voronezh_region', 'vezeteconom', 'op_root_voronezh_region', 'node', 'Econom Vezet', 'Эконом Везет', 'voronezh_region', 'op_Econom_voronezh_region'),
    ('sp_vezeteconom_Econom_Vezet_Эконом_Везет_voronezh_region', 'vezeteconom', 'sp_root_voronezh_region', 'node', 'Econom Vezet', 'Эконом Везет', 'voronezh_region', 'sp_Mass_voronezh_region')
ON CONFLICT (node_id) DO NOTHING;
