\set role testsuite
\ir ../../../taxi_billing_replication/sql/migrations/01_initial_schema.sql
\ir ../../../taxi_billing_replication/sql/migrations/02_fix_curr_charge_type.sql
\ir ../../../taxi_billing_replication/sql/migrations/03_add_status_to_contract.sql
\ir ../../../taxi_billing_replication/sql/migrations/04_add_not_null_to_balance_timestamps.sql
\ir ../../../taxi_billing_replication/sql/migrations/05_add_corp_clients_and_acts.sql
\ir ../../../taxi_billing_replication/sql/migrations/06_add_persons_fk_index.sql
\ir ../../../taxi_billing_replication/sql/migrations/07_add_contracts_status_index_.sql
\ir ../../../taxi_billing_replication/sql/migrations/08_add_status_to_person.sql
\ir ../../../taxi_billing_replication/sql/migrations/09_add_contract_fields.sql
\ir ../../../taxi_billing_replication/sql/migrations/10_create_queue_tables.sql
\ir ../../../taxi_billing_replication/sql/migrations/11_add_old_ids_to_queues.sql
\ir ../../../taxi_billing_replication/sql/migrations/12_remove_old_update_times.sql
\ir ../../../taxi_billing_replication/sql/migrations/13_prepare_corp_clients_sync.sql
\ir ../../../taxi_billing_replication/sql/migrations/14_create_contracts_billing_kwargs_index.sql
\ir ../../../taxi_billing_replication/sql/migrations/15_tables_to_schemas.sql
\ir ../../../taxi_billing_replication/sql/migrations/17_add_postaddress_to_persons.sql
\ir ../../../taxi_billing_replication/sql/migrations/18_create_indexes_for_new_ids_order.sql
\ir ../../../taxi_billing_replication/sql/migrations/19_remove_spendable_contracts.sql
\ir ../../../taxi_billing_replication/sql/migrations/20_add_country_field_to_contracts.sql
\ir ../../../taxi_billing_replication/sql/migrations/21_cleanup_balances_queue.sql
\ir ../../../taxi_billing_replication/sql/migrations/22_add_kz_in_field_to_persons.sql
\ir ../../../taxi_billing_replication/sql/migrations/23_add_index_on_park_id.sql
\ir ../../../taxi_billing_replication/sql/migrations/24_add_contracts_fields.sql
\ir ../../../taxi_billing_replication/sql/migrations/25_add_corp_yandex_uid.sql
\ir ../../../taxi_billing_replication/sql/migrations/26_contract_versions.sql
\ir ../../../taxi_billing_replication/sql/migrations/27_contract_versions_for_balances.sql
\ir ../../../taxi_billing_replication/sql/migrations/28_contract_versions_client_id_all_idx.sql
\ir ../../../taxi_billing_replication/sql/migrations/29_replicate_corp_contracts.sql
\ir ../../../taxi_billing_replication/sql/migrations/30_new_corp_queues.sql
\ir ../../../taxi_billing_replication/sql/migrations/31_copy_corp_data_from_park_queues.sql
\ir ../../../taxi_billing_replication/sql/migrations/32_delete_corp_data_from_park_queues.sql
\ir ../../../taxi_billing_replication/sql/migrations/33_delete_deprecated_triggers.sql
\ir ../../../taxi_billing_replication/sql/migrations/34_add_clients_revision.sql
\ir ../../../taxi_billing_replication/sql/migrations/35_contract_versions_add_client_id_expired_index.sql
\ir ../../../taxi_billing_replication/sql/migrations/36_contract_versions_remove_old_client_id_idxs.sql
\ir ../../../taxi_billing_replication/sql/migrations/37_serial_to_bigserial.sql
\ir ../../../taxi_billing_replication/sql/migrations/38_drop_contracts_table.sql
\ir ../../../taxi_billing_replication/sql/migrations/39_add_attributes_history.sql
\ir ../../../taxi_billing_replication/sql/migrations/40_add_firm_id.sql
\ir ../../../taxi_billing_replication/sql/migrations/41_persons_serial_to_bigint.sql
\ir ../../../taxi_billing_replication/sql/migrations/42_balance_replication_v2.sql
