\set role testsuite
\ir ../../../postgresql/discounts_operation_calculations/migrations/V1__initial.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V2__add_suggests.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V3__add_segment_stats_hist.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V4__add_fields_to_suggests.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V5__add_previous_suggest_id_field.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V6__add_budget_field.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V7__add_date_fields_hist.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V8__add_new_value_to_status.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V9__add_push_discounts.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V10__add_actions_field.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V11__add_waiting_statuses.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V12__add_multidraft_tasks.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V13__add_segment_stats_calcs.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V14__add_algorithms_configs.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V15__add_new_segment_stats_table.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V16__add_tz_to_suggests.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V17__add_salt_and_share_to_algorithms_configs.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V18__add_elasticities_table.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V19__add_segments_with_pushes.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V20__add_city_stats_table.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V21__add_currency_code_to_segment_stats.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V22__add_budget_share_in_gmv_field.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V23__add_fixed_discounts_field.sql
\ir ../../../postgresql/discounts_operation_calculations/migrations/V24__add_metric_name_field.sql
