# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/maps/proto/driving/action.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yandex/maps/proto/driving/action.proto',
  package='yandex.maps.proto.driving.action',
  syntax='proto2',
  serialized_pb=_b('\n&yandex/maps/proto/driving/action.proto\x12 yandex.maps.proto.driving.action*\xa7\x02\n\x06\x41\x63tion\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08STRAIGHT\x10\x02\x12\x0f\n\x0bSLIGHT_LEFT\x10\x03\x12\x10\n\x0cSLIGHT_RIGHT\x10\x04\x12\x08\n\x04LEFT\x10\x05\x12\t\n\x05RIGHT\x10\x06\x12\r\n\tHARD_LEFT\x10\x07\x12\x0e\n\nHARD_RIGHT\x10\x08\x12\r\n\tFORK_LEFT\x10\t\x12\x0e\n\nFORK_RIGHT\x10\n\x12\x0e\n\nUTURN_LEFT\x10\x0b\x12\x0f\n\x0bUTURN_RIGHT\x10\x0c\x12\x14\n\x10\x45NTER_ROUNDABOUT\x10\x0e\x12\x14\n\x10LEAVE_ROUNDABOUT\x10\x0f\x12\x0f\n\x0b\x42OARD_FERRY\x10\x10\x12\x0f\n\x0bLEAVE_FERRY\x10\x11\x12\r\n\tEXIT_LEFT\x10\x12\x12\x0e\n\nEXIT_RIGHT\x10\x13')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='yandex.maps.proto.driving.action.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STRAIGHT', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SLIGHT_LEFT', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SLIGHT_RIGHT', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HARD_LEFT', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HARD_RIGHT', index=7, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FORK_LEFT', index=8, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FORK_RIGHT', index=9, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UTURN_LEFT', index=10, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UTURN_RIGHT', index=11, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTER_ROUNDABOUT', index=12, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEAVE_ROUNDABOUT', index=13, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOARD_FERRY', index=14, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEAVE_FERRY', index=15, number=17,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXIT_LEFT', index=16, number=18,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXIT_RIGHT', index=17, number=19,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=77,
  serialized_end=372,
)
_sym_db.RegisterEnumDescriptor(_ACTION)

Action = enum_type_wrapper.EnumTypeWrapper(_ACTION)
UNKNOWN = 0
STRAIGHT = 2
SLIGHT_LEFT = 3
SLIGHT_RIGHT = 4
LEFT = 5
RIGHT = 6
HARD_LEFT = 7
HARD_RIGHT = 8
FORK_LEFT = 9
FORK_RIGHT = 10
UTURN_LEFT = 11
UTURN_RIGHT = 12
ENTER_ROUNDABOUT = 14
LEAVE_ROUNDABOUT = 15
BOARD_FERRY = 16
LEAVE_FERRY = 17
EXIT_LEFT = 18
EXIT_RIGHT = 19


DESCRIPTOR.enum_types_by_name['Action'] = _ACTION


# @@protoc_insertion_point(module_scope)
