# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/maps/proto/driving/description.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yandex/maps/proto/driving/description.proto',
  package='yandex.maps.proto.driving.description',
  syntax='proto2',
  serialized_pb=_b('\n+yandex/maps/proto/driving/description.proto\x12%yandex.maps.proto.driving.description\"\x1a\n\x0b\x44\x65scription\x12\x0b\n\x03via\x18\x01 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DESCRIPTION = _descriptor.Descriptor(
  name='Description',
  full_name='yandex.maps.proto.driving.description.Description',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='via', full_name='yandex.maps.proto.driving.description.Description.via', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['Description'] = _DESCRIPTION

Description = _reflection.GeneratedProtocolMessageType('Description', (_message.Message,), dict(
  DESCRIPTOR = _DESCRIPTION,
  __module__ = 'yandex.maps.proto.driving.description_pb2'
  # @@protoc_insertion_point(class_scope:yandex.maps.proto.driving.description.Description)
  ))
_sym_db.RegisterMessage(Description)


# @@protoc_insertion_point(module_scope)
