# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/maps/proto/driving/jam_segment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yandex/maps/proto/driving/jam_segment.proto',
  package='yandex.maps.proto.driving.jam_segment',
  syntax='proto2',
  serialized_pb=_b('\n+yandex/maps/proto/driving/jam_segment.proto\x12%yandex.maps.proto.driving.jam_segment\"q\n\nJamSegment\x12\x45\n\x04type\x18\x01 \x01(\x0e\x32..yandex.maps.proto.driving.jam_segment.JamType:\x07UNKNOWN\x12\r\n\x05speed\x18\x02 \x02(\x02\x12\r\n\x05\x63ount\x18\x03 \x02(\x05*P\n\x07JamType\x12\x0b\n\x07UNKNOWN\x10\x01\x12\n\n\x06\x43LOSED\x10\x02\x12\x08\n\x04\x46REE\x10\x03\x12\t\n\x05LIGHT\x10\x04\x12\x08\n\x04HARD\x10\x05\x12\r\n\tVERY_HARD\x10\x06')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_JAMTYPE = _descriptor.EnumDescriptor(
  name='JamType',
  full_name='yandex.maps.proto.driving.jam_segment.JamType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSED', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FREE', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIGHT', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HARD', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERY_HARD', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=201,
  serialized_end=281,
)
_sym_db.RegisterEnumDescriptor(_JAMTYPE)

JamType = enum_type_wrapper.EnumTypeWrapper(_JAMTYPE)
UNKNOWN = 1
CLOSED = 2
FREE = 3
LIGHT = 4
HARD = 5
VERY_HARD = 6



_JAMSEGMENT = _descriptor.Descriptor(
  name='JamSegment',
  full_name='yandex.maps.proto.driving.jam_segment.JamSegment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='yandex.maps.proto.driving.jam_segment.JamSegment.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='yandex.maps.proto.driving.jam_segment.JamSegment.speed', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='yandex.maps.proto.driving.jam_segment.JamSegment.count', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=199,
)

_JAMSEGMENT.fields_by_name['type'].enum_type = _JAMTYPE
DESCRIPTOR.message_types_by_name['JamSegment'] = _JAMSEGMENT
DESCRIPTOR.enum_types_by_name['JamType'] = _JAMTYPE

JamSegment = _reflection.GeneratedProtocolMessageType('JamSegment', (_message.Message,), dict(
  DESCRIPTOR = _JAMSEGMENT,
  __module__ = 'yandex.maps.proto.driving.jam_segment_pb2'
  # @@protoc_insertion_point(class_scope:yandex.maps.proto.driving.jam_segment.JamSegment)
  ))
_sym_db.RegisterMessage(JamSegment)


# @@protoc_insertion_point(module_scope)
