# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/maps/proto/driving/route.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..common2 import metadata_pb2 as yandex_dot_maps_dot_proto_dot_common2_dot_metadata__pb2
from . import description_pb2 as yandex_dot_maps_dot_proto_dot_driving_dot_description__pb2
from . import flags_pb2 as yandex_dot_maps_dot_proto_dot_driving_dot_flags__pb2
from . import weight_pb2 as yandex_dot_maps_dot_proto_dot_driving_dot_weight__pb2
from . import route_point_pb2 as yandex_dot_maps_dot_proto_dot_driving_dot_route__point__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yandex/maps/proto/driving/route.proto',
  package='yandex.maps.proto.driving.route',
  syntax='proto2',
  serialized_pb=_b('\n%yandex/maps/proto/driving/route.proto\x12\x1fyandex.maps.proto.driving.route\x1a(yandex/maps/proto/common2/metadata.proto\x1a+yandex/maps/proto/driving/description.proto\x1a%yandex/maps/proto/driving/flags.proto\x1a&yandex/maps/proto/driving/weight.proto\x1a+yandex/maps/proto/driving/route_point.proto\"\xdf\x02\n\x05Route\x12\x38\n\x06weight\x18\x01 \x02(\x0b\x32(.yandex.maps.proto.driving.weight.Weight\x12\x35\n\x05\x66lags\x18\x06 \x02(\x0b\x32&.yandex.maps.proto.driving.flags.Flags\x12G\n\x0b\x64\x65scription\x18\t \x01(\x0b\x32\x32.yandex.maps.proto.driving.description.Description\x12\x18\n\x10route_descriptor\x18\x05 \x01(\x0c\x12\x14\n\x0croute_traits\x18\x07 \x01(\x0c\x12\x10\n\x08route_id\x18\x08 \x01(\t\x12\x46\n\x0broute_point\x18\x0b \x03(\x0b\x32\x31.yandex.maps.proto.driving.route_point.RoutePoint\x12\x0c\n\x04tags\x18\x0c \x03(\tJ\x04\x08\n\x10\x0b:l\n\x0eROUTE_METADATA\x12,.yandex.maps.proto.common2.metadata.Metadata\x18[ \x01(\x0b\x32&.yandex.maps.proto.driving.route.Route')
  ,
  dependencies=[yandex_dot_maps_dot_proto_dot_common2_dot_metadata__pb2.DESCRIPTOR,yandex_dot_maps_dot_proto_dot_driving_dot_description__pb2.DESCRIPTOR,yandex_dot_maps_dot_proto_dot_driving_dot_flags__pb2.DESCRIPTOR,yandex_dot_maps_dot_proto_dot_driving_dot_weight__pb2.DESCRIPTOR,yandex_dot_maps_dot_proto_dot_driving_dot_route__point__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


ROUTE_METADATA_FIELD_NUMBER = 91
ROUTE_METADATA = _descriptor.FieldDescriptor(
  name='ROUTE_METADATA', full_name='yandex.maps.proto.driving.route.ROUTE_METADATA', index=0,
  number=91, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_ROUTE = _descriptor.Descriptor(
  name='Route',
  full_name='yandex.maps.proto.driving.route.Route',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight', full_name='yandex.maps.proto.driving.route.Route.weight', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flags', full_name='yandex.maps.proto.driving.route.Route.flags', index=1,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='yandex.maps.proto.driving.route.Route.description', index=2,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='route_descriptor', full_name='yandex.maps.proto.driving.route.Route.route_descriptor', index=3,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='route_traits', full_name='yandex.maps.proto.driving.route.Route.route_traits', index=4,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='route_id', full_name='yandex.maps.proto.driving.route.Route.route_id', index=5,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='route_point', full_name='yandex.maps.proto.driving.route.Route.route_point', index=6,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='yandex.maps.proto.driving.route.Route.tags', index=7,
      number=12, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=637,
)

_ROUTE.fields_by_name['weight'].message_type = yandex_dot_maps_dot_proto_dot_driving_dot_weight__pb2._WEIGHT
_ROUTE.fields_by_name['flags'].message_type = yandex_dot_maps_dot_proto_dot_driving_dot_flags__pb2._FLAGS
_ROUTE.fields_by_name['description'].message_type = yandex_dot_maps_dot_proto_dot_driving_dot_description__pb2._DESCRIPTION
_ROUTE.fields_by_name['route_point'].message_type = yandex_dot_maps_dot_proto_dot_driving_dot_route__point__pb2._ROUTEPOINT
DESCRIPTOR.message_types_by_name['Route'] = _ROUTE
DESCRIPTOR.extensions_by_name['ROUTE_METADATA'] = ROUTE_METADATA

Route = _reflection.GeneratedProtocolMessageType('Route', (_message.Message,), dict(
  DESCRIPTOR = _ROUTE,
  __module__ = 'yandex.maps.proto.driving.route_pb2'
  # @@protoc_insertion_point(class_scope:yandex.maps.proto.driving.route.Route)
  ))
_sym_db.RegisterMessage(Route)

ROUTE_METADATA.message_type = _ROUTE
yandex_dot_maps_dot_proto_dot_common2_dot_metadata__pb2.Metadata.RegisterExtension(ROUTE_METADATA)

# @@protoc_insertion_point(module_scope)
