# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/maps/proto/driving/route_events.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..road_events import road_events_pb2 as yandex_dot_maps_dot_proto_dot_road__events_dot_road__events__pb2
from ..common2 import geometry_pb2 as yandex_dot_maps_dot_proto_dot_common2_dot_geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yandex/maps/proto/driving/route_events.proto',
  package='yandex.maps.proto.driving.route_events',
  syntax='proto2',
  serialized_pb=_b('\n,yandex/maps/proto/driving/route_events.proto\x12&yandex.maps.proto.driving.route_events\x1a/yandex/maps/proto/road_events/road_events.proto\x1a(yandex/maps/proto/common2/geometry.proto\"\xf4\x01\n\x0cSegmentEvent\x12\x15\n\rsegment_index\x18\x01 \x02(\x05\x12\n\n\x02id\x18\x02 \x02(\t\x12H\n\x04type\x18\x03 \x03(\x0e\x32:.yandex.maps.proto.road_events.RoadEventMetadata.EventType\x12\x0b\n\x03tag\x18\x08 \x03(\t\x12;\n\x08location\x18\x05 \x02(\x0b\x32).yandex.maps.proto.common2.geometry.Point\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x18\n\x10segment_position\x18\x07 \x01(\x01\"[\n\x0bRouteEvents\x12L\n\x0esegment_events\x18\x01 \x03(\x0b\x32\x34.yandex.maps.proto.driving.route_events.SegmentEvent')
  ,
  dependencies=[yandex_dot_maps_dot_proto_dot_road__events_dot_road__events__pb2.DESCRIPTOR,yandex_dot_maps_dot_proto_dot_common2_dot_geometry__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SEGMENTEVENT = _descriptor.Descriptor(
  name='SegmentEvent',
  full_name='yandex.maps.proto.driving.route_events.SegmentEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='segment_index', full_name='yandex.maps.proto.driving.route_events.SegmentEvent.segment_index', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='yandex.maps.proto.driving.route_events.SegmentEvent.id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='yandex.maps.proto.driving.route_events.SegmentEvent.type', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag', full_name='yandex.maps.proto.driving.route_events.SegmentEvent.tag', index=3,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='yandex.maps.proto.driving.route_events.SegmentEvent.location', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='yandex.maps.proto.driving.route_events.SegmentEvent.description', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='segment_position', full_name='yandex.maps.proto.driving.route_events.SegmentEvent.segment_position', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=424,
)


_ROUTEEVENTS = _descriptor.Descriptor(
  name='RouteEvents',
  full_name='yandex.maps.proto.driving.route_events.RouteEvents',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='segment_events', full_name='yandex.maps.proto.driving.route_events.RouteEvents.segment_events', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=517,
)

_SEGMENTEVENT.fields_by_name['type'].enum_type = yandex_dot_maps_dot_proto_dot_road__events_dot_road__events__pb2._ROADEVENTMETADATA_EVENTTYPE
_SEGMENTEVENT.fields_by_name['location'].message_type = yandex_dot_maps_dot_proto_dot_common2_dot_geometry__pb2._POINT
_ROUTEEVENTS.fields_by_name['segment_events'].message_type = _SEGMENTEVENT
DESCRIPTOR.message_types_by_name['SegmentEvent'] = _SEGMENTEVENT
DESCRIPTOR.message_types_by_name['RouteEvents'] = _ROUTEEVENTS

SegmentEvent = _reflection.GeneratedProtocolMessageType('SegmentEvent', (_message.Message,), dict(
  DESCRIPTOR = _SEGMENTEVENT,
  __module__ = 'yandex.maps.proto.driving.route_events_pb2'
  # @@protoc_insertion_point(class_scope:yandex.maps.proto.driving.route_events.SegmentEvent)
  ))
_sym_db.RegisterMessage(SegmentEvent)

RouteEvents = _reflection.GeneratedProtocolMessageType('RouteEvents', (_message.Message,), dict(
  DESCRIPTOR = _ROUTEEVENTS,
  __module__ = 'yandex.maps.proto.driving.route_events_pb2'
  # @@protoc_insertion_point(class_scope:yandex.maps.proto.driving.route_events.RouteEvents)
  ))
_sym_db.RegisterMessage(RouteEvents)


# @@protoc_insertion_point(module_scope)
