# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/maps/proto/driving/speed_limits.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yandex/maps/proto/driving/speed_limits.proto',
  package='yandex.maps.proto.driving.speed_limits',
  syntax='proto2',
  serialized_pb=_b('\n,yandex/maps/proto/driving/speed_limits.proto\x12&yandex.maps.proto.driving.speed_limits\"*\n\nSpeedLimit\x12\r\n\x05speed\x18\x01 \x01(\x02\x12\r\n\x05\x63ount\x18\x02 \x02(\x05\"V\n\x0bSpeedLimits\x12G\n\x0bspeed_limit\x18\x01 \x03(\x0b\x32\x32.yandex.maps.proto.driving.speed_limits.SpeedLimit')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SPEEDLIMIT = _descriptor.Descriptor(
  name='SpeedLimit',
  full_name='yandex.maps.proto.driving.speed_limits.SpeedLimit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='yandex.maps.proto.driving.speed_limits.SpeedLimit.speed', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='yandex.maps.proto.driving.speed_limits.SpeedLimit.count', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=130,
)


_SPEEDLIMITS = _descriptor.Descriptor(
  name='SpeedLimits',
  full_name='yandex.maps.proto.driving.speed_limits.SpeedLimits',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed_limit', full_name='yandex.maps.proto.driving.speed_limits.SpeedLimits.speed_limit', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=218,
)

_SPEEDLIMITS.fields_by_name['speed_limit'].message_type = _SPEEDLIMIT
DESCRIPTOR.message_types_by_name['SpeedLimit'] = _SPEEDLIMIT
DESCRIPTOR.message_types_by_name['SpeedLimits'] = _SPEEDLIMITS

SpeedLimit = _reflection.GeneratedProtocolMessageType('SpeedLimit', (_message.Message,), dict(
  DESCRIPTOR = _SPEEDLIMIT,
  __module__ = 'yandex.maps.proto.driving.speed_limits_pb2'
  # @@protoc_insertion_point(class_scope:yandex.maps.proto.driving.speed_limits.SpeedLimit)
  ))
_sym_db.RegisterMessage(SpeedLimit)

SpeedLimits = _reflection.GeneratedProtocolMessageType('SpeedLimits', (_message.Message,), dict(
  DESCRIPTOR = _SPEEDLIMITS,
  __module__ = 'yandex.maps.proto.driving.speed_limits_pb2'
  # @@protoc_insertion_point(class_scope:yandex.maps.proto.driving.speed_limits.SpeedLimits)
  ))
_sym_db.RegisterMessage(SpeedLimits)


# @@protoc_insertion_point(module_scope)
