# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/maps/proto/driving/spot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yandex/maps/proto/driving/spot.proto',
  package='yandex.maps.proto.driving.spot',
  syntax='proto2',
  serialized_pb=_b('\n$yandex/maps/proto/driving/spot.proto\x12\x1eyandex.maps.proto.driving.spot\"\x8c\x01\n\x04Spot\x12@\n\x04type\x18\x01 \x01(\x0e\x32).yandex.maps.proto.driving.spot.Spot.Type:\x07UNKNOWN\x12\x10\n\x08position\x18\x02 \x02(\r\"0\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x1b\n\x17\x41\x43\x43\x45SS_PASS_RESTRICTION\x10\x01\";\n\x05Spots\x12\x32\n\x04spot\x18\x01 \x03(\x0b\x32$.yandex.maps.proto.driving.spot.Spot')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SPOT_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='yandex.maps.proto.driving.spot.Spot.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACCESS_PASS_RESTRICTION', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=165,
  serialized_end=213,
)
_sym_db.RegisterEnumDescriptor(_SPOT_TYPE)


_SPOT = _descriptor.Descriptor(
  name='Spot',
  full_name='yandex.maps.proto.driving.spot.Spot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='yandex.maps.proto.driving.spot.Spot.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='yandex.maps.proto.driving.spot.Spot.position', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SPOT_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=213,
)


_SPOTS = _descriptor.Descriptor(
  name='Spots',
  full_name='yandex.maps.proto.driving.spot.Spots',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spot', full_name='yandex.maps.proto.driving.spot.Spots.spot', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=274,
)

_SPOT.fields_by_name['type'].enum_type = _SPOT_TYPE
_SPOT_TYPE.containing_type = _SPOT
_SPOTS.fields_by_name['spot'].message_type = _SPOT
DESCRIPTOR.message_types_by_name['Spot'] = _SPOT
DESCRIPTOR.message_types_by_name['Spots'] = _SPOTS

Spot = _reflection.GeneratedProtocolMessageType('Spot', (_message.Message,), dict(
  DESCRIPTOR = _SPOT,
  __module__ = 'yandex.maps.proto.driving.spot_pb2'
  # @@protoc_insertion_point(class_scope:yandex.maps.proto.driving.spot.Spot)
  ))
_sym_db.RegisterMessage(Spot)

Spots = _reflection.GeneratedProtocolMessageType('Spots', (_message.Message,), dict(
  DESCRIPTOR = _SPOTS,
  __module__ = 'yandex.maps.proto.driving.spot_pb2'
  # @@protoc_insertion_point(class_scope:yandex.maps.proto.driving.spot.Spots)
  ))
_sym_db.RegisterMessage(Spots)


# @@protoc_insertion_point(module_scope)
