UA_STATE_CALLING = 1
UA_STATE_INCOMING = 2
UA_STATE_RINGING = 3
UA_STATE_CONNECTING = 4
UA_STATE_CONFIRMED = 5
UA_STATE_DISCONNECTED = 6

MEDIA_STATE_INACTIVE = 0
MEDIA_STATE_ACTIVE = 1

UA_CODE_NORMAL = 16
UA_CODE_TRYING = 100
UA_CODE_RINGING = 180
UA_CODE_OK = 200
UA_CODE_TEMP_UNAV = 480
UA_CODE_BUSY = 486
UA_CODE_CANCEL = 487
UA_CODE_DEFLECT = 502

