# pylint: disable=protected-access

import pytest

from mia.crontasks.extra_fetcher import extra_fetcher_lavka
from mia.crontasks.formatter import formatter_lavka


@pytest.mark.parametrize(
    'test',
    [
        {
            'request': {
                'row': {
                    'order_id': 123,
                    'order_nr': 'test_order_nr',
                    'created_at': 1635497371.1,
                    'created_idx': 1635497371,
                    'finished_at': 1635497371.1,
                    'status': 'canceled',
                    'address_entrance': 'test_address_entrance',
                    'address_city': 'test_address_city',
                    'address_street': 'test_address_street',
                    'address_house': 'test_address_house',
                    'address_comment': 'test_comment',
                    'address_flat': 'my_flat',
                    'courier_username': 'test_courier_username',
                    'personal_phone_id': 'test_phone_id',
                    'dispatch_courier_name': 'test_courier_username',
                    'offer_id': 'test_offer_id',
                    'client_price': 200,
                    'currency': 'RUB',
                    'address_country': 'test_country',
                    'personal_email_id': 'test_email_id',
                    'payment_method': {
                        'id': 'card-x415c48ed54fc26c8fd0a7c92',
                        'type': 'card',
                    },
                },
                'order_log': {
                    'order_id': 123,
                    'created_idx': 1635497371,
                    'cart_items': '[{\"id\": \"589ce2e7180d40d1a5dd4c870046419a000200010001\", \"price\": \"140\", \"quantity\": \"1\", \"item_name\": \"Печень цыплят-бройлеров «Петелинка»\", \"gross_weight\": \"0\", \"cashback_charge\": \"0\"}]',  # noqa: E501
                    'refund': 200,
                    'delivery_cost': 10,
                    'place_address': '125195, Москва г, Смольная ул, дом № 47',
                },
                'personal': {'phone': '123', 'email': '456'},
                'courier_personal_data': {
                    'id': 2,
                    'inn': 'test_inn_2',
                    'address': 'test_address_2',
                    'phone_number': 'test_phone_number_2',
                },
                'courier_service': {
                    'id': 2,
                    'inn': 'test_inn_2',
                    'address': 'test_address_2',
                    'phone_number': 'test_phone_number_2',
                    'name': 'test_name_2',
                },
                'user': {
                    'id': 1,
                    'first_name': 'test_first_name_1',
                    'email': 'test_email_1',
                },
            },
            'expected': {
                'order_id': 123,
                'order_nr': 'test_order_nr',
                'user_phone': '123',
                'user_first_name': 'test_first_name_1',
                'finished_at': '29.10.2021 11:49:31+0300',
                'address_entrance': 'test_address_entrance',
                'address_city': 'test_address_city',
                'address_street': 'test_address_street',
                'address_house': 'test_address_house',
                'address_comment': 'test_comment',
                'cost_for_customer': 200,
                'courier_name': 'test_courier_username',
                'deliverer_address': 'test_address_2',
                'deliverer_name': 'test_name_2',
                'deliverer_inn': 'test_inn_2',
                'deliverer_phone_number': 'test_phone_number_2',
                'created_at': '29.10.2021 11:49:31+0300',
                'order_items': ['Печень цыплят-бройлеров «Петелинка» x1'],
                'order_status': 'Отменён',
                'payment_method': 'Безналичный расчёт',
                'place_address': '125195, Москва г, Смольная ул, дом № 47',
                'place_name': 'Яндекс.Лавка',
                'user_email': '456',
                'address_office': 'my_flat',
                'address_floor': '-',
                'order_refunds': [{'amount': 200, 'id': 0, 'order_id': 123}],
                'delivery_cost': 10,
                'courier_phone': 'test_phone_number_2',
            },
        },
        {
            'request': {
                'row': {
                    'order_id': 123,
                    'order_nr': 'test_order_nr',
                    'created_at': 1635497371.1,
                    'created_idx': 1635497371,
                    'finished_at': 1635497371.1,
                    'status': 'closed',
                    'address_entrance': 'test_address_entrance',
                    'address_city': 'test_address_city',
                    'address_street': 'test_address_street',
                    'address_house': 'test_address_house',
                    'address_comment': 'test_comment',
                    'courier_username': 'test_courier_username',
                    'personal_phone_id': 'test_phone_id',
                    'dispatch_courier_name': 'test_courier_username',
                    'offer_id': 'test_offer_id',
                    'client_price': 200,
                    'currency': 'RUB',
                    'address_country': 'test_country',
                    'personal_email_id': None,
                    'payment_method': {'id': 'smth', 'type': 'applepay'},
                    'address_flat': 'my_flat',
                },
                'order_log': {
                    'order_id': 123,
                    'created_idx': 1635497371,
                    'cart_items': '[{\"id\": \"0e141f86679e41d2b8551145eca85c3e000200010000\", \"price\": \"79\", \"quantity\": \"1\", \"item_name\": \"Cyber Bite ваниль\"}, {\"id\": \"e469c3406c564b7d82b882e74515645f000300010000\", \"price\": \"159\", \"quantity\": \"3\", \"item_name\": \"Bite гречневые протеиновые\"}, {\"id\": \"0e4dea016f50416295ad44a228574111000200010001\", \"price\": \"139\", \"quantity\": \"1\", \"item_name\": \"Cyber Bite ваниль\"}]',  # noqa: E501
                    'refund': None,
                    'delivery_cost': 0,
                    'place_address': '125195, Москва г, Смольная ул, дом № 47',
                },
                'personal': {'phone': '123'},
                'courier_personal_data': {
                    'id': 2,
                    'inn': 'test_inn_2',
                    'address': 'test_address_2',
                    'phone_number': 'test_phone_number_2',
                },
                'courier_service': {
                    'id': 2,
                    'inn': 'test_inn_2',
                    'address': 'test_address_2',
                    'phone_number': 'test_phone_number_2',
                    'name': 'test_name_2',
                },
                'user': {
                    'id': 1,
                    'first_name': 'test_first_name_1',
                    'email': 'test_email_1',
                },
            },
            'expected': {
                'order_id': 123,
                'order_nr': 'test_order_nr',
                'user_phone': '123',
                'user_first_name': 'test_first_name_1',
                'finished_at': '29.10.2021 11:49:31+0300',
                'address_entrance': 'test_address_entrance',
                'address_city': 'test_address_city',
                'address_street': 'test_address_street',
                'address_house': 'test_address_house',
                'address_comment': 'test_comment',
                'cost_for_customer': 200,
                'courier_name': 'test_courier_username',
                'deliverer_address': 'test_address_2',
                'deliverer_name': 'test_name_2',
                'deliverer_inn': 'test_inn_2',
                'deliverer_phone_number': 'test_phone_number_2',
                'created_at': '29.10.2021 11:49:31+0300',
                'order_items': [
                    'Cyber Bite ваниль x1',
                    'Bite гречневые протеиновые x3',
                    'Cyber Bite ваниль x1',
                ],
                'order_status': 'Доставлен',
                'payment_method': 'Безналичный расчёт',
                'place_address': '125195, Москва г, Смольная ул, дом № 47',
                'place_name': 'Яндекс.Лавка',
                'user_email': 'test_email_1',
                'address_office': 'my_flat',
                'address_floor': '-',
                'order_refunds': None,
                'delivery_cost': 0,
                'courier_phone': 'test_phone_number_2',
            },
        },
        {
            'request': {
                'row': {
                    'order_id': 123,
                    'order_nr': 'test_order_nr',
                    'created_at': 1635497371.1,
                    'created_idx': 1635497371,
                    'finished_at': 1635497371.1,
                    'address_entrance': 'test_address_entrance',
                    'address_city': 'test_address_city',
                    'address_street': 'test_address_street',
                    'address_house': 'test_address_house',
                    'address_flat': 'my_flat',
                    'address_comment': 'test_comment',
                    'courier_username': 'test_courier_username',
                    'personal_phone_id': 'test_phone_id',
                    'dispatch_courier_name': 'test_courier_username',
                    'offer_id': 'test_offer_id',
                    'client_price': 200,
                    'currency': 'RUB',
                    'address_country': 'test_country',
                    'personal_email_id': None,
                    'status': None,
                    'payment_method': {
                        'id': 'smth',
                        'type': 'personal_wallet',
                    },
                    'courier_personal_data': {
                        'id': 2,
                        'inn': 'test_inn_2',
                        'address': 'test_address_2',
                        'phone_number': 'test_phone_number_2',
                    },
                    'courier_service': {
                        'id': 2,
                        'inn': 'test_inn_2',
                        'address': 'test_address_2',
                        'phone_number': 'test_phone_number_2',
                        'name': 'test_name_2',
                    },
                    'user': {
                        'id': 1,
                        'first_name': 'test_first_name_1',
                        'email': 'test_email_1',
                    },
                },
                'order_log': {
                    'order_id': 123,
                    'created_idx': 1635497371,
                    'cart_items': '[{\"id\": \"0e141f86679e41d2b8551145eca85c3e000200010000\", \"price\": \"79\", \"quantity\": \"1\", \"item_name\": \"Cyber Bite ваниль\"}, {\"id\": \"e469c3406c564b7d82b882e74515645f000300010000\", \"price\": \"159\", \"quantity\": \"3\", \"item_name\": \"Bite гречневые протеиновые\"}, {\"id\": \"0e4dea016f50416295ad44a228574111000200010001\", \"price\": \"139\", \"quantity\": \"1\", \"item_name\": \"Cyber Bite ваниль\"}]',  # noqa: E501
                    'refund': None,
                    'delivery_cost': 0,
                    'place_address': '125195, Москва г, Смольная ул, дом № 47',
                },
                'personal': {'phone': '123'},
                'courier_personal_data': {
                    'id': 2,
                    'inn': 'test_inn_2',
                    'address': 'test_address_2',
                    'phone_number': 'test_phone_number_2',
                },
                'courier_service': {
                    'id': 2,
                    'inn': 'test_inn_2',
                    'address': 'test_address_2',
                    'phone_number': 'test_phone_number_2',
                    'name': 'test_name_2',
                },
                'user': {
                    'id': 1,
                    'first_name': 'test_first_name_1',
                    'email': 'test_email_1',
                },
            },
            'expected': {
                'order_id': 123,
                'order_nr': 'test_order_nr',
                'user_phone': '123',
                'user_first_name': 'test_first_name_1',
                'finished_at': '29.10.2021 11:49:31+0300',
                'address_entrance': 'test_address_entrance',
                'address_city': 'test_address_city',
                'address_street': 'test_address_street',
                'address_house': 'test_address_house',
                'address_comment': 'test_comment',
                'cost_for_customer': 200,
                'courier_name': 'test_courier_username',
                'deliverer_address': 'test_address_2',
                'deliverer_name': 'test_name_2',
                'deliverer_inn': 'test_inn_2',
                'deliverer_phone_number': 'test_phone_number_2',
                'created_at': '29.10.2021 11:49:31+0300',
                'order_items': [
                    'Cyber Bite ваниль x1',
                    'Bite гречневые протеиновые x3',
                    'Cyber Bite ваниль x1',
                ],
                'order_status': 'Не доставлен',
                'payment_method': 'Наличный расчёт',
                'place_address': '125195, Москва г, Смольная ул, дом № 47',
                'place_name': 'Яндекс.Лавка',
                'user_email': 'test_email_1',
                'address_office': 'my_flat',
                'address_floor': '-',
                'order_refunds': None,
                'delivery_cost': 0,
                'courier_phone': 'test_phone_number_2',
            },
        },
    ],
)
async def test_format_row(test):
    request = test['request']
    expected = test['expected']

    formatter = formatter_lavka.FormatterLavka()

    row_with_extra = extra_fetcher_lavka.RowWithExtraLavka(
        row=request['row'],
        order_log=request['order_log'],
        personal=request['personal'],
        courier_personal_data=request['courier_personal_data'],
        courier_service=request['courier_service'],
        user=request['user'],
    )

    result = await formatter._format_row(row_with_extra)

    assert result == expected
