CREATE SCHEMA eats_feedback;

CREATE TABLE IF NOT EXISTS eats_feedback.orders (
    order_nr VARCHAR(255) NOT NULL PRIMARY KEY,
    order_delivered_at TIMESTAMPTZ,
    status VARCHAR(255) NOT NULL,
    eater_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP NOT NULL
);
