INSERT INTO persey_payments.donation
    (
        fund_id,
        yandex_uid,
        sum,
        status,
        ride_subs_id,
        brand,
        order_id
    )
VALUES
    (
        'friends',
        'phonish_uid',
        '4',
        'started',
        1,
        'lavka',
        '777'
    ),
    (
        'friends',
        'phonish_uid',
        '4',
        'not_authorized',
        1,
        'lavka',
        '778'
    ),
    (
        'friends',
        'phonish_uid',
        '4',
        'finished',
        1,
        'lavka',
        '779'
    );
