INSERT INTO dispatch_airport_partner_protocol.parking_drivers AS drivers (driver_id,
                                                                          parking_id,
                                                                          created_ts,
                                                                          updated_ts,
                                                                          heartbeated,
                                                                          car_number,
                                                                          car_number_normalized,
                                                                          latitude,
                                                                          longitude,
                                                                          driver_diagnostics_updated_ts,
                                                                          driver_status,
                                                                          tags_block_reason,
                                                                          has_allowed_provider)
--     driver with no tag reasons
VALUES ('dbid_uuid1',
        'parking_lot1',
        '2020-02-02T00:00:00+00:00',
        '2020-02-02T00:00:00+00:00',
        '2020-02-02T00:00:00+00:00',
        'А 111 АА',
        'A111AA',
        0,
        0,
        '2020-02-02T00:00:00+00:00',
        'online',
        NULL,
        TRUE),
--        driver with tag reasons
       ('dbid_uuid2',
        'parking_lot1',
        '2020-02-02T00:00:00+00:00',
        '2020-02-02T00:00:00+00:00',
        '2020-02-02T00:00:00+00:00',
        NULL,
        'A222AA',
        0,
        0,
        '2020-02-02T00:00:00+00:00',
        'online',
        'forbidden_tag_reason',
        TRUE)
;
