INSERT INTO payouts.data_open (
  "id"
  , "process_uid"
  , "transaction_id"
  , "part_count"
  , "payout_batch_id"
  , "branch_type"
  , "firm_id"
  , "client_id"
  , "contract_id"
  , "contract_alias"
  , "currency"
  , "amount_w_vat"
  , "amount_w_vat_applied"
  , "amount_w_vat_saldo"
  , "netting_sign"
  , "accounting_date"
  , "accounting_period"
  , "payload"
  , "created_at_utc"
  , "updated_at_utc"
  , "person_id"
  , "dry_run"
  , "payment_processor"
  , "batch_group_key"
  , "external_ref"
  , "status_code"
) VALUES (
  3803347329
, '0211e0cb1c254f22a2e403f2a66413bd'
, 21107474801
, 8
, 70893424
, 'revenues'
, 13
, '92057445'
, '2626879'
, '1459100/21'
, 'RUB'
, - 3103.45
, 0.00
, - 3103.45
, - 1
, '2022-06-27'
, '2022-06'
, '{"target": "oebs", "product": "coupon_plus", "alias_id": "fe44164b1c95c1b6b1746732c6b164e8", "vat_rate": "20.00", "event_time": "2022-06-27T02:01:51.000000+00:00", "service_id": 111, "account_info": {"account": "ЛСТ-3526707426-1", "account_type": "YANDEX_SERVICE"}, "external_ref": "alias_id/fe44164b1c95c1b6b1746732c6b164e8", "invoice_date": "2022-06-27T02:01:51.000000+00:00", "tariff_class": "business", "agglomeration": "PERc", "contract_info": {"alias": "1459100/21", "firm_id": 13, "person_id": 12678339, "country_geo": 225, "netting_flag": 1}, "driver_details": {"uuid": "2d7cbec3cf434dd3ab414cc435c96edf", "db_id": "d6b76379484d4beebb2d52bc349952d0"}, "detailed_product": "coupon_plus", "transaction_time": "2022-06-27T05:02:00.631624+03:00", "transaction_type": "payment", "amount_with_vat_flag": true, "country_netting_flag": true, "expense_in_revenue_flag": true}'::jsonb
, to_timestamp('2022-06-27 17:45:15.79579', 'null')
, to_timestamp('2022-06-27 17:45:15.79579', 'null')
, '12678339'
, 'true'
, 'OEBS'
, '2626879~NETTING~TAXI_GRP1'
, 'DEFAULT'
, 'WITH_NETTING'
);

INSERT INTO interface.revenues (
  "id"
  , "status_code"
  , "status_msg"
  , "transaction_id"
  , "accounting_date"
  , "client_id"
  , "contract_id"
  , "currency"
  , "amount_tlog"
  , "amount"
  , "table_name"
  , "row_index"
  , "payload"
  , "created_at_utc"
  , "accounting_period"
  , "dry_run"
  , "payment_processor"
  , "batch_group_key"
  , "external_ref"
) VALUES (
  651697321
, 'WITH_NETTING'
, NULL
, 21130918307
, '2022-06-27'
, '92057445'
, '2626879'
, 'RUB'
, 244.0000
, - 244.00
, '2022-06-27'
, NULL
, '{"target": "oebs", "product": "coupon_plus", "alias_id": "307c0fc9186121fe8786f797a7ffb05f", "vat_rate": "20.00", "event_time": "2022-06-27T17:45:13.000000+00:00", "service_id": 111, "account_info": {"account": "ЛСТ-3526707426-1", "account_type": "YANDEX_SERVICE"}, "external_ref": "alias_id/307c0fc9186121fe8786f797a7ffb05f", "invoice_date": "2022-06-27T17:45:10.370000+00:00", "tariff_class": "business", "agglomeration": "PERc", "contract_info": {"alias": "1459100/21", "firm_id": 13, "person_id": 12678339, "country_geo": 225, "netting_flag": 1}, "driver_details": {"uuid": "2d7cbec3cf434dd3ab414cc435c96edf", "db_id": "d6b76379484d4beebb2d52bc349952d0"}, "detailed_product": "coupon_plus", "transaction_time": "2022-06-27T20:45:22.131983+03:00", "transaction_type": "payment", "amount_with_vat_flag": true, "country_netting_flag": true, "expense_in_revenue_flag": true}'::jsonb
, to_timestamp('2022-06-27 17:45:22.564329', 'null')
, '2022-06'
, 'true'
, 'YA_BANK'
, '2626879~NETTING~TAXI_GRP1'
, 'alias_id/307c0fc9186121fe8786f797a7ffb05f'
);
INSERT INTO interface.revenues (
  "id"
  , "status_code"
  , "status_msg"
  , "transaction_id"
  , "accounting_date"
  , "client_id"
  , "contract_id"
  , "currency"
  , "amount_tlog"
  , "amount"
  , "table_name"
  , "row_index"
  , "payload"
  , "created_at_utc"
  , "accounting_period"
  , "dry_run"
  , "payment_processor"
  , "batch_group_key"
  , "external_ref"
) VALUES (
  654855142
, 'WITH_NETTING'
, NULL
, 21135874821
, '2022-06-28'
, '92057445'
, '2626879'
, 'RUB'
, 203.0000
, - 203.00
, '2022-06-28'
, NULL
, '{"target": "oebs", "product": "coupon_plus", "alias_id": "56486ef88c6239518e27ed85e497bc60", "vat_rate": "20.00", "event_time": "2022-06-27T22:21:21.000000+00:00", "service_id": 111, "account_info": {"account": "ЛСТ-3526707426-1", "account_type": "YANDEX_SERVICE"}, "external_ref": "alias_id/56486ef88c6239518e27ed85e497bc60", "invoice_date": "2022-06-27T22:21:15.949000+00:00", "tariff_class": "business", "agglomeration": "PERc", "contract_info": {"alias": "1459100/21", "firm_id": 13, "person_id": 12678339, "country_geo": 225, "netting_flag": 1}, "driver_details": {"uuid": "2d7cbec3cf434dd3ab414cc435c96edf", "db_id": "d6b76379484d4beebb2d52bc349952d0"}, "detailed_product": "coupon_plus", "transaction_time": "2022-06-28T01:21:30.520520+03:00", "transaction_type": "payment", "amount_with_vat_flag": true, "country_netting_flag": true, "expense_in_revenue_flag": true}'::jsonb
, to_timestamp('2022-06-27 22:21:30.706175', 'null')
, '2022-06'
, 'true'
, 'YA_BANK'
, '2626879~NETTING~TAXI_GRP1'
, 'alias_id/56486ef88c6239518e27ed85e497bc60'
);
INSERT INTO interface.revenues (
  "id"
  , "status_code"
  , "status_msg"
  , "transaction_id"
  , "accounting_date"
  , "client_id"
  , "contract_id"
  , "currency"
  , "amount_tlog"
  , "amount"
  , "table_name"
  , "row_index"
  , "payload"
  , "created_at_utc"
  , "accounting_period"
  , "dry_run"
  , "payment_processor"
  , "batch_group_key"
  , "external_ref"
) VALUES (
  670875643
, 'WITH_NETTING'
, NULL
, 21159490372
, '2022-06-28'
, '92057445'
, '2626879'
, 'RUB'
, 19.5056
, 23.41
, '2022-06-28'
, NULL
, '{"target": "oebs", "product": "order", "alias_id": "4af2a8ff54dcc474858a609501aeac77", "vat_rate": "20.00", "event_time": "2022-06-28T16:23:44.018530+00:00", "service_id": 128, "account_info": {"account": "ЛСТ-3526707426-1", "account_type": "YANDEX_SERVICE"}, "external_ref": "alias_id/4af2a8ff54dcc474858a609501aeac77", "invoice_date": "2022-06-28T16:23:30.086000+00:00", "tariff_class": "econom", "agglomeration": "PERc", "contract_info": {"alias": "1459100/21", "firm_id": 13, "person_id": 12678339, "country_geo": 225, "netting_flag": 1}, "driver_details": {"uuid": "2d7cbec3cf434dd3ab414cc435c96edf", "db_id": "d6b76379484d4beebb2d52bc349952d0"}, "detailed_product": "gross_commission_trips", "transaction_time": "2022-06-28T16:23:45.857166+00:00", "transaction_type": "payment", "country_netting_flag": true}'::jsonb
, to_timestamp('2022-06-28 16:23:46.17632', 'null')
, '2022-06'
, 'true'
, 'YA_BANK'
, '2626879~NETTING~TAXI_GRP1'
, 'alias_id/4af2a8ff54dcc474858a609501aeac77'
);
INSERT INTO interface.revenues (
  "id"
  , "status_code"
  , "status_msg"
  , "transaction_id"
  , "accounting_date"
  , "client_id"
  , "contract_id"
  , "currency"
  , "amount_tlog"
  , "amount"
  , "table_name"
  , "row_index"
  , "payload"
  , "created_at_utc"
  , "accounting_period"
  , "dry_run"
  , "payment_processor"
  , "batch_group_key"
  , "external_ref"
) VALUES (
  670875650
, 'WITH_NETTING'
, NULL
, 21159490373
, '2022-06-28'
, '92057445'
, '2626879'
, 'RUB'
, 1.0000
, 1.20
, '2022-06-28'
, NULL
, '{"target": "oebs", "product": "order", "alias_id": "4af2a8ff54dcc474858a609501aeac77", "vat_rate": "20.00", "event_time": "2022-06-28T16:23:44.018530+00:00", "service_id": 128, "account_info": {"account": "ЛСТ-3526707426-1", "account_type": "YANDEX_SERVICE"}, "external_ref": "alias_id/4af2a8ff54dcc474858a609501aeac77", "invoice_date": "2022-06-28T16:23:30.086000+00:00", "tariff_class": "econom", "agglomeration": "PERc", "contract_info": {"alias": "1459100/21", "firm_id": 13, "person_id": 12678339, "country_geo": 225, "netting_flag": 1}, "driver_details": {"uuid": "2d7cbec3cf434dd3ab414cc435c96edf", "db_id": "d6b76379484d4beebb2d52bc349952d0"}, "detailed_product": "gross_taximeter_payment", "transaction_time": "2022-06-28T16:23:45.857166+00:00", "transaction_type": "payment", "country_netting_flag": true}'::jsonb
, to_timestamp('2022-06-28 16:23:46.17632', 'null')
, '2022-06'
, 'true'
, 'YA_BANK'
, '2626879~NETTING~TAXI_GRP1'
, 'alias_id/4af2a8ff54dcc474858a609501aeac77'
);
INSERT INTO interface.revenues (
  "id"
  , "status_code"
  , "status_msg"
  , "transaction_id"
  , "accounting_date"
  , "client_id"
  , "contract_id"
  , "currency"
  , "amount_tlog"
  , "amount"
  , "table_name"
  , "row_index"
  , "payload"
  , "created_at_utc"
  , "accounting_period"
  , "dry_run"
  , "payment_processor"
  , "batch_group_key"
  , "external_ref"
) VALUES (
  674431202
, 'WITH_NETTING'
, NULL
, 21164951701
, '2022-06-28'
, '92057445'
, '2626879'
, 'RUB'
, 39.4120
, 47.29
, '2022-06-28'
, NULL
, '{"target": "oebs", "product": "order", "alias_id": "1b4f9e66a0c627bf9c22a14c58f7be4b", "vat_rate": "20.00", "event_time": "2022-06-28T19:59:59.410289+00:00", "service_id": 128, "account_info": {"account": "ЛСТ-3526707426-1", "account_type": "YANDEX_SERVICE"}, "external_ref": "alias_id/1b4f9e66a0c627bf9c22a14c58f7be4b", "invoice_date": "2022-06-28T19:59:56.586000+00:00", "tariff_class": "econom", "agglomeration": "PERc", "contract_info": {"alias": "1459100/21", "firm_id": 13, "person_id": 12678339, "country_geo": 225, "netting_flag": 1}, "driver_details": {"uuid": "2d7cbec3cf434dd3ab414cc435c96edf", "db_id": "d6b76379484d4beebb2d52bc349952d0"}, "detailed_product": "gross_commission_trips", "transaction_time": "2022-06-28T20:00:00.802108+00:00", "transaction_type": "payment", "country_netting_flag": true}'::jsonb
, to_timestamp('2022-06-28 20:00:00.965146', 'null')
, '2022-06'
, 'true'
, 'YA_BANK'
, '2626879~NETTING~TAXI_GRP1'
, 'alias_id/1b4f9e66a0c627bf9c22a14c58f7be4b'
);
