import pytest

HANDLER_PATH = 'v1/comment/properties'

DRIVER_METRICS_COMMENT_SETTINGS = {
    'min_word_length': 3,
    'neighbour_default_weight': 0.5,
    'neighbours': {
        'a': ['q', 'w', 's', 'z', 'x'],
        'b': ['v', 'g', 'h', 'j', 'n'],
        'c': ['x', 'd', 'f', 'g', 'v'],
        'd': ['w', 'e', 'r', 's', 'f', 'x', 'c', 'z'],
        'e': ['3', '4', 'w', 'r', 's', 'd', 'f'],
        'f': ['e', 'r', 't', 'd', 'g', 'c', 'v', 'x'],
        'g': ['r', 't', 'y', 'f', 'h', 'v', 'b', 'c'],
        'h': ['t', 'y', 'u', 'g', 'j', 'b', 'n', 'v'],
        'i': ['8', '9', 'u', 'o', 'j', 'k', 'l'],
        'j': ['y', 'u', 'i', 'h', 'k', 'b', 'n', 'm'],
        'k': ['u', 'i', 'o', 'j', 'l', 'n', 'm'],
        'l': ['o', 'p', 'k', 'm'],
        'm': ['n', 'j', 'k', 'l', '.'],
        'n': ['b', 'h', 'j', 'k', 'm'],
        'o': ['9', '0', 'i', 'p', 'k', 'l'],
        'p': ['9', '0', 'o', 'k', 'l'],
        'q': ['1', '2', 'w', 's', 'z'],
        'r': ['4', '5', 'e', 't', 'd', 'f', 'g'],
        's': ['q', 'w', 'e', 'a', 'd', 'z', 'x'],
        't': ['5', '6', 'r', 'y', 'f', 'g', 'h'],
        'u': ['7', '8', 'y', 'i', 'h', 'j', 'k'],
        'v': ['c', 'f', 'g', 'v'],
        'w': ['2', '3', 'q', 'e', 'a', 'd', 'z'],
        'x': ['z', 'a', 's', 'd', 'f', 'c'],
        'y': ['6', '7', 't', 'u', 'g', 'h', 'j'],
        'z': ['a', 's', 'x'],
        'б': ['m', 'k', 'l', 'ж', 'ю'],
        'ж': ['э', 'ю', 'б', 'l', 'p'],
        'х': ['p', 'з', 'ж', 'э'],
        'э': ['p', 'з', 'ж', 'ю'],
        'ю': ['б', 'l', 'ж', 'э'],
    },
    'rus_eng_map': {
        'а': 'f',
        'в': 'd',
        'г': 'u',
        'д': 'l',
        'е': 't',
        'ё': 't',
        'з': 'p',
        'и': 'b',
        'й': 'q',
        'к': 'r',
        'л': 'k',
        'м': 'v',
        'н': 'y',
        'о': 'j',
        'п': 'g',
        'р': 'h',
        'с': 'c',
        'т': 'n',
        'у': 'e',
        'ф': 'a',
        'ц': 'w',
        'ч': 'x',
        'ш': 'i',
        'щ': 'o',
        'ы': 's',
        'ь': 'm',
        'я': 'z',
    },
}


@pytest.mark.parametrize(
    'comment, comment_properties',
    [
        ('!!можно,    без кавказцев', ['bad_order_comment']),
        ('детское кресло', ['bad_order_comment']),
        ('буду с ребенком', ['bad_order_comment']),
        ('надо будет подъехать к 12ому, столбу!!', []),
        ('подъехать через 15 минут', ['bad_order_comment']),
        ('С маленьким  ребёнком! ', ['bad_order_comment']),
        ('Детский сад Вырастайка вход со стороны змеиногорского', []),
        (
            'На парковку колледжа к воротам. С ребенком 9 лет',
            ['bad_order_comment'],
        ),
        ('поедем с собакой.', ['bad_order_comment']),
        ('На ручках будет маленькая собачка', ['bad_order_comment']),
        ('Маленькая собачка на колени', ['bad_order_comment']),
        ('Сдача с 5000', ['bad_order_comment']),
        ('С дачного проспекта', []),
        ('буду с переноской', ['bad_order_comment']),
        ('Платитб я конечно не буду))', ['money']),
        ('Нужен водитель без картонавируса!', ['corona']),
        ('Платитб я конечно не буду))', ['money']),
        ('Доплачу 700 рублей если будете в маске', ['money', 'corona']),
        (
            'У ребенка симптомы срочно в больницу!',
            ['bad_order_comment', 'corona'],
        ),
        (
            'Вот у нас на кавказе можно не платить за такси',
            ['bad_order_comment', 'money'],
        ),
        (
            'если схвачу вирус от кресла то заплатите',
            ['bad_order_comment', 'money', 'corona'],
        ),
        ('мы бежим с тобой как будто от гепарда', ['bad_order_comment']),
    ],
)
@pytest.mark.config(
    DRIVER_METRICS_COMMENT_SETTINGS={
        'min_word_length': 3,
        'neighbour_default_weight': 0.5,
        'neighbours': {
            'a': ['q', 'w', 's', 'z', 'x'],
            'b': ['v', 'g', 'h', 'j', 'n'],
            'c': ['x', 'd', 'f', 'g', 'v'],
            'd': ['w', 'e', 'r', 's', 'f', 'x', 'c', 'z'],
            'e': ['3', '4', 'w', 'r', 's', 'd', 'f'],
            'f': ['e', 'r', 't', 'd', 'g', 'c', 'v', 'x'],
            'g': ['r', 't', 'y', 'f', 'h', 'v', 'b', 'c'],
            'h': ['t', 'y', 'u', 'g', 'j', 'b', 'n', 'v'],
            'i': ['8', '9', 'u', 'o', 'j', 'k', 'l'],
            'j': ['y', 'u', 'i', 'h', 'k', 'b', 'n', 'm'],
            'k': ['u', 'i', 'o', 'j', 'l', 'n', 'm'],
            'l': ['o', 'p', 'k', 'm'],
            'm': ['n', 'j', 'k', 'l', '.'],
            'n': ['b', 'h', 'j', 'k', 'm'],
            'o': ['9', '0', 'i', 'p', 'k', 'l'],
            'p': ['9', '0', 'o', 'k', 'l'],
            'q': ['1', '2', 'w', 's', 'z'],
            'r': ['4', '5', 'e', 't', 'd', 'f', 'g'],
            's': ['q', 'w', 'e', 'a', 'd', 'z', 'x'],
            't': ['5', '6', 'r', 'y', 'f', 'g', 'h'],
            'u': ['7', '8', 'y', 'i', 'h', 'j', 'k'],
            'v': ['c', 'f', 'g', 'v'],
            'w': ['2', '3', 'q', 'e', 'a', 'd', 'z'],
            'x': ['z', 'a', 's', 'd', 'f', 'c'],
            'y': ['6', '7', 't', 'u', 'g', 'h', 'j'],
            'z': ['a', 's', 'x'],
            'б': ['m', 'k', 'l', 'ж', 'ю'],
            'ж': ['э', 'ю', 'б', 'l', 'p'],
            'х': ['p', 'з', 'ж', 'э'],
            'э': ['p', 'з', 'ж', 'ю'],
            'ю': ['б', 'l', 'ж', 'э'],
        },
        'rus_eng_map': {
            'а': 'f',
            'в': 'd',
            'г': 'u',
            'д': 'l',
            'е': 't',
            'ё': 't',
            'з': 'p',
            'и': 'b',
            'й': 'q',
            'к': 'r',
            'л': 'k',
            'м': 'v',
            'н': 'y',
            'о': 'j',
            'п': 'g',
            'р': 'h',
            'с': 'c',
            'т': 'n',
            'у': 'e',
            'ф': 'a',
            'ц': 'w',
            'ч': 'x',
            'ш': 'i',
            'щ': 'o',
            'ы': 's',
            'ь': 'm',
            'я': 'z',
        },
    },
    DRIVER_METRICS_STOP_WORDS_FOR_COMMENTS={
        'similarity_threshold': 0.7,
        'comment_properties': [
            {
                'name': 'bad_order_comment',
                'stop_words': [
                    {'word': 'кресло'},
                    {'word': 'хач'},
                    {'word': 'кавказец'},
                    {'word': 'ребенок', 'similarity_threshold': 0.6},
                    {'word': 'гепарда', 'similarity_threshold': 1},
                    {'word': 'собака'},
                    {'word': 'сдача'},
                    {'word': 'дети'},
                    {'word': 'минута'},
                    {'word': 'переноска'},
                ],
            },
            {
                'name': 'money',
                'stop_words': [
                    {'word': 'платить', 'similarity_threshold': 0.6},
                    {'word': 'деньги', 'similarity_threshold': 0.6},
                    {'word': 'скидка'},
                    {'word': 'рубль', 'similarity_threshold': 0.6},
                ],
            },
            {
                'name': 'corona',
                'stop_words': [
                    {'word': 'корона'},
                    {'word': 'коронавирус'},
                    {'word': 'вирус'},
                    {'word': 'болезнь'},
                    {'word': 'симптом'},
                    {'word': 'маска'},
                ],
            },
        ],
    },
)
async def test_base(taxi_driver_metrics_storage, comment, comment_properties):
    response = await taxi_driver_metrics_storage.post(
        HANDLER_PATH, json={'comment': comment},
    )
    assert response.status_code == 200
    assert response.json()['comment_properties'] == comment_properties
