#!/bin/sh
export Y_PYTHON_SOURCE_ROOT=/home/rumkex/work/arcadia
export Y_PYTHON_ENTRY_POINT=":main"
/home/rumkex/work/arcadia/taxi/uservices/services/arcadia-userver-test/testsuite/services-arcadia-userver-test-testsuite "$@"
