\ir ../../../postgresql/supportai_calls/migrations/V01__initial.sql
\ir ../../../postgresql/supportai_calls/migrations/V02__token_auth.sql
\ir ../../../postgresql/supportai_calls/migrations/V03__dispatcher_params.sql
\ir ../../../postgresql/supportai_calls/migrations/V04__NONTRANSACTIONAL_outgoing_calls_callback.sql
\ir ../../../postgresql/supportai_calls/migrations/V05__audio_files_metadata.sql
\ir ../../../postgresql/supportai_calls/migrations/V06__audio_files_user_filename.sql
\ir ../../../postgresql/supportai_calls/migrations/V07__common_tasks.sql
\ir ../../../postgresql/supportai_calls/migrations/V08__audio_files_secret.sql
\ir ../../../postgresql/supportai_calls/migrations/V09__fill_in_audio_files_secrets.sql
\ir ../../../postgresql/supportai_calls/migrations/V10__audio_files_user_comment.sql
\ir ../../../postgresql/supportai_calls/migrations/V11__NONTRANSACTIONAL_ivr_framework_call_service.sql
\ir ../../../postgresql/supportai_calls/migrations/V12__outgoing_call_call_record_id.sql
\ir ../../../postgresql/supportai_calls/migrations/V13__incoming_calls.sql
\ir ../../../postgresql/supportai_calls/migrations/V14__external_phone_id.sql
\ir ../../../postgresql/supportai_calls/migrations/V15__unique_chat_ids.sql
\ir ../../../postgresql/supportai_calls/migrations/V16__default_call_service_ivr_framework.sql
\ir ../../../postgresql/supportai_calls/migrations/V17__outgoing_calls_index.sql
\ir ../../../postgresql/supportai_calls/migrations/V18__call_control_timetamps.sql
\ir ../../../postgresql/supportai_calls/migrations/V19__call_attempt_number.sql
\ir ../../../postgresql/supportai_calls/migrations/V20__NONTRANSACTIONAL_ya_telephony_service.sql
