INSERT INTO storage.places (
    id,
    created_at,
    updated_at,
    slug,
    enabled,
    name,
    revision,
    type,
    business,
    launched_at,
    payment_methods,
    gallery,
    brand,
    address,
    country,
    categories,
    quick_filters,
    wizard_quick_filters,
    region,
    location,
    price_category,
    assembly_cost,
    rating,
    extra_info,
    features,
    timing,
    sorting,
    address_comment,
    contacts,
    working_intervals,
    allowed_couriers_types)
VALUES
    (10, '2020-10-10T05:05:05+03:00', '2020-10-10T05:05:05+03:00', 'slug10', true, 'Название10', 100,
        'native', 'zapravki', '2020-10-10T05:05:05+03:00',
        ARRAY['cash','taxi']::storage.place_payment_method[], ARRAY[]::storage.place_gallery[],
        (1,'slug','name', 'aspect_fit')::storage.place_brand_v2, ('city','short')::storage.place_address,
        (1,'name','code',('code','sign')::storage.place_country_currency)::storage.place_country,
        ARRAY[]::storage.place_category[], ARRAY[]::storage.place_quick_filter[],
        ARRAY[]::storage.place_quick_filter[], (1,'{1,2}'::bigint[],'zone','name')::storage.place_region,
        point(3,4), (1,'name',0.5)::storage.place_price_category, 123,
        '{"shown":4.83, "users":4.5, "admin":1.0, "count":200}', '{}',
        '{"fast_food": true, "ignore_surge": false, "supports_preordering": false}',
        '{"preparation": 300, "extra_preparation": 300, "average_preparation": 300}',
        '{"popular": 1, "weight": 1, "wizard": 1}', NULL, NULL,
     ARRAY[]::storage.working_interval[], ARRAY[]::storage.delivery_zone_couriers_type[]);

INSERT INTO storage.delivery_zones(
    id,
    source,
    external_id,
    place_id,
    couriers_zone_id,
    name,
    created_at,
    updated_at,
    revision,
    enabled,
    couriers_type,
    shipping_type,
    delivery_conditions,
    market_avg_time,
    arrival_time,
    working_intervals,
    polygons)
VALUES
    (100, 'eats_core', 'id-100', 10, 1000, 'Название100', '2020-10-10T07:07:07+03:00', '2020-10-10T07:07:07+03:00', 1, false,
        'vehicle', 'delivery',
        ARRAY[(100,200)::storage.delivery_zone_delivery_condition]::storage.delivery_zone_delivery_condition[],
        100.2, 600.5,
        ARRAY[('2020-10-10T10:00:00+03:00', '2020-10-10T19:00:00+03:00')::storage.working_interval]::storage.working_interval[],
        '{"((1,1),(2,1),(2,2),(1,2))"}');
