const base = {
  cartPromocodesListEpsilon: 'cartPromocodesListEpsilon',
  cartRetrieveEpsilon: 'cartRetrieveEpsilon',
  cartRetrieveGamma: 'cartRetrieveGamma',
  cartRetrieveParcel1: 'cartRetrieveParcel1',
  categoryBase: 'categoryBase',
  categoryDelta: 'categoryDelta',
  categoryDeltaA2: 'categoryDelta-A2',
  categoryDeltaA: 'categoryDelta-A',
  categoryDeltaBubbles: 'categoryDeltaBubbles',
  categoryDeltaCarousel: 'categoryDeltaCarousel',
  categoryDeltaSoldOut1: 'categoryDeltaSoldOut1',
  categoryDeltaSoldOut2: 'categoryDeltaSoldOut2',
  categoryDeltaSoldOut3: 'categoryDeltaSoldOut3',
  categoryDeltaThreeInRow: 'categoryDeltaThreeInRow',
  categoryDeltaTwoInRow: 'categoryDeltaTwoInRow',
  categorySigma: 'categorySigma',
  categoryWithBundles: 'categoryWithBundles',
  categoryWithHero: 'categoryWithHero',
  categoryWithSomeProductDiscount: 'categoryWithSomeProductDiscount',
  gammaCartRetrieve: 'gammaCartRetrieve',
  geoPointMarksistskaya:
    'ymapsbm1://geo?ll=37.656%2C55.741&spn=0.001%2C0.001&text=%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D1%8F%2C%20%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0%2C%20%D0%9C%D0%B0%D1%80%D0%BA%D1%81%D0%B8%D1%81%D1%82%D1%81%D0%BA%D0%B0%D1%8F%20%D1%83%D0%BB%D0%B8%D1%86%D0%B0%2C%202',
  geoPointMarksistskayaDecoded:
    'ymapsbm1://geo?ll=37.656,55.741&spn=0.001,0.001&text=Россия, Москва, Марксистская улица, 2',
  groupDelta: 'groupDelta',
  groupDeltaCarousel: 'groupDeltaCarousel',
  groupDeltaCarouselWithRestrictionsAdult18: 'groupDeltaCarouselWithRestrictionsAdult18',
  groupDeltaSpecific: 'groupDeltaSpecific',
  layoutDeltaId: 'deltaLayoutId',
  layoutRouterId: 'routerLayoutId',
  listPaymentMethodsWithCorp: 'listPaymentMethodsWithCorp',
  productBase: 'productBase',
  productDelta: 'productDelta',
  productParcel1: 'alphaItem1Id:st-pa',
  productSigmaExpiring: 'productSigmaExpiring',
  productSigmaNoImage: 'productSigmaNoImage',
  productSigmaWithCashback: 'productSigmaWithCashback',
  productSigmaWithDiscount: 'productSigmaWithDiscount',
  productSigmaWithGrades: 'productSigmaWithGrades',
  productSigmaWithInformers: 'productSigmaWithInformers',
  productSigmaWithStickers: 'productSigmaWithStickers',
  productSigmaWithUpsale: 'productSigmaWithUpsale',
  productSigmaWithSigmaUpsale: 'productSigmaWithSigmaUpsale',
  productUpsaleAlpha: 'upsaleAlphaProduct',
  productUpsaleBetta: 'upsaleBettaProduct',
  productWithDiscount: 'productWithDiscount',
  productMetaWithBundles: 'productMetaWithBundles',
  productMetaWithBundlesStatic: 'productMetaWithBundlesStatic',
  productWithRelatedNonUniqueCombo: 'productWithRelatedNonUniqueCombo',
  productWithRelatedSingleSelectionCombo: 'productWithRelatedSingleSelectionCombo',
  productWithRelatedSingleSelectionGroupCombo: 'productWithRelatedSingleSelectionGroupCombo',
  promocodeEpsilon1: 'promocodeEpsilon1',
  promocodeEpsilon2: 'promocodeEpsilon2',
  promocodeEpsilon3: 'promocodeEpsilon3',
  promocodeEpsilonA: 'promocodeEpsilonA',
  promocodeEpsilonB: 'promocodeEpsilonB',
  promocodeEpsilonC: 'promocodeEpsilonC',
  subcategoryDelta: 'subcategoryDelta',
  subcategoryDeltaCarousel: 'subcategoryDeltaCarousel',
  subcategoryDeltaThreeInRow: 'subcategoryDeltaThreeInRow',
  subcategoryDeltaTwoInRow: 'subcategoryDeltaTwoInRow',
  subcategorySigma: 'subcategorySigma',
  subcategoryBase: 'subcategoryBase',
  subcategoryWithBundles: 'subcategoryWithBundles',
  subcategoryWithBundleProducts: 'subcategoryWithBundleProducts',
  groupBase: 'groupBase',
  pageTrackingLayout: 'tracking-page-layout',
  pageTrackingMapLayout: 'tracking-page-map-layout',
  orderSadovnicheskaya: 'sadovnicheskaya82c2OrderId',
  orderSadovnicheskayaWithMoreAddressFields: 'stateForOrderOnSadovnicheskaya82c2WithAddressFields',
  orderSadovnicheskayaWithDriverInfo: 'stateForOrderOnSadovnicheskaya82c2WithDriverId',
  uidLocal: 'localUid',
  cardIdAlpha: 'cardIdAlpha',
}

export const identifiers = {
  ...base,
  groupDeltaBottom1: `${base.groupDelta}-bottomGroups-0`,
  groupDeltaBottom2: `${base.groupDelta}-bottomGroups-1`,
  groupDeltaBottom3: `${base.groupDelta}-bottomGroups-2`,
  groupDeltaA: `${base.groupDelta}-A`,
}
