-- PG shard 1/4
SET client_min_messages TO WARNING;
SET lock_timeout TO '30s';

\set schema_name ba_tst_40
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_41
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_42
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_43
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_44
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_45
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_46
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_47
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_48
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_49
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_4a
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_4b
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_4c
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_4d
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_4e
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_4f
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_50
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_51
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_52
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_53
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_54
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_55
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_56
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_57
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_58
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_59
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_5a
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_5b
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_5c
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_5d
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_5e
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_5f
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_60
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_61
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_62
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_63
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_64
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_65
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_66
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_67
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_68
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_69
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_6a
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_6b
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_6c
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_6d
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_6e
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_6f
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_70
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_71
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_72
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_73
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_74
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_75
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_76
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_77
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_78
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_79
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_7a
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_7b
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_7c
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_7d
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_7e
\ir ../account-add-updated-index.psql

\set schema_name ba_tst_7f
\ir ../account-add-updated-index.psql

