-- PG shard 3/4
SET client_min_messages TO WARNING;

\set schema_name bd_tst_c0
\i add-index.psql

\set schema_name bd_tst_c1
\i add-index.psql

\set schema_name bd_tst_c2
\i add-index.psql

\set schema_name bd_tst_c3
\i add-index.psql

\set schema_name bd_tst_c4
\i add-index.psql

\set schema_name bd_tst_c5
\i add-index.psql

\set schema_name bd_tst_c6
\i add-index.psql

\set schema_name bd_tst_c7
\i add-index.psql

\set schema_name bd_tst_c8
\i add-index.psql

\set schema_name bd_tst_c9
\i add-index.psql

\set schema_name bd_tst_ca
\i add-index.psql

\set schema_name bd_tst_cb
\i add-index.psql

\set schema_name bd_tst_cc
\i add-index.psql

\set schema_name bd_tst_cd
\i add-index.psql

\set schema_name bd_tst_ce
\i add-index.psql

\set schema_name bd_tst_cf
\i add-index.psql

\set schema_name bd_tst_d0
\i add-index.psql

\set schema_name bd_tst_d1
\i add-index.psql

\set schema_name bd_tst_d2
\i add-index.psql

\set schema_name bd_tst_d3
\i add-index.psql

\set schema_name bd_tst_d4
\i add-index.psql

\set schema_name bd_tst_d5
\i add-index.psql

\set schema_name bd_tst_d6
\i add-index.psql

\set schema_name bd_tst_d7
\i add-index.psql

\set schema_name bd_tst_d8
\i add-index.psql

\set schema_name bd_tst_d9
\i add-index.psql

\set schema_name bd_tst_da
\i add-index.psql

\set schema_name bd_tst_db
\i add-index.psql

\set schema_name bd_tst_dc
\i add-index.psql

\set schema_name bd_tst_dd
\i add-index.psql

\set schema_name bd_tst_de
\i add-index.psql

\set schema_name bd_tst_df
\i add-index.psql

\set schema_name bd_tst_e0
\i add-index.psql

\set schema_name bd_tst_e1
\i add-index.psql

\set schema_name bd_tst_e2
\i add-index.psql

\set schema_name bd_tst_e3
\i add-index.psql

\set schema_name bd_tst_e4
\i add-index.psql

\set schema_name bd_tst_e5
\i add-index.psql

\set schema_name bd_tst_e6
\i add-index.psql

\set schema_name bd_tst_e7
\i add-index.psql

\set schema_name bd_tst_e8
\i add-index.psql

\set schema_name bd_tst_e9
\i add-index.psql

\set schema_name bd_tst_ea
\i add-index.psql

\set schema_name bd_tst_eb
\i add-index.psql

\set schema_name bd_tst_ec
\i add-index.psql

\set schema_name bd_tst_ed
\i add-index.psql

\set schema_name bd_tst_ee
\i add-index.psql

\set schema_name bd_tst_ef
\i add-index.psql

\set schema_name bd_tst_f0
\i add-index.psql

\set schema_name bd_tst_f1
\i add-index.psql

\set schema_name bd_tst_f2
\i add-index.psql

\set schema_name bd_tst_f3
\i add-index.psql

\set schema_name bd_tst_f4
\i add-index.psql

\set schema_name bd_tst_f5
\i add-index.psql

\set schema_name bd_tst_f6
\i add-index.psql

\set schema_name bd_tst_f7
\i add-index.psql

\set schema_name bd_tst_f8
\i add-index.psql

\set schema_name bd_tst_f9
\i add-index.psql

\set schema_name bd_tst_fa
\i add-index.psql

\set schema_name bd_tst_fb
\i add-index.psql

\set schema_name bd_tst_fc
\i add-index.psql

\set schema_name bd_tst_fd
\i add-index.psql

\set schema_name bd_tst_fe
\i add-index.psql

\set schema_name bd_tst_ff
\i add-index.psql
