-- PG shard 2/4
SET client_min_messages TO WARNING;

\set schema_name bd_tst_80
\i add-seq-id.psql

\set schema_name bd_tst_81
\i add-seq-id.psql

\set schema_name bd_tst_82
\i add-seq-id.psql

\set schema_name bd_tst_83
\i add-seq-id.psql

\set schema_name bd_tst_84
\i add-seq-id.psql

\set schema_name bd_tst_85
\i add-seq-id.psql

\set schema_name bd_tst_86
\i add-seq-id.psql

\set schema_name bd_tst_87
\i add-seq-id.psql

\set schema_name bd_tst_88
\i add-seq-id.psql

\set schema_name bd_tst_89
\i add-seq-id.psql

\set schema_name bd_tst_8a
\i add-seq-id.psql

\set schema_name bd_tst_8b
\i add-seq-id.psql

\set schema_name bd_tst_8c
\i add-seq-id.psql

\set schema_name bd_tst_8d
\i add-seq-id.psql

\set schema_name bd_tst_8e
\i add-seq-id.psql

\set schema_name bd_tst_8f
\i add-seq-id.psql

\set schema_name bd_tst_90
\i add-seq-id.psql

\set schema_name bd_tst_91
\i add-seq-id.psql

\set schema_name bd_tst_92
\i add-seq-id.psql

\set schema_name bd_tst_93
\i add-seq-id.psql

\set schema_name bd_tst_94
\i add-seq-id.psql

\set schema_name bd_tst_95
\i add-seq-id.psql

\set schema_name bd_tst_96
\i add-seq-id.psql

\set schema_name bd_tst_97
\i add-seq-id.psql

\set schema_name bd_tst_98
\i add-seq-id.psql

\set schema_name bd_tst_99
\i add-seq-id.psql

\set schema_name bd_tst_9a
\i add-seq-id.psql

\set schema_name bd_tst_9b
\i add-seq-id.psql

\set schema_name bd_tst_9c
\i add-seq-id.psql

\set schema_name bd_tst_9d
\i add-seq-id.psql

\set schema_name bd_tst_9e
\i add-seq-id.psql

\set schema_name bd_tst_9f
\i add-seq-id.psql

\set schema_name bd_tst_a0
\i add-seq-id.psql

\set schema_name bd_tst_a1
\i add-seq-id.psql

\set schema_name bd_tst_a2
\i add-seq-id.psql

\set schema_name bd_tst_a3
\i add-seq-id.psql

\set schema_name bd_tst_a4
\i add-seq-id.psql

\set schema_name bd_tst_a5
\i add-seq-id.psql

\set schema_name bd_tst_a6
\i add-seq-id.psql

\set schema_name bd_tst_a7
\i add-seq-id.psql

\set schema_name bd_tst_a8
\i add-seq-id.psql

\set schema_name bd_tst_a9
\i add-seq-id.psql

\set schema_name bd_tst_aa
\i add-seq-id.psql

\set schema_name bd_tst_ab
\i add-seq-id.psql

\set schema_name bd_tst_ac
\i add-seq-id.psql

\set schema_name bd_tst_ad
\i add-seq-id.psql

\set schema_name bd_tst_ae
\i add-seq-id.psql

\set schema_name bd_tst_af
\i add-seq-id.psql

\set schema_name bd_tst_b0
\i add-seq-id.psql

\set schema_name bd_tst_b1
\i add-seq-id.psql

\set schema_name bd_tst_b2
\i add-seq-id.psql

\set schema_name bd_tst_b3
\i add-seq-id.psql

\set schema_name bd_tst_b4
\i add-seq-id.psql

\set schema_name bd_tst_b5
\i add-seq-id.psql

\set schema_name bd_tst_b6
\i add-seq-id.psql

\set schema_name bd_tst_b7
\i add-seq-id.psql

\set schema_name bd_tst_b8
\i add-seq-id.psql

\set schema_name bd_tst_b9
\i add-seq-id.psql

\set schema_name bd_tst_ba
\i add-seq-id.psql

\set schema_name bd_tst_bb
\i add-seq-id.psql

\set schema_name bd_tst_bc
\i add-seq-id.psql

\set schema_name bd_tst_bd
\i add-seq-id.psql

\set schema_name bd_tst_be
\i add-seq-id.psql

\set schema_name bd_tst_bf
\i add-seq-id.psql
