-- PG shard 0/4
SET client_min_messages TO WARNING;

\set schema_name ba_tst_00
\i add.psql

\set schema_name ba_tst_01
\i add.psql

\set schema_name ba_tst_02
\i add.psql

\set schema_name ba_tst_03
\i add.psql

\set schema_name ba_tst_04
\i add.psql

\set schema_name ba_tst_05
\i add.psql

\set schema_name ba_tst_06
\i add.psql

\set schema_name ba_tst_07
\i add.psql

\set schema_name ba_tst_08
\i add.psql

\set schema_name ba_tst_09
\i add.psql

\set schema_name ba_tst_0a
\i add.psql

\set schema_name ba_tst_0b
\i add.psql

\set schema_name ba_tst_0c
\i add.psql

\set schema_name ba_tst_0d
\i add.psql

\set schema_name ba_tst_0e
\i add.psql

\set schema_name ba_tst_0f
\i add.psql

\set schema_name ba_tst_10
\i add.psql

\set schema_name ba_tst_11
\i add.psql

\set schema_name ba_tst_12
\i add.psql

\set schema_name ba_tst_13
\i add.psql

\set schema_name ba_tst_14
\i add.psql

\set schema_name ba_tst_15
\i add.psql

\set schema_name ba_tst_16
\i add.psql

\set schema_name ba_tst_17
\i add.psql

\set schema_name ba_tst_18
\i add.psql

\set schema_name ba_tst_19
\i add.psql

\set schema_name ba_tst_1a
\i add.psql

\set schema_name ba_tst_1b
\i add.psql

\set schema_name ba_tst_1c
\i add.psql

\set schema_name ba_tst_1d
\i add.psql

\set schema_name ba_tst_1e
\i add.psql

\set schema_name ba_tst_1f
\i add.psql

\set schema_name ba_tst_20
\i add.psql

\set schema_name ba_tst_21
\i add.psql

\set schema_name ba_tst_22
\i add.psql

\set schema_name ba_tst_23
\i add.psql

\set schema_name ba_tst_24
\i add.psql

\set schema_name ba_tst_25
\i add.psql

\set schema_name ba_tst_26
\i add.psql

\set schema_name ba_tst_27
\i add.psql

\set schema_name ba_tst_28
\i add.psql

\set schema_name ba_tst_29
\i add.psql

\set schema_name ba_tst_2a
\i add.psql

\set schema_name ba_tst_2b
\i add.psql

\set schema_name ba_tst_2c
\i add.psql

\set schema_name ba_tst_2d
\i add.psql

\set schema_name ba_tst_2e
\i add.psql

\set schema_name ba_tst_2f
\i add.psql

\set schema_name ba_tst_30
\i add.psql

\set schema_name ba_tst_31
\i add.psql

\set schema_name ba_tst_32
\i add.psql

\set schema_name ba_tst_33
\i add.psql

\set schema_name ba_tst_34
\i add.psql

\set schema_name ba_tst_35
\i add.psql

\set schema_name ba_tst_36
\i add.psql

\set schema_name ba_tst_37
\i add.psql

\set schema_name ba_tst_38
\i add.psql

\set schema_name ba_tst_39
\i add.psql

\set schema_name ba_tst_3a
\i add.psql

\set schema_name ba_tst_3b
\i add.psql

\set schema_name ba_tst_3c
\i add.psql

\set schema_name ba_tst_3d
\i add.psql

\set schema_name ba_tst_3e
\i add.psql

\set schema_name ba_tst_3f
\i add.psql
