-- PG shard 2/4
SET client_min_messages TO WARNING;
SET lock_timeout TO '30s';

\set schema_name bd_tst_80
\ir ../alter_event_table.psql

\set schema_name bd_tst_81
\ir ../alter_event_table.psql

\set schema_name bd_tst_82
\ir ../alter_event_table.psql

\set schema_name bd_tst_83
\ir ../alter_event_table.psql

\set schema_name bd_tst_84
\ir ../alter_event_table.psql

\set schema_name bd_tst_85
\ir ../alter_event_table.psql

\set schema_name bd_tst_86
\ir ../alter_event_table.psql

\set schema_name bd_tst_87
\ir ../alter_event_table.psql

\set schema_name bd_tst_88
\ir ../alter_event_table.psql

\set schema_name bd_tst_89
\ir ../alter_event_table.psql

\set schema_name bd_tst_8a
\ir ../alter_event_table.psql

\set schema_name bd_tst_8b
\ir ../alter_event_table.psql

\set schema_name bd_tst_8c
\ir ../alter_event_table.psql

\set schema_name bd_tst_8d
\ir ../alter_event_table.psql

\set schema_name bd_tst_8e
\ir ../alter_event_table.psql

\set schema_name bd_tst_8f
\ir ../alter_event_table.psql

\set schema_name bd_tst_90
\ir ../alter_event_table.psql

\set schema_name bd_tst_91
\ir ../alter_event_table.psql

\set schema_name bd_tst_92
\ir ../alter_event_table.psql

\set schema_name bd_tst_93
\ir ../alter_event_table.psql

\set schema_name bd_tst_94
\ir ../alter_event_table.psql

\set schema_name bd_tst_95
\ir ../alter_event_table.psql

\set schema_name bd_tst_96
\ir ../alter_event_table.psql

\set schema_name bd_tst_97
\ir ../alter_event_table.psql

\set schema_name bd_tst_98
\ir ../alter_event_table.psql

\set schema_name bd_tst_99
\ir ../alter_event_table.psql

\set schema_name bd_tst_9a
\ir ../alter_event_table.psql

\set schema_name bd_tst_9b
\ir ../alter_event_table.psql

\set schema_name bd_tst_9c
\ir ../alter_event_table.psql

\set schema_name bd_tst_9d
\ir ../alter_event_table.psql

\set schema_name bd_tst_9e
\ir ../alter_event_table.psql

\set schema_name bd_tst_9f
\ir ../alter_event_table.psql

\set schema_name bd_tst_a0
\ir ../alter_event_table.psql

\set schema_name bd_tst_a1
\ir ../alter_event_table.psql

\set schema_name bd_tst_a2
\ir ../alter_event_table.psql

\set schema_name bd_tst_a3
\ir ../alter_event_table.psql

\set schema_name bd_tst_a4
\ir ../alter_event_table.psql

\set schema_name bd_tst_a5
\ir ../alter_event_table.psql

\set schema_name bd_tst_a6
\ir ../alter_event_table.psql

\set schema_name bd_tst_a7
\ir ../alter_event_table.psql

\set schema_name bd_tst_a8
\ir ../alter_event_table.psql

\set schema_name bd_tst_a9
\ir ../alter_event_table.psql

\set schema_name bd_tst_aa
\ir ../alter_event_table.psql

\set schema_name bd_tst_ab
\ir ../alter_event_table.psql

\set schema_name bd_tst_ac
\ir ../alter_event_table.psql

\set schema_name bd_tst_ad
\ir ../alter_event_table.psql

\set schema_name bd_tst_ae
\ir ../alter_event_table.psql

\set schema_name bd_tst_af
\ir ../alter_event_table.psql

\set schema_name bd_tst_b0
\ir ../alter_event_table.psql

\set schema_name bd_tst_b1
\ir ../alter_event_table.psql

\set schema_name bd_tst_b2
\ir ../alter_event_table.psql

\set schema_name bd_tst_b3
\ir ../alter_event_table.psql

\set schema_name bd_tst_b4
\ir ../alter_event_table.psql

\set schema_name bd_tst_b5
\ir ../alter_event_table.psql

\set schema_name bd_tst_b6
\ir ../alter_event_table.psql

\set schema_name bd_tst_b7
\ir ../alter_event_table.psql

\set schema_name bd_tst_b8
\ir ../alter_event_table.psql

\set schema_name bd_tst_b9
\ir ../alter_event_table.psql

\set schema_name bd_tst_ba
\ir ../alter_event_table.psql

\set schema_name bd_tst_bb
\ir ../alter_event_table.psql

\set schema_name bd_tst_bc
\ir ../alter_event_table.psql

\set schema_name bd_tst_bd
\ir ../alter_event_table.psql

\set schema_name bd_tst_be
\ir ../alter_event_table.psql

\set schema_name bd_tst_bf
\ir ../alter_event_table.psql
