-- PG shard 3/4
SET client_min_messages TO WARNING;
SET lock_timeout TO '30s';

\set schema_name ba_tst_c0
\ir ../alter_journal_table.psql

\set schema_name ba_tst_c1
\ir ../alter_journal_table.psql

\set schema_name ba_tst_c2
\ir ../alter_journal_table.psql

\set schema_name ba_tst_c3
\ir ../alter_journal_table.psql

\set schema_name ba_tst_c4
\ir ../alter_journal_table.psql

\set schema_name ba_tst_c5
\ir ../alter_journal_table.psql

\set schema_name ba_tst_c6
\ir ../alter_journal_table.psql

\set schema_name ba_tst_c7
\ir ../alter_journal_table.psql

\set schema_name ba_tst_c8
\ir ../alter_journal_table.psql

\set schema_name ba_tst_c9
\ir ../alter_journal_table.psql

\set schema_name ba_tst_ca
\ir ../alter_journal_table.psql

\set schema_name ba_tst_cb
\ir ../alter_journal_table.psql

\set schema_name ba_tst_cc
\ir ../alter_journal_table.psql

\set schema_name ba_tst_cd
\ir ../alter_journal_table.psql

\set schema_name ba_tst_ce
\ir ../alter_journal_table.psql

\set schema_name ba_tst_cf
\ir ../alter_journal_table.psql

\set schema_name ba_tst_d0
\ir ../alter_journal_table.psql

\set schema_name ba_tst_d1
\ir ../alter_journal_table.psql

\set schema_name ba_tst_d2
\ir ../alter_journal_table.psql

\set schema_name ba_tst_d3
\ir ../alter_journal_table.psql

\set schema_name ba_tst_d4
\ir ../alter_journal_table.psql

\set schema_name ba_tst_d5
\ir ../alter_journal_table.psql

\set schema_name ba_tst_d6
\ir ../alter_journal_table.psql

\set schema_name ba_tst_d7
\ir ../alter_journal_table.psql

\set schema_name ba_tst_d8
\ir ../alter_journal_table.psql

\set schema_name ba_tst_d9
\ir ../alter_journal_table.psql

\set schema_name ba_tst_da
\ir ../alter_journal_table.psql

\set schema_name ba_tst_db
\ir ../alter_journal_table.psql

\set schema_name ba_tst_dc
\ir ../alter_journal_table.psql

\set schema_name ba_tst_dd
\ir ../alter_journal_table.psql

\set schema_name ba_tst_de
\ir ../alter_journal_table.psql

\set schema_name ba_tst_df
\ir ../alter_journal_table.psql

\set schema_name ba_tst_e0
\ir ../alter_journal_table.psql

\set schema_name ba_tst_e1
\ir ../alter_journal_table.psql

\set schema_name ba_tst_e2
\ir ../alter_journal_table.psql

\set schema_name ba_tst_e3
\ir ../alter_journal_table.psql

\set schema_name ba_tst_e4
\ir ../alter_journal_table.psql

\set schema_name ba_tst_e5
\ir ../alter_journal_table.psql

\set schema_name ba_tst_e6
\ir ../alter_journal_table.psql

\set schema_name ba_tst_e7
\ir ../alter_journal_table.psql

\set schema_name ba_tst_e8
\ir ../alter_journal_table.psql

\set schema_name ba_tst_e9
\ir ../alter_journal_table.psql

\set schema_name ba_tst_ea
\ir ../alter_journal_table.psql

\set schema_name ba_tst_eb
\ir ../alter_journal_table.psql

\set schema_name ba_tst_ec
\ir ../alter_journal_table.psql

\set schema_name ba_tst_ed
\ir ../alter_journal_table.psql

\set schema_name ba_tst_ee
\ir ../alter_journal_table.psql

\set schema_name ba_tst_ef
\ir ../alter_journal_table.psql

\set schema_name ba_tst_f0
\ir ../alter_journal_table.psql

\set schema_name ba_tst_f1
\ir ../alter_journal_table.psql

\set schema_name ba_tst_f2
\ir ../alter_journal_table.psql

\set schema_name ba_tst_f3
\ir ../alter_journal_table.psql

\set schema_name ba_tst_f4
\ir ../alter_journal_table.psql

\set schema_name ba_tst_f5
\ir ../alter_journal_table.psql

\set schema_name ba_tst_f6
\ir ../alter_journal_table.psql

\set schema_name ba_tst_f7
\ir ../alter_journal_table.psql

\set schema_name ba_tst_f8
\ir ../alter_journal_table.psql

\set schema_name ba_tst_f9
\ir ../alter_journal_table.psql

\set schema_name ba_tst_fa
\ir ../alter_journal_table.psql

\set schema_name ba_tst_fb
\ir ../alter_journal_table.psql

\set schema_name ba_tst_fc
\ir ../alter_journal_table.psql

\set schema_name ba_tst_fd
\ir ../alter_journal_table.psql

\set schema_name ba_tst_fe
\ir ../alter_journal_table.psql

\set schema_name ba_tst_ff
\ir ../alter_journal_table.psql
