-- PG shard 3/4
SET client_min_messages TO WARNING;

\set schema_name bd_tst_c0
\i backfill.psql

\set schema_name bd_tst_c1
\i backfill.psql

\set schema_name bd_tst_c2
\i backfill.psql

\set schema_name bd_tst_c3
\i backfill.psql

\set schema_name bd_tst_c4
\i backfill.psql

\set schema_name bd_tst_c5
\i backfill.psql

\set schema_name bd_tst_c6
\i backfill.psql

\set schema_name bd_tst_c7
\i backfill.psql

\set schema_name bd_tst_c8
\i backfill.psql

\set schema_name bd_tst_c9
\i backfill.psql

\set schema_name bd_tst_ca
\i backfill.psql

\set schema_name bd_tst_cb
\i backfill.psql

\set schema_name bd_tst_cc
\i backfill.psql

\set schema_name bd_tst_cd
\i backfill.psql

\set schema_name bd_tst_ce
\i backfill.psql

\set schema_name bd_tst_cf
\i backfill.psql

\set schema_name bd_tst_d0
\i backfill.psql

\set schema_name bd_tst_d1
\i backfill.psql

\set schema_name bd_tst_d2
\i backfill.psql

\set schema_name bd_tst_d3
\i backfill.psql

\set schema_name bd_tst_d4
\i backfill.psql

\set schema_name bd_tst_d5
\i backfill.psql

\set schema_name bd_tst_d6
\i backfill.psql

\set schema_name bd_tst_d7
\i backfill.psql

\set schema_name bd_tst_d8
\i backfill.psql

\set schema_name bd_tst_d9
\i backfill.psql

\set schema_name bd_tst_da
\i backfill.psql

\set schema_name bd_tst_db
\i backfill.psql

\set schema_name bd_tst_dc
\i backfill.psql

\set schema_name bd_tst_dd
\i backfill.psql

\set schema_name bd_tst_de
\i backfill.psql

\set schema_name bd_tst_df
\i backfill.psql

\set schema_name bd_tst_e0
\i backfill.psql

\set schema_name bd_tst_e1
\i backfill.psql

\set schema_name bd_tst_e2
\i backfill.psql

\set schema_name bd_tst_e3
\i backfill.psql

\set schema_name bd_tst_e4
\i backfill.psql

\set schema_name bd_tst_e5
\i backfill.psql

\set schema_name bd_tst_e6
\i backfill.psql

\set schema_name bd_tst_e7
\i backfill.psql

\set schema_name bd_tst_e8
\i backfill.psql

\set schema_name bd_tst_e9
\i backfill.psql

\set schema_name bd_tst_ea
\i backfill.psql

\set schema_name bd_tst_eb
\i backfill.psql

\set schema_name bd_tst_ec
\i backfill.psql

\set schema_name bd_tst_ed
\i backfill.psql

\set schema_name bd_tst_ee
\i backfill.psql

\set schema_name bd_tst_ef
\i backfill.psql

\set schema_name bd_tst_f0
\i backfill.psql

\set schema_name bd_tst_f1
\i backfill.psql

\set schema_name bd_tst_f2
\i backfill.psql

\set schema_name bd_tst_f3
\i backfill.psql

\set schema_name bd_tst_f4
\i backfill.psql

\set schema_name bd_tst_f5
\i backfill.psql

\set schema_name bd_tst_f6
\i backfill.psql

\set schema_name bd_tst_f7
\i backfill.psql

\set schema_name bd_tst_f8
\i backfill.psql

\set schema_name bd_tst_f9
\i backfill.psql

\set schema_name bd_tst_fa
\i backfill.psql

\set schema_name bd_tst_fb
\i backfill.psql

\set schema_name bd_tst_fc
\i backfill.psql

\set schema_name bd_tst_fd
\i backfill.psql

\set schema_name bd_tst_fe
\i backfill.psql

\set schema_name bd_tst_ff
\i backfill.psql
