-- PG shard 1/4
SET client_min_messages TO WARNING;

\set schema_name bd_tst_40
\i change-index.psql

\set schema_name bd_tst_41
\i change-index.psql

\set schema_name bd_tst_42
\i change-index.psql

\set schema_name bd_tst_43
\i change-index.psql

\set schema_name bd_tst_44
\i change-index.psql

\set schema_name bd_tst_45
\i change-index.psql

\set schema_name bd_tst_46
\i change-index.psql

\set schema_name bd_tst_47
\i change-index.psql

\set schema_name bd_tst_48
\i change-index.psql

\set schema_name bd_tst_49
\i change-index.psql

\set schema_name bd_tst_4a
\i change-index.psql

\set schema_name bd_tst_4b
\i change-index.psql

\set schema_name bd_tst_4c
\i change-index.psql

\set schema_name bd_tst_4d
\i change-index.psql

\set schema_name bd_tst_4e
\i change-index.psql

\set schema_name bd_tst_4f
\i change-index.psql

\set schema_name bd_tst_50
\i change-index.psql

\set schema_name bd_tst_51
\i change-index.psql

\set schema_name bd_tst_52
\i change-index.psql

\set schema_name bd_tst_53
\i change-index.psql

\set schema_name bd_tst_54
\i change-index.psql

\set schema_name bd_tst_55
\i change-index.psql

\set schema_name bd_tst_56
\i change-index.psql

\set schema_name bd_tst_57
\i change-index.psql

\set schema_name bd_tst_58
\i change-index.psql

\set schema_name bd_tst_59
\i change-index.psql

\set schema_name bd_tst_5a
\i change-index.psql

\set schema_name bd_tst_5b
\i change-index.psql

\set schema_name bd_tst_5c
\i change-index.psql

\set schema_name bd_tst_5d
\i change-index.psql

\set schema_name bd_tst_5e
\i change-index.psql

\set schema_name bd_tst_5f
\i change-index.psql

\set schema_name bd_tst_60
\i change-index.psql

\set schema_name bd_tst_61
\i change-index.psql

\set schema_name bd_tst_62
\i change-index.psql

\set schema_name bd_tst_63
\i change-index.psql

\set schema_name bd_tst_64
\i change-index.psql

\set schema_name bd_tst_65
\i change-index.psql

\set schema_name bd_tst_66
\i change-index.psql

\set schema_name bd_tst_67
\i change-index.psql

\set schema_name bd_tst_68
\i change-index.psql

\set schema_name bd_tst_69
\i change-index.psql

\set schema_name bd_tst_6a
\i change-index.psql

\set schema_name bd_tst_6b
\i change-index.psql

\set schema_name bd_tst_6c
\i change-index.psql

\set schema_name bd_tst_6d
\i change-index.psql

\set schema_name bd_tst_6e
\i change-index.psql

\set schema_name bd_tst_6f
\i change-index.psql

\set schema_name bd_tst_70
\i change-index.psql

\set schema_name bd_tst_71
\i change-index.psql

\set schema_name bd_tst_72
\i change-index.psql

\set schema_name bd_tst_73
\i change-index.psql

\set schema_name bd_tst_74
\i change-index.psql

\set schema_name bd_tst_75
\i change-index.psql

\set schema_name bd_tst_76
\i change-index.psql

\set schema_name bd_tst_77
\i change-index.psql

\set schema_name bd_tst_78
\i change-index.psql

\set schema_name bd_tst_79
\i change-index.psql

\set schema_name bd_tst_7a
\i change-index.psql

\set schema_name bd_tst_7b
\i change-index.psql

\set schema_name bd_tst_7c
\i change-index.psql

\set schema_name bd_tst_7d
\i change-index.psql

\set schema_name bd_tst_7e
\i change-index.psql

\set schema_name bd_tst_7f
\i change-index.psql
