-- PG shard 3/4
SET client_min_messages TO WARNING;
\i testing/role-names.psql

\set schema_name ba_tst_c0
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_c1
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_c2
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_c3
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_c4
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_c5
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_c6
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_c7
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_c8
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_c9
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_ca
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_cb
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_cc
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_cd
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_ce
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_cf
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_d0
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_d1
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_d2
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_d3
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_d4
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_d5
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_d6
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_d7
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_d8
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_d9
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_da
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_db
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_dc
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_dd
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_de
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_df
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_e0
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_e1
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_e2
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_e3
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_e4
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_e5
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_e6
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_e7
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_e8
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_e9
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_ea
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_eb
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_ec
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_ed
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_ee
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_ef
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_f0
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_f1
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_f2
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_f3
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_f4
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_f5
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_f6
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_f7
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_f8
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_f9
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_fa
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_fb
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_fc
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_fd
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_fe
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_ff
\i create-journal-replication-chunks-table.psql
