-- PG shard 1/4
SET client_min_messages TO WARNING;
\i testing/role-names.psql

\set schema_name ba_tst_40
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_41
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_42
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_43
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_44
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_45
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_46
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_47
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_48
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_49
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_4a
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_4b
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_4c
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_4d
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_4e
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_4f
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_50
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_51
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_52
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_53
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_54
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_55
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_56
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_57
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_58
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_59
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_5a
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_5b
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_5c
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_5d
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_5e
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_5f
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_60
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_61
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_62
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_63
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_64
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_65
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_66
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_67
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_68
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_69
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_6a
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_6b
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_6c
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_6d
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_6e
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_6f
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_70
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_71
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_72
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_73
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_74
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_75
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_76
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_77
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_78
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_79
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_7a
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_7b
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_7c
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_7d
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_7e
\i create-journal-replication-chunks-table.psql

\set schema_name ba_tst_7f
\i create-journal-replication-chunks-table.psql
