
        -- PG shard 3/3
        SET client_min_messages TO WARNING;

        -- Setup all global variables, roles and meta
        \set suffix tst_
        \ir ../../../schema/00.vars.psql
        \set role_ro  qa_billing_ro
        \set role_svc qa_billing_svc
        \set role_arc qa_billing_arc
        \ir ../../../schema/01.roles.psql
        \ir ../../../schema/meta.ddl.psql

            \set bd_vshard :bd_vshard_pfx c0
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx c1
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx c2
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx c3
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx c4
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx c5
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx c6
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx c7
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx c8
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx c9
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx ca
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx cb
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx cc
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx cd
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx ce
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx cf
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx d0
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx d1
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx d2
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx d3
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx d4
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx d5
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx d6
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx d7
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx d8
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx d9
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx da
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx db
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx dc
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx dd
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx de
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx df
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx e0
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx e1
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx e2
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx e3
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx e4
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx e5
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx e6
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx e7
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx e8
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx e9
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx ea
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx eb
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx ec
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx ed
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx ee
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx ef
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx f0
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx f1
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx f2
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx f3
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx f4
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx f5
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx f6
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx f7
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx f8
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx f9
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx fa
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx fb
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx fc
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx fd
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx fe
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx ff
            \ir ../../../schema/create.vshard.psql
