
        -- PG shard 1/3
        SET client_min_messages TO WARNING;

        -- Setup all global variables, roles and meta
        \set suffix tst_
        \ir ../../../schema/00.vars.psql
        \set role_ro  qa_billing_ro
        \set role_svc qa_billing_svc
        \set role_arc qa_billing_arc
        \ir ../../../schema/01.roles.psql
        \ir ../../../schema/meta.ddl.psql

            \set bd_vshard :bd_vshard_pfx 40
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 41
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 42
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 43
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 44
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 45
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 46
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 47
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 48
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 49
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 4a
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 4b
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 4c
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 4d
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 4e
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 4f
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 50
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 51
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 52
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 53
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 54
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 55
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 56
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 57
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 58
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 59
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 5a
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 5b
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 5c
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 5d
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 5e
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 5f
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 60
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 61
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 62
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 63
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 64
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 65
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 66
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 67
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 68
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 69
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 6a
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 6b
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 6c
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 6d
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 6e
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 6f
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 70
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 71
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 72
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 73
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 74
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 75
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 76
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 77
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 78
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 79
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 7a
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 7b
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 7c
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 7d
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 7e
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 7f
            \ir ../../../schema/create.vshard.psql
