
        -- PG shard 0/3
        SET client_min_messages TO WARNING;

        -- Setup all global variables, roles and meta
        \set suffix tst_
        \ir ../../../schema/00.vars.psql
        \set role_ro  qa_billing_ro
        \set role_svc qa_billing_svc
        \set role_arc qa_billing_arc
        \ir ../../../schema/01.roles.psql
        \ir ../../../schema/meta.ddl.psql

            \set bd_vshard :bd_vshard_pfx 00
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 01
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 02
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 03
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 04
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 05
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 06
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 07
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 08
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 09
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 0a
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 0b
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 0c
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 0d
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 0e
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 0f
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 10
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 11
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 12
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 13
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 14
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 15
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 16
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 17
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 18
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 19
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 1a
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 1b
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 1c
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 1d
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 1e
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 1f
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 20
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 21
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 22
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 23
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 24
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 25
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 26
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 27
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 28
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 29
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 2a
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 2b
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 2c
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 2d
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 2e
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 2f
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 30
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 31
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 32
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 33
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 34
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 35
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 36
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 37
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 38
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 39
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 3a
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 3b
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 3c
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 3d
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 3e
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 3f
            \ir ../../../schema/create.vshard.psql
