
        -- PG shard 2/3
        SET client_min_messages TO WARNING;

        -- Setup all global variables, roles and meta
        \set suffix tst_
        \ir ../../../schema/00.vars.psql
        \set role_ro  qa_billing_ro
        \set role_svc qa_billing_svc
        \set role_arc qa_billing_arc
        \ir ../../../schema/01.roles.psql
        \ir ../../../schema/meta.ddl.psql

            \set bd_vshard :bd_vshard_pfx 80
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 81
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 82
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 83
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 84
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 85
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 86
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 87
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 88
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 89
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 8a
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 8b
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 8c
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 8d
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 8e
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 8f
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 90
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 91
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 92
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 93
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 94
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 95
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 96
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 97
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 98
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 99
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 9a
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 9b
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 9c
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 9d
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 9e
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx 9f
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx a0
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx a1
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx a2
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx a3
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx a4
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx a5
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx a6
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx a7
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx a8
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx a9
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx aa
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx ab
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx ac
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx ad
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx ae
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx af
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx b0
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx b1
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx b2
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx b3
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx b4
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx b5
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx b6
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx b7
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx b8
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx b9
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx ba
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx bb
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx bc
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx bd
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx be
            \ir ../../../schema/create.vshard.psql

            \set bd_vshard :bd_vshard_pfx bf
            \ir ../../../schema/create.vshard.psql
