-- PG shard 0/4
SET client_min_messages TO WARNING;
\i testing/role-names.psql

\set schema_name ba_tst_00
\i recreate-table.psql

\set schema_name ba_tst_01
\i recreate-table.psql

\set schema_name ba_tst_02
\i recreate-table.psql

\set schema_name ba_tst_03
\i recreate-table.psql

\set schema_name ba_tst_04
\i recreate-table.psql

\set schema_name ba_tst_05
\i recreate-table.psql

\set schema_name ba_tst_06
\i recreate-table.psql

\set schema_name ba_tst_07
\i recreate-table.psql

\set schema_name ba_tst_08
\i recreate-table.psql

\set schema_name ba_tst_09
\i recreate-table.psql

\set schema_name ba_tst_0a
\i recreate-table.psql

\set schema_name ba_tst_0b
\i recreate-table.psql

\set schema_name ba_tst_0c
\i recreate-table.psql

\set schema_name ba_tst_0d
\i recreate-table.psql

\set schema_name ba_tst_0e
\i recreate-table.psql

\set schema_name ba_tst_0f
\i recreate-table.psql

\set schema_name ba_tst_10
\i recreate-table.psql

\set schema_name ba_tst_11
\i recreate-table.psql

\set schema_name ba_tst_12
\i recreate-table.psql

\set schema_name ba_tst_13
\i recreate-table.psql

\set schema_name ba_tst_14
\i recreate-table.psql

\set schema_name ba_tst_15
\i recreate-table.psql

\set schema_name ba_tst_16
\i recreate-table.psql

\set schema_name ba_tst_17
\i recreate-table.psql

\set schema_name ba_tst_18
\i recreate-table.psql

\set schema_name ba_tst_19
\i recreate-table.psql

\set schema_name ba_tst_1a
\i recreate-table.psql

\set schema_name ba_tst_1b
\i recreate-table.psql

\set schema_name ba_tst_1c
\i recreate-table.psql

\set schema_name ba_tst_1d
\i recreate-table.psql

\set schema_name ba_tst_1e
\i recreate-table.psql

\set schema_name ba_tst_1f
\i recreate-table.psql

\set schema_name ba_tst_20
\i recreate-table.psql

\set schema_name ba_tst_21
\i recreate-table.psql

\set schema_name ba_tst_22
\i recreate-table.psql

\set schema_name ba_tst_23
\i recreate-table.psql

\set schema_name ba_tst_24
\i recreate-table.psql

\set schema_name ba_tst_25
\i recreate-table.psql

\set schema_name ba_tst_26
\i recreate-table.psql

\set schema_name ba_tst_27
\i recreate-table.psql

\set schema_name ba_tst_28
\i recreate-table.psql

\set schema_name ba_tst_29
\i recreate-table.psql

\set schema_name ba_tst_2a
\i recreate-table.psql

\set schema_name ba_tst_2b
\i recreate-table.psql

\set schema_name ba_tst_2c
\i recreate-table.psql

\set schema_name ba_tst_2d
\i recreate-table.psql

\set schema_name ba_tst_2e
\i recreate-table.psql

\set schema_name ba_tst_2f
\i recreate-table.psql

\set schema_name ba_tst_30
\i recreate-table.psql

\set schema_name ba_tst_31
\i recreate-table.psql

\set schema_name ba_tst_32
\i recreate-table.psql

\set schema_name ba_tst_33
\i recreate-table.psql

\set schema_name ba_tst_34
\i recreate-table.psql

\set schema_name ba_tst_35
\i recreate-table.psql

\set schema_name ba_tst_36
\i recreate-table.psql

\set schema_name ba_tst_37
\i recreate-table.psql

\set schema_name ba_tst_38
\i recreate-table.psql

\set schema_name ba_tst_39
\i recreate-table.psql

\set schema_name ba_tst_3a
\i recreate-table.psql

\set schema_name ba_tst_3b
\i recreate-table.psql

\set schema_name ba_tst_3c
\i recreate-table.psql

\set schema_name ba_tst_3d
\i recreate-table.psql

\set schema_name ba_tst_3e
\i recreate-table.psql

\set schema_name ba_tst_3f
\i recreate-table.psql
