-- PG shard 2/4
SET client_min_messages TO WARNING;
\i testing/role-names.psql

\set schema_name ba_tst_80
\i recreate-table.psql

\set schema_name ba_tst_81
\i recreate-table.psql

\set schema_name ba_tst_82
\i recreate-table.psql

\set schema_name ba_tst_83
\i recreate-table.psql

\set schema_name ba_tst_84
\i recreate-table.psql

\set schema_name ba_tst_85
\i recreate-table.psql

\set schema_name ba_tst_86
\i recreate-table.psql

\set schema_name ba_tst_87
\i recreate-table.psql

\set schema_name ba_tst_88
\i recreate-table.psql

\set schema_name ba_tst_89
\i recreate-table.psql

\set schema_name ba_tst_8a
\i recreate-table.psql

\set schema_name ba_tst_8b
\i recreate-table.psql

\set schema_name ba_tst_8c
\i recreate-table.psql

\set schema_name ba_tst_8d
\i recreate-table.psql

\set schema_name ba_tst_8e
\i recreate-table.psql

\set schema_name ba_tst_8f
\i recreate-table.psql

\set schema_name ba_tst_90
\i recreate-table.psql

\set schema_name ba_tst_91
\i recreate-table.psql

\set schema_name ba_tst_92
\i recreate-table.psql

\set schema_name ba_tst_93
\i recreate-table.psql

\set schema_name ba_tst_94
\i recreate-table.psql

\set schema_name ba_tst_95
\i recreate-table.psql

\set schema_name ba_tst_96
\i recreate-table.psql

\set schema_name ba_tst_97
\i recreate-table.psql

\set schema_name ba_tst_98
\i recreate-table.psql

\set schema_name ba_tst_99
\i recreate-table.psql

\set schema_name ba_tst_9a
\i recreate-table.psql

\set schema_name ba_tst_9b
\i recreate-table.psql

\set schema_name ba_tst_9c
\i recreate-table.psql

\set schema_name ba_tst_9d
\i recreate-table.psql

\set schema_name ba_tst_9e
\i recreate-table.psql

\set schema_name ba_tst_9f
\i recreate-table.psql

\set schema_name ba_tst_a0
\i recreate-table.psql

\set schema_name ba_tst_a1
\i recreate-table.psql

\set schema_name ba_tst_a2
\i recreate-table.psql

\set schema_name ba_tst_a3
\i recreate-table.psql

\set schema_name ba_tst_a4
\i recreate-table.psql

\set schema_name ba_tst_a5
\i recreate-table.psql

\set schema_name ba_tst_a6
\i recreate-table.psql

\set schema_name ba_tst_a7
\i recreate-table.psql

\set schema_name ba_tst_a8
\i recreate-table.psql

\set schema_name ba_tst_a9
\i recreate-table.psql

\set schema_name ba_tst_aa
\i recreate-table.psql

\set schema_name ba_tst_ab
\i recreate-table.psql

\set schema_name ba_tst_ac
\i recreate-table.psql

\set schema_name ba_tst_ad
\i recreate-table.psql

\set schema_name ba_tst_ae
\i recreate-table.psql

\set schema_name ba_tst_af
\i recreate-table.psql

\set schema_name ba_tst_b0
\i recreate-table.psql

\set schema_name ba_tst_b1
\i recreate-table.psql

\set schema_name ba_tst_b2
\i recreate-table.psql

\set schema_name ba_tst_b3
\i recreate-table.psql

\set schema_name ba_tst_b4
\i recreate-table.psql

\set schema_name ba_tst_b5
\i recreate-table.psql

\set schema_name ba_tst_b6
\i recreate-table.psql

\set schema_name ba_tst_b7
\i recreate-table.psql

\set schema_name ba_tst_b8
\i recreate-table.psql

\set schema_name ba_tst_b9
\i recreate-table.psql

\set schema_name ba_tst_ba
\i recreate-table.psql

\set schema_name ba_tst_bb
\i recreate-table.psql

\set schema_name ba_tst_bc
\i recreate-table.psql

\set schema_name ba_tst_bd
\i recreate-table.psql

\set schema_name ba_tst_be
\i recreate-table.psql

\set schema_name ba_tst_bf
\i recreate-table.psql
