-- PG shard 0/8
SET client_min_messages TO WARNING;

\set schema_name bd_tst_00
\ir ../remove_index.psql

\set schema_name bd_tst_01
\ir ../remove_index.psql

\set schema_name bd_tst_02
\ir ../remove_index.psql

\set schema_name bd_tst_03
\ir ../remove_index.psql

\set schema_name bd_tst_04
\ir ../remove_index.psql

\set schema_name bd_tst_05
\ir ../remove_index.psql

\set schema_name bd_tst_06
\ir ../remove_index.psql

\set schema_name bd_tst_07
\ir ../remove_index.psql

\set schema_name bd_tst_08
\ir ../remove_index.psql

\set schema_name bd_tst_09
\ir ../remove_index.psql

\set schema_name bd_tst_0a
\ir ../remove_index.psql

\set schema_name bd_tst_0b
\ir ../remove_index.psql

\set schema_name bd_tst_0c
\ir ../remove_index.psql

\set schema_name bd_tst_0d
\ir ../remove_index.psql

\set schema_name bd_tst_0e
\ir ../remove_index.psql

\set schema_name bd_tst_0f
\ir ../remove_index.psql

\set schema_name bd_tst_10
\ir ../remove_index.psql

\set schema_name bd_tst_11
\ir ../remove_index.psql

\set schema_name bd_tst_12
\ir ../remove_index.psql

\set schema_name bd_tst_13
\ir ../remove_index.psql

\set schema_name bd_tst_14
\ir ../remove_index.psql

\set schema_name bd_tst_15
\ir ../remove_index.psql

\set schema_name bd_tst_16
\ir ../remove_index.psql

\set schema_name bd_tst_17
\ir ../remove_index.psql

\set schema_name bd_tst_18
\ir ../remove_index.psql

\set schema_name bd_tst_19
\ir ../remove_index.psql

\set schema_name bd_tst_1a
\ir ../remove_index.psql

\set schema_name bd_tst_1b
\ir ../remove_index.psql

\set schema_name bd_tst_1c
\ir ../remove_index.psql

\set schema_name bd_tst_1d
\ir ../remove_index.psql

\set schema_name bd_tst_1e
\ir ../remove_index.psql

\set schema_name bd_tst_1f
\ir ../remove_index.psql

\set schema_name bd_tst_20
\ir ../remove_index.psql

\set schema_name bd_tst_21
\ir ../remove_index.psql

\set schema_name bd_tst_22
\ir ../remove_index.psql

\set schema_name bd_tst_23
\ir ../remove_index.psql

\set schema_name bd_tst_24
\ir ../remove_index.psql

\set schema_name bd_tst_25
\ir ../remove_index.psql

\set schema_name bd_tst_26
\ir ../remove_index.psql

\set schema_name bd_tst_27
\ir ../remove_index.psql

\set schema_name bd_tst_28
\ir ../remove_index.psql

\set schema_name bd_tst_29
\ir ../remove_index.psql

\set schema_name bd_tst_2a
\ir ../remove_index.psql

\set schema_name bd_tst_2b
\ir ../remove_index.psql

\set schema_name bd_tst_2c
\ir ../remove_index.psql

\set schema_name bd_tst_2d
\ir ../remove_index.psql

\set schema_name bd_tst_2e
\ir ../remove_index.psql

\set schema_name bd_tst_2f
\ir ../remove_index.psql

\set schema_name bd_tst_30
\ir ../remove_index.psql

\set schema_name bd_tst_31
\ir ../remove_index.psql

\set schema_name bd_tst_32
\ir ../remove_index.psql

\set schema_name bd_tst_33
\ir ../remove_index.psql

\set schema_name bd_tst_34
\ir ../remove_index.psql

\set schema_name bd_tst_35
\ir ../remove_index.psql

\set schema_name bd_tst_36
\ir ../remove_index.psql

\set schema_name bd_tst_37
\ir ../remove_index.psql

\set schema_name bd_tst_38
\ir ../remove_index.psql

\set schema_name bd_tst_39
\ir ../remove_index.psql

\set schema_name bd_tst_3a
\ir ../remove_index.psql

\set schema_name bd_tst_3b
\ir ../remove_index.psql

\set schema_name bd_tst_3c
\ir ../remove_index.psql

\set schema_name bd_tst_3d
\ir ../remove_index.psql

\set schema_name bd_tst_3e
\ir ../remove_index.psql

\set schema_name bd_tst_3f
\ir ../remove_index.psql
