-- PG shard 1/4
SET client_min_messages TO WARNING;

\set schema_name bd_tst_40
\i reset.psql

\set schema_name bd_tst_41
\i reset.psql

\set schema_name bd_tst_42
\i reset.psql

\set schema_name bd_tst_43
\i reset.psql

\set schema_name bd_tst_44
\i reset.psql

\set schema_name bd_tst_45
\i reset.psql

\set schema_name bd_tst_46
\i reset.psql

\set schema_name bd_tst_47
\i reset.psql

\set schema_name bd_tst_48
\i reset.psql

\set schema_name bd_tst_49
\i reset.psql

\set schema_name bd_tst_4a
\i reset.psql

\set schema_name bd_tst_4b
\i reset.psql

\set schema_name bd_tst_4c
\i reset.psql

\set schema_name bd_tst_4d
\i reset.psql

\set schema_name bd_tst_4e
\i reset.psql

\set schema_name bd_tst_4f
\i reset.psql

\set schema_name bd_tst_50
\i reset.psql

\set schema_name bd_tst_51
\i reset.psql

\set schema_name bd_tst_52
\i reset.psql

\set schema_name bd_tst_53
\i reset.psql

\set schema_name bd_tst_54
\i reset.psql

\set schema_name bd_tst_55
\i reset.psql

\set schema_name bd_tst_56
\i reset.psql

\set schema_name bd_tst_57
\i reset.psql

\set schema_name bd_tst_58
\i reset.psql

\set schema_name bd_tst_59
\i reset.psql

\set schema_name bd_tst_5a
\i reset.psql

\set schema_name bd_tst_5b
\i reset.psql

\set schema_name bd_tst_5c
\i reset.psql

\set schema_name bd_tst_5d
\i reset.psql

\set schema_name bd_tst_5e
\i reset.psql

\set schema_name bd_tst_5f
\i reset.psql

\set schema_name bd_tst_60
\i reset.psql

\set schema_name bd_tst_61
\i reset.psql

\set schema_name bd_tst_62
\i reset.psql

\set schema_name bd_tst_63
\i reset.psql

\set schema_name bd_tst_64
\i reset.psql

\set schema_name bd_tst_65
\i reset.psql

\set schema_name bd_tst_66
\i reset.psql

\set schema_name bd_tst_67
\i reset.psql

\set schema_name bd_tst_68
\i reset.psql

\set schema_name bd_tst_69
\i reset.psql

\set schema_name bd_tst_6a
\i reset.psql

\set schema_name bd_tst_6b
\i reset.psql

\set schema_name bd_tst_6c
\i reset.psql

\set schema_name bd_tst_6d
\i reset.psql

\set schema_name bd_tst_6e
\i reset.psql

\set schema_name bd_tst_6f
\i reset.psql

\set schema_name bd_tst_70
\i reset.psql

\set schema_name bd_tst_71
\i reset.psql

\set schema_name bd_tst_72
\i reset.psql

\set schema_name bd_tst_73
\i reset.psql

\set schema_name bd_tst_74
\i reset.psql

\set schema_name bd_tst_75
\i reset.psql

\set schema_name bd_tst_76
\i reset.psql

\set schema_name bd_tst_77
\i reset.psql

\set schema_name bd_tst_78
\i reset.psql

\set schema_name bd_tst_79
\i reset.psql

\set schema_name bd_tst_7a
\i reset.psql

\set schema_name bd_tst_7b
\i reset.psql

\set schema_name bd_tst_7c
\i reset.psql

\set schema_name bd_tst_7d
\i reset.psql

\set schema_name bd_tst_7e
\i reset.psql

\set schema_name bd_tst_7f
\i reset.psql
