-- PG shard 0/4
SET client_min_messages TO WARNING;
SET lock_timeout TO '30s';

\set role_ro  qa_billing_ro
\set role_arc qa_billing_arc

\set schema_name ba_tst_00
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_01
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_02
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_03
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_04
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_05
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_06
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_07
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_08
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_09
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_0a
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_0b
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_0c
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_0d
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_0e
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_0f
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_10
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_11
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_12
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_13
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_14
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_15
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_16
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_17
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_18
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_19
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_1a
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_1b
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_1c
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_1d
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_1e
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_1f
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_20
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_21
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_22
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_23
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_24
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_25
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_26
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_27
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_28
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_29
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_2a
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_2b
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_2c
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_2d
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_2e
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_2f
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_30
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_31
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_32
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_33
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_34
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_35
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_36
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_37
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_38
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_39
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_3a
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_3b
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_3c
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_3d
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_3e
\ir ../balance_replicaion_chunks.psql

\set schema_name ba_tst_3f
\ir ../balance_replicaion_chunks.psql
