-- noinspection SqlInsertValues

INSERT INTO basic_counter_stat
SELECT intDiv(CounterID, 100),
       today(),
       arrayReduce('sumState', [toInt8(42)]) as Visits,
       arrayReduce('sumState', [intDiv(PageViewsSum, 100000000000)]) as PageViewsSum,
       arrayReduce('sumState', [intDiv(SumTime, 100000000000)]) as SumTime,
       arrayReduce('sumIfState', [OneHour], [1]) as OneHour,
       arrayReduce('uniqIfState', [intDiv(NewUsers, 100000000000)], [1]) as NewUsers,
       arrayReduce('uniqState', [intDiv(`Users`, 100000000000)]) as `Users`,
       arrayReduce('sumState', [intDiv(GoalsReached, 100000000000)]) as GoalsReached,
       arrayReduce('maxState', [RecountRequestID]) as RecountRequestID,
       IsRobot,
       arrayReduce('sumState', [toInt8(111)]) as NoRobotVisits,
       arrayReduce('sumState', [intDiv(NoRobotPageViewsSum, 100000000000)]) as NoRobotPageViewsSum,
       arrayReduce('sumState', [intDiv(NoRobotSumTime, 100000000000)]) as NoRobotSumTime,
       arrayReduce('sumIfState', [intDiv(NoRobotOneHour, 100)], [1]) as NoRobotOneHour,
       arrayReduce('uniqIfState', [intDiv(NoRobotNewUsers, 100)], [1]) as NoRobotNewUsers,
       arrayReduce('uniqIfState', [intDiv(NoRobotUsers, 100000000000)], [1]) as NoRobotUsers,
       arrayReduce('sumState', [intDiv(NoRobotGoalsReached, 100000000000)]) as NoRobotGoalsReached,
       arrayReduce('sumIfState', [intDiv(HttpVisits, 100)], [1]) as HttpVisits,
       arrayReduce('sumIfState', [intDiv(HttpsVisits, 100)], [1]) as HttpsVisits,
       arrayReduce('sumIfState', [intDiv(NoRobotHttpVisits, 100)], [1]) as NoRobotHttpVisits,
       arrayReduce('sumIfState', [intDiv(NoRobotHttpsVisits, 100)], [1]) as NoRobotHttpsVisits
FROM generateRandom('`CounterID` UInt32,
    `StartDate` Date,
    `Visits` Int8,
    `PageViewsSum` Int64,
    `SumTime` Int64,
    `OneHour` Int8,
    `NewUsers` UInt64,
    `Users` UInt64,
    `GoalsReached` Int64,
    `RecountRequestID` String,
    `IsRobot` UInt8,
    `NoRobotVisits` Int8,
    `NoRobotPageViewsSum` Int64,
    `NoRobotSumTime` Int64,
    `NoRobotOneHour` Int8,
    `NoRobotNewUsers` UInt64,
    `NoRobotUsers` UInt64,
    `NoRobotGoalsReached` Int64,
    `HttpVisits` Int8,
    `HttpsVisits` Int8,
    `NoRobotHttpVisits` Int8,
    `NoRobotHttpsVisits` Int8', 1, 10, 2)
WHERE CounterID < exp10(9)
LIMIT %{numberOfRows};
