import maintenance.etl.backfilling.taxi_ods_orders.loader as loader


def test_data_processor():
    order_proc_data = [
        {
            'order_created': '2019-12-03 10:00:00',
            'id': '07a00f61544e3418bc2fc6604c330eb8',
            'doc': {'_id': '07a00f61544e3418bc2fc6604c330eb8',
                    '_shard_id': 7,
                    'aliases': [{'due': '2019-12-03 10:04:00.000000',
                                 'due_optimistic': None,
                                 'generation': 1,
                                 'id': 'bb1459129f5f3c639d0dcc85cde7f49c'}],
                    'candidates': [{'adjusted_point': {'avg_speed': -1,
                                                       'direction': 113,
                                                       'geopoint': [37.439057,
                                                                    55.822931999999994],
                                                       'time': 1575367190},
                                    'alias_id': 'bb1459129f5f3c639d0dcc85cde7f49c',
                                    'ar': 1.0,
                                    'car_color': '\xd0\xb1\xd0\xb5\xd0\xbb\xd1\x8b\xd0\xb9',
                                    'car_color_code': 'FAFBFB',
                                    'car_model': 'Kia Rio',
                                    'car_number': 'car-number-1',
                                    'ci': '65123e26844d4c989f90bb3f14108d2b',
                                    'cr': 1.0,
                                    'created': '2019-12-03 10:00:04.102000',
                                    'db_id': '20f39e832b184e939dfc493c2a78f93f',
                                    'dbcar_id': '8173a0eec71e8e6fdfdb68eaa82974ea',
                                    'discount': {},
                                    'dist': 1834,
                                    'dp_values': {'a': -16,
                                                  'c': 1,
                                                  'd': 0,
                                                  'm': 0,
                                                  'n': -6,
                                                  'o': -6,
                                                  'p': -6,
                                                  'r': -6,
                                                  's': 0,
                                                  't': 0,
                                                  'u': 0,
                                                  'w': 0},
                                    'driver_classes': ['econom',
                                                       'uberx',
                                                       'ubernight'],
                                    'driver_eta': '2019-12-03 10:02:56.103000',
                                    'driver_experiments': ['yandex_support_chat_webview',
                                                           'xiaomi_crutch',
                                                           ],
                                    'driver_id': '400000001483_f141da70c0fc4b2bb7d4e4fc5cbfac05',
                                    'driver_license': 'test_driver_license',
                                    'driver_license_personal_id': 'fcda32d38fc542eb91f58ecb1b99a1b5',
                                    'driver_metrics': {'activity': 100,
                                                       'activity_blocking': {'activity_threshold': 11,
                                                                             'duration_sec': 3600},
                                                       'activity_prediction': {'a': -16,
                                                                               'c': 1,
                                                                               'd': 0,
                                                                               'm': 0,
                                                                               'n': -6,
                                                                               'o': -6,
                                                                               'p': -6,
                                                                               'r': -6,
                                                                               's': 0,
                                                                               't': 0,
                                                                               'u': 0,
                                                                               'w': 0},
                                                       'dispatch': 'short',
                                                       'id': '07a00f61544e3418bc2fc6604c330eb8',
                                                       'properties': ['dispatch_short'],
                                                       'type': 'dm_service'},
                                    'driver_points': 100,
                                    'driverclientchat_enabled': True,
                                    'driverclientchat_translate_enabled': True,
                                    'experiments': ['proxy_gps_set_to_geotracks',
                                                    'order_show_comment',
                                                    ],
                                    'experiments3': {'exclude_dist_and_time_left_chain': {}},
                                    'first_name': 'test-first-name',
                                    'forwarding': {'ext': '4569',
                                                   'phone': '+79942222222'},
                                    'gprs_time': 20.0,
                                    'hd': True,
                                    'is': True,
                                    'line_dist': 997,
                                    'name': 'test candidate 1 name',
                                    'order_allowed_classes': ['uberx'],
                                    'ost': '2019-12-03 10:00:06.129000',
                                    'paid_supply': False,
                                    'phone': '+79670000000',
                                    'phone_personal_id': '746956ce56714393a8a11cdcfec3a7c1',
                                    'point': [37.439057, 55.822931999999994],
                                    'push_on_driver_arriving_send_at_eta': None,
                                    'push_on_driver_arriving_sent': None,
                                    'rd': True,
                                    'setcared': '2019-12-03 10:00:06.129000',
                                    'subvention_geoareas': [{'_id': '4a6ea914d3ac405fbb3cddfc64096663',
                                                             'created': '2018-09-03 18:34:58.054000',
                                                             'name': 'msk-polygon-4'},
                                                            {'_id': 'bb65572017614f8b8c4b7659a8bdc641',
                                                             'created': '2019-08-30 08:20:01.663000',
                                                             'name': 'msc-2sept-1'},
                                                            {'_id': 'b7e490e9c7f747fe887b487ddf7a1fd6',
                                                             'created': '2019-06-14 12:57:05.024000',
                                                             'name': 'msk-spartak0'},
                                                            {'_id': 'c1b54c94739546ccad214e76d810f7b9',
                                                             'created': '2018-12-27 12:35:52.128000',
                                                             'name': 'msk-tag-pol_1'}],
                                    'tags': ['bru_rusfraud',
                                             'bank_cards_banners',
                                             'loyalty_partners_banner',
                                             'silver',
                                             'support_driver_novice',
                                             'recent_tariff_econom'],
                                    'tariff_class': 'uberx',
                                    'tariff_currency': 'RUB',
                                    'tariff_id': '65123e26844d4c989f90bb3f14108d2b',
                                    'taximeter_version': '9.18',
                                    'time': 172,
                                    'udid': '5baa5c6f41e102a72f3e5607',
                                    'z': ['01e6b48421754e4e95d102873a4827c8',
                                          '052d1a4431b2487487dc95550bd3430a',
                                          '1f121111472a45e9bcbb7c72200c6340',
                                          '2ecf2f96e5b340bd97654c82b48eaa3c',
                                          '4348f5f6e84d4fde8bcee46b77dd0b0d',
                                          '48b2d2bbf6284a8fb2507eae80f076b7',
                                          '70ef1ee0efd142a78db526e9f75defec',
                                          '7c64e39b00c241a5ae015ce07bccdd79',
                                          '894c08769c1a443c85a90a7fc484e8de',
                                          '8a97a2ca3ee3421aa96ca72afee7a35e',
                                          '8f2b98a666b4437fbbaaeadab7f5566a',
                                          'b17c2eabb7e34928a202edc7694ba98b',
                                          'bca9b71aa10f4a5cb3fed9f2a24a8dd1',
                                          'dbff41b3669d4a99b336f235972a8725',
                                          'eb825a9f01754789b4435d1bf72bd033',
                                          'f029e9f33b8945889dffc4295b6d6e27',
                                          'f903fad6a40b4860929e4befb89ccab1',
                                          'fdb3759eabaf474faf2eada4a08ad5af']}],
                    'commit_state': 'done',
                    'created': '2019-12-03 10:00:00.750000',
                    'extra_data': {'overdraft': {'overdraft_order': False,
                                                 'phone_hash': '8bdc1881ede1a8462bebfb8e38c8cc92'}},
                    'free_cancel_for_reason': False,
                    'fwd_driver_phone': True,
                    'insurer_id': '83d0d8e57b9242f7a7968653ecfe490b',
                    'lookup': {'eta': '2019-12-03 10:00:01.854000',
                               'generation': 1,
                               'generation_updated': '2019-12-03 10:00:01.854000',
                               'name': 'direct_assignment',
                               'need_start': False,
                               'params': {},
                               'restart_eta': None,
                               'state': {'excluded_licenses_for_phone': ['7706441044'],
                                         'next_call_eta': None,
                                         'wave': 2},
                               'version': 3},
                    'order': {'_id': '07a00f61544e3418bc2fc6604c330eb8',
                              '_shard_id': 7,
                              '_type': 'soon',
                              'application': 'uber_android',
                              'billing_contract': {'acquiring_percent': '0',
                                                   'currency': 'RUB',
                                                   'currency_rate': '1',
                                                   'donate_discounts_multiplier': '1.00',
                                                   'donate_multiplier': '1',
                                                   'ind_bel_nds_percent': None,
                                                   'is_set': True,
                                                   'max_cost_for_commission': '15000',
                                                   'offer_currency': 'RUB',
                                                   'offer_currency_rate': '1',
                                                   'rebate_percent': '0',
                                                   'subventions_hold_delay': 0},
                              'billing_tech': {'compensations': [],
                                               'refresh_attempts_count': 0,
                                               'service_orders': {'ride': None,
                                                                  'tips': None},
                                               'transactions': [],
                                               'version': 1},
                              'calc': {'allowed_tariffs': {'__park__': {'uberblack': 437.0,
                                                                        'uberkids': 287.0,
                                                                        'uberlux': 875.0,
                                                                        'uberselect': 201.0,
                                                                        'uberselectplus': 274.0,
                                                                        'ubervan': 333.0,
                                                                        'uberx': 142.014201420142}},
                                       'distance': 3867.5493383407593,
                                       'extra_distance_multiplier': 1.0,
                                       'recalculated': False,
                                       'time': 431.8479856200972},
                              'calc_method': 'fixed',
                              'calc_total': 153.0,
                              'city': '\xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0',
                              'cost': 142.0,
                              'coupon': {},
                              'created': '2019-12-03 10:00:00.750000',
                              'creditcard': {'credentials': {'card_number': '220220****0648',
                                                             'card_system': 'MIR'},
                                             'tips': {'type': 'percent',
                                                      'value': 0.0},
                                             'tips_perc_default': 0.0},
                              'device_id': None,
                              'dont_call': False,
                              'dont_sms': True,
                              'driver_cost': {'calc_method': 'fixed',
                                              'cost': 142.0,
                                              'reason': 'fixed'},
                              'experiments': ['add_free_waiting_to_notification_on_driver_arriving',
                                              'address_change_logging',
                                              ],
                              'feedback': {'app_comment': False,
                                           'c': False,
                                           'choices': {},
                                           'ct': '2019-12-04 04:38:59.000000',
                                           'iac': True,
                                           'rating': 5},
                              'fixed_price': {'destination': [37.446133056655526,
                                                              55.85837053600699],
                                              'driver_price': 142.0,
                                              'max_distance_from_b': 500,
                                              'price': 142.0,
                                              'price_original': 142.0,
                                              'show_price_in_taximeter': False},
                              'need_sync_grades': True,
                              'no_cars_order': False,
                              'nz': 'moscow',
                              'operator_login': None,
                              'original_locale': 'ru-RU',
                              'performer': {'car': 'Kia Rio',
                                            'car_age': 2017,
                                            'car_number': 'car-number-1',
                                            'carrier': {
                                                'address': 'carrier-address',
                                                'name': 'carrier-name',
                                                'registration_number': '111111',
                                                'work_hours': '9:00\xe2\x80\x9418:00'},
                                            'clid': '400000001483',
                                            'db_id': '20f39e832b184e939dfc493c2a78f93f',
                                            'driver_license': 'test_driver_license',
                                            'driver_license_personal_id': 'fcda32d38fc542eb91f58ecb1b99a1b5',
                                            'paid_supply': False,
                                            'real_clid': '20f39e832b184e939dfc493c2a78f93f',
                                            'sr': None,
                                            'tariff': {'ci': '65123e26844d4c989f90bb3f14108d2b',
                                                       'class': 'uberx',
                                                       'currency': 'RUB',
                                                       'id': '65123e26844d4c989f90bb3f14108d2b'},
                                            'taxi_alias': {'id': 'bb1459129f5f3c639d0dcc85cde7f49c'},
                                            'uuid': 'f141da70c0fc4b2bb7d4e4fc5cbfac05'},
                              'referral_id': None,
                              'referral_timestamp': None,
                              'reorder': {'id': None},
                              'request': {'class': ['econom', 'uberx'],
                                          'cargo_ref_id': 'order/56884cd1-d0fe-4abf-91cc-61a9795de8a5',
                                          'comment': '',
                                          'corp': {'cost_center': '', 'user_id': 'test-corp-user-id',
                                                   'client_id': 'test-corp-client-id'},
                                          'destinations': [
                                              {'country': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f',
                                               'description': '\xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0, \xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f',
                                               'fullname': 'test-destination-fullname',
                                               'geopoint': [37.446133056655526,
                                                            55.85837053600699],
                                               'locality': '\xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0',
                                               'object_type': '\xd0\xb4\xd1\x80\xd1\x83\xd0\xb3\xd0\xbe\xd0\xb5',
                                               'premisenumber': '0',
                                               'short_text': 'test-destination-short-text',
                                               'thoroughfare': 'test-destination-thoroughfare',
                                               'type': 'address',
                                               }],
                                          'driverclientchat_enabled': True,
                                          'driverclientchat_translate_enabled': True,
                                          'due': '2019-12-03 10:04:00.000000',
                                          'excluded_parks': [],
                                          'ignore_excluded_parks': True,
                                          'ip': '::ffff:31.173.28.129',
                                          'offer': 'cb6246950c649d965c51ae0790964294',
                                          'payment': {'payment_method_id': 'card-xb806d2011dc88d70ed363867',
                                                      'type': 'card'},
                                          'requirements': {},
                                          'selected_promotions': [],
                                          'service_level': 150,
                                          'source': {'country': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f',
                                                     'description': '\xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0, \xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f',
                                                     'fullname': 'test-source-fullname',
                                                     'geopoint': [37.452790665186285,
                                                                  55.82751274625591],
                                                     'locality': '\xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0',
                                                     'object_type': '\xd0\xb4\xd1\x80\xd1\x83\xd0\xb3\xd0\xbe\xd0\xb5',
                                                     'premisenumber': '0',
                                                     'short_text': 'test-source-short-text',
                                                     'thoroughfare': 'test-source-thoroughfare',
                                                     'type': 'address',
                                                     },
                                          'source_geoareas': ['nwao',
                                                              'moscow',
                                                              'mkad',
                                                              'moscow_activation',
                                                              'reposition_discount_B',
                                                              'moscow_for_mo'],
                                          'sp': 0.9,
                                          'sp_alpha': 1.111,
                                          'sp_beta': 0.0,
                                          'sp_surcharge': 0.0},
                              'route': {'distance': 3867.5493383407593,
                                        'time': 431.8479856200972},
                              'routestats_link': 'd74ed08b7780bf73b1145dc10d3006fe',
                              'rsk': '1417747d99717c2c83122d5c694a0f47',
                              'source': 'yauber',
                              'statistics': {'application': 'uber_android',
                                             'urgency': 600},
                              'status': 'finished',
                              'status_change_positions': [],
                              'status_updated': '2019-12-03 10:12:13.950000',
                              'taxi_status': 'complete',
                              'taximeter_receipt': {
                                  'area_ids': {'balashiha_1_transfer': '48b2d2bbf6284a8fb2507eae80f076b7',
                                               'balashiha_2_transfer': '4348f5f6e84d4fde8bcee46b77dd0b0d',
                                               'balashiha_3_transfer': 'f029e9f33b8945889dffc4295b6d6e27',
                                               'balashiha_4_transfer': '052d1a4431b2487487dc95550bd3430a',
                                               'balashiha_5_transfer': 'eb825a9f01754789b4435d1bf72bd033',
                                               'balashiha_6_transfer': '7c64e39b00c241a5ae015ce07bccdd79',
                                               'dme': 'f903fad6a40b4860929e4befb89ccab1',
                                               'metro_medvedkovo_transfer': 'bca9b71aa10f4a5cb3fed9f2a24a8dd1',
                                               'metro_novogireevo_transfer': '8f2b98a666b4437fbbaaeadab7f5566a',
                                               'metro_novokosino_transfer': 'fdb3759eabaf474faf2eada4a08ad5af',
                                               'moscow': '1f121111472a45e9bcbb7c72200c6340',
                                               'mytishchi_1_transfer': 'b17c2eabb7e34928a202edc7694ba98b',
                                               'mytishchi_2_transfer': 'dbff41b3669d4a99b336f235972a8725',
                                               'mytishchi_3_transfer': '70ef1ee0efd142a78db526e9f75defec',
                                               'mytishchi_4_transfer': '8a97a2ca3ee3421aa96ca72afee7a35e',
                                               'svo': '894c08769c1a443c85a90a7fc484e8de',
                                               'szk': '2ecf2f96e5b340bd97654c82b48eaa3c',
                                               'vko': '01e6b48421754e4e95d102873a4827c8'},
                                  'areas': ['moscow'],
                                  'calc_method': 2,
                                  'calc_total': 153.0,
                                  'details': [{'meter_type': 'time',
                                               'meter_value': 236.0,
                                               'per': 60.0,
                                               'price': 6.0,
                                               'service_type': 'free_route',
                                               'sum': 23.6,
                                               'zone_names': ['moscow']}],
                                  'distances_by_areas': {'moscow': 3910.387733224616},
                                  'dst_actual_point': {'lat': 55.858101,
                                                       'lon': 37.4454776},
                                  'dst_address': 'test-destination-fullname',
                                  'dst_order_point': {'lat': 55.858370536,
                                                      'lon': 37.4461330567},
                                  'durations_by_areas': {'moscow': 536.0},
                                  'min_price': 129.0,
                                  'src_address': 'test-source-fullname',
                                  'src_point': {'lat': 55.8275127463,
                                                'lon': 37.4527906652},
                                  'sum': 142.0,
                                  'tariff_id': '65123e26844d4c989f90bb3f14108d2b',
                                  'total': 142.0,
                                  'total_distance': 3910.387733224616,
                                  'total_duration': 536.0,
                                  'transfer': False,
                                  'version': '9.18 (2213)'},
                              'terminal_id': None,
                              'user_agent': 'yandex-uber/3.86.0.78641 Android/9 (Xiaomi; MI 8)',
                              'user_experiments': ['abijan_econom_show',
                                                   'acquire_via_graph',
                                                   ],
                              'user_id': '797d8dfe2700d3bf772986d889c4d1e4',
                              'user_locale': 'ru',
                              'user_phone_id': '5b275d0c927754110f6f4c0f',
                              'user_ready': False,
                              'user_uid': '744009150',
                              'vendor_id': None,
                              'version': 6},
                    'order_info': {'cc': 142.0,
                                   'lta': '2019-12-03 10:11:23.593000',
                                   'need_sync': False,
                                   'order_object_skipped': False,
                                   'source_point': [37.452790665186285,
                                                    55.82751274625591],
                                   'statistics': {'assign_route_time': 159.88873403519392,
                                                  'assign_surge': 0.9,
                                                  'corp_ride_report_sent': False,
                                                  'setcared': '2019-12-03 10:00:16.902000',
                                                  'status_updates': [{'c': '2019-12-03 10:00:00.750000',
                                                                      'h': False,
                                                                      'q': 'create',
                                                                      's': 'pending'},
                                                                     {'c': '2019-12-03 10:00:04.125000',
                                                                      'h': False,
                                                                      'q': 'new_driver_found'},
                                                                     {'c': '2019-12-03 10:00:09.238000',
                                                                      'd': [37.4428728,
                                                                            55.8219368],
                                                                      'h': False,
                                                                      'i': 0,
                                                                      'p': {'avg_speed': 0.0,
                                                                            'direction': 0.0,
                                                                            'geopoint': [37.4428728,
                                                                                         55.8219368],
                                                                            'taxi_status': 'pending',
                                                                            'time': '2019-12-03 10:00:09.000000',
                                                                            'updated': '2019-12-03 10:00:09.238000'},
                                                                      'q': 'seen'},
                                                                     {'c': '2019-12-03 10:00:16.902000',
                                                                      'g': 1,
                                                                      'h': False,
                                                                      'i': 0,
                                                                      's': 'assigned'},
                                                                     {'c': '2019-12-03 10:00:16.902000',
                                                                      'd': [37.442643,
                                                                            55.821985],
                                                                      'h': False,
                                                                      'i': 0,
                                                                      'l': 1721.921875,
                                                                      'p': {'avg_speed': 0.0,
                                                                            'direction': 117.0,
                                                                            'geopoint': [37.442643,
                                                                                         55.821985],
                                                                            'taxi_status': 'driving',
                                                                            'time': '2019-12-03 10:00:06.000000',
                                                                            'updated': '2019-12-03 07:00:17.000000'},
                                                                      't': 'driving'},
                                                                     {'c': '2019-12-03 10:03:02.851000',
                                                                      'd': [37.452483,
                                                                            55.826868999999995],
                                                                      'h': False,
                                                                      'i': 0,
                                                                      'l': 1408.9765625,
                                                                      'p': {'avg_speed': 0.0,
                                                                            'direction': 7.0,
                                                                            'geopoint': [37.452483,
                                                                                         55.826868999999995],
                                                                            'taxi_status': 'waiting',
                                                                            'time': '2019-12-03 10:02:57.000000',
                                                                            'updated': '2019-12-03 07:03:03.000000'},
                                                                      't': 'waiting'},
                                                                     {'c': '2019-12-03 10:03:15.525000',
                                                                      'd': [37.452619999999996,
                                                                            55.827255],
                                                                      'h': False,
                                                                      'i': 0,
                                                                      'l': 35.109375,
                                                                      'p': {'avg_speed': 20.0,
                                                                            'direction': 9.0,
                                                                            'geopoint': [37.452619999999996,
                                                                                         55.827255],
                                                                            'taxi_status': 'transporting',
                                                                            'time': '2019-12-03 10:03:06.000000',
                                                                            'updated': '2019-12-03 07:03:16.000000'},
                                                                      't': 'transporting'},
                                                                     {'a': {'paid_amount': {'ride': 1420000}},
                                                                      'c': '2019-12-03 10:05:28.253000',
                                                                      'h': False,
                                                                      'q': 'moneyflow'},
                                                                     {'c': '2019-12-03 10:12:13.950000',
                                                                      'd': [37.445634,
                                                                            55.858069],
                                                                      'h': False,
                                                                      'i': 0,
                                                                      'l': 3910.9453125,
                                                                      'p': {'avg_speed': 0.0,
                                                                            'direction': 239.0,
                                                                            'geopoint': [37.445634,
                                                                                         55.858069],
                                                                            'taxi_status': 'complete',
                                                                            'time': '2019-12-03 10:12:04.000000',
                                                                            'updated': '2019-12-03 07:12:13.000000'},
                                                                      's': 'finished',
                                                                      't': 'complete',
                                                                      'tl': 3910.387733224616}]},
                                   't': 'transporting',
                                   'with_coupon': False},
                    'order_link': 'd916a2f13d145161053932b0a76a3539',
                    'payment_tech': {'antifraud_finished': False,
                                     'antifraud_group': 4,
                                     'antifraud_group_recalculated': False,
                                     'check_card_is_finished': True,
                                     'ctt': True,
                                     'debt': False,
                                     'driver_without_vat_to_pay': {'ride': 0,
                                                                   'tips': 0},
                                     'finish_handled': False,
                                     'history': [],
                                     'hold_initiated': False,
                                     'last_known_ip': '::ffff:31.173.28.129',
                                     'last_known_region_id': 225,
                                     'main_card_billing_id': 'xb806d2011dc88d70ed363867',
                                     'main_card_payment_id': 'card-xb806d2011dc88d70ed363867',
                                     'main_card_persistent_id': 'uber:uber:9ff692167b01440ea3e4cd414d13a02a',
                                     'main_card_possible_moneyless': False,
                                     'need_cvn': False,
                                     'notifications': {'payment': {'attempts': 0,
                                                                   'sent': None,
                                                                   'to_send': None},
                                                       'updaterequest': {'attempts': 0,
                                                                         'sent': None,
                                                                         'to_send': None}},
                                     'paid_amount': {'ride': 1420000},
                                     'prev_type': 'card',
                                     'sum_to_pay': {'ride': 0, 'tips': 0},
                                     'type': 'card',
                                     'user_to_pay': {'ride': 0, 'tips': 0},
                                     'without_vat_to_pay': {'ride': 0, 'tips': 0}},
                    'performer': {'alias_id': 'bb1459129f5f3c639d0dcc85cde7f49c',
                                  'candidate_index': 0,
                                  'driver_id': '400000001483_f141da70c0fc4b2bb7d4e4fc5cbfac05',
                                  'need_sync': False,
                                  'park_id': '400000001483',
                                  'presetcar': False,
                                  'seen': '2019-12-03 10:00:09.238000'},
                    'processing': {'version': 25},
                    'reorder': {'decisions': [], 'suggestions': []},
                    'status': 'finished',
                    'trigger': {'s': {'lookupinit': {'last_called': '2019-12-03 10:00:01.854000'},
                                      'updateordercost': {'last_called': '2019-12-03 10:11:25.181000'}}},
                    'updated': '2019-12-04 04:39:00.045000',
                    'waiting_mode': 'regular'},
        }
    ]

    expected = [{
        'application': 'uber_android',
        'assigned_cnt': 1,
        'calc_alternative_type': None,
        'cancel_wasted_time': None,
        'cancelled_cnt': 0,
        'cand_cnt': '1',
        'cand_first_adjusted_point__geopoint': [37.439057, 55.822931999999994],
        'cand_first_cp__dest_quadkey': None,
        'cand_first_cp__id': None,
        'cand_first_cp__left_dist': None,
        'cand_first_cp__left_time': None,
        'cand_first_dist': 1834,
        'cand_first_dp': None,
        'cand_first_driver_classes': ['econom', 'uberx', 'ubernight'],
        'cand_first_driver_eta': 1575367376,
        'cand_first_driver_points': 100,
        'cand_first_gprs_time': 20.0,
        'cand_first_line_dist': 997,
        'cand_first_point': [37.439057, 55.822931999999994],
        'cand_first_push_on_driver_arriving_send_at_eta': None,
        'cand_first_push_on_driver_arriving_sent': None,
        'cand_first_reposition_mode': None,
        'cand_first_subvention_geoareas': ['msk-polygon-4',
                                           'msc-2sept-1',
                                           'msk-spartak0',
                                           'msk-tag-pol_1'],
        'cand_first_tags': ['bru_rusfraud',
                            'bank_cards_banners',
                            'loyalty_partners_banner',
                            'silver',
                            'support_driver_novice',
                            'recent_tariff_econom'],
        'cand_first_taximeter_version': '9.18',
        'cand_first_time': 172,
        'cand_perf_adjusted_point__geopoint': [37.439057, 55.822931999999994],
        'cand_perf_cp__dest_quadkey': None,
        'cand_perf_cp__id': None,
        'cand_perf_cp__left_dist': None,
        'cand_perf_cp__left_time': None,
        'cand_perf_dist': 1834,
        'cand_perf_dp': None,
        'cand_perf_driver_classes': ['econom', 'uberx', 'ubernight'],
        'cand_perf_driver_eta': 1575367376,
        'cand_perf_driver_points': 100,
        'cand_perf_gprs_time': 20.0,
        'cand_perf_line_dist': 997,
        'cand_perf_point': [37.439057, 55.822931999999994],
        'cand_perf_push_on_driver_arriving_send_at_eta': None,
        'cand_perf_push_on_driver_arriving_sent': None,
        'cand_perf_reposition_mode': None,
        'cand_perf_subvention_geoareas': ['msk-polygon-4',
                                          'msc-2sept-1',
                                          'msk-spartak0',
                                          'msk-tag-pol_1'],
        'cand_perf_tags': ['bru_rusfraud',
                           'bank_cards_banners',
                           'loyalty_partners_banner',
                           'silver',
                           'support_driver_novice',
                           'recent_tariff_econom'],
        'cand_perf_taximeter_version': '9.18',
        'cand_perf_time': 172,
        'car_class': 'econom',
        'car_class_refined': 'uberx',
        'cargo_ref_id': 'order/56884cd1-d0fe-4abf-91cc-61a9795de8a5',
        'city': '\xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0',
        'corp_client_id': 'test-corp-client-id',
        'corp_user_id': 'test-corp-user-id',
        'corp_contract_id': 'test-corp-contract-id',
        'cost': 142.0,
        'created': 1575367200,
        'dest_cnt': 1,
        'dest_geopoint': [37.446133056655526, 55.85837053600699],
        'dest_quadkey': '120310101012222213',
        'discount_discard_surge': None,
        'discount_driver_less_coeff': None,
        'discount_method': '',
        'discount_price': None,
        'discount_reason': '',
        'discount_value': None,
        'driver_clid': '400000001483',
        'driver_dbid': '20f39e832b184e939dfc493c2a78f93f',
        'driver_id': '400000001483_f141da70c0fc4b2bb7d4e4fc5cbfac05',
        'driver_license': 'test_driver_license',
        'driver_uuid': 'f141da70c0fc4b2bb7d4e4fc5cbfac05',
        'driving_time': 165.949,
        'dttm_utc_1_min': 1575367200,
        'failed_cnt': 0,
        'fastest_class_flg': True,
        'fixed_price__destination': [37.446133056655526, 55.85837053600699],
        'fixed_price__destination_quadkey': '120310101012222213',
        'fixed_price__driver_price': 142.0,
        'fixed_price__price': 142.0,
        'fixed_price__price_original': 142.0,
        'fixed_price__show_price_in_taximeter': False,
        'multiorder_order_number': None,
        'nearest_zone': 'moscow',
        'no_cars_order': False,
        'offer_timeout_cnt': 0,
        'order_due': 1575367440,
        'order_id': '07a00f61544e3418bc2fc6604c330eb8',
        'order_source': 'yauber',
        'order_type': 'soon',
        'overdraft_flg': False,
        'paid_supply': False,
        'paid_supply_price': None,
        'payment_method_id': 'card-xb806d2011dc88d70ed363867',
        'payment_type': 'card',
        'plan_cost__alternative_type': None,
        'plan_cost__by_tariffs_names': ['uberblack',
                                        'uberkids',
                                        'uberlux',
                                        'uberselect',
                                        'uberselectplus',
                                        'ubervan',
                                        'uberx'],
        'plan_cost__by_tariffs_values': [437.0,
                                         287.0,
                                         875.0,
                                         201.0,
                                         274.0,
                                         333.0,
                                         142.014201420142],
        'plan_cost__distance': 3867.5493383407593,
        'plan_cost__extra_distance_multiplier': 1.0,
        'plan_cost__recalculated': False,
        'plan_cost__time': 431.8479856200972,
        'preorder_flg': False,
        'price_modifiers__pay_subventions': None,
        'price_modifiers__reason': '',
        'price_modifiers__tariff_categories': [],
        'price_modifiers__type': '',
        'price_modifiers__value': None,
        'reorder_cnt': 0,
        'requirements': [],
        'request_classes': ['econom', 'uberx'],
        'search_time': 16.152,
        'seen_cnt': 1,
        'seen_timeout_cnt': 0,
        'source_geoareas': ['nwao',
                            'moscow',
                            'mkad',
                            'moscow_activation',
                            'reposition_discount_B',
                            'moscow_for_mo'],
        'source_geopoint': [37.452790665186285, 55.82751274625591],
        'source_metrica_action': None,
        'source_quadkey': '120310101030201202',
        'status': 'finished',
        'status_updated': 1575367933,
        'surcharge': 0.0,
        'surge_alpha': 1.111,
        'surge_beta': 0.0,
        'surge_value': 0.9,
        'taxi_status': 'complete',
        'transporting_time': 538.425,
        'ts_1_min': 1575367200,
        'updated': 1575434340,
        'user_agent': 'yandex-uber/3.86.0.78641 Android/9 (Xiaomi; MI 8)',
        'user_fraud': 0,
        'user_id': '797d8dfe2700d3bf772986d889c4d1e4',
        'user_tags': [],
        'waiting_time': 165.949
    }
    ]

    transformed = list(loader.transform_data(
        order_proc_data,
        corp_client_to_contract={'test-corp-client-id': 'test-corp-contract-id'}
    ))

    assert transformed == expected
