#!/bin/bash

set -e

COMPOSE_FILES=(base-images.yml \
	 compose/storage.yml \
     compose/mock-server.yml \
     compose/taxi-infra.yml \
     compose/grocery.yml \
     compose/networks.yml)

docker-compose ${COMPOSE_FILES[@]/#/-f } $@
