INSERT INTO storage.places (
    id,
    updated_at,
    slug,
    enabled,
    name,
    revision,
    type,
    business,
    launched_at,
    payment_methods,
    gallery,
    brand,
    address,
    country,
    categories,
    quick_filters,
    wizard_quick_filters,
    region,
    location,
    price_category,
    assembly_cost,
    rating,
    extra_info,
    features,
    timing,
    sorting,
    address_comment,
    contacts,
    working_intervals,
    allowed_couriers_types)
VALUES
    (1, '2018-12-14T00:00:01+03:00', 'slug1', true, 'name', 1, 'native', 'zapravki', '2015-12-14T00:00:00+03:00',
        ARRAY['cash','taxi']::storage.place_payment_method[], ARRAY[]::storage.place_gallery[],
        (1,'slug','name', 'aspect_fit')::storage.place_brand_v2, ('cuty','short')::storage.place_address,
        (1,'name','code',('code','sign')::storage.place_country_currency)::storage.place_country,
        ARRAY[]::storage.place_category[], ARRAY[]::storage.place_quick_filter[],
        ARRAY[]::storage.place_quick_filter[], (1,'{1,2}'::bigint[],'zone','name')::storage.place_region,
        point(3,4), (1,'name',0.5)::storage.place_price_category, 123,
        '{"shown":4.83, "users":4.5, "admin":1.0, "count":200}', '{}', '{}', '{}', '{}', '', '[]',
     ARRAY[]::storage.working_interval[], ARRAY[]::storage.delivery_zone_couriers_type[]),
    (2, '2018-12-14T00:00:01+03:00', 'slug2', true, 'name', 1, 'native', 'zapravki', '2015-12-14T00:00:00+03:00',
        ARRAY['cash','taxi']::storage.place_payment_method[], ARRAY[]::storage.place_gallery[],
        (1,'slug','name', 'aspect_fit')::storage.place_brand_v2, ('cuty','short')::storage.place_address,
        (1,'name','code',('code','sign')::storage.place_country_currency)::storage.place_country,
        ARRAY[]::storage.place_category[], ARRAY[]::storage.place_quick_filter[],
        ARRAY[]::storage.place_quick_filter[], (1,'{1,2}'::bigint[],'zone','name')::storage.place_region,
        point(3,4), (1,'name',0.5)::storage.place_price_category, 123,
        '{"shown":4.83, "users":4.5, "admin":1.0, "count":200}', '{}', '{}', '{}', '{}', '', '[]',
     ARRAY[]::storage.working_interval[], ARRAY[]::storage.delivery_zone_couriers_type[]),
    (3, '2018-12-14T00:00:02+03:00', 'slug3', true, 'name', 1, 'native', 'zapravki', '2015-12-14T00:00:00+03:00',
        ARRAY['cash','taxi']::storage.place_payment_method[], ARRAY[]::storage.place_gallery[],
        (1,'slug','name', 'aspect_fit')::storage.place_brand_v2, ('cuty','short')::storage.place_address,
        (1,'name','code',('code','sign')::storage.place_country_currency)::storage.place_country,
        ARRAY[]::storage.place_category[], ARRAY[]::storage.place_quick_filter[],
        ARRAY[]::storage.place_quick_filter[], (1,'{1,2}'::bigint[],'zone','name')::storage.place_region,
        point(3,4), (1,'name',0.5)::storage.place_price_category, 123, '{}', '{}', '{}', '{}', '{}', '', '[]',
     ARRAY[]::storage.working_interval[], ARRAY[]::storage.delivery_zone_couriers_type[]),
    (4, '2018-12-14T00:00:03+03:00', 'slug4', true, 'name', 1, 'native', 'zapravki', '2015-12-14T00:00:00+03:00',
        ARRAY['cash','taxi']::storage.place_payment_method[], ARRAY[]::storage.place_gallery[],
        (1,'slug','name', 'aspect_fit')::storage.place_brand_v2, ('cuty','short')::storage.place_address,
        (1,'name','code',('code','sign')::storage.place_country_currency)::storage.place_country,
        ARRAY[]::storage.place_category[], ARRAY[]::storage.place_quick_filter[],
        ARRAY[]::storage.place_quick_filter[], (1,'{1,2}'::bigint[],'zone','name')::storage.place_region,
        point(3,4), (1,'name',0.5)::storage.place_price_category, 123, '{}', '{}', '{}', '{}', '{}', '', '[]',
     ARRAY[]::storage.working_interval[], ARRAY[]::storage.delivery_zone_couriers_type[]),
    (5, '2018-12-14T00:00:04+03:00', 'slug5', true, 'name', 1, 'native', 'zapravki', '2015-12-14T00:00:00+03:00',
        ARRAY['cash','taxi']::storage.place_payment_method[], ARRAY[]::storage.place_gallery[],
        (1,'slug','name', 'aspect_fit')::storage.place_brand_v2, ('cuty','short')::storage.place_address,
        (1,'name','code',('code','sign')::storage.place_country_currency)::storage.place_country,
        ARRAY[]::storage.place_category[], ARRAY[]::storage.place_quick_filter[],
        ARRAY[]::storage.place_quick_filter[], (1,'{1,2}'::bigint[],'zone','name')::storage.place_region,
        point(3,4), (1,'name',0.5)::storage.place_price_category, 123, '{}', '{}', '{}', '{}', '{}', '', '[]',
     ARRAY[]::storage.working_interval[], ARRAY[]::storage.delivery_zone_couriers_type[]),
    (6, '2018-12-14T00:00:04+03:00', 'slug6', true, 'name', 1, 'native', 'zapravki', '2015-12-14T00:00:00+03:00',
        ARRAY['cash','taxi']::storage.place_payment_method[], ARRAY[]::storage.place_gallery[],
        (1,'slug','name', 'aspect_fit')::storage.place_brand_v2, ('cuty','short')::storage.place_address,
        (1,'name','code',('code','sign')::storage.place_country_currency)::storage.place_country,
        ARRAY[]::storage.place_category[], ARRAY[]::storage.place_quick_filter[],
        ARRAY[]::storage.place_quick_filter[], (1,'{1,2}'::bigint[],'zone','name')::storage.place_region,
        point(3,4), (1,'name',0.5)::storage.place_price_category, 123, '{}', '{}', '{}', '{}', '{}', '', '[]',
     ARRAY[]::storage.working_interval[], ARRAY[]::storage.delivery_zone_couriers_type[])
