#! /usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = "Zasimov Alexey"
__email__ = "zasimov-a@yandex-team.ru"

u"""
Тестируем конфигурацию котировок.
"""


from wp7desktop.share.config import open_config
from wp7desktop.stocks.config import StocksConfig


if __name__ == "__main__":
    cp = open_config("config/wp7desktop.conf")
    c = StocksConfig(cp)
    print c.get_stock_url(42)
