SET TIME ZONE 'UTC';

INSERT INTO eda_cdm_supply.agg_place_plus_metric(brand_id,
                                                 place_id,
                                                 utc_period_start_dttm,
                                                 scale_name,
                                                 place_plus_status,
                                                 user_w_plus_gmv_lcy,
                                                 user_wo_plus_gmv_lcy,
                                                 user_w_plus_order_cnt,
                                                 user_wo_plus_order_cnt,
                                                 cashback_by_place_lcy,
                                                 cashback_spent_by_user_lcy,
                                                 avg_cashback_by_place_pcnt,
                                                 new_user_w_plus_cnt,
                                                 new_user_wo_plus_cnt,
                                                 user_w_plus_ltv_lcy,
                                                 user_wo_plus_ltv_lcy,
                                                 user_w_plus_frequency_val,
                                                 user_wo_plus_frequency_val,
                                                 _etl_processed_dttm)
VALUES (1,
        1,
        '2021-07-01 00:00'::timestamp,
        'month',
        NULL,
        5.1,
        5.2,
        1,
        2,
        5.3,
        5.4,
        5.5,
        3,
        4,
        NULL,
        NULL,
        NULL,
        NULL,
        '2021-06-30 00:03:30+00'::timestamp + interval '1 minute'),
       (1,
        1,
        '2021-06-30 00:03:32+00'::timestamp,
        'week',
        'partly_active',
        3.1,
        3.2,
        1,
        2,
        3.3,
        3.4,
        3.5,
        3,
        4,
        3.6,
        3.7,
        3.8,
        3.9,
        '2021-06-30 00:03:30+00'::timestamp + interval '1 minute')
        ,
       (1,
        1,
        '2021-06-30 00:03:30'::timestamp,
        'day',
        'partly_active',
        4.1,
        4.2,
        1,
        2,
        4.3,
        4.4,
        4.5,
        3,
        4,
        4.6,
        4.7,
        4.8,
        4.9,
        '2021-06-30 00:03:30'::timestamp + interval '2 minute'),
       (10,
        10,
        '2021-06-30 00:00'::timestamp,
        'day',
        'partly_active',
        10.1,
        10.2,
        10,
        20,
        40.3,
        40.4,
        40.5,
        30,
        40,
        40.6,
        40.7,
        40.8,
        40.9,
        '2021-06-30 00:03:30'::timestamp + interval '2 minute')
;
