\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V01__init.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V02__photos.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V03__NONTRANSACTIONAL_updated_at_indexes.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V05__devices_web_info.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V06__events.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V07__videos_add_duration.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V08__columns_for_events.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V09__photo_file_id_and_gnss.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V10__events_video.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V11__declared_devices.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V12__NONTRANSACTIONAL_updated_at_indexes_declared_and_web.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V13__declared_devices_traits.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V14__binary_sign_keys.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V15__camera_bindings.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V16__add_driver_and_vehicle_to_event.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V17__software_version.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V18__NONTRANSACTIONAL_events_list_indexes.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V19__position_updated_at.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V20__public_event_id.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V21__event_seen.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V22__event_resolution.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V23__event_comments.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V24__event_comments_and_signalled.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V25__event_comments_validate_constraints.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V26__NONTRANSACTIONAL_event_at_index.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V27__NONTRANSACTIONAL_events_device_feed.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V28__NONTRANSACTIONAL_events_driver_idx.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V29__cron_last_deleted_events.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V30__last_videos_and_photos_deleted_event_id.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V31__park_critical_event_types.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V32__device_uptime_total.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V33__external_photos_and_videos_for_events.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V34__NONTRANSACTIONAL_updated_at_event_index.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V35__external_videos_for_events.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V36__status_history.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V37__NONTRANSACTIONAL_updated_at_status_history_idx.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V38__cdb_is_tag_active.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V39__last_videos_and_photos_deleted_event_type.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V40__declared_serial_numbers.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V41__declared_serial_numbers_from_devices.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V42__NONTRANSACTIONAL_park_device_profiles_pkey.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V43__status_states.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V44__device_driver_detected.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V45__NONTRANSACTIONAL_status_history_fix_idx.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V46__NONTRANSACTIONAL_device_driver_detected_indexes.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V47__event_resolution_comeback.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V48__user_notifications.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V49__sim_meta.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V50__device_groups.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V51__NONTRANSACTIONAL_devices_group_idx.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V52__video_chunks_concat_status.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V53__NONTRANSACTIONAL_concat_status_idx.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V54__lb_events_producer.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V55__upload_queue.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V56__files.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V57__device_error_states.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V58__NONTRANSACTIONAL_files_updated_at_idx.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V59__traffic_counters.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V60__monitoring_acceptance.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V61__NONTRANSACTIONAL_created_at_monitoring_acceptance_idx.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V62__declared_serial_numbers_details.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V63__NONTRANSACTIONAL_sim_stats_updated_at_idx.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V64__last_best_shot_time_at.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V65__offsets_for_traffic_counters.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V66__last_requested_traffic.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V67__NONTRANSACTIONAL_events_photos_and_videos_indexes.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V68__park_view_mode.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V69__NONTRANSACTIONAL_index_videos_created_at.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V70__internal_filters.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V71__park_view_mode_user_specific.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V72__NONTRANSACTIONAL_events_park_car_idx.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V73__NONTRANSACTIONAL_created_at_idx.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V74__NONTRANSACTIONAL_events_idxs.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V75__add_last_requested_traffic_datetime.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V76__fix_device_error_states_names.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V77__last_videos_and_photos_deleted_without_events.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V78__add_is_drive_device.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V79__last_external_videos_and_photos_deleted.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V80__add_is_sent_to_ml.sql
\ir ../../../signal_device_api_worker/storage/postgresql/signal_device_api_meta_db/migrations/V81__NONTRANSACTIONAL_park_resolution_idx.sql
