insert into personal_wallet.wallets (id, yandex_uid, currency, fallback_balance, merge_status)
values
('fallback_wallet', 'fallback_uid', 'RUB', '364', NULL),
('negative_wallet', 'uid-uid', 'RUB', '-364', NULL),
('bound_wallet_1', 'bound_uid_1', 'RUB', '1', NULL),
('bound_wallet_2', 'bound_uid_2', 'RUB', '2', NULL),
('merged_wallet', 'merged_uid', 'RUB', '0', 'merged'),
('portal_wallet', 'portal_uid', 'RUB', '0', NULL),
('must_rounded_rub_wallet_id_1', 'portal_uid_1', 'RUB', '10.7', NULL),
('must_rounded_rub_wallet_id_2', 'portal_uid_2', 'RUB', '10.3', NULL),
('must_rounded_rub_wallet_id_3', 'portal_uid_3', 'RUB', '10.5', NULL),
('must_rounded_kzt_wallet_id_1', 'portal_uid_1', 'KZT', '10', NULL),
('must_rounded_kzt_wallet_id_2', 'portal_uid_2', 'KZT', '17.3', NULL),
('must_rounded_kzt_wallet_id_3', 'portal_uid_3', 'KZT', '19.9', NULL),
('must_rounded_uah_wallet_id_1', 'portal_uid_1', 'UAH', '10.7', NULL),
('must_rounded_uah_wallet_id_2', 'portal_uid_2', 'UAH', '10.3', NULL),
('must_rounded_uah_wallet_id_3', 'portal_uid_3', 'UAH', '10.5', NULL),
('fallback_wallet_eur', 'eur_uid', 'EUR', '142.14', NULL),
('rounding_factor_kzt_wallet', 'rounding_factor_uid', 'KZT', '10.85', NULL),
('req_curr_wallet_id_kzt', 'req_curr_uid', 'KZT', '100.00', NULL),
('req_curr_many_wallet_id_rub', 'req_curr_many_uid', 'RUB', '120.00', NULL),
('req_curr_many_wallet_id_kzt', 'req_curr_many_uid', 'KZT', '100.00', NULL),
('request_currency_not_in_allowed_id_rub', 'request_currency_not_in_allowed', 'RUB', '100.00', NULL),
('rounding_factor_byn', 'rounding_factor_byn', 'BYN', '1.4', NULL)
