CREATE TABLE modx_web_user_attributes (
  id int NOT NULL,
  date_reg int(11) NOT NULL DEFAULT '0',
  internalKey int NOT NULL DEFAULT '0',
  name_small varchar(100) NOT NULL,
  fullname varchar(100) NOT NULL DEFAULT '',
  blocked int NOT NULL DEFAULT '0',
  photo varchar(255) NOT NULL DEFAULT '',
  phone varchar(100) NOT NULL DEFAULT '',
  interface varchar(255) NOT NULL DEFAULT '',
  show_name int not null default '0',
  saving_up_for varchar(255) default '',
  trans_guest_block int not null default '0',
  trans_guest int not null default '0',
  pay_page_bw int not null default '0',
  pay_page_option int not null default '0',
  proc1 int not null default '5',
  proc2 int not null default '7',
  proc3 int not null default '10',
  proc4 int not null default '15',
  proc_all int,
  price1 int(2) DEFAULT '50' COMMENT 'Фиксированная сумма чаевых для отображения на странице оплаты 1',
  price2 int(2) DEFAULT '100' COMMENT 'Фиксированная сумма чаевых для отображения на странице оплаты 2',
  price3 int(2) DEFAULT '300' COMMENT 'Фиксированная сумма чаевых для отображения на странице оплаты 3',
  price4 int(2) DEFAULT '500' COMMENT 'Фиксированная сумма чаевых для отображения на странице оплаты 4',
  price_all int(2) DEFAULT '0' COMMENT 'Сумма по умолчанию при открытии страницы оплаты',
  b2p_block_mcc int(1) DEFAULT '0' COMMENT 'Сработала или проставлена блокировка МСС кодов',
  best2pay_card_token varchar(40) NOT NULL COMMENT 'токен привязанной банковской карты'
);

CREATE TABLE modx_web_users_org (
  id int NOT NULL,
  user_id int NOT NULL,
  to_user_id int NOT NULL,
  status int NOT NULL,
  show_in_menu int not null default 1
);

CREATE TABLE modx_web_users_pays (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `to_user_id` int(11) NOT NULL,
  `to_user_sub_id` int(11) NOT NULL DEFAULT '0',
  `card_id` int(11) NOT NULL DEFAULT '0',
  `transaction_id` varchar(50) DEFAULT NULL,
  `transaction_status` varchar(50) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `amount_trans` decimal(10,2) DEFAULT '0.00',
  `date_created` int(11) NOT NULL,
  `transaction_status_date` int(11) NOT NULL DEFAULT '0',
  `transaction_pay_date` int(11) NOT NULL,
  `language` varchar(3) NOT NULL,
  `test` int(1) NOT NULL,
  `is_blago` int(1) NOT NULL,
  `procent` int(1) NOT NULL COMMENT '1 - процент с приглашенного друга или 2 - процент ЯК или 3 - проценит Агенту или 4 - процент сайта или 5 - заявка на вывод; 6 - Компенсация комиссии от системы по акции; 7 - Компенсация от Сервиса; 8 - оплата платной СМС;',
  `who` int(11) NOT NULL,
  `type` int(1) NOT NULL COMMENT '0 - приход, 1 - вывод',
  `is_apple` int(1) NOT NULL,
  `is_google` int(1) NOT NULL,
  `is_samsung` int(1) NOT NULL,
  `is_ecommpay` int(1) NOT NULL,
  `is_best2pay` int(1) NOT NULL,
  `best2pay_fee` decimal(10,2) NOT NULL,
  `is_mp` int(1) NOT NULL DEFAULT '0',
  `code` int(1) NOT NULL,
  `room_id` int(11) NOT NULL,
  `comment` varchar(255) NOT NULL,
  `parent_id` int(11) NOT NULL,
  `idempotenceKey` varchar(50) NOT NULL,
  `message` varchar(255) NOT NULL,
  `email` varchar(50) NOT NULL,
  `pan` varchar(20) DEFAULT NULL,
  `is_b2p_fail` int(1) NOT NULL DEFAULT '0',
  `is_yandex` int(11) NOT NULL DEFAULT '0' COMMENT 'Yandex Pay',
  PRIMARY KEY (`id`),
  unique KEY transaction_id_unq (transaction_id)
);


CREATE TABLE `modx_web_users_withdrawal` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `fullname` varchar(255) NOT NULL,
  `sum` int(11) NOT NULL,
  `date_time` int(11) NOT NULL,
  `admin_id` int(11) NOT NULL,
  `transaction_date` int(11) NOT NULL,
  `pay_id` int(11) NOT NULL,
  `pay_method` varchar(10) NOT NULL,
  `cancel_admin_id` int(11) NOT NULL,
  `cancel_date` int(11) NOT NULL,
  `cancel_reason` varchar(255) NOT NULL,
  `cancel_reason_description` varchar(255) NOT NULL,
  `is_blacklist` int(1) NOT NULL DEFAULT '0' COMMENT 'если есть в транзакциях карта из черного списка',
  `is_one_card` int(1) NOT NULL DEFAULT '0' COMMENT 'если было от 3-х транзакций с одной карты за последние сутки',
  `is_not_from_russian` int(1) NOT NULL DEFAULT '0' COMMENT 'если создали заявку не с российского IP',
  `exceeded_threshold` int(1) NOT NULL DEFAULT '0' COMMENT 'превышен порог безопасного вывода',
  `exceeded_threshold_fresh` int(1) NOT NULL DEFAULT '0' COMMENT 'превышен порог безопасного вывода для новых пользователей',
  `yandex_antifraud_block` int(1) NOT NULL DEFAULT '0' COMMENT 'yandex antifraud blocked',
  `is_from_3k_pay` int(1) DEFAULT '0',
  `bank_id` varchar(20) DEFAULT NULL COMMENT 'SBP bank id',
  `target_phone_id` varchar(50) NOT NULL DEFAULT '',
  `last_update_time` int(10) NOT NULL DEFAULT '0',
  `precheck_id` int(10) NOT NULL DEFAULT '0',
  `status` varchar(50) DEFAULT 'not SBP' NOT NULL,
  `manual_check_reasons` int(10) NOT NULL DEFAULT '0',
  `idempotency_key` varchar(32) DEFAULT NULL NULL,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `date_time` (`date_time`),
  KEY `admin_id` (`admin_id`),
  KEY `transaction_date` (`transaction_date`),
  KEY `pay_id` (`pay_id`),
  KEY `requests_in_progress` (`status`,`last_update_time`),
  FULLTEXT KEY `pay_method` (`pay_method`),
  unique KEY idempotency_key (idempotency_key)
) ENGINE=InnoDB AUTO_INCREMENT=1998225 DEFAULT CHARSET=utf8;
