#!/bin/bash

PGMIGRATE=$(which pgmigrate)
if [ "x$PGMIGRATE" == "x" ]; then
    echo "No pgmigrate found. Run 'apt-get install yandex-pgmigrate'
 or 'pip install yandex-pgmigrate'" >&2
    exit 1
fi

exec $PGMIGRATE "$@"
