TEST_SUITE_CONFIGS = [
    'Android_Bro_Alpha.yaml',
    'Android_Bro_Beta.yaml',
    'Android_Bro_Major_Inter.yaml',
    'Android_Bro_Major_Final.yaml',
    'Android_Bro_Minor_Inter.yaml',
    'Android_Bro_Minor_Final.yaml',
    'Android_Bro_Merge_smoke_1.yaml',
    'Android_Bro_Merge_smoke_2.yaml',
    'Android_Bro_Merge_regression.yaml',
    'Android_Bro_PP_Major.yaml',
    'Android_Bro_PP_Minor.yaml',
    'Android_Bro_PP_Merge_smoke_1.yaml',
    'Android_Bro_PP_Merge_smoke_2.yaml',
    'Android_Bro_PP_Merge_regression.yaml',
    'google_apps.yaml',
]
