INSERT INTO discounts_operation_calculations.suggests(
    id,
    algorithm_ids,
    author,
    discounts_city,
    draft_url,
    draft_id,
    status,
    created_at,
    updated_at,
    statistics,
    multidraft_params,
    budget,
    max_absolute_value,
    calc_segments_params,
    fixed_discounts
)
VALUES (1, ARRAY['kt'], 'test_user', 'test_city', 'https://ya.ru/1123', 1123, 'NOT_PUBLISHED', '2021-08-10 23:43:21', '2021-08-10 23:53:21', '[]', '{}', NULL, NULL,
'{"common_params": {"discounts_city": "test_city", "companies": ["company1", "company2"], "tariffs": ["uberx", "econom"], "min_discount": 0, "max_discount": 40},
  "custom_params": [{"algorithm_id": "kt", "max_surge": 1.8, "with_push": true, "fallback_discount": 6}]}', '{}'),
(2, ARRAY['kt'], 'test_user', 'test_city', 'https://ya.ru/1124', 1124, 'NOT_PUBLISHED', '2021-08-10 23:43:21', '2021-08-10 23:53:21', '[]', '{}', NULL, NULL,
'{"common_params": {"discounts_city": "test_city", "companies": ["company1", "company2"], "tariffs": ["uberx", "econom"], "min_discount": 6, "max_discount": 30},
  "custom_params": [{"algorithm_id": "kt", "max_surge": 1.8, "with_push": true, "fallback_discount": 6}]}',
 '[{"algorithm_id": "kt", "fixed_discounts": [{"segment": "random", "discount_value": 12}, {"segment": "control", "discount_value": 0}]}]'),
(3, ARRAY['kt'], 'test_user', 'test_city', 'https://ya.ru/1123', 1123,
    'NOT_PUBLISHED', '2021-08-10 23:43:21', '2021-08-10 23:53:21', '[]', '{}', NULL, NULL,
'{"common_params": {"discounts_city": "test_city", "companies": ["company1", "company2"], "tariffs": ["uberx", "econom"], "min_discount": 0, "max_discount": 40},
  "custom_params": [{"algorithm_id": "kt", "max_surge": 1.8, "with_push": false, "fallback_discount": 6}]}',
 '[{"algorithm_id": "kt", "fixed_discounts": [{"segment": "random", "discount_value": 12}, {"segment": "control", "discount_value": 0}]}]');
