INSERT INTO discounts_operation_calculations.algorithms_configs (
    algorithm_name,
    description,
    algorithm_type,
    metric_name,
    second_metric_name,
    max_absolute_value,
    min_value,
    max_value,
    is_price_strikethrough,
    classes,
    discount_duration,
    disable_by_surge,
    payment_types,
    push_segment_stats_path,
    segment_stats_path,
    segment_stats_hist_path,
    user_segment_path,
    yql_tagging_path,
    yql_tagging_hist_path,
    is_tagging_active,
    control_hashing_salt,
    random_hashing_salt,
    control_share,
    random_share
) VALUES (
    'kt2',
    'тут описание для вывода на фронт',
    'katusha',
    'название метрики: экстра трипы, отобранные офферы',
    'название второй метрики',
    300,
    0.05,
    0.5,
    true,
    ARRAY['econom', 'uberx', 'business'],
    365,
    1.2,
    ARRAY['card', 'applepay'],
    'kt2_segment_stats_push',
    'kt2_segment_stats_hist2',
    'kt2_segment_stats',
    'kt2_user_segments',
    'kt2_tagging_test2',
    'kt2_tagging_test_hist2',
    'true',
    '',
    '2021-07-19-random_users-kt2',
    20,
    10
);

INSERT INTO discounts_operation_calculations.algorithms_configs (
    algorithm_name,
    description,
    metric_name,
    second_metric_name,
    max_absolute_value,
    min_value,
    max_value,
    is_price_strikethrough,
    classes,
    discount_duration,
    disable_by_surge,
    payment_types,
    segment_stats_path,
    segment_stats_hist_path,
    user_segment_path,
    yql_tagging_path,
    yql_tagging_hist_path,
    is_tagging_active,
    control_hashing_salt,
    random_hashing_salt,
    control_share,
    random_share
) VALUES (
    'testing',
    'Тестовый алгоритм',
    'первая метрика',
    'вторая метрика ',
    200,
    0,
    0.5,
    true,
    ARRAY['econom', 'uberx', 'business'],
    7,
    1.2,
    ARRAY['card', 'applepay'],
    'testing_segment_stats_hist2',
    'testing_segment_stats',
    'testing_user_segments',
    'testing_tagging_test2',
    'testing_tagging_test_hist2',
    'true',
    '10_2020_kt',
    '2021-07-19-random_users-kt2',
    30,
    10
);
