--- Assuming now is 2020-01-03 10:00+05
INSERT INTO rent.records
(record_id, idempotency_token,
 owner_park_id, owner_serial_id, asset_type, asset_params,
 driver_id, affiliation_id,
 begins_at_tz, ends_at_tz,
 charging_type,
 charging_params,
 charging_starts_at_tz,
 creator_uid, created_at_tz,
 accepted_at_tz,
 transfer_order_number,
 use_event_queue,
 use_arbitrary_entries)
VALUES ('basic_rent_id', 'idempotency_token',
        'park_id5', 1, 'other', '{"subtype": "misc"}',
        'driver_id', NULL,
        '2020-01-01 00:00+05', '2020-01-31+00',
        'active_days',
        '{"daily_price": "100"}',
        '2020-01-01 00:00+05',
        'creator_uid', '2020-01-01+00',
        '2020-01-01+00',
        'park_id_1',
        TRUE, TRUE);

INSERT INTO rent.rent_history(rent_id, version,
                              modification_source,
                              owner_park_id,
                              owner_serial_id,
                              asset_type,
                              asset_params,
                              driver_id,
                              affiliation_id,
                              begins_at, ends_at,
                              charging_type, charging_params,
                              charging_starts_at,
                              creator_uid, created_at,
                              modified_at,
                              accepted_at,
                              transfer_order_number,
                              use_event_queue,
                              use_arbitrary_entries)
VALUES ('basic_rent_id', 1,
        '{"kind":"dispatcher", "uid": "hello"}',
        'park_id5', 1, 'other', '{"subtype": "misc"}',
        'driver_id', NULL,
        '2020-01-01 00:00+05', '2020-01-31+00',
        'active_days',
        '{"daily_price": "100"}',
        '2020-01-01 00:00+05',
        'creator_uid', '2020-01-01+00',
        '2020-01-01+00',
        '2020-01-01+00',
        'park_id_1',
        TRUE, TRUE);
