#!/bin/bash

. $TESTSUITE_LIB_UTILS

YTLOCAL_BASEDIR=$YT_TMPDIR/ytlocal
YTLOCAL_DATADIR=$YTLOCAL_BASEDIR/testsuite
YTLOCAL_CYPRESSDIR=$YTLOCAL_BASEDIR/cypress

YTLOCAL_START=/usr/lib/yandex/taxi-yt-local/bin/yt-local-start
YTLOCAL_STOP=/usr/lib/yandex/taxi-yt-local/bin/yt-local-stop

if [ "$(uname -s)" != "Linux" ]; then
    die "Native yt-local is only supported on GNU/Linux systems.

Please use docker to start yt-local on macOS:

  git clone git@github.yandex-team.ru:yt/docker.git yt-docker
  cd yt-docker
  docker-compose up -d ytbackend

Then re-run testsuite with yt proxy address specified:

  PYTEST_ARGS += --yt-proxy=localhost:8000

For more info please visit https://wiki.yandex-team.ru/taxi/backend/testsuite/yt/"
fi

if [ ! -x $YTLOCAL_START -o ! -x $YTLOCAL_STOP ]; then
    die "Please install yandex-taxi-yt-local package.

$ sudo apt-get install yandex-taxi-yt-local

For more info please visit https://wiki.yandex-team.ru/taxi/backend/testsuite/yt/"
fi

start() {
    echo "Testsuite yt-local directory: $YTLOCAL_BASEDIR"

    rm -rf "$YTLOCAL_DATADIR"
    mkdir -p "$YTLOCAL_DATADIR" "$YTLOCAL_CYPRESSDIR"
    cd "$YTLOCAL_DATADIR"

    $YTLOCAL_START \
        --fqdn $YT_HOSTNAME \
        --id testsuite \
        --proxy-config "{address_resolver={enable_ipv4=%true;enable_ipv6=%false;};coordinator={public_fqdn=\"${YT_HOSTNAME}:${YT_HTTP_PROXY_PORT}\"}}" \
        --local-cypress-dir "$YTLOCAL_CYPRESSDIR" \
        --proxy-port $YT_HTTP_PROXY_PORT --rpc-proxy-port $YT_RPC_PROXY_PORT \
        --wait-tablet-cell-initialization
}

stop() {
    cd "$YTLOCAL_DATADIR"
    $YTLOCAL_STOP testsuite
    rm -rf "$YTLOCAL_DATADIR"
}

script_main "$@"
