# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/maps/proto/search/geocoder_internal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import geocoder_pb2 as yandex_dot_maps_dot_proto_dot_search_dot_geocoder__pb2
from . import kind_pb2 as yandex_dot_maps_dot_proto_dot_search_dot_kind__pb2
from ..common2 import geometry_pb2 as yandex_dot_maps_dot_proto_dot_common2_dot_geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yandex/maps/proto/search/geocoder_internal.proto',
  package='yandex.maps.proto.search.geocoder_internal',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n0yandex/maps/proto/search/geocoder_internal.proto\x12*yandex.maps.proto.search.geocoder_internal\x1a\'yandex/maps/proto/search/geocoder.proto\x1a#yandex/maps/proto/search/kind.proto\x1a(yandex/maps/proto/common2/geometry.proto\"O\n\x05House\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x38\n\x05point\x18\x02 \x02(\x0b\x32).yandex.maps.proto.common2.geometry.Point\"q\n\x0cResponseInfo\x12\x10\n\x08\x61\x63\x63uracy\x18\x01 \x01(\x01\x12>\n\x04mode\x18\x02 \x02(\x0e\x32\x30.yandex.maps.proto.search.geocoder_internal.Mode\x12\x0f\n\x07version\x18\x03 \x02(\t\"E\n\x10MatchedComponent\x12\x31\n\x04kind\x18\x01 \x01(\x0e\x32#.yandex.maps.proto.search.kind.Kind\"\xb6\x02\n\x0bToponymInfo\x12\r\n\x05geoid\x18\x01 \x02(\x05\x12\x13\n\x0bhouse_count\x18\x03 \x01(\r\x12\x38\n\x05point\x18\x04 \x02(\x0b\x32).yandex.maps.proto.common2.geometry.Point\x12W\n\x11matched_component\x18\x08 \x03(\x0b\x32<.yandex.maps.proto.search.geocoder_internal.MatchedComponent\x12\x0f\n\x07seoname\x18\t \x01(\t\x12\x0b\n\x03tag\x18\n \x03(\t\x12@\n\x05house\x18\x06 \x03(\x0b\x32\x31.yandex.maps.proto.search.geocoder_internal.HouseJ\x04\x08\x02\x10\x03J\x04\x08\x05\x10\x06J\x04\x08\x07\x10\x08* \n\x04Mode\x12\x0b\n\x07GEOCODE\x10\x01\x12\x0b\n\x07REVERSE\x10\x02:\x83\x01\n\x0cTOPONYM_INFO\x12\x34.yandex.maps.proto.search.geocoder.GeoObjectMetadata\x18\x64 \x01(\x0b\x32\x37.yandex.maps.proto.search.geocoder_internal.ToponymInfo:\x84\x01\n\rRESPONSE_INFO\x12\x33.yandex.maps.proto.search.geocoder.ResponseMetadata\x18\x64 \x01(\x0b\x32\x38.yandex.maps.proto.search.geocoder_internal.ResponseInfo')
  ,
  dependencies=[yandex_dot_maps_dot_proto_dot_search_dot_geocoder__pb2.DESCRIPTOR,yandex_dot_maps_dot_proto_dot_search_dot_kind__pb2.DESCRIPTOR,yandex_dot_maps_dot_proto_dot_common2_dot_geometry__pb2.DESCRIPTOR,])

_MODE = _descriptor.EnumDescriptor(
  name='Mode',
  full_name='yandex.maps.proto.search.geocoder_internal.Mode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GEOCODE', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REVERSE', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=796,
  serialized_end=828,
)
_sym_db.RegisterEnumDescriptor(_MODE)

Mode = enum_type_wrapper.EnumTypeWrapper(_MODE)
GEOCODE = 1
REVERSE = 2

TOPONYM_INFO_FIELD_NUMBER = 100
TOPONYM_INFO = _descriptor.FieldDescriptor(
  name='TOPONYM_INFO', full_name='yandex.maps.proto.search.geocoder_internal.TOPONYM_INFO', index=0,
  number=100, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
RESPONSE_INFO_FIELD_NUMBER = 100
RESPONSE_INFO = _descriptor.FieldDescriptor(
  name='RESPONSE_INFO', full_name='yandex.maps.proto.search.geocoder_internal.RESPONSE_INFO', index=1,
  number=100, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)


_HOUSE = _descriptor.Descriptor(
  name='House',
  full_name='yandex.maps.proto.search.geocoder_internal.House',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='yandex.maps.proto.search.geocoder_internal.House.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='point', full_name='yandex.maps.proto.search.geocoder_internal.House.point', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=295,
)


_RESPONSEINFO = _descriptor.Descriptor(
  name='ResponseInfo',
  full_name='yandex.maps.proto.search.geocoder_internal.ResponseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='yandex.maps.proto.search.geocoder_internal.ResponseInfo.accuracy', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='yandex.maps.proto.search.geocoder_internal.ResponseInfo.mode', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='yandex.maps.proto.search.geocoder_internal.ResponseInfo.version', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=410,
)


_MATCHEDCOMPONENT = _descriptor.Descriptor(
  name='MatchedComponent',
  full_name='yandex.maps.proto.search.geocoder_internal.MatchedComponent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kind', full_name='yandex.maps.proto.search.geocoder_internal.MatchedComponent.kind', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=32,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=481,
)


_TOPONYMINFO = _descriptor.Descriptor(
  name='ToponymInfo',
  full_name='yandex.maps.proto.search.geocoder_internal.ToponymInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='geoid', full_name='yandex.maps.proto.search.geocoder_internal.ToponymInfo.geoid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='house_count', full_name='yandex.maps.proto.search.geocoder_internal.ToponymInfo.house_count', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='point', full_name='yandex.maps.proto.search.geocoder_internal.ToponymInfo.point', index=2,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='matched_component', full_name='yandex.maps.proto.search.geocoder_internal.ToponymInfo.matched_component', index=3,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seoname', full_name='yandex.maps.proto.search.geocoder_internal.ToponymInfo.seoname', index=4,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='yandex.maps.proto.search.geocoder_internal.ToponymInfo.tag', index=5,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='house', full_name='yandex.maps.proto.search.geocoder_internal.ToponymInfo.house', index=6,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=794,
)

_HOUSE.fields_by_name['point'].message_type = yandex_dot_maps_dot_proto_dot_common2_dot_geometry__pb2._POINT
_RESPONSEINFO.fields_by_name['mode'].enum_type = _MODE
_MATCHEDCOMPONENT.fields_by_name['kind'].enum_type = yandex_dot_maps_dot_proto_dot_search_dot_kind__pb2._KIND
_TOPONYMINFO.fields_by_name['point'].message_type = yandex_dot_maps_dot_proto_dot_common2_dot_geometry__pb2._POINT
_TOPONYMINFO.fields_by_name['matched_component'].message_type = _MATCHEDCOMPONENT
_TOPONYMINFO.fields_by_name['house'].message_type = _HOUSE
DESCRIPTOR.message_types_by_name['House'] = _HOUSE
DESCRIPTOR.message_types_by_name['ResponseInfo'] = _RESPONSEINFO
DESCRIPTOR.message_types_by_name['MatchedComponent'] = _MATCHEDCOMPONENT
DESCRIPTOR.message_types_by_name['ToponymInfo'] = _TOPONYMINFO
DESCRIPTOR.enum_types_by_name['Mode'] = _MODE
DESCRIPTOR.extensions_by_name['TOPONYM_INFO'] = TOPONYM_INFO
DESCRIPTOR.extensions_by_name['RESPONSE_INFO'] = RESPONSE_INFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

House = _reflection.GeneratedProtocolMessageType('House', (_message.Message,), {
  'DESCRIPTOR' : _HOUSE,
  '__module__' : 'yandex.maps.proto.search.geocoder_internal_pb2'
  # @@protoc_insertion_point(class_scope:yandex.maps.proto.search.geocoder_internal.House)
  })
_sym_db.RegisterMessage(House)

ResponseInfo = _reflection.GeneratedProtocolMessageType('ResponseInfo', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEINFO,
  '__module__' : 'yandex.maps.proto.search.geocoder_internal_pb2'
  # @@protoc_insertion_point(class_scope:yandex.maps.proto.search.geocoder_internal.ResponseInfo)
  })
_sym_db.RegisterMessage(ResponseInfo)

MatchedComponent = _reflection.GeneratedProtocolMessageType('MatchedComponent', (_message.Message,), {
  'DESCRIPTOR' : _MATCHEDCOMPONENT,
  '__module__' : 'yandex.maps.proto.search.geocoder_internal_pb2'
  # @@protoc_insertion_point(class_scope:yandex.maps.proto.search.geocoder_internal.MatchedComponent)
  })
_sym_db.RegisterMessage(MatchedComponent)

ToponymInfo = _reflection.GeneratedProtocolMessageType('ToponymInfo', (_message.Message,), {
  'DESCRIPTOR' : _TOPONYMINFO,
  '__module__' : 'yandex.maps.proto.search.geocoder_internal_pb2'
  # @@protoc_insertion_point(class_scope:yandex.maps.proto.search.geocoder_internal.ToponymInfo)
  })
_sym_db.RegisterMessage(ToponymInfo)

TOPONYM_INFO.message_type = _TOPONYMINFO
yandex_dot_maps_dot_proto_dot_search_dot_geocoder__pb2.GeoObjectMetadata.RegisterExtension(TOPONYM_INFO)
RESPONSE_INFO.message_type = _RESPONSEINFO
yandex_dot_maps_dot_proto_dot_search_dot_geocoder__pb2.ResponseMetadata.RegisterExtension(RESPONSE_INFO)

# @@protoc_insertion_point(module_scope)
