# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/maps/proto/search/search_internal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import commands_pb2 as yandex_dot_maps_dot_proto_dot_search_dot_commands__pb2
from . import search_pb2 as yandex_dot_maps_dot_proto_dot_search_dot_search__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yandex/maps/proto/search/search_internal.proto',
  package='yandex.maps.proto.search.search_internal',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n.yandex/maps/proto/search/search_internal.proto\x12(yandex.maps.proto.search.search_internal\x1a\'yandex/maps/proto/search/commands.proto\x1a%yandex/maps/proto/search/search.proto\"\xcb\x01\n\x0cResponseInfo\x12\x46\n\x07\x64isplay\x18\x01 \x02(\x0e\x32\x35.yandex.maps.proto.search.search_internal.DisplayType\x12\x0f\n\x07\x63ontext\x18\x02 \x02(\t\x12\r\n\x05reqid\x18\x03 \x02(\t\x12\x0e\n\x06serpid\x18\x04 \x01(\t\x12=\n\x08\x63ommands\x18\x06 \x01(\x0b\x32+.yandex.maps.proto.search.commands.CommandsJ\x04\x08\x05\x10\x06*\'\n\x0b\x44isplayType\x12\n\n\x06SINGLE\x10\x01\x12\x0c\n\x08MULTIPLE\x10\x02:\x80\x01\n\rRESPONSE_INFO\x12\x31.yandex.maps.proto.search.search.ResponseMetadata\x18\x64 \x01(\x0b\x32\x36.yandex.maps.proto.search.search_internal.ResponseInfo')
  ,
  dependencies=[yandex_dot_maps_dot_proto_dot_search_dot_commands__pb2.DESCRIPTOR,yandex_dot_maps_dot_proto_dot_search_dot_search__pb2.DESCRIPTOR,])

_DISPLAYTYPE = _descriptor.EnumDescriptor(
  name='DisplayType',
  full_name='yandex.maps.proto.search.search_internal.DisplayType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SINGLE', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTIPLE', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=378,
  serialized_end=417,
)
_sym_db.RegisterEnumDescriptor(_DISPLAYTYPE)

DisplayType = enum_type_wrapper.EnumTypeWrapper(_DISPLAYTYPE)
SINGLE = 1
MULTIPLE = 2

RESPONSE_INFO_FIELD_NUMBER = 100
RESPONSE_INFO = _descriptor.FieldDescriptor(
  name='RESPONSE_INFO', full_name='yandex.maps.proto.search.search_internal.RESPONSE_INFO', index=0,
  number=100, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)


_RESPONSEINFO = _descriptor.Descriptor(
  name='ResponseInfo',
  full_name='yandex.maps.proto.search.search_internal.ResponseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='display', full_name='yandex.maps.proto.search.search_internal.ResponseInfo.display', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='context', full_name='yandex.maps.proto.search.search_internal.ResponseInfo.context', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reqid', full_name='yandex.maps.proto.search.search_internal.ResponseInfo.reqid', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serpid', full_name='yandex.maps.proto.search.search_internal.ResponseInfo.serpid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commands', full_name='yandex.maps.proto.search.search_internal.ResponseInfo.commands', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=376,
)

_RESPONSEINFO.fields_by_name['display'].enum_type = _DISPLAYTYPE
_RESPONSEINFO.fields_by_name['commands'].message_type = yandex_dot_maps_dot_proto_dot_search_dot_commands__pb2._COMMANDS
DESCRIPTOR.message_types_by_name['ResponseInfo'] = _RESPONSEINFO
DESCRIPTOR.enum_types_by_name['DisplayType'] = _DISPLAYTYPE
DESCRIPTOR.extensions_by_name['RESPONSE_INFO'] = RESPONSE_INFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResponseInfo = _reflection.GeneratedProtocolMessageType('ResponseInfo', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEINFO,
  '__module__' : 'yandex.maps.proto.search.search_internal_pb2'
  # @@protoc_insertion_point(class_scope:yandex.maps.proto.search.search_internal.ResponseInfo)
  })
_sym_db.RegisterMessage(ResponseInfo)

RESPONSE_INFO.message_type = _RESPONSEINFO
yandex_dot_maps_dot_proto_dot_search_dot_search__pb2.ResponseMetadata.RegisterExtension(RESPONSE_INFO)

# @@protoc_insertion_point(module_scope)
