\ir ../../../postgresql/supportai_tasks/migrations/V01__initial.sql
\ir ../../../postgresql/supportai_tasks/migrations/V02__editor.sql
\ir ../../../postgresql/supportai_tasks/migrations/V03__chatterbox_project.sql
\ir ../../../postgresql/supportai_tasks/migrations/V04__improve_features.sql
\ir ../../../postgresql/supportai_tasks/migrations/V05__scenario_multiple_rules.sql
\ir ../../../postgresql/supportai_tasks/migrations/V06__drop_scenario_old_rule_value.sql
\ir ../../../postgresql/supportai_tasks/migrations/V07__tasks.sql
\ir ../../../postgresql/supportai_tasks/migrations/V08__update_title_collation.sql
\ir ../../../postgresql/supportai_tasks/migrations/V09__change_task_timestamp_tz.sql
\ir ../../../postgresql/supportai_tasks/migrations/V10__new_statistics.sql
\ir ../../../postgresql/supportai_tasks/migrations/V11__features_clarification.sql
\ir ../../../postgresql/supportai_tasks/migrations/V12__thresholds.sql
\ir ../../../postgresql/supportai_tasks/migrations/V13__expand_topic_slug.sql
\ir ../../../postgresql/supportai_tasks/migrations/V14__compressed_rules.sql
\ir ../../../postgresql/supportai_tasks/migrations/V15__features_default_value.sql
\ir ../../../postgresql/supportai_tasks/migrations/V16__validation_results.sql
\ir ../../../postgresql/supportai_tasks/migrations/V17__NONTRANSACTIONAL_calls.sql
\ir ../../../postgresql/supportai_tasks/migrations/V18__NONTRANSACTIONAL_task_out_calls_results.sql
\ir ../../../postgresql/supportai_tasks/migrations/V19__out_calls_tz.sql
\ir ../../../postgresql/supportai_tasks/migrations/V20__topic_rule.sql
\ir ../../../postgresql/supportai_tasks/migrations/V21__task_processing_state.sql
\ir ../../../postgresql/supportai_tasks/migrations/V22__NONTRANSACTIONAL_new_calls_statuses.sql
\ir ../../../postgresql/supportai_tasks/migrations/V23__scenario_add_multiple_texts.sql
\ir ../../../postgresql/supportai_tasks/migrations/V24__drop_scenario_reply_macros_text.sql
\ir ../../../postgresql/supportai_tasks/migrations/V25__NONTRANSACTIONAL_demo_task_types.sql
\ir ../../../postgresql/supportai_tasks/migrations/V26__outgoing_call_init_time.sql
\ir ../../../postgresql/supportai_tasks/migrations/V27__call_session_id.sql
\ir ../../../postgresql/supportai_tasks/migrations/V28__users_and_roles_to_db.sql
\ir ../../../postgresql/supportai_tasks/migrations/V29__setup_roles.sql
\ir ../../../postgresql/supportai_tasks/migrations/V30__NONTRANSACTIONAL_export_lk_types.sql
\ir ../../../postgresql/supportai_tasks/migrations/V31__project_new_schema.sql
\ir ../../../postgresql/supportai_tasks/migrations/V32__user_login.sql
\ir ../../../postgresql/supportai_tasks/migrations/V33__name_of_task.sql
\ir ../../../postgresql/supportai_tasks/migrations/V34__calls_has_record.sql
\ir ../../../postgresql/supportai_tasks/migrations/V35__capabilities_in_db.sql
\ir ../../../postgresql/supportai_tasks/migrations/V36__drop_unused_tables.sql
\ir ../../../postgresql/supportai_tasks/migrations/V37__configuration_test.sql
\ir ../../../postgresql/supportai_tasks/migrations/V38__NONTRANSACTIONAL_test_configuration_types.sql
\ir ../../../postgresql/supportai_tasks/migrations/V39__event_logs.sql
\ir ../../../postgresql/supportai_tasks/migrations/V40__task_user_id.sql
\ir ../../../postgresql/supportai_tasks/migrations/V41__NONTRANSACTIONAL_export_dialog_history.sql
\ir ../../../postgresql/supportai_tasks/migrations/V42__add_constraint_default_provider_source.sql
\ir ../../../postgresql/supportai_tasks/migrations/V43__add_voice_template_file_id_to_project.sql
\ir ../../../postgresql/supportai_tasks/migrations/V44__testing_aggregation.sql
\ir ../../../postgresql/supportai_tasks/migrations/V45__add_project_slug_non_empty_string_constraint.sql
\ir ../../../postgresql/supportai_tasks/migrations/V46__password.sql
\ir ../../../postgresql/supportai_tasks/migrations/V47__NONTRANSACTIONAL_clear_calls_data.sql
\ir ../../../postgresql/supportai_tasks/migrations/V48__capabilities_presets.sql
\ir ../../../postgresql/supportai_tasks/migrations/V49__common_tasks.sql
\ir ../../../postgresql/supportai_tasks/migrations/V50__NONTRANSACTIONAL_expand_task_types.sql
\ir ../../../postgresql/supportai_tasks/migrations/V51__clustering_results.sql
\ir ../../../postgresql/supportai_tasks/migrations/V52__NONTRANSACTIONAL_clustering_task_type.sql
\ir ../../../postgresql/supportai_tasks/migrations/V53__NONTRANSACTIONAL_upload_rp_task_type.sql
\ir ../../../postgresql/supportai_tasks/migrations/V54__add_tmp_columns_to_tasks_table.sql
