import os

TEST_DOCKERFILE = """
# AUTOGENERATED, DON'T CHANGE THIS FILE!

ARG APP_ENV=production
FROM registry.yandex.net/test-baseimage/${APP_ENV}

LABEL maintainer="Aleksandr Dorodnykh <seanchaidh@yandex-team.ru>"

ARG APP_ROOT

RUN apt-get update -qq

# Link skynet into container
RUN ln -s /Berkanavt/supervisor/base/active /skynet
RUN ln -s /skynet/tools/sky /usr/local/bin/sky

# Install service from deb
ADD services/*.deb /deb/
RUN mv /deb/yandex-taxi-some-project_*.deb /deb/yandex-taxi-some-project.deb || true
RUN apt install -y /deb/yandex-taxi-some-project.deb
"""  # noqa: E501


def test_docker_deploy(monkeypatch, tmpdir, generate_service):
    service_path = generate_service(
        package_name='test_service',
        service_plugins_cfg={
            'docker-deploy': {
                'baseimage': 'test-baseimage',
                'skynet-enabled': True,
            },
        },
    ).path

    with open(os.path.join(service_path, 'Dockerfile')) as file:
        assert file.read() == TEST_DOCKERFILE.lstrip()
