INSERT INTO grocery_performer_mentorship.shifts(shift_id, performer_id,
                                                depot_id, legacy_depot_id,
                                                started_at,
                                                closes_at,
                                                status)
VALUES ('100', '123_101', 'FFF_123', '123', CURRENT_TIMESTAMP + interval '1 hour',
        CURRENT_TIMESTAMP + interval '2 hour',
        'waiting'),
       ('101', '123_102', 'FFF_123', '123', CURRENT_TIMESTAMP + interval '1 hour',
        CURRENT_TIMESTAMP + interval '2 hour',
        'waiting'),
       ('102', '123_102', 'FFF_123', '123', CURRENT_TIMESTAMP + interval '3 hour',
        CURRENT_TIMESTAMP + interval '4 hour',
        'waiting'),
       ('103', '123_103', 'FFF_123', '123', CURRENT_TIMESTAMP + interval '3 hour',
        CURRENT_TIMESTAMP + interval '4 hour',
        'closed'),
       ('104', '123_104', 'FFF_123', '123', CURRENT_TIMESTAMP + interval '3 hour',
        CURRENT_TIMESTAMP + interval '4 hour',
        'in_progress');
