INSERT INTO "agglomerations"."fi_geo_nodes" ("id",
                                             "name",
                                             "tanker_key",
                                             "name_en",
                                             "name_ru",
                                             "node_type",
                                             "parent_name",
                                             "draft_id",
                                             "created_at")
VALUES ('df903a97-fc19-4c08-8513-43ad576775c2',
        'fi_root',
        'name.fi_root',
        'Financial Regions',
        'Финансовые регионы',
        'root',
        NULL,
        'fi_root_draft_id',
        '2021-01-01T00:00:00'),
       ('1d0847ab-c66c-4812-832f-8f2ffca4bdd8',
        'fi_emea',
        'name.fi_emea',
        'EMEA',
        'EMEA',
        'node',
        'fi_root',
        'fi_emea_draft_id',
        '2021-01-01T00:00:00'
       );


INSERT INTO "agglomerations"."br_geo_nodes" ("id",
                                             "name",
                                             "tanker_key",
                                             "name_en",
                                             "name_ru",
                                             "node_type",
                                             "currency",
                                             "parent_name",
                                             "fi_parent_name",
                                             "region_id",
                                             "tags",
                                             "operational_managers",
                                             "regional_managers",
                                             "macro_managers",
                                             "oebs_mvp_id",
                                             "meta_tags",
                                             "has_tariff_zones",
                                             "under_agglomeration",
                                             "draft_id",
                                             "created_at")
VALUES ('d6082411-562e-4b02-8786-fa85a14e3522',
        'br_root',
        'name.br_root',
        'Basic Hierarchy',
        'Базовая иерархия',
        'root',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        FALSE,
        FALSE,
        'br_root_draft_id',
        '2021-01-01T00:00:00'),
       ('73f33067-7f7a-454d-8860-9eed085a7061',
        'br_russia',
        'name.br_russia',
        'Russia',
        'Россия',
        'country',
        'RUB',
        'br_root',
        NULL,
        '225',
        NULL,
        '{"berenda"}',
        NULL,
        NULL,
        NULL,
        NULL,
        FALSE,
        FALSE,
        'br_russia_draft_id',
        '2021-01-01T00:00:00'),
       ('a45517e1-b402-41bd-a9f3-38069be50300',
        'br_kazakhstan',
        'name.br_kazakhstan',
        'Kazakhstan',
        'Казахстан',
        'country',
        'KZT',
        'br_root',
        NULL,
        '159',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        FALSE,
        FALSE,
        'br_kazakhstan_draft_id',
        '2021-01-01T00:00:00'),
       ('75bdf61a-1ccf-4c17-a3d0-8366e2cf2ef9',
        'br_tsentralnyj_fo',
        'name.br_tsentralnyj_fo',
        'Central Federal District',
        'Центральный ФО',
        'node',
        NULL,
        'br_russia',
        NULL,
        '3',
        '{"federal district"}',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        FALSE,
        FALSE,
        'br_tsentralnyj_fo_draft_id',
        '2021-01-01T00:00:00'),
       ('9de24f54-a4a2-4cf9-9fd1-e01ae1914206',
        'br_moskovskaja_obl',
        'name.br_moskovskaja_obl',
        'Moscow Region',
        'Московская область',
        'node',
        NULL,
        'br_tsentralnyj_fo',
        NULL,
        '1',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        FALSE,
        FALSE,
        'br_moskovskaja_obl_draft_id',
        '2021-01-01T00:00:00'),
       ('62f0f9b3-f4b5-4e71-a0a0-320aed78fec1',
        'br_moscow',
        'name.br_moscow',
        'Moscow',
        'Москва',
        'agglomeration',
        NULL,
        'br_moskovskaja_obl',
        'fi_root',
        NULL,
        NULL,
        '{"susloparov"}',
        NULL,
        '{"mikhailra"}',
        'MSKc',
        '{"agglomeration_with_only_br_parent"}',
        FALSE,
        FALSE,
        'br_moscow_draft_id',
        '2021-01-01T00:00:00'),
       ('c25a68a5-75ee-4296-98d8-6a32aa391d57',
        'br_moscow_adm',
        'name.br_moscow_adm',
        'Moscow (adm)',
        'Москва (адм)',
        'node',
        NULL,
        'br_moscow',
        NULL,
        '213',
        NULL,
        NULL,
        NULL,
        NULL,
        'MSKc',
        NULL,
        TRUE,
        TRUE,
        'br_moscow_adm_draft_id',
        '2021-01-01T00:00:00'),
       ('b383ab8c-d14f-43a3-8de1-2704e017c0f7',
        'br_moscow_middle_region',
        'name.br_moscow_middle_region',
        'Moscow (Middle Region)',
        'Москва (среднее)',
        'node',
        NULL,
        'br_moscow',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'br_moscow_oebs_mvp_id',
        NULL,
        FALSE,
        TRUE,
        'br_moscow_middle_region_draft_id',
        '2021-01-01T00:00:00');


INSERT INTO "agglomerations"."tariff_zone" ("name", "geo_node_name")
VALUES ('boryasvo', 'br_moscow_adm'),
       ('moscow', 'br_moscow_adm'),
       ('vko', 'br_moscow_adm');

INSERT INTO "agglomerations"."tariff_zone_oebs_mvp_id" ("created_at", "tariff_zone", "oebs_mvp_id")
VALUES ('2021-01-01T00:00:00', 'boryasvo', 'MSKc'),
       ('2021-01-01T00:00:00', 'moscow', 'MSKc'),
       ('2021-01-01T00:00:00', 'vko', 'MSKc');


INSERT INTO "agglomerations"."op_geo_nodes" ("id",
                                             "name",
                                             "tanker_key",
                                             "name_en",
                                             "name_ru",
                                             "node_type",
                                             "draft_id",
                                             "created_at")
VALUES ('df903a97-fc19-4c08-8513-43ad576775c2',
        'op_root',
        'name.op_root',
        'Operational hierarchy',
        'Операционная иерархия',
        'root',
        'op_root_draft_id',
        '2021-01-01T00:00:00');

INSERT INTO "agglomerations"."br_op_geo_nodes_relations" ("name", "op_parent_name")
VALUES ('br_moscow', 'op_root');
