CREATE ROLE dummy WITH LOGIN PASSWORD 'dummy';
CREATE ROLE taxiro WITH LOGIN PASSWORD 'taxiro';
CREATE DATABASE testdb0;
ALTER DATABASE testdb0 OWNER TO dummy;
CREATE DATABASE testdb1;
ALTER DATABASE testdb1 OWNER TO dummy;
