{
  "ARC_OAUTH_TOKEN": "{{ API_TOKEN_TAXI_INFRA_CLOWNDUCTOR_ARCADIA }}",
  "ARC_OAUTH_TOKENS": {
    "robot-taxi-clown": "{{ API_TOKEN_TAXI_INFRA_CLOWNDUCTOR_ARCADIA }}",
    "robot-taxi-clown-arc": "{{API_TOKEN_TAXI_CLOWNDUCTOR_ROBOT_TAXI_CLOWN_ARC_OAUTH }}"
  }
}
