{
    "mongo_settings": {
        {{ MONGOS_PROXY_TAXI_NONCRITICAL_ANTIFRAUD_PY }},
        {{ MONGOS_PROXY_TAXI_NONCRITICAL_ANTIFRAUD_PY1 }},
        {{ MONGOS_PROXY_TAXI_NONCRITICAL_ANTIFRAUD_PY2 }}
    }
}
