ACCEPTANCE_AUTOTEST_PARAMS = [
    '-w ru',
    '-w ua',
    '-w com.tr',
    '-w weather',
    '-w tune',
    '-w oid2addr',
    '--threads=32',
    '-t //home/qreg/tests_data/',
    '-i beru',
    '-i ci_abidjan_tests',
    '-i ci_poland_tests',
    '-i common',
    '-i nyak',
    '-i personal_data',
    '-i simple_clicks_10k_2017-03-01_2017-03-15.taxi',
    '-i str_num_test7',
    '-i street_house7',
    '-i surveys',
    '-i syntetic_israel_toponyms_tests',
    '-i transit',
    '-i tur_tests.oid',
    '-i tur_tests1',
    '-i tur_tests2',
    '-i weather'
]

ACCEPTANCE_QUALITY_CONDITIONS = [
    {'suite_regex': '.*taxi_israel.*all', 'delta_percent': 3},
    {'suite_regex': '//home/qreg/tests_data/.*', 'delta_percent': 2},
    {'suite_regex': '//home/qreg/tests_data/query_.*', 'delta_percent': 5},
    {'suite_regex': 'com.tr', 'delta_percent': 3},
    {'suite_regex': 'oid2addr', 'delta_percent': 3},
    {'suite_regex': 'ru', 'delta_percent': 3},
    {'suite_regex': 'tune', 'delta_percent': 3},
    {'suite_regex': 'ua', 'delta_percent': 3},
    {'suite_regex': 'beru', 'max_failed': 0},
    {'suite_regex': 'ci_abidjan_tests', 'delta_percent': 3},
    {'suite_regex': 'ci_poland_tests', 'delta_percent': 1},
    {'suite_regex': 'common', 'max_failed': 0},
    {'suite_regex': 'nyak', 'max_failed': 0},
    {'suite_regex': 'personal_data', 'max_failed': 0},
    {'suite_regex': 'simple_clicks_10k_2017-03-01_2017-03-15.taxi', 'delta_percent': 1},
    {'suite_regex': 'str_num_test7', 'delta_percent': 1},
    {'suite_regex': 'street_house7', 'delta_percent': 1},
    {'suite_regex': 'surveys', 'max_failed': 0},
    {'suite_regex': 'syntetic_israel_toponyms_tests', 'delta_percent': 1},
    {'suite_regex': 'transit', 'delta_percent': 3},
    {'suite_regex': 'tur_tests.oid', 'delta_percent': 3},
    {'suite_regex': 'tur_tests1', 'delta_percent': 3},
    {'suite_regex': 'tur_tests2', 'delta_percent': 3},
    {'suite_regex': 'weather', 'delta_percent': 3},
    {'suite_regex': 'Total'}
]
