INSERT INTO
    deptrans.session_statuses(
        driver_license_pd_id,
        session_status,
        session_deny_reason,
        ended_at,
        is_driver_online
    )
VALUES
    (
        'driver_license_pd_id_1',
        'SESSION_DENIED',
        'MEDICAL_CHECKUP_NOT_PASSED',
        NOW(),
        True
    ),
    (
        'driver_license_pd_id_2',
        'NO_WAYBILL',
        NULL,
        NOW(),
        False
    ),
    (
        'driver_license_pd_id_3',
        'SESSION_DENIED',
        'DRIVER_INVALID',
        NOW(),
        True
    );
