INSERT INTO partner(id, category, name, logo, comment, created_by, created_at, updated_by, updated_at)
VALUES (1,
        'food',
        'Big zombie shop',
        'https://example.com/image.jpg',
        'Some comment text',
        'valery',
        '2019-05-26 19:10:25+3',
        'valery',
        '2019-05-26 19:10:25+3'),
       (2,
        'fix',
        'Remonters',
        'https://tipsy.com/image.jpg',
        'Some comment text',
        'valery',
        '2019-05-26 19:10:25+3',
        'valery',
        '2019-05-26 19:10:25+3'),
       (3,
        'carwash',
        'Washers',
        'https://lemon.com/image.jpg',
        'Some comment text',
        'valery',
        '2019-05-26 19:10:25+3',
        'valery',
        '2019-05-26 19:10:25+3');

INSERT INTO location(business_oid, partner_id, longitude, latitude, country, city, address, name, work_time_intervals,
                     tz_offset)
VALUES (11,
        1,
        40.5,
        80.4,
        'Russia',
        'Moscow',
        'Москва, Лубянка, 5',
        'Big zombie shop',
        '[]'::JSONB,
        0),
       (21,
        2,
        40.5,
        80.4,
        'Russia',
        'Moscow',
        'Москва, Лубянка, 5',
        'Remonters',
        '[]'::JSONB,
        0),
       (31,
        3,
        40.5,
        80.4,
        'Russia',
        'Moscow',
        'Москва, Лубянка, 5',
        'Washers',
        '[]'::JSONB,
        0);
