INSERT INTO fleet.park_order (
  park_id,
  id,
  number,
  last_order_alias_id,
  status,
  tariff_class,
  personal_phone_id,
  address_from,
  addresses_to,
  geopoint_from,
  geopoints_to,
  created_at,
  is_creator,
  event_index,
  last_contractor_park_id,
  last_contractor_id,
  last_contractor_car_id,
  record_created_at,
  record_updated_at,
  update_seq_no
)
VALUES (
  'park_id1',
  'order1',
  1,
  'order_alias_id1',
  'transporting',
  'econom',
  'phone_id1',
  'address_A',
  ARRAY['address_B1', 'address_B2'],
  '{37.6, 50.6}',
  '{{37.6, 51.6}, {37.6, 52.6}}',
  '2021-02-09T17:00:00Z',
  True,
  2,
  'park_id1',
  'contractor_id1',
  'car_id1',
  '2021-02-09T19:00:00Z',
  '2021-02-09T19:00:00Z',
  1
);
