include:
  -  mongos-local.mongos.taxi_test_db_mongo_billing
  -  mongos-local.mongos.taxi_test_db_mongo_gprs_timings
  -  mongos-local.mongos.taxi_test_db_mongo_histat
  -  mongos-local.mongos.taxi_test_db_mongo_main
  -  mongos-local.mongos.taxi_test_db_mongo_minor
  -  mongos-local.mongos.taxi_test_db_mongo_pda
  -  mongos-local.mongos.taxi_test_db_mongo_personal
  -  mongos-local.mongos.taxi_test_db_mongo_phone
  -  mongos-local.mongos.taxi_test_db_mongo_subs
  -  mongos-local.mongos.taxi_test_db_mongo_support
  -  mongos-local.mongos.taxi_test_db_mongo_taximeter_logs
  -  mongos-local.mongos.taxi_test_db_mongo_tracker
  -  mongos-local.mongos.taxi_test_db_mongo_users
  -  mongos-local.mongos.taxi_test_db_mongo_dbarchive
  -  mongos-local.mongos.taxi_test_db_mongo_dbarchive1
  -  mongos-local.mongos.taxi_test_db_mongo_dbarchive3
  -  mongos-local.mongos.taxi_test_db_mongo_antifraud
