#!/bin/sh

set -e

case "$1" in
    configure)
        update-alternatives --install /usr/bin/cc cc /usr/bin/clang-7 30
        update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-7 30
        systemctl disable postgresql.service ||:
        service postgresql stop ||:
        if ! grep -q "^user_allow_other$" /etc/fuse.conf; then
            echo "user_allow_other" >> /etc/fuse.conf
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
