#!/bin/sh

set -e

case "$1" in
    configure)
        systemctl disable postgresql.service ||:
        service postgresql stop ||:
        if [ -d /home/buildfarm/teamcity/projects ]; then
            setfacl -dm u:buildfarm:rwX /home/buildfarm/teamcity/projects ||:
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
