import datetime


def mongo_after_create_unusual() -> list:
    return [
        {
            'b': datetime.datetime(2001, 12, 12, 9, 0),
            'e': datetime.datetime(2001, 12, 12, 10, 0),
            'bv': {'bcd': 42, 'p_max': 2, 'p_min': 1, 'u_max': 2, 'u_min': 1},
            'cm': {
                'acp': 0,
                'agp': 420000,
                'bd': [
                    {
                        'marketing_level': ['sfsfdsfsdfs'],
                        'value': 123122130000,
                    },
                ],
                'callcenter_commission_percent': 420000,
                'cp': 0,
                'd': {},
                'ec': 320000,
                'ep': 420000,
                'hacp': True,
                'has_fixed_cancel_percent': False,
                'hc': True,
                'hiring': {
                    'extra_percent': 420000,
                    'extra_percent_with_rent': 420000,
                    'max_age_in_seconds': 3628800,
                },
                'max': 120000,
                'min': 420000,
                'p': 420000,
                't': 'fixed_percent',
                'taximeter_payment': 420000,
                'vat': 130000,
            },
            'external_id': 'no_acquiring',
            'cn': {'p': 'cash', 'tariff_class': 'econom', 'z': 'moscow'},
            'status': 'draft',
        },
    ]


def mongo_after_create() -> list:
    return [
        {
            'b': datetime.datetime(2001, 12, 12, 9, 0),
            'bv': {'bcd': 42, 'p_max': 2, 'p_min': 1, 'u_max': 2, 'u_min': 1},
            'cm': {
                'acp': 420000,
                'agp': 420000,
                'bd': [
                    {
                        'marketing_level': ['sfsfdsfsdfs'],
                        'value': 123122130000,
                    },
                ],
                'callcenter_commission_percent': 420000,
                'cp': 0,
                'd': {
                    'asymp': 420000,
                    'cost_norm': 420000,
                    'max_commission_percent': 420000,
                    'numerator': 420000,
                },
                'ec': 320000,
                'ep': 420000,
                'hacp': True,
                'has_fixed_cancel_percent': True,
                'hc': True,
                'hiring': {
                    'extra_percent': 420000,
                    'extra_percent_with_rent': 420000,
                    'max_age_in_seconds': 3628800,
                },
                'max': 120000,
                'min': 420000,
                'p': 0,
                't': 'asymptotic_formula',
                'taximeter_payment': 420000,
                'vat': 130000,
            },
            'cn': {'p': 'cash', 'tag': 'xyz', 'z': 'moscow'},
            'external_id': '42',
            'status': 'draft',
        },
        {
            'b': datetime.datetime(2001, 12, 12, 9, 0),
            'bv': {'bcd': 42, 'p_max': 2, 'p_min': 1, 'u_max': 2, 'u_min': 1},
            'cm': {
                'acp': 420000,
                'agp': 420000,
                'bd': [
                    {
                        'marketing_level': ['sfsfdsfsdfs'],
                        'value': 123122130000,
                    },
                ],
                'callcenter_commission_percent': 420000,
                'cp': 420000,
                'd': {},
                'ec': 320000,
                'ep': 420000,
                'hacp': True,
                'has_fixed_cancel_percent': True,
                'hc': True,
                'hiring': {
                    'extra_percent': 420000,
                    'extra_percent_with_rent': 420000,
                    'max_age_in_seconds': 3628800,
                },
                'max': 120000,
                'min': 420000,
                'p': 420000,
                't': 'fixed_percent',
                'taximeter_payment': 420000,
                'vat': 11200,
            },
            'cn': {
                'p': 'cash',
                'tag': 'xyz',
                'tariff_class': 'econom',
                'z': 'moscow',
            },
            'e': datetime.datetime(2001, 12, 12, 10, 0),
            'external_id': '43',
            'status': 'draft',
        },
        {
            'b': datetime.datetime(2001, 12, 12, 9, 0),
            'bv': {'bcd': 42, 'p_max': 2, 'p_min': 1, 'u_max': 2, 'u_min': 1},
            'cm': {
                'acp': 420000,
                'agp': 420000,
                'bd': [
                    {
                        'marketing_level': ['sfsfdsfsdfs'],
                        'value': 123122130000,
                    },
                ],
                'callcenter_commission_percent': 420000,
                'cp': 0,
                'd': {
                    'cancel_commission': 420000,
                    'commission': 420000,
                    'expired_commission': 420000,
                },
                'ec': 320000,
                'ep': 0,
                'hacp': True,
                'has_fixed_cancel_percent': True,
                'hc': True,
                'hiring': {
                    'extra_percent': 420000,
                    'extra_percent_with_rent': 420000,
                    'max_age_in_seconds': 3628800,
                },
                'max': 120000,
                'min': 420000,
                'p': 0,
                't': 'absolute_value',
                'taximeter_payment': 420000,
                'vat': 130000,
            },
            'cn': {
                'p': 'cash',
                'tag': 'xyz',
                'tariff_class': 'econom',
                'z': 'moscow',
            },
            'e': datetime.datetime(2001, 12, 12, 10, 0),
            'external_id': '44',
            'status': 'draft',
        },
    ]


def mongo_after_create_approve() -> list:
    return [
        {
            'b': datetime.datetime(2000, 12, 12, 9, 0),
            'e': datetime.datetime(2001, 12, 12, 9, 0),
            'bv': {'bcd': 42, 'p_max': 2, 'p_min': 1, 'u_max': 2, 'u_min': 1},
            'cm': {
                'acp': 420000,
                'agp': 420000,
                'bd': [
                    {
                        'marketing_level': ['sfsfdsfsdfs'],
                        'value': 123122130000,
                    },
                ],
                'callcenter_commission_percent': 420000,
                'cp': 420000,
                'd': {
                    'asymp': 420000,
                    'cost_norm': 420000,
                    'max_commission_percent': 420000,
                    'numerator': 420000,
                },
                'ec': 320000,
                'ep': 420000,
                'hacp': True,
                'has_fixed_cancel_percent': True,
                'hc': True,
                'hiring': {
                    'extra_percent': 420000,
                    'extra_percent_with_rent': 420000,
                    'max_age_in_seconds': 3628800,
                },
                'max': 120000,
                'min': 420000,
                'p': 0,
                't': 'asymptotic_formula',
                'taximeter_payment': 420000,
                'vat': 120000,
            },
            'log': [
                {
                    'login': 'author',
                    'e': datetime.datetime(2001, 12, 12, 9, 0),
                    'ticket': 'RUPRICE-55',
                },
            ],
            'cn': {'p': 'cash', 'tariff_class': 'econom', 'z': 'moscow'},
            'external_id': '41',
        },
        {
            'b': datetime.datetime(2001, 12, 12, 9, 0),
            'bv': {'bcd': 42, 'p_max': 2, 'p_min': 1, 'u_max': 2, 'u_min': 1},
            'cm': {
                'acp': 420000,
                'agp': 420000,
                'bd': [
                    {
                        'marketing_level': ['sfsfdsfsdfs'],
                        'value': 123122130000,
                    },
                ],
                'callcenter_commission_percent': 420000,
                'cp': 420000,
                'd': {
                    'asymp': 420000,
                    'cost_norm': 420000,
                    'max_commission_percent': 420000,
                    'numerator': 420000,
                },
                'ec': 320000,
                'ep': 420000,
                'hacp': True,
                'has_fixed_cancel_percent': True,
                'hc': True,
                'hiring': {
                    'extra_percent': 420000,
                    'extra_percent_with_rent': 420000,
                    'max_age_in_seconds': 3628800,
                },
                'max': 120000,
                'min': 420000,
                'p': 0,
                't': 'asymptotic_formula',
                'taximeter_payment': 420000,
                'vat': 120000,
            },
            'log': [
                {
                    'login': 'author',
                    'status': 'approved',
                    'ticket': 'RUPRICE-55',
                },
            ],
            'cn': {'p': 'cash', 'tariff_class': 'econom', 'z': 'moscow'},
            'external_id': '42',
            'status': 'approved',
        },
        {
            'b': datetime.datetime(1999, 12, 12, 9, 0),
            'bv': {'bcd': 42, 'p_max': 2, 'p_min': 1, 'u_max': 2, 'u_min': 1},
            'cm': {
                'acp': 420000,
                'agp': 420000,
                'bd': [
                    {
                        'marketing_level': ['sfsfdsfsdfs'],
                        'value': 123122130000,
                    },
                ],
                'callcenter_commission_percent': 420000,
                'cp': 420000,
                'd': {
                    'asymp': 420000,
                    'cost_norm': 420000,
                    'max_commission_percent': 420000,
                    'numerator': 420000,
                },
                'ec': 320000,
                'ep': 420000,
                'hacp': True,
                'has_fixed_cancel_percent': True,
                'hc': True,
                'hiring': {
                    'extra_percent': 420000,
                    'extra_percent_with_rent': 420000,
                    'max_age_in_seconds': 3628800,
                },
                'max': 120000,
                'min': 420000,
                'p': 0,
                't': 'asymptotic_formula',
                'taximeter_payment': 420000,
                'vat': 120000,
            },
            'cn': {'p': 'cash', 'tariff_class': 'econom', 'z': 'moscow'},
            'external_id': '42.1',
            'status': 'draft',
        },
        {
            'b': datetime.datetime(2001, 12, 12, 9, 0),
            'bv': {'bcd': 42, 'p_max': 2, 'p_min': 1, 'u_max': 2, 'u_min': 1},
            'cm': {
                'acp': 420000,
                'agp': 420000,
                'bd': [
                    {
                        'marketing_level': ['sfsfdsfsdfs'],
                        'value': 123122130000,
                    },
                ],
                'callcenter_commission_percent': 420000,
                'cp': 420000,
                'd': {
                    'asymp': 420000,
                    'cost_norm': 420000,
                    'max_commission_percent': 420000,
                    'numerator': 420000,
                },
                'ec': 320000,
                'ep': 420000,
                'hacp': True,
                'has_fixed_cancel_percent': True,
                'hc': True,
                'hiring': {
                    'extra_percent': 420000,
                    'extra_percent_with_rent': 420000,
                    'max_age_in_seconds': 3628800,
                },
                'max': 120000,
                'min': 420000,
                'p': 0,
                't': 'asymptotic_formula',
                'taximeter_payment': 420000,
                'vat': 120000,
            },
            'cn': {'p': 'cash', 'tariff_class': 'econom', 'z': 'moscow'},
            'external_id': '43',
            'status': 'draft',
        },
    ]
