def make_rules():
    return {
        '14-15-5percent': {
            'start_ts': '2021-09-08T14:00:00.372+03:00',
            'finish_ts': '2021-09-08T15:00:00.372+03:00',
            'ticket': 'ticket',
            'campaign_name': 'campaign_name',
            'issuer': 'issuer',
            'percent': '5',
            'description': 'description',
        },
        '15-16-3percent': {
            'start_ts': '2021-09-08T15:00:00.372+03:00',
            'finish_ts': '2021-09-08T16:00:00.372+03:00',
            'ticket': 'ticket',
            'campaign_name': 'campaign_name',
            'issuer': 'issuer',
            'percent': '3',
            'description': 'description',
        },
        '14:20-14:30-10percent': {
            'start_ts': '2021-09-08T14:20:00.372+03:00',
            'finish_ts': '2021-09-08T14:30:00.372+03:00',
            'ticket': 'ticket',
            'campaign_name': 'campaign_name',
            'issuer': 'issuer',
            'percent': '10',
            'description': 'description',
        },
        'taxi_rule-15percent': {
            'start_ts': '2021-09-08T12:00:00.372+03:00',
            'finish_ts': '2021-09-08T20:00:00.372+03:00',
            'ticket': 'ticket',
            'campaign_name': 'campaign_name',
            'issuer': 'issuer',
            'percent': '15',
            'description': 'description',
            'only_ya_services': True,
            'merchant_names': ['MERCHANT_TAXI'],
        },
        'ya_services_rule-1percent': {
            'start_ts': '2021-09-08T15:30:00.372+03:00',
            'finish_ts': '2021-10-08T20:00:00.372+03:00',
            'percent': '1',
            'description': 'description',
            'ticket': 'ticket',
            'campaign_name': 'campaign_name',
            'issuer': 'issuer',
            'only_ya_services': True,
        },
        'specific_mcc_rule-5percent': {
            'start_ts': '2021-09-08T14:00:00.372+03:00',
            'finish_ts': '2021-09-08T15:00:00.372+03:00',
            'percent': '5',
            'description': 'description',
            'ticket': 'ticket',
            'campaign_name': 'campaign_name',
            'issuer': 'issuer',
            'mcc_list': ['3456'],
        },
        'first_rub_rule': {
            'start_ts': '2022-01-02T14:00:00.372+03:00',
            'finish_ts': '2022-01-03T15:00:00.372+03:00',
            'percent': '5',
            'description': 'description',
            'is_money_rule': True,
            'execution_moment': 'MONTH_END',
            'execution_trigger': 'DELIVERY',
            'ticket': 'ticket',
            'campaign_name': 'campaign_name',
            'issuer': 'issuer',
        },
        'first_product_id_rule': {
            'start_ts': '2022-01-02T16:00:00.372+03:00',
            'finish_ts': '2022-01-03T17:00:00.372+03:00',
            'percent': '5',
            'description': 'description',
            'execution_moment': 'MONTH_END',
            'execution_trigger': 'DELIVERY',
            'ticket': 'ticket',
            'campaign_name': 'campaign_name',
            'issuer': 'issuer',
            'product_id': 'product_id',
        },
        'same_rule_as_above_without_product_id': {
            'start_ts': '2022-01-02T16:00:00.372+03:00',
            'finish_ts': '2022-01-03T17:00:00.372+03:00',
            'percent': '5',
            'description': 'description',
            'execution_moment': 'MONTH_END',
            'execution_trigger': 'DELIVERY',
            'ticket': 'ticket',
            'campaign_name': 'campaign_name',
            'issuer': 'issuer',
        },
        'new_rule_for_ya_card': {
            'start_ts': '2022-01-04T14:00:00.372+03:00',
            'finish_ts': '2022-01-05T15:00:00.372+03:00',
            'percent': '5',
            'description': 'description',
            'is_money_rule': False,
            'execution_moment': 'MONTH_END',
            'execution_trigger': 'DELIVERY',
            'transaction_status': 'CLEAR',
            'product_id': 'ya_card_product_id',
            'ticket': 'ticket',
            'campaign_name': 'campaign_name',
            'issuer': 'issuer',
        },
        'new_rule_for_driver_card': {
            'start_ts': '2022-01-04T14:00:00.372+03:00',
            'finish_ts': '2022-01-05T15:00:00.372+03:00',
            'percent': '5',
            'description': 'description',
            'is_money_rule': False,
            'execution_moment': 'MONTH_END',
            'execution_trigger': 'DELIVERY',
            'transaction_status': 'CLEAR',
            'product_id': 'driver_card_product_id',
            'ticket': 'ticket',
            'campaign_name': 'campaign_name',
            'issuer': 'issuer',
        },
        'only_clear_rule': {
            'start_ts': '2022-01-06T16:00:00.372+03:00',
            'finish_ts': '2022-01-07T17:00:00.372+03:00',
            'percent': '5',
            'description': 'description',
            'is_money_rule': False,
            'execution_moment': 'NOW',
            'execution_trigger': 'NOW',
            'transaction_status': 'CLEAR',
            'ticket': 'ticket',
            'campaign_name': 'campaign_name',
            'issuer': 'issuer',
        },
        'only_clear_rule_with_execute_status_clear': {
            'start_ts': '2022-01-06T16:00:00.372+03:00',
            'finish_ts': '2022-01-07T17:00:00.372+03:00',
            'percent': '5',
            'description': 'description',
            'is_money_rule': False,
            'execution_moment': 'NOW',
            'execution_trigger': 'NOW',
            'execution_status': 'CLEAR',
            'transaction_status': 'CLEAR',
            'ticket': 'ticket',
            'campaign_name': 'campaign_name2',
            'issuer': 'issuer',
        },
        'only_clear_rule_with_execute_status_hold': {
            'start_ts': '2020-01-06T16:00:00.372+03:00',
            'finish_ts': '2020-01-07T17:00:00.372+03:00',
            'percent': '5',
            'description': 'description',
            'is_money_rule': False,
            'execution_moment': 'NOW',
            'execution_trigger': 'NOW',
            'execution_status': 'HOLD',
            'transaction_status': 'CLEAR',
            'ticket': 'ticket',
            'campaign_name': 'campaign_name3',
            'issuer': 'issuer',
            'bank_commission_irf_rate': '1',
            'bank_commission_acquiring_rate': '2',
            'issued_in': 'non_ico',
        },
    }


def make_service_info():
    return {
        'TAXI': {
            'merchant_name': 'MERCHANT_TAXI',
            'mcc': '567',
            'service_id': 'taxi_service_id',
        },
        'EDA': {
            'merchant_name': 'MERCHANT_EDA',
            'mcc': '678',
            'service_id': 'eda_service_id',
        },
    }
