ES_RESPONSE_EXAMPLE_WITH_LOGS = {
    'took': 504,
    'timed_out': False,
    '_shards': {'total': 161, 'successful': 161, 'failed': 0},
    'hits': {
        'total': 3,
        'max_score': None,
        'hits': [
            {
                '_index': 'yandex-taxi-2019.06.04.11',
                '_type': 'response',
                '_id': 'AWsiPG3R9ieCrAgIdCaK',
                '_score': None,
                '_source': {
                    '@timestamp': '2019-06-04T11:25:13.974Z',
                    'module': 'taxi.util.aiohttp_kit.middleware',
                    'level': 'INFO',
                    'link': '291c7a1c2d2447c9a47a943999e7d2d1',
                    'type': 'response',
                    'host': 'crons-sas-01.taxi.dev.yandex.net',
                    'uri': 'uri',
                    'method': 'POST',
                    'meta_type': 'v1/task/{name}/lock/prolong',
                    'meta_code': 200,
                    'parent_link': 'None',
                    'span_id': 'f4b555796dac4d2cbc10914c8f8a0ff8',
                    'trace_id': '92f3860dced744b9986863716ee2e071',
                    'stopwatch_name': 'api',
                    'total_time': '0.009348392486572266',
                    'delay': '0.009348392486572266',
                    'body': 'None',
                    'text': 'POST',
                    'tags': ['_pilorama_parsed'],
                    'cgroups': ['taxi_unstable_crons'],
                    'path': '/var/log/yandex/taxi-crons-web/taxi.log',
                    'message': 'tskv',
                },
                'sort': [1559647513974],
            },
            {
                '_index': 'yandex-taxi-2019.06.04.11',
                '_type': 'request',
                '_id': 'AWsiPG3R9ieCrAgIdCaD',
                '_score': None,
                '_source': {
                    '@timestamp': '2019-06-04T11:25:13.964Z',
                    'module': 'taxi.util.aiohttp_kit.middleware',
                    'level': 'INFO',
                    'link': '291c7a1c2d2447c9a47a943999e7d2d1',
                    'type': 'request',
                    'host': 'crons-sas-01.taxi.dev.yandex.net',
                    'uri': 'uri',
                    'method': 'POST',
                    'meta_type': 'v1/task/{name}/lock/prolong',
                    'parent_link': 'None',
                    'span_id': 'f4b555796dac4d2cbc10914c8f8a0ff8',
                    'trace_id': '92f3860dced744b9986863716ee2e071',
                    'useragent': 'python-requests/2.10.0',
                    'body': '{}',
                    'text': 'POST',
                    'tags': ['_pilorama_parsed'],
                    'cgroups': ['taxi_unstable_crons'],
                    'path': '/var/log/yandex/taxi-crons-web/taxi.log',
                    'message': 'tskv',
                },
                'sort': [1559647513964],
            },
            {
                '_index': 'yandex-taxi-2019.06.04.11',
                '_type': 'log',
                '_id': 'AWsiPG3R9ieCrAgIdCad',
                '_score': None,
                '_source': {
                    '@timestamp': '2019-06-04T11:25:13.964Z',
                    'module': 'taxi.util.aiohttp_kit.middleware',
                    'level': 'INFO',
                    'link': '291c7a1c2d2447c9a47a943999e7d2d1',
                    'type': 'log',
                    'host': 'crons-sas-01.taxi.dev.yandex.net',
                    'uri': 'uri',
                    'method': 'POST',
                    'meta_type': 'v1/task/{name}/lock/prolong',
                    'parent_link': 'None',
                    'span_id': 'f4b555796dac4d2cbc10914c8f8a0ff8',
                    'trace_id': '92f3860dced744b9986863716ee2e071',
                    'useragent': 'python-requests/2.10.0',
                    'text': 'all ok',
                    'tags': ['_pilorama_parsed'],
                    'cgroups': ['taxi_unstable_crons'],
                    'path': '/var/log/yandex/taxi-crons-web/taxi.log',
                    'message': 'tskv',
                },
                'sort': [1559647513964],
            },
            {
                '_index': 'yandex-taxi-2019.06.04.11',
                '_type': 'log',
                '_id': 'AWsiPG3R9ieCrAgIdCad',
                '_score': None,
                '_source': {
                    '@timestamp': '2019-06-04T11:25:13.964Z',
                    'module': 'taxi.util.aiohttp_kit.middleware',
                    'level': 'TRACE',
                    'link': '291c7a1c2d2447c9a47a943999e7d2d1',
                    'type': 'log',
                    'host': 'crons-sas-01.taxi.dev.yandex.net',
                    'uri': 'uri',
                    'method': 'POST',
                    'meta_type': 'v1/task/{name}/lock/prolong',
                    'parent_link': 'None',
                    'span_id': 'f4b555796dac4d2cbc10914c8f8a0ff8',
                    'trace_id': '92f3860dced744b9986863716ee2e071',
                    'useragent': 'python-requests/2.10.0',
                    'text': 'all ok',
                    'tags': ['_pilorama_parsed'],
                    'cgroups': ['taxi_unstable_crons'],
                    'path': '/var/log/yandex/taxi-crons-web/taxi.log',
                    'message': 'tskv',
                },
                'sort': [1559647513964],
            },
        ],
    },
}
ES_RESPONSE_EXAMPLE_WITHOUT_LOGS = {
    'took': 504,
    'timed_out': False,
    '_shards': {'total': 161, 'successful': 161, 'failed': 0},
    'hits': {
        'total': 2,
        'max_score': None,
        'hits': [
            {
                '_index': 'yandex-taxi-2019.06.04.11',
                '_type': 'response',
                '_id': 'AWsiPG3R9ieCrAgIdCaK',
                '_score': None,
                '_source': {
                    '@timestamp': '2019-06-04T11:25:13.974Z',
                    'module': 'taxi.util.aiohttp_kit.middleware',
                    'level': 'INFO',
                    'link': '291c7a1c2d2447c9a47a943999e7d2d1',
                    'type': 'response',
                    'host': 'crons-sas-01.taxi.dev.yandex.net',
                    'uri': 'uri',
                    'method': 'POST',
                    'meta_type': 'v1/task/{name}/lock/prolong',
                    'meta_code': 200,
                    'parent_link': 'None',
                    'span_id': 'f4b555796dac4d2cbc10914c8f8a0ff8',
                    'trace_id': '92f3860dced744b9986863716ee2e071',
                    'stopwatch_name': 'api',
                    'total_time': '0.009348392486572266',
                    'delay': '0.009348392486572266',
                    'body': 'None',
                    'text': 'POST',
                    'tags': ['_pilorama_parsed'],
                    'cgroups': ['taxi_unstable_crons'],
                    'path': '/var/log/yandex/taxi-crons-web/taxi.log',
                    'message': 'tskv',
                },
                'sort': [1559647513974],
            },
            {
                '_index': 'yandex-taxi-2019.06.04.11',
                '_type': 'request',
                '_id': 'AWsiPG3R9ieCrAgIdCaD',
                '_score': None,
                '_source': {
                    '@timestamp': '2019-06-04T11:25:13.964Z',
                    'module': 'taxi.util.aiohttp_kit.middleware',
                    'level': 'INFO',
                    'link': '291c7a1c2d2447c9a47a943999e7d2d1',
                    'type': 'request',
                    'host': 'crons-sas-01.taxi.dev.yandex.net',
                    'uri': 'uri',
                    'method': 'POST',
                    'meta_type': 'v1/task/{name}/lock/prolong',
                    'parent_link': 'None',
                    'span_id': 'f4b555796dac4d2cbc10914c8f8a0ff8',
                    'trace_id': '92f3860dced744b9986863716ee2e071',
                    'useragent': 'python-requests/2.10.0',
                    'body': '{}',
                    'text': 'POST',
                    'tags': ['_pilorama_parsed'],
                    'cgroups': ['taxi_unstable_crons'],
                    'path': '/var/log/yandex/taxi-crons-web/taxi.log',
                    'message': 'tskv',
                },
                'sort': [1559647513964],
            },
        ],
    },
}

ES_RESPONSE_EXAMPLE_EMPTY = {
    'took': 504,
    'timed_out': False,
    '_shards': {'total': 161, 'successful': 161, 'failed': 0},
    'hits': {'total': 0, 'max_score': None, 'hits': []},
}

ES_RESPONSE_CRONS_EMPTY = {
    'took': 504,
    'timed_out': False,
    '_shards': {'total': 161, 'successful': 161, 'failed': 0},
    'hits': {'total': 0, 'max_score': None, 'hits': []},
}
ES_RESPONSE_CRONS_SOME_LOGS = {
    'took': 504,
    'timed_out': False,
    '_shards': {'total': 161, 'successful': 161, 'failed': 0},
    'hits': {
        'total': 2,
        'max_score': None,
        'hits': [
            {
                '_index': 'yandex-taxi-import-2019.06.26',
                '_type': 'log',
                '_id': 'AWuTPpBjmR-5viHCZHR3',
                '_score': None,
                '_source': {
                    '@timestamp': '2019-06-26T10:00:10.347Z',
                    'module': 'taxi.maintenance.run',
                    'level': 'INFO',
                    'link': '4a0e7cd4847c4f96be3af750cd06d6bf',
                    'type': 'log',
                    'host': 'imports-py3-sas-01.taxi.yandex.net',
                    'command': (
                        'replication-archive-' 'queue_mongo-dm_storage_events'
                    ),
                    'text': (
                        'Starting replication-archive-'
                        'queue_mongo-dm_storage_events, pid 6623'
                    ),
                    'tags': ['_pilorama_parsed'],
                    'cgroups': [
                        'taxi_prestable_all',
                        'taxi_imports_py3',
                        'taxi_prestable_imports_py3',
                    ],
                    'path': '/var/log/yandex/taxi-replication-cron/taxi.log',
                },
            },
            {
                '_index': 'yandex-taxi-import-2019.06.26',
                '_type': 'log',
                '_id': 'AWuTPpBkmR-5viHCZHiX',
                '_score': None,
                '_source': {
                    '@timestamp': '2019-06-26T10:00:17.275Z',
                    'module': 'taxi.maintenance.run',
                    'level': 'INFO',
                    'link': '4a0e7cd4847c4f96be3af750cd06d6bf',
                    'type': 'log',
                    'host': 'imports-py3-sas-01.taxi.yandex.net',
                    'command': (
                        'replication-archive-' 'queue_mongo-dm_storage_events'
                    ),
                    'text': (
                        'Finished replication-archive-'
                        'queue_mongo-dm_storage_events '
                        'successfully, pid 6623'
                    ),
                    'tags': ['_pilorama_parsed'],
                    'cgroups': [
                        'taxi_prestable_all',
                        'taxi_imports_py3',
                        'taxi_prestable_imports_py3',
                    ],
                    'path': '/var/log/yandex/taxi-replication-cron/taxi.log',
                },
            },
        ],
    },
}

ES_RESPONSE_EXAMPLE_REQUESTS = {
    'took': 504,
    'timed_out': False,
    '_shards': {'total': 161, 'successful': 161, 'failed': 0},
    'hits': {
        'total': 1,
        'max_score': None,
        'hits': [
            {
                '_index': 'yandex-taxi-2019.06.04.11',
                '_type': 'request',
                '_id': 'AWsiPG3R9ieCrAgIdCaD',
                '_score': None,
                '_source': {
                    '@timestamp': '2019-06-04T11:25:13.964Z',
                    'module': 'taxi.util.aiohttp_kit.middleware',
                    'level': 'INFO',
                    'link': '291c7a1c2d2447c9a47a943999e7d2d1',
                    'type': 'request',
                    'host': 'crons-sas-01.taxi.dev.yandex.net',
                    'uri': 'uri',
                    'method': 'POST',
                    'meta_type': 'v1/task/{name}/lock/prolong',
                    'parent_link': 'None',
                    'span_id': 'f4b555796dac4d2cbc10914c8f8a0ff8',
                    'trace_id': '92f3860dced744b9986863716ee2e071',
                    'useragent': 'python-requests/2.10.0',
                    'body': '{}',
                    'text': 'POST',
                    'tags': ['_pilorama_parsed'],
                    'cgroups': ['taxi_unstable_crons'],
                    'path': '/var/log/yandex/taxi-crons-web/taxi.log',
                    'message': 'tskv',
                },
                'sort': [1559647513964],
            },
        ],
    },
}
ES_RESPONSE_EXAMPLE_RESPONSES = {
    'took': 504,
    'timed_out': False,
    '_shards': {'total': 161, 'successful': 161, 'failed': 0},
    'hits': {
        'total': 1,
        'max_score': None,
        'hits': [
            {
                '_index': 'yandex-taxi-2019.06.04.11',
                '_type': 'response',
                '_id': 'AWsiPG3R9ieCrAgIdCaK',
                '_score': None,
                '_source': {
                    '@timestamp': '2019-06-04T11:25:13.974Z',
                    'module': 'taxi.util.aiohttp_kit.middleware',
                    'level': 'INFO',
                    'link': '291c7a1c2d2447c9a47a943999e7d2d1',
                    'type': 'response',
                    'host': 'crons-sas-01.taxi.dev.yandex.net',
                    'uri': 'uri',
                    'method': 'POST',
                    'meta_type': 'v1/task/{name}/lock/prolong',
                    'meta_code': 200,
                    'parent_link': 'None',
                    'span_id': 'f4b555796dac4d2cbc10914c8f8a0ff8',
                    'trace_id': '92f3860dced744b9986863716ee2e071',
                    'stopwatch_name': 'api',
                    'total_time': '0.009348392486572266',
                    'delay': None,
                    'body': 'None',
                    'text': 'POST',
                    'tags': ['_pilorama_parsed'],
                    'cgroups': ['taxi_unstable_crons'],
                    'path': '/var/log/yandex/taxi-crons-web/taxi.log',
                    'message': 'tskv',
                },
                'sort': [1559647513974],
            },
        ],
    },
}

ES_RESPONSE_PROTOCOL_REQUEST = {
    'hits': {
        'hits': [
            {
                '_index': 'yandex-taxi-2019.07.30.11',
                '_type': 'request',
                '_id': 'AWxCqTDZ6Lz_ZkdQ0KHK',
                '_score': None,
                '_source': {
                    '@timestamp': '2019-07-30T11:34:34.767Z',
                    'module': (
                        'handleRequest '
                        '( common/src/handler_util/base.cpp:199 )'
                    ),
                    'level': 'INFO',
                    'thread': '7f2ed01bb700',
                    'link': '83f9b4dc8cc77b2b6c94ecd4866fe32a',
                    'span_id': '3d57e7a9971b56b4e052feaac5b0b075',
                    'trace_id': '1564486474-1d303504753c4fb7',
                    'body': (
                        '{"zone_name":"moscow","skin_version":5,'
                        '"size_hint":9999,"supports_hideable_tariffs":true}'
                    ),
                    'host': 'taxi-api-myt-01.taxi.dev.yandex.net',
                    'acceptlang': 'ru',
                    'x_taxi': 'taxi-frontend',
                    'uri': '/3.0/zoneinfo',
                    'method': 'POST',
                    'useragent': 'nodejs',
                    'request_application': 'turboapp',
                    'type': 'request',
                    'requested_with': 'nodejs',
                    'remote_ip': '::ffff:95.108.136.75',
                    'requested_uri': (
                        'https://taxi-frontend.taxi.dev.yandex.ru/corp-tariff'
                    ),
                    'text': 'start handling /3.0/zoneinfo',
                    'tags': ['_pilorama_parsed'],
                    'cgroups': [
                        'taxi_unstable_api',
                        'taxi_unstable_sharesandbox',
                    ],
                    'path': '/var/log/fastcgi2/taxi-protocol.log',
                    'message': '',
                },
            },
        ],
    },
}
ES_RESPONSE_PROTOCOL_RESPONSE = {
    'hits': {
        'hits': [
            {
                '_index': 'yandex-taxi-2019.07.30.11',
                '_type': 'response',
                '_id': 'AWxCqTDZ6Lz_ZkdQ0KIg',
                '_score': None,
                '_source': {
                    '@timestamp': '2019-07-30T11:34:34.786Z',
                    'module': (
                        'handleRequest '
                        '( common/src/handler_util/base.cpp:259 )'
                    ),
                    'level': 'INFO',
                    'thread': '7f2ed01bb700',
                    'link': '83f9b4dc8cc77b2b6c94ecd4866fe32a',
                    'x_requested_uri': (
                        'https://taxi-frontend.taxi.dev.yandex.ru/corp-tariff'
                    ),
                    'x_taxi': 'taxi-frontend',
                    'app_ver1': '2',
                    'trace_id': '1564486474-1d303504753c4fb7',
                    'span_id': '3d57e7a9971b56b4e052feaac5b0b075',
                    'body': '{}',
                    'meta_code': 200,
                    'type': 'response',
                    'uri': '/3.0/zoneinfo',
                    'host': 'taxi-api-myt-01.taxi.dev.yandex.net',
                    'meta_type': 'zoneinfo',
                    'app_name': 'web',
                    'meta_application': 'web',
                    'delay': '0.018634',
                    'x_requested_with': 'nodejs',
                    'text': 'finish handling /3.0/zoneinfo',
                    'tags': ['_pilorama_parsed'],
                    'cgroups': [
                        'taxi_unstable_api',
                        'taxi_unstable_sharesandbox',
                    ],
                    'path': '/var/log/fastcgi2/taxi-protocol.log',
                    'message': '',
                },
            },
        ],
    },
}
