INSERT INTO orders_0 (
  park_id,
  id,
  number,
  status,
  date_create,
  date_end,
  driver_id,
  driver_name,
  car_id,
  car_name,
  car_number,
  driver_signal,
  rule_type_id,
  rule_type_name,
  date_booking,
  provider,
  address_from,
  address_to,
  route_points,
  description_canceled,
  receipt_data,
  rule_work_id,
  rule_work_name,
  categorys,
  category,
  tariff_id,--Park
  tariff_name,--Park
  requirements,
  cost_total,
  cost_pay,
  payment,
  client_id,--Park
  client_name,--Park
  phone1,--Park
  phone2,--Park
  phone3,--Park
  company_id,--Park
  company_name,--Park
  company_slip,--Park
  company_comment,--Park
  date_drive,
  date_waiting,
  date_calling,
  date_transporting,
  flags
)
VALUES (
  'park_id_0',--park_id
  'order0',--id
  1,--number
  50,--status
  '2019-05-01T10:00:00',--date_create
  '2019-05-01T10:20:00',--date_end
  'driver_id_0',--driver_id
  'driver_name_0',--driver_name
  'car_id_0',--car_id
  'car_model_0',--car_name
  'car_number_0',--car_number
  'callsign_0',--driver_signal
  'request_type_0',--rule_type_id
  'request_type_name',--rule_type_name
  '2019-05-01T10:05:00',--date_booking
  1,--provider
  '{"City": "Москва", "Street":"Рядом с: улица Островитянова, 47","Region":"","Lat":55.6348324304,"Lon":37.541191945}',--address_from,
  '{"City": "Москва", "Street":"Гостиница Прибалтийская", "Lat": 55.5545, "Lon": 37.8989, "Order": 3}',--address_to
  '[
      {"City": "Москва", "Street":"Улица 1", "Lat": 55.5111, "Lon": 37.222, "Order": 2},
      {"City": "Химки", "Street": "Нагорная улица", "Country": "Россия", "Lat": 55.123, "Lon": 37.1, "Order": 1}
   ]',--route_points
  'canceled',--description_canceled
  '{"total_distance": 1500}',--receipt_data
  'work_rule_id_1',--rule_work_id
  'work_rule_name_1',--rule_work_name
  32,--categorys
  'park_vip',--category
  'tariff_id_0',--tariff_id
  'tariff_name_0',--tariff_name
  8,--requirements
  159.99911,--cost_total,
  100.99,--cost_pay
  5,--payment
  'client_id_0',--client_id
  'client_name_0',--client_name
  'phone1',--phone1
  'phone2',--phone2
  'phone3',--phone3
  'company_id_0',--company_id
  'company_name_0',--company_name
  'company_slip_0',--company_slip
  'company_comment_0',--company_comment
  '2019-05-01T10:10:00',--date_drive
  '2019-05-01T10:15:00',--date_waiting
  '2019-05-01T10:16:00',--date_calling
  '2019-05-01T10:17:00',--date_transporting
  NULL--flags
),
(
  'park_id_1',--park_id
  'order1',--id
  1,--number
  50,--status
  '2019-05-01T16:18:00',--date_create
  '2019-05-01T17:30:00',--date_end
  'driver_id_1',--driver_id
  'driver_name_1',--driver_name
  NULL,--car_id
  NULL,--car_name
  NULL,--car_number
  NULL,--driver_signal
  NULL,--rule_type_id
  NULL,--rule_type_name
  '2019-05-01T16:20:00',--date_booking
  0,--provider
  '{"Street":"Вильнюсская улица, 7к2","Region":"","Lat":55.6022246645,"Lon":37.5224489641}',--address_from,
  NULL,--address_to
  NULL,--route_points
  NULL,--description_canceled
  NULL,--receipt_data
  NULL,--rule_work_id
  NULL,--rule_work_name
  65536,--categorys
  'mkk',--category
  NULL,--tariff_id
  NULL,--tariff_name
  0,--requirements
  NULL,--cost_total
  NULL,--cost_pay
  0,--payment
  NULL,--client_id
  NULL,--client_name
  '',--phone1
  NULL,--phone2
  NULL,--phone3
  NULL,--company_id
  NULL,--company_name
  NULL,--company_slip
  NULL,--company_comment
  '2019-05-01T16:18:00',--date_drive
  NULL,--date_waiting
  NULL,--date_calling
  NULL,--date_transporting
  NULL--flags
),
(
  'park_id_1',--park_id
  'order2',--id
  2,--number
  50,--status
  '2019-05-01T12:18:00',--date_create
  '2019-05-01T17:18:00',--date_end
  'driver_id_2',--driver_id
  NULL,--driver_name
  'car_id_2',--car_id
  NULL,--car_name
  NULL,--car_number
  NULL,--driver_signal
  NULL,--rule_type_id
  NULL,--rule_type_name
  '2019-05-01T12:18:00',--date_booking
  0,--provider
'{"City": "Москва", "Street":"Рядом с: улица Островитянова, 47","Region":"","Lat":55.6348324304,"Lon":37.541191945}',--address_from,
  NULL,--address_to
  NULL,--route_points
  NULL,--description_canceled
  '{"waiting_sum":56.4,"waiting_time":376.0,"waiting_cost":9.0,"total_distance":0.993930481845542}',--receipt_data
  'work_rule_id_1',--rule_work_id
  'work_rule_name_1',--rule_work_name
  0,--categorys
  'econom',--category
  NULL,--tariff_id
  NULL,--tariff_name
  0,--requirements
  157.0,--cost_total
  157.0,--cost_pay
  0,--payment
  NULL,--client_id
  NULL,--client_name
  NULL,--phone1
  NULL,--phone2
  NULL,--phone3
  NULL,--company_id
  NULL,--company_name
  NULL,--company_slip
  NULL,--company_comment
  NULL,--date_drive
  NULL,--date_waiting
  NULL,--date_calling
  NULL,--date_transporting
  NULL--flags
),
(
  'park_id_1',--park_id
  'order3',--id
  3,--number
  50,--status
  '2019-05-01T12:18:00',--date_create
  '2019-05-01T17:20:00',--date_end
  'driver_id_3',--driver_id
  'driver_name_3',--driver_name
  'car_id_3',--car_id
  'car_name_3',--car_name
  'car_number_3',--car_number
  'callsign_3',--driver_signal
  NULL,--rule_type_id
  NULL,--rule_type_name
  '2019-05-01T12:18:00',--date_booking
  0,--provider
  '{"Street":"Abc","Lat":55.6022246645,"Lon":37.5224489641}',--address_from,
  NULL,--address_to
  NULL,--route_points
  NULL,--description_canceled
  NULL,--receipt_data
  NULL,--rule_work_id
  NULL,--rule_work_name
  0,--categorys
  NULL,--category
  NULL,--tariff_id
  NULL,--tariff_name
  0,--requirements
  NULL,--cost_total
  NULL,--cost_pay
  0,--payment
  NULL,--client_id
  NULL,--client_name
  NULL,--phone1
  NULL,--phone2
  NULL,--phone3
  NULL,--company_id
  NULL,--company_name
  NULL,--company_slip
  NULL,--company_comment
  '2019-05-01T12:18:00',--date_drive
  NULL,--date_waiting
  NULL,--date_calling
  NULL,--date_transporting
  NULL--flags
),
(
  'park_id_2',--park_id
  'order4',--id
  4,--number
  80,--status
  '2019-05-01T20:00:00',--date_create
  '2019-05-01T21:00:00',--date_end
  NULL,--driver_id
  NULL,--driver_name
  NULL,--car_id
  NULL,--car_name
  NULL,--car_number
  NULL,--driver_signal
  NULL,--rule_type_id
  NULL,--rule_type_name
  '2019-05-01T20:30:00',--date_booking
  2,--provider
  '{"Street":"Abc4","Lat":55.6022246645,"Lon":37.5224489641}',--address_from,
  NULL,--address_to
  NULL,--route_points
  NULL,--description_canceled
  NULL,--receipt_data
  NULL,--rule_work_id
  NULL,--rule_work_name
  2,--categorys
  'business',--category
  NULL,--tariff_id
  NULL,--tariff_name
  0,--requirements
  160.05,--cost_total
  160.05,--cost_pay
  0,--payment
  NULL,--client_id
  NULL,--client_name
  NULL,--phone1
  NULL,--phone2
  NULL,--phone3
  NULL,--company_id
  NULL,--company_name
  NULL,--company_slip
  NULL,--company_comment
  NULL,--date_drive
  NULL,--date_waiting
  NULL,--date_calling
  NULL,--date_transporting
  NULL--flags
),
(
  'park_id_2',--park_id
  'order5',--id
  5,--number
  70,--status
  '2019-05-01T22:00:00',--date_create
  '2019-05-01T23:00:00',--date_end
  '',--driver_id
  NULL,--driver_name
  NULL,--car_id
  NULL,--car_name
  NULL,--car_number
  NULL,--driver_signal
  NULL,--rule_type_id
  NULL,--rule_type_name
  '2019-05-01T22:30:00',--date_booking
  1,--provider
  '{"Street":"Abc5","Lat":55.6022246645,"Lon":37.5224489641}',--address_from,
  NULL,--address_to
  NULL,--route_points
  NULL,--description_canceled
  NULL,--receipt_data
  NULL,--rule_work_id
  NULL,--rule_work_name
  32,--categorys
  'park_vip',--category
  NULL,--tariff_id
  NULL,--tariff_name
  0,--requirements
  140.50,--cost_total
  140.50,--cost_pay
  5,--payment
  NULL,--client_id
  NULL,--client_name
  NULL,--phone1
  NULL,--phone2
  NULL,--phone3
  NULL,--company_id
  NULL,--company_name
  NULL,--company_slip
  NULL,--company_comment
  NULL,--date_drive
  NULL,--date_waiting
  NULL,--date_calling
  NULL,--date_transporting
  NULL--flags
),
(
  'park_id_3',--park_id
  'order6',--id
  6,--number
  10,--status
  '2019-05-01T22:00:00',--date_create
  NULL,--date_end
  NULL,--driver_id
  NULL,--driver_name
  NULL,--car_id
  NULL,--car_name
  NULL,--car_number
  NULL,--driver_signal
  NULL,--rule_type_id
  NULL,--rule_type_name
  '2019-05-01T22:30:00',--date_booking
  2,--provider
  '{"Street":"Abc6","Lat":55.6022246645,"Lon":37.5224489641}',--address_from,
  '{"City": "Москва", "Street":"Abc6", "Lat": 55.5545, "Lon": 37.8989, "Order": 3}',--address_to
  '[
      {"City": "Москва", "Street":"Улица 1", "Lat": 55.5111, "Lon": 37.222, "Order": 2},
      {"City": "Химки", "Street": "Нагорная улица", "Country": "Россия", "Lat": 55.123, "Lon": 37.1, "Order": 1}
   ]',--route_points
  NULL,--description_canceled
  NULL,--receipt_data
  NULL,--rule_work_id
  NULL,--rule_work_name
  32,--categorys
  'park_vip',--category
  'tariff_id',--tariff_id
  'tariff_name',--tariff_name
  0,--requirements
  100,--cost_total
  100,--cost_pay
  NULL,--payment
  NULL,--client_id
  NULL,--client_name
  NULL,--phone1
  NULL,--phone2
  NULL,--phone3
  NULL,--company_id
  NULL,--company_name
  NULL,--company_slip
  NULL,--company_comment
  '2019-05-01T22:30:00',--date_drive
  NULL,--date_waiting
  NULL,--date_calling
  NULL,--date_transporting
  NULL--flags
),
(
  'park_id_35',--park_id
  'order65',--id
  65,--number
  0,--status
  '2019-05-01T22:00:00',--date_create
  NULL,--date_end
  NULL,--driver_id
  NULL,--driver_name
  NULL,--car_id
  NULL,--car_name
  NULL,--car_number
  NULL,--driver_signal
  NULL,--rule_type_id
  NULL,--rule_type_name
  '2019-05-01T22:30:00',--date_booking
  2,--provider
  '{"Street":"Abc6","Lat":55.6022246645,"Lon":37.5224489641}',--address_from,
  '{"City": "Москва", "Street":"Abc6", "Lat": 55.5545, "Lon": 37.8989, "Order": 3}',--address_to
  '[
      {"City": "Москва", "Street":"Улица 1", "Lat": 55.5111, "Lon": 37.222, "Order": 2},
      {"City": "Химки", "Street": "Нагорная улица", "Country": "Россия", "Lat": 55.123, "Lon": 37.1, "Order": 1}
   ]',--route_points
  NULL,--description_canceled
  NULL,--receipt_data
  NULL,--rule_work_id
  NULL,--rule_work_name
  32,--categorys
  'park_vip',--category
  'tariff_id',--tariff_id
  'tariff_name',--tariff_name
  0,--requirements
  100,--cost_total
  100,--cost_pay
  NULL,--payment
  NULL,--client_id
  NULL,--client_name
  NULL,--phone1
  NULL,--phone2
  NULL,--phone3
  NULL,--company_id
  NULL,--company_name
  NULL,--company_slip
  NULL,--company_comment
  NULL,--date_drive
  NULL,--date_waiting
  NULL,--date_calling
  NULL,--date_transporting
  NULL--flags
),
(
  'park_id_4',--park_id
  'order7',--id
  7,--number
  NULL,--status
  '2019-05-01T22:00:00',--date_create
  NULL,--date_end
  NULL,--driver_id
  NULL,--driver_name
  NULL,--car_id
  NULL,--car_name
  NULL,--car_number
  NULL,--driver_signal
  NULL,--rule_type_id
  NULL,--rule_type_name
  '2019-05-01T22:30:00',--date_booking
  NULL,--provider
  '{Invalid',--address_from,
  'Invalid{',--address_to
  NULL,--route_points
  NULL,--description_canceled
  NULL,--receipt_data
  NULL,--rule_work_id
  NULL,--rule_work_name
  NULL,--categorys
  NULL,--category
  NULL,--tariff_id
  NULL,--tariff_name
  NULL,--requirements
  NULL,--cost_total
  NULL,--cost_pay
  NULL,--payment
  NULL,--client_id
  NULL,--client_name
  NULL,--phone1
  NULL,--phone2
  NULL,--phone3
  NULL,--company_id
  NULL,--company_name
  NULL,--company_slip
  NULL,--company_comment
  NULL,--date_drive
  NULL,--date_waiting
  NULL,--date_calling
  NULL,--date_transporting
  NULL--flags
),
(
  'park_id_8',--park_id
  'order8',--id
  8,--number
  50,--status
  '2019-05-01T10:00:00',--date_create
  '2019-05-01T10:30:00',--date_end
  'driver_id_0',--driver_id
  'driver_name_0',--driver_name
  'car_id_0',--car_id
  'car_model_0',--car_name
  'car_number_0',--car_number
  'callsign_0',--driver_signal
  'request_type_0',--rule_type_id
  'request_type_name',--rule_type_name
  '2019-05-01T10:05:00',--date_booking
  1,--provider
  '{"City": "Москва", "Street":"Рядом с: улица Островитянова, 47","Region":"","Lat":55.6348324304,"Lon":37.541191945}',--address_from,
  '{"City": "Москва", "Street":"Гостиница Прибалтийская", "Lat": 55.5545, "Lon": 37.8989, "Order": 3}',--address_to
  '[
      {"City": "Москва", "Street":"Улица 1", "Lat": 55.5111, "Lon": 37.222, "Order": 2},
      {"City": "Химки", "Street": "Нагорная улица", "Country": "Россия", "Lat": 55.123, "Lon": 37.1, "Order": 1}
   ]',--route_points
  'canceled',--description_canceled
  '{"total_distance": 1500}',--receipt_data
  'work_rule_id_1',--rule_work_id
  'work_rule_name_1',--rule_work_name
  32,--categorys
  'park_vip',--category
  'tariff_id_0',--tariff_id
  'tariff_name_0',--tariff_name
  8,--requirements
  159.99911,--cost_total,
  100.99,--cost_pay
  5,--payment
  'client_id_0',--client_id
  'client_name_0',--client_name
  'phone1',--phone1
  'phone2',--phone2
  'phone3',--phone3
  'company_id_0',--company_id
  'company_name_0',--company_name
  'company_slip_0',--company_slip
  'company_comment_0',--company_comment
  '2019-05-01T10:10:00',--date_drive
  '2019-05-01T10:15:00',--date_waiting
  '2019-05-01T10:16:00',--date_calling
  '2019-05-01T10:21:00',--date_transporting
  NULL--flags
),
(  'park_id_3',--park_id
  'order_with_flags',--id
  6,--number
  10,--status
  '2019-05-01T22:00:00',--date_create
  NULL,--date_end
  NULL,--driver_id
  NULL,--driver_name
  NULL,--car_id
  NULL,--car_name
  NULL,--car_number
  NULL,--driver_signal
  NULL,--rule_type_id
  NULL,--rule_type_name
  '2019-05-01T22:30:00',--date_booking
  2,--provider
  '{"Street":"Abc6","Lat":55.6022246645,"Lon":37.5224489641}',--address_from,
  '{"City": "Москва", "Street":"Abc6", "Lat": 55.5545, "Lon": 37.8989, "Order": 3}',--address_to
  '[
      {"City": "Москва", "Street":"Улица 1", "Lat": 55.5111, "Lon": 37.222, "Order": 2},
      {"City": "Химки", "Street": "Нагорная улица", "Country": "Россия", "Lat": 55.123, "Lon": 37.1, "Order": 1}
   ]',--route_points
  NULL,--description_canceled
  NULL,--receipt_data
  NULL,--rule_work_id
  NULL,--rule_work_name
  35,--categorys
  'invalid_category',--category
  'tariff_id',--tariff_id
  'tariff_name',--tariff_name
  0,--requirements
  100,--cost_total
  100,--cost_pay
  NULL,--payment
  NULL,--client_id
  NULL,--client_name
  NULL,--phone1
  NULL,--phone2
  NULL,--phone3
  NULL,--company_id
  NULL,--company_name
  NULL,--company_slip
  NULL,--company_comment
  '2019-05-01T22:30:00',--date_drive
  NULL,--date_waiting
  NULL,--date_calling
  NULL,--date_transporting
  '{"flag_1", "flag_2"}'--flags
);
