<?xml version="1.0" encoding="UTF-8"?>
<yandex>
    <settings>
        <daemonRoot>${daemonRoot}</daemonRoot>
    </settings>
    <metrikaLambdaConfig>
        <deleteTemporaryFiles>false</deleteTemporaryFiles>
        <logParseDelay>0</logParseDelay>
        <visitLogParseDelay>0</visitLogParseDelay>
        <dspLogParseDelay>0</dspLogParseDelay>
        <offlineConversionLogParseDelay>0</offlineConversionLogParseDelay>
        <adfoxLogParseDelay>0</adfoxLogParseDelay>
        <adfoxDspLogParseDelay>0</adfoxDspLogParseDelay>
        <adfoxUndoDspLogParseDelay>0</adfoxUndoDspLogParseDelay>
        <sampling>100</sampling>
        <visitSampling>100</visitSampling>
        <ttlLog>${(10 * 365 * 24 * 60 * 60 * 1000)?c}</ttlLog>
        <visitLogRoot>//logs/visit-v2-log</visitLogRoot>
        <ytPool>default</ytPool>
        <gigaLayers>2</gigaLayers>
        <nanoLayers>2</nanoLayers>
        <writeShardedOutput>true</writeShardedOutput>
        <writeUnshardedOutput>true</writeUnshardedOutput>
    </metrikaLambdaConfig>
    <mysql_misc_misc>
        <db>misc</db>
        <host>${RECIPE_MYSQL_HOST}</host>
        <port>${RECIPE_MYSQL_PORT}</port>
        <user>${RECIPE_MYSQL_USER}</user>
    </mysql_misc_misc>
    <mysql_counters>
        <db>conv_main</db>
        <host>${RECIPE_MYSQL_HOST}</host>
        <port>${RECIPE_MYSQL_PORT}</port>
        <user>${RECIPE_MYSQL_USER}</user>
    </mysql_counters>
    <zookeeperSettings>
        <node index="0">
            <host>${RECIPE_ZOOKEEPER_HOST}</host>
            <port>${RECIPE_ZOOKEEPER_PORT}</port>
        </node>
    </zookeeperSettings>
    <yqlDataSourceFactory1>
        <url>jdbc:yql://${yqlHost}:${yqlPort}/${yqlDatabase}?syntaxVersion=1</url>
    </yqlDataSourceFactory1>
    <bkYTProperties>
        <proxies index="0">${targetHost}:${ytProxyPort}</proxies>
        <port>${ytRpcProxyPort}</port>
        <token>dummy-token</token>
    </bkYTProperties>
    <ytTransactionalClient>
        <clusterName>${targetHost}:${ytProxyPort}</clusterName>
    </ytTransactionalClient>
    <ytDynamicUtils>
        <cellBundle>default</cellBundle>
        <medium>default</medium>
    </ytDynamicUtils>
    <lambdaDspLogMapTask>
        <enabled>true</enabled>
    </lambdaDspLogMapTask>
    <lambdaUndoDspLogMapTask>
        <enabled>true</enabled>
    </lambdaUndoDspLogMapTask>
    <lambdaVisitMapRunnerTask>
        <enabled>true</enabled>
        <maxParallelChunks>8</maxParallelChunks>
    </lambdaVisitMapRunnerTask>
    <lambdaDspJoinTask>
        <enabled>true</enabled>
    </lambdaDspJoinTask>
    <lambdaVisitJoinRunnerTask>
        <enabled>true</enabled>
        <maxParallelTasks>1</maxParallelTasks>
        <minBatchSize>1</minBatchSize>
    </lambdaVisitJoinRunnerTask>
    <lambdaWideDiffTask>
        <enabled>true</enabled>
        <usePoolTreesPragmas>false</usePoolTreesPragmas>
    </lambdaWideDiffTask>
    <lambdaWideSlowDiffTask>
        <enabled>true</enabled>
        <batchSize>80</batchSize>
    </lambdaWideSlowDiffTask>
    <lambdaAdfoxLogMapTask>
        <enabled>true</enabled>
        <filterFraud>true</filterFraud>
    </lambdaAdfoxLogMapTask>
    <lambdaAdfoxLogAggregateAndDivideTask>
        <enabled>true</enabled>
    </lambdaAdfoxLogAggregateAndDivideTask>
    <lambdaAdfoxDspLogMapTask>
        <enabled>true</enabled>
    </lambdaAdfoxDspLogMapTask>
    <lambdaAdfoxUndoDspLogMapTask>
        <enabled>true</enabled>
    </lambdaAdfoxUndoDspLogMapTask>
    <lambdaAdfoxVisitJoinTask>
        <enabled>true</enabled>
    </lambdaAdfoxVisitJoinTask>
    <lambdaAdfoxYanDspJoinTask>
        <enabled>true</enabled>
    </lambdaAdfoxYanDspJoinTask>
    <lambdaAdfoxDspYanJoinTask>
        <enabled>true</enabled>
    </lambdaAdfoxDspYanJoinTask>
    <lambdaRecommendationWidgetMapTask>
        <enabled>true</enabled>
    </lambdaRecommendationWidgetMapTask>
    <lambdaRecommendationWidgetJoinTask>
        <enabled>true</enabled>
    </lambdaRecommendationWidgetJoinTask>
    <lambdaCleanUpTTLTask>
        <enabled>false</enabled>
    </lambdaCleanUpTTLTask>
    <lambdaSplitVisitLogTask>
        <enabled>true</enabled>
    </lambdaSplitVisitLogTask>
    <lambdaSplitVisitSlowLogTask>
        <enabled>true</enabled>
    </lambdaSplitVisitSlowLogTask>
    <visitSortedAnyChunksCollapsingTask>
        <enabled>false</enabled>
    </visitSortedAnyChunksCollapsingTask>
    <lambdaDiffTask>
        <enabled>true</enabled>
    </lambdaDiffTask>
    <lambdaJoinedVisitsPackTask>
        <enabled>true</enabled>
    </lambdaJoinedVisitsPackTask>
    <lambdaStatePatchTask>
        <enabled>true</enabled>
    </lambdaStatePatchTask>
    <lambdaOfflineCountersTask>
        <enabled>true</enabled>
    </lambdaOfflineCountersTask>
    <lambdaTelephonyCountersTask>
        <enabled>true</enabled>
    </lambdaTelephonyCountersTask>
    <lambdaPartnerCountersTask>
        <enabled>true</enabled>
    </lambdaPartnerCountersTask>
    <lambdaAdfoxCountersTask>
        <enabled>true</enabled>
    </lambdaAdfoxCountersTask>
    <lambdaOfflineConversionMapTask>
        <enabled>true</enabled>
    </lambdaOfflineConversionMapTask>
    <lambdaOfflineConversionAttributionTask>
        <enabled>true</enabled>
    </lambdaOfflineConversionAttributionTask>
    <lambdaOfflineConversionDiffTask>
        <enabled>true</enabled>
    </lambdaOfflineConversionDiffTask>
    <lambdaOfflineConversionPatchTask>
        <enabled>true</enabled>
    </lambdaOfflineConversionPatchTask>
    <lambdaUploadingStatusUpdateTask>
        <enabled>true</enabled>
    </lambdaUploadingStatusUpdateTask>
    <lambdaAdfoxUndoDspYanJoinTask>
        <enabled>true</enabled>
    </lambdaAdfoxUndoDspYanJoinTask>
    <lambdaAdfoxUndoVisitJoinTask>
        <enabled>true</enabled>
    </lambdaAdfoxUndoVisitJoinTask>
    <lambdaVisitAlterTask>
        <enabled>true</enabled>
    </lambdaVisitAlterTask>
    <lambdaPbxMapTask>
        <enabled>true</enabled>
    </lambdaPbxMapTask>
    <lambdaCalltrackingMapTask>
        <enabled>true</enabled>
    </lambdaCalltrackingMapTask>
    <lambdaCryptaMatchingPhoneMd5ImportTask>
        <enabled>false</enabled>
    </lambdaCryptaMatchingPhoneMd5ImportTask>
    <lambdaCryptaExtendedPhoneMatchingImportTask>
        <enabled>false</enabled>
    </lambdaCryptaExtendedPhoneMatchingImportTask>
    <lambdaPbxCryptaJoinTask>
        <enabled>true</enabled>
    </lambdaPbxCryptaJoinTask>
    <lambdaCalltrackingCryptaJoinTask>
        <enabled>true</enabled>
    </lambdaCalltrackingCryptaJoinTask>
    <lambdaPbxAttributionTask>
        <enabled>true</enabled>
    </lambdaPbxAttributionTask>
    <lambdaCalltrackingAttributionTask>
        <enabled>true</enabled>
    </lambdaCalltrackingAttributionTask>
    <lambdaTelephonyVisitAttributionTask>
        <enabled>true</enabled>
    </lambdaTelephonyVisitAttributionTask>
    <lambdaTelephonyDiffTask>
        <enabled>true</enabled>
    </lambdaTelephonyDiffTask>
    <lambdaTelephonyPatchTask>
        <enabled>true</enabled>
    </lambdaTelephonyPatchTask>
</yandex>
