INSERT INTO yt.report_summary_parks(
    park_id,
    date_month,
    count_active_cars,
    count_active_drivers,
    count_orders_completed,
    count_orders_all,
    count_orders_platform,
    count_orders_accepted,
    count_orders_cancelled_by_driver,
    count_orders_cancelled_by_client,
    count_new_drivers,
    ratio_driver_churn,
    work_time_seconds,
    avg_drivers_work_time_seconds,
    avg_cars_work_time_seconds,
    price_cash,
    price_cashless,
    price_platform_commission,
    price_park_commission,
    price_software_commission,
    price_hiring_services,
    price_hiring_returned_inc_vat
)
VALUES
    (
        '12121',
        '2022-03',
        1,
        1,
        3,
        5,
        5,
        5,
        0,
        1,
        0,
        null,
        10154,
        758,
        758,
        null,
        -635.1266,
        -166.08,
        null,
        null,
        null,
        12.12
    )
;
 INSERT INTO yt.operations
            (
                operation_id,
                operation_status,
                type,
                status,
                cluster,
                created_at,
                updated_at
            )
        VALUES
            (
                'operation_id_0',
                'COMPLETED',
                'report_summary_v2',
                'yql_finished',
                'hahn',
                '2020-05-18T00:00:00+00:00',
                '2020-05-18T00:00:00+00:00'
            )
        ;
