START TRANSACTION;

DROP SCHEMA pins CASCADE;

CREATE SCHEMA pins;

CREATE TABLE pins.SHORT_LIFE_PINS(
  id BIGSERIAL,
  "timestamp" TIMESTAMP NOT NULL,
  user_id TEXT NOT NULL,
  pin_stats_info JSON NOT NULL
) PARTITION BY RANGE("timestamp");

COMMIT;
