import pytest
import xlrd

from taxi_corp.api.common import reports
from taxi_corp.internal.reports.orders.common import structs
from taxi_corp.internal.reports.orders.taxi import report


REPORT_COLUMN_HEADERS = (
    'report.due_data',
    'report.created_time',
    'report.due_time',
    'report.creator',
    'report.order_method',
    'report.due_weekday',
    'report.user_fullname',
    'report.user_class',
    'report.user_phone',
    'report.user_email',
    'report.user_nickname',
    'report.extra_user_phone',
    'report.combo_order_phones',
    'report.order_id',
    'report.city',
    'report.source_fullname',
    'report.interim_destinations',
    'report.destination_fullname',
    'report.source',
    'report.interim_points',
    'report.destination',
    'report.start_waiting_fulldate',
    'report.start_fulldate',
    'report.finish_fulldate',
    'report.tariff_class',
    'report.cost_center',
    'report.comment',
    'report.distance',
    'report.ride_cost',
    'report.waiting_cost',
    'report.waiting_in_depart_time',
    'report.waiting_in_transit_time',
    'report.requirements',
    'report.cost',
    'report.vat',
    'report.total_cost',
)
DEPARTMENT_REPORT_COLUMN_HEADERS = (
    REPORT_COLUMN_HEADERS[:8]
    + ('report.department', 'report.department_path')
    + REPORT_COLUMN_HEADERS[8:]
)

HIDDEN_PRICES_REPORT_FORBIDDEN_COLUMNS = (
    'report.ride_cost',
    'report.waiting_cost',
    'report.cost',
    'report.vat',
    'report.total_cost',
)
HIDDEN_PRICES_REPORT_COLUMN_HEADERS = tuple(
    col
    for col in DEPARTMENT_REPORT_COLUMN_HEADERS
    if col not in HIDDEN_PRICES_REPORT_FORBIDDEN_COLUMNS
)
COMBO_ORDERS_RESPONSE = {
    'orders': [
        {
            'id': 'order8',
            'user_points': [
                {'user_personal_phone_id': '+79881234567', 'point': ''},
                {'user_personal_phone_id': '+79881234568', 'point': ''},
            ],
        },
    ],
}


def with_cc(column_headers):
    cc_headers = ('Центр затрат', 'Цель поездки')
    return column_headers[:-3] + cc_headers + column_headers[-3:]


@pytest.mark.parametrize(
    'file_format, content_type',
    [
        pytest.param('xls', 'application/vnd.ms-excel', id='xls'),
        pytest.param(
            'xlsx',
            'application/vnd.openxmlformats-officedocument.spreadsheetml'
            '.sheet',
            id='xlsx',
        ),
    ],
)
@pytest.mark.parametrize(
    [
        'client_id',
        'passport_mock',
        'department_id',
        'locale',
        'since_date',
        'till_date',
        'status',
        'expected_content',
    ],
    [
        pytest.param(
            'client1',
            'client1',
            None,
            'ru',
            '2016-03-19',
            '2016-03-25',
            200,
            [
                ('report.company', '', 'Yandex.Taxi team', *[''] * 37),
                ('report.period', '', '19.03.2016 - 25.03.2016', *[''] * 37),
                ('report.rides_count', '', 3.0, *[''] * 37),
                ('report.total_cost_with_vat', '', 2218.4, *[''] * 37),
                tuple([''] * 40),
                with_cc(DEPARTMENT_REPORT_COLUMN_HEADERS),
                (
                    '19.03.2016',
                    '15:35:20',
                    '15:35:20',
                    'some_manager',
                    'report.app.callcenter',
                    'Weekday.saturday',
                    'Moe',
                    'role.others_name',
                    'd1_1',
                    'd1 → d1_1',
                    '+79291112202',
                    'moe@mail.com',
                    '',
                    '',
                    '',
                    'order4',
                    'moscow',
                    'Россия, Москва, улица Льва Толстого, 16',
                    '',
                    '',
                    '',
                    '',
                    '\'37.600296\', \'55.750379\'',
                    '19.03.2016 15:40:10',
                    '19.03.2016 15:40:20',
                    '19.03.2016 15:55:20',
                    'econom',
                    'в этом заказе старый ЦЗ в новом формате',
                    'комментарий сотрудника',
                    50.0,
                    670.0,
                    100.0,
                    60,
                    '',
                    'requirements.childchair_moscow '
                    'requirements.chairgrade.1, '
                    'requirements.childchair_moscow requirements.chairgrade.3',
                    '',
                    '',
                    670.0,
                    120.60,
                    790.6,
                ),
                (
                    '19.03.2016',
                    '15:35:20',
                    '15:35:20',
                    'some_manager',
                    'report.app.callcenter',
                    'Weekday.saturday',
                    'Moe',
                    'role.others_name',
                    'd1_1',
                    'd1 → d1_1',
                    '+79291112202',
                    'moe@mail.com',
                    '',
                    '',
                    '',
                    'order5',
                    'moscow',
                    'Россия, Москва, улица Льва Толстого, 16',
                    '',
                    '',
                    '',
                    '',
                    '\'37.600296\', \'55.750379\'',
                    '19.03.2016 15:40:10',
                    '19.03.2016 15:40:20',
                    '19.03.2016 15:55:20',
                    'econom',
                    'default cost center',
                    'комментарий сотрудника',
                    50.0,
                    670.0,
                    100.0,
                    60,
                    '',
                    'requirements.childchair_moscow '
                    'requirements.chairgrade.1, '
                    'requirements.childchair_moscow requirements.chairgrade.3',
                    'работа',
                    'какое-то значение',
                    670.0,
                    120.60,
                    790.6,
                ),
                (
                    '25.03.2016',
                    '00:27:17',
                    '00:37:17',
                    '+79291112201',
                    'report.app.mobile',
                    'Weekday.friday',
                    'Zoe',
                    'sales',
                    'd1',
                    'd1',
                    '+79291112201',
                    'zoe@mail.com',
                    'ZoeTheCoolest',
                    '',
                    '',
                    'order1',
                    '',
                    'Россия, Москва, улица Тимура Фрунзе, 11к8',
                    '',
                    'Россия, Москва, Большая Никитская улица, 13',
                    '\'37.5887876121\', \'55.734141752\'',
                    '',
                    '\'37.600296\', \'55.750379\'',
                    '25.03.2016 00:40:07',
                    '25.03.2016 00:40:17',
                    '25.03.2016 00:47:17',
                    'econom',
                    'user defined cost center',
                    '',
                    '',
                    540.0,
                    '',
                    '',
                    '',
                    '',
                    'отдых',
                    'просто так',
                    540.0,
                    97.20,
                    637.2,
                ),
                (*[''] * 38, 'report.result', 2218.4),
            ],
            id='test-1, client1, with cost center',
        ),
        pytest.param(
            'client5',
            'client5',
            None,
            'ru',
            '2017-12-01',
            '2017-12-31',
            200,
            [
                ('report.company', '', 'yandex5', *[''] * 35),
                ('report.period', '', '01.12.2017 - 31.12.2017', *[''] * 35),
                ('report.rides_count', '', 1, *[''] * 35),
                ('report.total_cost_with_vat', '', 790.6, *[''] * 35),
                tuple([''] * 38),
                DEPARTMENT_REPORT_COLUMN_HEADERS,
                (
                    '21.12.2017',
                    '15:14:42',
                    '15:28:00',
                    '+79264333315',
                    '',
                    'Weekday.thursday',
                    'TestUser1',
                    'sales',
                    'd5',
                    'd5',
                    '+79264333315',
                    'testuser1@mail.com',
                    '',
                    '',
                    '',
                    'order7',
                    'moscow',
                    'Россия, Москва, улица Льва Толстого, 16',
                    (
                        'Садовническая улица, 84с7\n'
                        'Малая Никитская улица, 43'
                    ),
                    'Россия, Москва, Большая Никитская улица, 13',
                    '\'37.58878761211858\', \'55.73414175200699\'',
                    '\'33.6\', \'55.1\'\n\'37.6\', \'55.7\'',
                    '\'37.600296\', \'55.750379\'',
                    '',
                    '',
                    '21.12.2017 16:14:00',
                    'econom',
                    '',
                    '',
                    '',
                    670.0,
                    '',
                    100,
                    200,
                    'requirements.bicycle, requirements.childchair_moscow '
                    'requirements.chairgrade.3, requirements.conditioner, '
                    'requirements.nosmoking, requirements.yellowcarnumber',
                    670.0,
                    120.6,
                    790.6,
                ),
                (*[''] * 36, 'report.result', 790.6),
            ],
            id='test-2, client5, new title',
        ),
        pytest.param(
            'client1',
            'client1',
            'd1',
            'ru',
            '2016-03-19',
            '2016-03-25',
            200,
            [
                ('report.company', '', 'Yandex.Taxi team', *[''] * 37),
                ('report.department', '', 'd1', *[''] * 37),
                ('report.department_path', '', 'd1', *[''] * 37),
                ('report.period', '', '19.03.2016 - 25.03.2016', *[''] * 37),
                ('report.rides_count', '', 3.0, *[''] * 37),
                ('report.total_cost_with_vat', '', 2218.4, *[''] * 37),
                tuple([''] * 40),
                with_cc(DEPARTMENT_REPORT_COLUMN_HEADERS),
                (
                    '19.03.2016',
                    '15:35:20',
                    '15:35:20',
                    'some_manager',
                    'report.app.callcenter',
                    'Weekday.saturday',
                    'Moe',
                    'role.others_name',
                    'd1_1',
                    'd1 → d1_1',
                    '+79291112202',
                    'moe@mail.com',
                    '',
                    '',
                    '',
                    'order4',
                    'moscow',
                    'Россия, Москва, улица Льва Толстого, 16',
                    '',
                    '',
                    '',
                    '',
                    '\'37.600296\', \'55.750379\'',
                    '19.03.2016 15:40:10',
                    '19.03.2016 15:40:20',
                    '19.03.2016 15:55:20',
                    'econom',
                    'в этом заказе старый ЦЗ в новом формате',
                    'комментарий сотрудника',
                    50.0,
                    670.0,
                    100.0,
                    60,
                    '',
                    'requirements.childchair_moscow'
                    ' requirements.chairgrade.1, '
                    'requirements.childchair_moscow requirements.chairgrade.3',
                    '',
                    '',
                    670.0,
                    120.60,
                    790.6,
                ),
                (
                    '19.03.2016',
                    '15:35:20',
                    '15:35:20',
                    'some_manager',
                    'report.app.callcenter',
                    'Weekday.saturday',
                    'Moe',
                    'role.others_name',
                    'd1_1',
                    'd1 → d1_1',
                    '+79291112202',
                    'moe@mail.com',
                    '',
                    '',
                    '',
                    'order5',
                    'moscow',
                    'Россия, Москва, улица Льва Толстого, 16',
                    '',
                    '',
                    '',
                    '',
                    '\'37.600296\', \'55.750379\'',
                    '19.03.2016 15:40:10',
                    '19.03.2016 15:40:20',
                    '19.03.2016 15:55:20',
                    'econom',
                    'default cost center',
                    'комментарий сотрудника',
                    50.0,
                    670.0,
                    100.0,
                    60,
                    '',
                    'requirements.childchair_moscow'
                    ' requirements.chairgrade.1, '
                    'requirements.childchair_moscow requirements.chairgrade.3',
                    'работа',
                    'какое-то значение',
                    670.0,
                    120.60,
                    790.6,
                ),
                (
                    '25.03.2016',
                    '00:27:17',
                    '00:37:17',
                    '+79291112201',
                    'report.app.mobile',
                    'Weekday.friday',
                    'Zoe',
                    'sales',
                    'd1',
                    'd1',
                    '+79291112201',
                    'zoe@mail.com',
                    'ZoeTheCoolest',
                    '',
                    '',
                    'order1',
                    '',
                    'Россия, Москва, улица Тимура Фрунзе, 11к8',
                    '',
                    'Россия, Москва, Большая Никитская улица, 13',
                    '\'37.5887876121\', \'55.734141752\'',
                    '',
                    '\'37.600296\', \'55.750379\'',
                    '25.03.2016 00:40:07',
                    '25.03.2016 00:40:17',
                    '25.03.2016 00:47:17',
                    'econom',
                    'user defined cost center',
                    '',
                    '',
                    540.0,
                    '',
                    '',
                    '',
                    '',
                    'отдых',
                    'просто так',
                    540.0,
                    97.20,
                    637.2,
                ),
                (*[''] * 38, 'report.result', 2218.4),
            ],
            id='test-3, client1, with cost center',
        ),
        pytest.param(
            'client1',
            'manager1',
            'd1',
            'ru',
            '2016-03-19',
            '2016-03-25',
            403,
            None,
            id='test-5, client1, 403 error',
        ),
        pytest.param(
            'client1',
            'manager1',
            'd1_1',
            'ru',
            '2016-01-01',
            '2016-01-01',
            200,
            [
                ('report.company', '', 'Yandex.Taxi team', *[''] * 37),
                ('report.department', '', 'd1_1', *[''] * 37),
                ('report.department_path', '', 'd1 → d1_1', *[''] * 37),
                ('report.period', '', '01.01.2016 - 01.01.2016', *[''] * 37),
                ('report.rides_count', '', 0.0, *[''] * 37),
                ('report.total_cost_with_vat', '', 0.0, *[''] * 37),
                tuple([''] * 40),
                with_cc(DEPARTMENT_REPORT_COLUMN_HEADERS),
                (*[''] * 38, 'report.result', 0.0),
            ],
            id='test-6, client1, manager 1, with cost center',
        ),
        pytest.param(
            'client1',
            'manager1',
            'd1_1',
            'ru',
            '2016-03-19',
            '2016-03-25',
            200,
            [
                ('report.company', '', 'Yandex.Taxi team', *[''] * 37),
                ('report.department', '', 'd1_1', *[''] * 37),
                ('report.department_path', '', 'd1 → d1_1', *[''] * 37),
                ('report.period', '', '19.03.2016 - 25.03.2016', *[''] * 37),
                ('report.rides_count', '', 2.0, *[''] * 37),
                ('report.total_cost_with_vat', '', 1581.2, *[''] * 37),
                tuple([''] * 40),
                with_cc(DEPARTMENT_REPORT_COLUMN_HEADERS),
                (
                    '19.03.2016',
                    '15:35:20',
                    '15:35:20',
                    'some_manager',
                    'report.app.callcenter',
                    'Weekday.saturday',
                    'Moe',
                    'role.others_name',
                    'd1_1',
                    'd1 → d1_1',
                    '+79291112202',
                    'moe@mail.com',
                    '',
                    '',
                    '',
                    'order4',
                    'moscow',
                    'Россия, Москва, улица Льва Толстого, 16',
                    '',
                    '',
                    '',
                    '',
                    '\'37.600296\', \'55.750379\'',
                    '19.03.2016 15:40:10',
                    '19.03.2016 15:40:20',
                    '19.03.2016 15:55:20',
                    'econom',
                    'в этом заказе старый ЦЗ в новом формате',
                    'комментарий сотрудника',
                    50.0,
                    670.0,
                    100.0,
                    60,
                    '',
                    'requirements.childchair_moscow'
                    ' requirements.chairgrade.1, '
                    'requirements.childchair_moscow requirements.chairgrade.3',
                    '',
                    '',
                    670.0,
                    120.60,
                    790.6,
                ),
                (
                    '19.03.2016',
                    '15:35:20',
                    '15:35:20',
                    'some_manager',
                    'report.app.callcenter',
                    'Weekday.saturday',
                    'Moe',
                    'role.others_name',
                    'd1_1',
                    'd1 → d1_1',
                    '+79291112202',
                    'moe@mail.com',
                    '',
                    '',
                    '',
                    'order5',
                    'moscow',
                    'Россия, Москва, улица Льва Толстого, 16',
                    '',
                    '',
                    '',
                    '',
                    '\'37.600296\', \'55.750379\'',
                    '19.03.2016 15:40:10',
                    '19.03.2016 15:40:20',
                    '19.03.2016 15:55:20',
                    'econom',
                    'default cost center',
                    'комментарий сотрудника',
                    50.0,
                    670.0,
                    100.0,
                    60,
                    '',
                    'requirements.childchair_moscow'
                    ' requirements.chairgrade.1, '
                    'requirements.childchair_moscow requirements.chairgrade.3',
                    'работа',
                    'какое-то значение',
                    670.0,
                    120.60,
                    790.6,
                ),
                (*[''] * 38, 'report.result', 1581.2),
            ],
            id='test-7, client1, manager 1, with cost center',
        ),
        pytest.param(
            'client1',
            'client1',
            None,
            'ru',
            '2016-03-17',
            '2016-03-18',
            200,
            [
                ('report.company', '', 'Yandex.Taxi team', *[''] * 37),
                ('report.period', '', '17.03.2016 - 18.03.2016', *[''] * 37),
                ('report.rides_count', '', 0.0, *[''] * 37),
                ('report.total_cost_with_vat', '', 0.0, *[''] * 37),
                tuple([''] * 40),
                with_cc(DEPARTMENT_REPORT_COLUMN_HEADERS),
                (*[''] * 38, 'report.result', 0.0),
            ],
            id='test-8, client1, with cost center',
        ),
        pytest.param(
            'client7',
            'client7',
            None,
            'ru',
            '2020-02-01',
            '2020-03-01',
            200,
            [
                ('report.company', '', 'yandex7', *[''] * 30),
                ('report.period', '', '01.02.2020 - 01.03.2020', *[''] * 30),
                ('report.rides_count', '', 1.0, *[''] * 30),
                tuple([''] * 33),
                HIDDEN_PRICES_REPORT_COLUMN_HEADERS,
                (
                    '02.02.2020',
                    '12:00:00',
                    '13:00:00',
                    '+79264333399',
                    '',
                    'Weekday.sunday',
                    'TestU6',
                    'sales',
                    'd6',
                    'd6',
                    '+79264333399',
                    'testu6@mail.com',
                    '',
                    '+79992224444',
                    '+79881234567, +79881234568',
                    'order8',
                    'moscow',
                    'Россия, Москва, улица Льва Толстого, 16',
                    '',
                    'Россия, Москва, Большая Никитская улица, 13',
                    '\'37.58878761211858\', \'55.73414175200699\'',
                    '',
                    '\'37.600296\', \'55.750379\'',
                    '',
                    '',
                    '02.02.2020 13:14:00',
                    'econom',
                    '',
                    '',
                    '',
                    '',
                    50,
                    '',
                ),
            ],
            id='test-9, client1, hidden prices and combo order',
        ),
    ],
    indirect=['passport_mock'],
)
@pytest.mark.config(
    CORP_CATEGORIES={'__default__': {'econom': 'econom'}},
    CORP_COUNTRIES_SUPPORTED={'isr': {'vat': 0.17}},
)
async def test_general_get_xls(
        taxi_corp_real_auth_client,
        taxi_corp_app_stq,
        db,
        patch,
        pd_patch,
        file_format,
        content_type,
        client_id,
        passport_mock,
        department_id,
        locale,
        since_date,
        till_date,
        status,
        expected_content,
):
    @patch('taxi.clients.passport.PassportClient.get_info_by_uid')
    async def _get_uid(*args, **kwargs):
        return {'uid': '11111', 'login': 'some_manager'}

    @patch(
        'taxi_corp.clients.corp_discounts.'
        'CorpDiscountsClient.get_client_links',
    )
    async def _get_client_links(*args, **kwargs):
        return {'items': []}

    @patch(
        'taxi_corp.clients.corp_combo_orders.'
        'CorpComboOrdersClient.get_orders_list',
    )
    async def _get_orders_list(*args, **kwargs):
        return COMBO_ORDERS_RESPONSE  # check only for order8

    params = {
        'format': file_format,
        'since_date': since_date,
        'till_date': till_date,
        'lang': locale,
    }
    if department_id:
        params['department_id'] = department_id

    response = await taxi_corp_real_auth_client.get(
        '/1.0/client/{}/order'.format(client_id), params=params,
    )

    assert response.status == status
    if status != 200:
        return

    assert response.headers.get('Content-Type') == content_type

    book = xlrd.open_workbook(file_contents=await response.read())
    sheet = book.sheet_by_index(0)
    actual_content = [
        tuple(col.value for col in row) for row in sheet.get_rows()
    ]
    assert actual_content == expected_content

    period = reports.parse_period_args(since_date, till_date, 'Europe/Moscow')
    report_request = structs.OrdersReportParams(
        client_id=client_id,
        department_id=department_id,
        since=period.since,
        till=period.till,
        locale=locale,
        requested_by_ip='127.0.0.1',
    )

    report_generator = report.TaxiReport(taxi_corp_app_stq)

    if file_format == 'xls':
        data = (await report_generator.generate_xls(report_request)).to_xls()
    else:
        data = (await report_generator.generate(report_request)).to_xlsx()

    book = xlrd.open_workbook(file_contents=data)
    sheet = book.sheet_by_index(0)
    actual_content = [
        tuple(col.value for col in row) for row in sheet.get_rows()
    ]
    assert actual_content == expected_content
