# flake8: noqa: I100
# pylint: disable=broad-except
import aiohttp
import pytest

from supportai_actions.actions import action as action_module
from supportai_actions.actions import features as feature_module
from supportai_actions.actions import params as params_module
from supportai_actions.actions import state as state_module
from supportai_actions.action_types.burger_king_dialog import orders_table

DATA = {
    'status': 'ok',
    'techwork': None,
    'response': [
        {
            'id': 202595043,
            'uuid': '0ec838ea-b808-44c0-8987-6a61a8d9ff21',
            'user_id': 6414390,
            'user_address': None,
            'order_source': 'kiosk',
            'courier_name': None,
            'courier_phone': None,
            'fiscal_receipt_number': None,
            'shift_number': None,
            'created_at': '2022-04-09 17:02:49.7708',
            'price': 98997,
            'status': 9,
            'restaurant_name': (
                '0054-МСК, ш Киевское 1, БП Румянцево корп Б пав 105Б'
            ),
            'restaurant_phone': '8(495)544-50-00',
            'territorial_name': 'Соколова Юлия Геннадьевна',
            'territorial_phone': '89992777256',
            'taken_status': None,
            'queue': 'P-88',
            'external_id': None,
            'dishes': [],
            'combos': [
                {
                    'id': 6065,
                    'guid': None,
                    'code': None,
                    'rel_dish_id': 0,
                    'name': '6 за 329,99',
                    'price': 0,
                    'item_price': None,
                    'total_price': None,
                    'type': 0,
                    'count': 1,
                    'tax': None,
                    'dishes': [
                        {
                            'id': 4,
                            'guid': None,
                            'code': None,
                            'group_id': 4676,
                            'name': 'Воппер',
                            'price': 18999,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 103,
                            'guid': None,
                            'code': None,
                            'group_id': 4680,
                            'name': 'Сырные Медальоны 3 штуки',
                            'price': 4999,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 617,
                            'guid': None,
                            'code': None,
                            'group_id': 4677,
                            'name': 'Сандэй Ванильный',
                            'price': 4404,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 156,
                            'guid': None,
                            'code': None,
                            'group_id': 4679,
                            'name': 'Картофель Деревенский джуниор',
                            'price': 100,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 156,
                            'guid': None,
                            'code': None,
                            'group_id': 4678,
                            'name': 'Картофель Деревенский джуниор',
                            'price': 100,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 626,
                            'guid': None,
                            'code': None,
                            'group_id': 4681,
                            'name': 'Липтон Грин джуниор',
                            'price': 4397,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                    ],
                },
                {
                    'id': 6065,
                    'guid': None,
                    'code': None,
                    'rel_dish_id': 0,
                    'name': '6 за 329,99',
                    'price': 0,
                    'item_price': None,
                    'total_price': None,
                    'type': 0,
                    'count': 1,
                    'tax': None,
                    'dishes': [
                        {
                            'id': 10267,
                            'guid': None,
                            'code': None,
                            'group_id': 4678,
                            'name': 'Луковые колечки 3 штуки',
                            'price': 100,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 96,
                            'guid': None,
                            'code': None,
                            'group_id': 4680,
                            'name': 'Кинг Наггетс 4 штуки',
                            'price': 4999,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 617,
                            'guid': None,
                            'code': None,
                            'group_id': 4677,
                            'name': 'Сандэй Ванильный',
                            'price': 4404,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 4,
                            'guid': None,
                            'code': None,
                            'group_id': 4676,
                            'name': 'Воппер',
                            'price': 18999,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 156,
                            'guid': None,
                            'code': None,
                            'group_id': 4679,
                            'name': 'Картофель Деревенский джуниор',
                            'price': 100,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 624,
                            'guid': None,
                            'code': None,
                            'group_id': 4681,
                            'name': 'Миринда оранж джуниор 0,3л',
                            'price': 4397,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                    ],
                },
                {
                    'id': 6065,
                    'guid': None,
                    'code': None,
                    'rel_dish_id': 0,
                    'name': '6 за 329,99',
                    'price': 0,
                    'item_price': None,
                    'total_price': None,
                    'type': 0,
                    'count': 1,
                    'tax': None,
                    'dishes': [
                        {
                            'id': 625,
                            'guid': None,
                            'code': None,
                            'group_id': 4681,
                            'name': 'Липтон Лимон',
                            'price': 4397,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 4,
                            'guid': None,
                            'code': None,
                            'group_id': 4676,
                            'name': 'Воппер',
                            'price': 18999,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 10267,
                            'guid': None,
                            'code': None,
                            'group_id': 4679,
                            'name': 'Луковые колечки 3 штуки',
                            'price': 100,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 96,
                            'guid': None,
                            'code': None,
                            'group_id': 4680,
                            'name': 'Кинг Наггетс 4 штуки',
                            'price': 4999,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 7682,
                            'guid': None,
                            'code': None,
                            'group_id': 4677,
                            'name': 'Шоколадный батончик Snickers Stick',
                            'price': 4404,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 156,
                            'guid': None,
                            'code': None,
                            'group_id': 4678,
                            'name': 'Картофель Деревенский джуниор',
                            'price': 100,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                    ],
                },
            ],
        },
        {
            'id': 202593153,
            'uuid': 'd3bf9c29-3a09-4fe1-a629-9a8b9ec5dd38',
            'user_id': 6414390,
            'user_address': None,
            'order_source': 'kiosk',
            'courier_name': None,
            'courier_phone': None,
            'fiscal_receipt_number': None,
            'shift_number': None,
            'created_at': '2022-04-09 16:59:47.2757',
            'price': 47597,
            'status': 9,
            'restaurant_name': (
                '0054-МСК, ш Киевское 1, БП Румянцево корп Б пав 105Б'
            ),
            'restaurant_phone': '8(495)544-50-00',
            'territorial_name': 'Соколова Юлия Геннадьевна',
            'territorial_phone': '89992777256',
            'taken_status': None,
            'queue': 'P-90',
            'external_id': None,
            'dishes': [],
            'combos': [
                {
                    'id': 3998,
                    'guid': '9f3822db-4ee7-4653-9411-e83276027a15',
                    'code': '16375',
                    'rel_dish_id': 9055,
                    'name': '3 соуса на выбор',
                    'price': 12999,
                    'item_price': 12999,
                    'total_price': 12999,
                    'type': 0,
                    'count': 1,
                    'tax': None,
                    'dishes': [
                        {
                            'id': 31,
                            'guid': None,
                            'code': None,
                            'group_id': 3023,
                            'name': 'Соус Кисло-сладкий',
                            'price': 0,
                            'item_price': None,
                            'total_price': None,
                            'type': 7,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 32,
                            'guid': None,
                            'code': None,
                            'group_id': 3023,
                            'name': 'Соус Сырный',
                            'price': 0,
                            'item_price': None,
                            'total_price': None,
                            'type': 7,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 31,
                            'guid': None,
                            'code': None,
                            'group_id': 3023,
                            'name': 'Соус Кисло-сладкий',
                            'price': 0,
                            'item_price': None,
                            'total_price': None,
                            'type': 7,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                    ],
                },
                {
                    'id': 6065,
                    'guid': None,
                    'code': None,
                    'rel_dish_id': 0,
                    'name': '6 за 329,99',
                    'price': 0,
                    'item_price': None,
                    'total_price': None,
                    'type': 0,
                    'count': 1,
                    'tax': None,
                    'dishes': [
                        {
                            'id': 10267,
                            'guid': None,
                            'code': None,
                            'group_id': 4678,
                            'name': 'Луковые колечки 3 штуки',
                            'price': 100,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 2343,
                            'guid': None,
                            'code': None,
                            'group_id': 4677,
                            'name': 'Ванильный Шейк малый 0,3л',
                            'price': 6003,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 156,
                            'guid': None,
                            'code': None,
                            'group_id': 4679,
                            'name': 'Картофель Деревенский джуниор',
                            'price': 100,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 96,
                            'guid': None,
                            'code': None,
                            'group_id': 4680,
                            'name': 'Кинг Наггетс 4 штуки',
                            'price': 4999,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 4,
                            'guid': None,
                            'code': None,
                            'group_id': 4676,
                            'name': 'Воппер',
                            'price': 18999,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                        {
                            'id': 625,
                            'guid': None,
                            'code': None,
                            'group_id': 4681,
                            'name': 'Липтон Лимон',
                            'price': 4397,
                            'item_price': None,
                            'total_price': None,
                            'type': None,
                            'count': 1,
                            'combo_modi_id': None,
                            'tax': None,
                            'modifiers': [],
                        },
                    ],
                },
            ],
        },
    ],
}


@pytest.fixture(name='mock_service', autouse=True)
def _mock_service(monkeypatch, response_mock):
    def request(**kwargs):
        url = kwargs.get('url')

        class RequestContextManager:
            async def __aenter__(self):
                return response_mock(
                    status=200 if '200' in url else 500, json=DATA,
                )

            async def __aexit__(self, exc_type, exc_val, exc_tb):
                pass

        return RequestContextManager()

    monkeypatch.setattr(aiohttp, 'request', request)


@pytest.mark.parametrize(
    '_call_param, state',
    [
        pytest.param(
            [
                params_module.ActionParam({'url': 'http://localhost/200'}),
                params_module.ActionParam({'method': 'GET'}),
                params_module.ActionParam(
                    {'headers': {'some_header': 'some_header'}},
                ),
                params_module.ActionParam({'timeout_s': 300}),
                params_module.ActionParam({'retries': 5}),
                params_module.ActionParam({'backoff_factor': 2}),
                params_module.ActionParam(
                    {'basic_auth': {'login': 'some_login'}},
                ),
            ],
            state_module.State(
                features=feature_module.Features(
                    features=[
                        {'key': 'selected_order_id', 'value': '202593153'},
                        {'key': 'phone', 'value': '+79533313773'},
                        {'key': 'selected_date_end', 'value': '2022-04-06'},
                        {'key': 'selected_date_start', 'value': '2022-04-13'},
                        {'key': 'code', 'value': '200'},
                    ],
                ),
            ),
        ),
    ],
)
async def test_burger_king_orders_table(web_context, state, _call_param):
    action = orders_table.OrdersTableAction('echo', 'echo', '0', _call_param)
    res = await action(web_context, state)
    assert res.features['orders_table'] is not None
