INSERT INTO payment_transactions (uuid, order_id, order_items, payment_type, front_uuid, side_payment_id, status, place_id)
VALUES ('transaction_uuid__1',
        1,
        '[{"id": "product_id__1", "title": "Торт с холестерином", "price": 0.1,
        "base_price": 0.1, "quantity": 1, "in_pay_count": 0, "paid_count": 1,
        "vat": 20.0},
           {"id" : "product_id__2", "title": "Палтус за палтус", "price": 0.2,
        "base_price": 0.2, "quantity": 1, "in_pay_count": 0, "paid_count": 1,
        "vat": 20.0}]',
        'sbp',
        'transaction_front_uuid__1',
        1204138470,
        'success',
        'place_id__1'),
       ('transaction_uuid__2',
        2,
        '[{"id": "product_id__1", "title": "Торт с холестерином", "price": 0.1,
        "base_price": 0.1, "quantity": 1, "in_pay_count": 0, "paid_count": 1,
        "vat": 20.0},
           {"id" : "product_id__2", "title": "Палтус за палтус", "price": 0.2,
        "base_price": 0.2, "quantity": 1, "in_pay_count": 0, "paid_count": 1,
        "vat": 20.0}]',
        'sbp',
        'transaction_front_uuid__2',
        1204138470,
        'success',
        'place_id__2'),
       ('transaction_uuid__3',
        1,
        '[{"id": "product_id__1", "title": "Торт с холестерином", "price": 0.1,
        "base_price": 0.1, "quantity": 1, "in_pay_count": 1, "paid_count": 0,
        "vat": 20.0},
           {"id" : "product_id__2", "title": "Палтус за палтус", "price": 0.2,
        "base_price": 0.2, "quantity": 1, "in_pay_count": 1, "paid_count": 0,
        "vat": 20.0}]',
        'sbp',
        'transaction_front_uuid__3',
        1204138470,
        'in_progress',
        'place_id__1'),
       ('transaction_uuid__4',
        1,
        '[{"id": "product_id__1", "title": "Торт с холестерином", "price": 0.1,
        "base_price": 0.1, "quantity": 1, "in_pay_count": 0, "paid_count": 1,
        "vat": 20.0},
           {"id" : "product_id__2", "title": "Палтус за палтус", "price": 0.2,
        "base_price": 0.2, "quantity": 1, "in_pay_count": 0, "paid_count": 1,
        "vat": 20.0}]',
        'payture',
        'transaction_front_uuid__4',
        1204138470,
        'success',
        'place_id__1'),
       ('transaction_uuid__5',
        2,
        '[{"id": "product_id__1", "title": "Торт с холестерином", "price": 0.1,
        "base_price": 0.1, "quantity": 1, "in_pay_count": 0, "paid_count": 1,
        "vat": 20.0},
           {"id" : "product_id__2", "title": "Палтус за палтус", "price": 0.2,
        "base_price": 0.2, "quantity": 1, "in_pay_count": 0, "paid_count": 1,
        "vat": 20.0}]',
        'payture',
        'transaction_front_uuid__5',
        1204138470,
        'success',
        'place_id__2'),
       ('transaction_uuid__6',
        1,
        '[{"id": "product_id__1", "title": "Торт с холестерином", "price": 0.1,
        "base_price": 0.1, "quantity": 1, "in_pay_count": 0, "paid_count": 1,
        "vat": 20.0},
           {"id" : "product_id__2", "title": "Палтус за палтус", "price": 0.2,
        "base_price": 0.2, "quantity": 1, "in_pay_count": 0, "paid_count": 1,
        "vat": 20.0}]',
        'trust_card',
        'transaction_front_uuid__6',
        1204138470,
        'success',
        'place_id__1'),
       ('transaction_uuid__7',
        2,
        '[{"id": "product_id__1", "title": "Торт с холестерином", "price": 0.1,
        "base_price": 0.1, "quantity": 1, "in_pay_count": 0, "paid_count": 1,
        "vat": 20.0},
           {"id" : "product_id__2", "title": "Палтус за палтус", "price": 0.2,
        "base_price": 0.2, "quantity": 1, "in_pay_count": 0, "paid_count": 1,
        "vat": 20.0}]',
        'trust_card',
        'transaction_front_uuid__7',
        1204138470,
        'success',
        'place_id__2')
;

