#! /usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = "Zasimov Alexey"
__email__ = "zasimov-a@yandex-team.ru"

u"""
Забираем текущие экспорты и парсим их.
"""

from httplib2 import Http
from wp7desktop.share.xml import parse
from wp7desktop.share.network import get_page
from StringIO import StringIO

if __name__ == "__main__":
    http = Http()
    c = get_page(http, "http://stocks-dev.yandex.net/xmlhist/10000.xml")
    parse(StringIO(c))
    get_page(http, "http://export.yandex.ru/weather-ng/export-by-geo.tar.bz2")
    c = get_page(http, "http://info.maps.yandex.net/traffic/current/stat.xml")
    parse(StringIO(c))
