#! /bin/bash

# Экспортные файлы, которые мы используем.

[ -f tests-data/exports/stocks/10000.xml ] || exit 1
[ -f tests-data/exports/traffic/stat.xml ] || exit 1
[ -f tests-data/exports/weather/10.xml ] || exit 1
