INSERT INTO price_modifications.rules
    (rule_id, previous_version_id, deleted, name, source_code, policy, author, approvals_id, ast, updated, extra_return)
  VALUES
(1, null, true, 'draft_with_base_rule', 'return (1 / *ride.price) * ride.price;', 'backend_only', '200ok', 11, 'CR(boarding=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(boarding)),distance=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(distance)),time=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(time)),waiting=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(waiting)),requirements=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(requirements)),transit_waiting=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(transit_waiting)),destination_waiting=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(destination_waiting)))', '2010-04-04 06:00:00', ARRAY['ex1', 'ex2']),
(2, 1, false, 'draft_with_base_rule', 'return (1 / *ride.price) * ride.price;', 'backend_only', '200ok', 12, 'CR(boarding=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(boarding)),distance=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(distance)),time=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(time)),waiting=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(waiting)),requirements=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(requirements)),transit_waiting=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(transit_waiting)),destination_waiting=B(B(B(1.00000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(destination_waiting)))', '2010-04-04 06:00:00', ARRAY['ex1', 'ex2']),
(3, null, false, 'draft_with_no_base_rule', 'return (2 / *ride.price) * ride.price;', 'backend_only', '200ok', 13, 'CR(boarding=B(B(B(2.000000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(boarding)),distance=B(B(B(2.000000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(distance)),time=B(B(B(2.000000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(time)),waiting=B(B(B(2.000000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(waiting)),requirements=B(B(B(2.000000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(requirements)),transit_waiting=B(B(B(2.000000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(transit_waiting)),destination_waiting=B(B(B(2.000000,/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(destination_waiting)))', '2011-04-04 06:00:00', ARRAY['ex1'])
;

INSERT INTO price_modifications.rules_drafts
    (rule_id, previous_version_id, use_draft_previous_rule_id, name, source_code, policy, author, status, ast, approvals_id, pmv_task_id)
  VALUES
(4, null, false, 'draft_with_no_base_rule', 'return ride.price;', 'backend_only', '200ok draft', 'to_approve', 'CR(boarding=TX(1,0),destination_waiting=TX(1,6),distance=TX(1,1),metadata=NT(),requirements=51.000000,time=TX(1,2),transit_waiting=TX(1,5),waiting=TX(1,3))', 1, 1),
(5, 1, true, 'draft_with_base_rule', 'return ride.price;', 'backend_only', '200ok draft', 'to_approve', 'CR(boarding=TX(1,0),destination_waiting=TX(1,6),distance=TX(1,1),metadata=NT(),requirements=51.000000,time=TX(1,2),transit_waiting=TX(1,5),waiting=TX(1,3))', 1, 1),
(6, null, false, 'draft_new_rule', 'return ride.price;', 'backend_only', '200ok draft', 'to_approve', 'CR(boarding=TX(1,0),destination_waiting=TX(1,6),distance=TX(1,1),metadata=NT(),requirements=51.000000,time=TX(1,2),transit_waiting=TX(1,5),waiting=TX(1,3))', 1, 1)
;
