#!/bin/sh

set -e

case "$1" in
    configure)
	mkdir -p /var/lib/mongodb
	if [[ -f /var/lib/mongodb/key ]]; then
	  chown mongodb:mongodb /var/lib/mongodb/key
	  chmod 400 /var/lib/mongodb/key
	fi
	if [[ ! -d  /opt/configdb ]]; then mkdir -p /opt/configdb; fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0


