INSERT INTO dispatch_check_in.check_in_orders (
    order_id,
    updated_ts,
    created_ts,
    check_in_ts,
    terminal_id,
    pickup_line,
    tariff_zone,
    user_id,
    user_phone_id,
    user_locale,
    classes
) VALUES
      (
          'order_id',
          NOW(),
          NOW(),
          NOW(),
          'svo',
          'svo_line_1',
          'some_tariff_zone',
          'some_user1',
          'some_phone_id',
          'ru',
          '{econom, comfortplus}'
      ),
      (
          'order_id2',
          NOW(),
          NOW(),
          NULL,
          'svo',
          'svo_line_1',
          'some_tariff_zone2',
          'some_user2',
          'some_phone_id2',
          'ru',
          '{business}'
      );
