INSERT INTO callcenter_auth.operators_access
    (yandex_uid, yandex_login, callcenter_id, first_name, middle_name, last_name, created_at, deleted_at, updated_at, state, password, supervisor_login, phone_number, working_domain, operator_id, staff_login, staff_login_state, mentor_login, employment_date, name_in_telephony, timezone)
VALUES
    ('uid1', 'login1', 'random_cc', 'name1', NULL, 'surname1', '2018-06-21 20:00:00+00'::TIMESTAMPTZ, NULL, '2018-06-22 19:00:00+00'::TIMESTAMPTZ, 'ready', 'DBg+FwQTGD4XBB4WOBoLUg==', 'admin@unit.test', '+1', 'yandex-team.ru', 1000000000, NULL, 'unverified', NULL, '2018-06-21'::DATE, 'tel_name', 'Europe/Moscow'),
    ('uid2', 'login2', 'cc1', 'name2', NULL, 'surname2', '2018-06-21 19:00:00+00'::TIMESTAMPTZ, NULL, '2018-06-22 19:00:00+00'::TIMESTAMPTZ, 'ready', 'DBg+FwQTGD4XBB4WOBoLUg==', 'admin@unit.test', '+2', 'yandex-team.ru',  1000000001, 'staff_login2', 'unverified', NULL, '2018-06-21'::DATE, 'tel_name', 'Europe/Moscow'),
    ('uid3', 'login3', 'another_random_cc', 'name3', 'middle_name', 'surname3', '2018-06-21 19:00:00+00'::TIMESTAMPTZ, NULL, '2018-06-22 19:00:00+00'::TIMESTAMPTZ,  'ready', 'DBg+FwQTGD4XBB4WOBoLUg==', 'admin@unit.test', '+3', 'yandex-team.ru', 1000000002, 'not_staff_login3', 'unverified', NULL, '2018-06-21'::DATE, 'tel_name', 'Europe/Moscow'),
    ('uid_deleted', 'login_deleted', 'another_random_cc', 'name3', NULL, 'surname3', '2018-06-21 19:00:00+00'::TIMESTAMPTZ, NULL, '2018-06-22 19:00:00+00'::TIMESTAMPTZ,  'deleted', 'DBg+FwQTGD4XBB4WOBoLUg==', 'admin@unit.test', '+3', 'yandex-team.ru', 1000000003, 'not_staff_login3', 'unverified', NULL, '2018-06-21'::DATE, 'tel_name', 'Europe/Moscow'),
    ('uid_not_internal_domain', 'login_not_internal_domain', 'another_random_cc', 'name3', NULL, 'surname3', '2018-06-21 19:00:00+00'::TIMESTAMPTZ, NULL, '2018-06-22 19:00:00+00'::TIMESTAMPTZ,  'ready', 'DBg+FwQTGD4XBB4WOBoLUg==', 'admin@unit.test', '+3', 'not-yandex-team.ru', 1000000004, 'not_staff_login3', 'unverified', NULL, '2018-06-21'::DATE, 'tel_name', 'Europe/Moscow');
   
INSERT INTO callcenter_auth.m2m_operators_roles
    (yandex_uid, role)
VALUES
    ('uid1', 'operator'),
    ('uid2', 'operator'),
    ('uid3', 'operator');

INSERT INTO callcenter_auth.current_info
    (
        sub_status,
        status,
        metaqueues,
        id
    )
VALUES
    (
        'tech',
        'paused',
        '{test}',
        0
    ),
    (
        NULL,
        'disconnected',
        '{test_another}',
        1
    ),
    (
        NULL,
        'connected',
        '{test}',
        2
    );
