INSERT INTO clients_schema.experiments (name,
                                        date_from,
                                        date_to,
                                        rev,
                                        default_value,
                                        clauses,
                                        predicate,
                                        description,
                                        enabled,
                                        schema,
                                        is_config,
                                        removed,
                                        department)
    VALUES ('single_config',  -- 1
            CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
            nextval('clients_schema.clients_rev'),
            NULL,
            '[{"title": "clause_title", "value": {}, "predicate": {"type": "true"}}]'::jsonb,
            '{"type": "true"}'::jsonb,
            'DESCRIPTION',
            FALSE,
            'additionalProperties: true',
            TRUE,
            FALSE,
            'market'),


           ('object_with_duplicated_name',  -- 2 Experiment
            CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
            nextval('clients_schema.clients_rev'),
            NULL,
            '[{"title": "clause_title", "value": {}, "predicate": {"type": "true"}}]'::jsonb,
            '{"type": "true"}'::jsonb,
            'DESCRIPTION',
            FALSE,
            'additionalProperties: true',
            FALSE,
            FALSE,
            'market'),
           ('object_with_duplicated_name',  -- 3 Config
            CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
            nextval('clients_schema.clients_rev'),
            NULL,
            '[{"title": "clause_title", "value": {}, "predicate": {"type": "true"}}]'::jsonb,
            '{"type": "true"}'::jsonb,
            'DESCRIPTION',
            FALSE,
            'additionalProperties: true',
            TRUE,
            FALSE,
            'market'),
           ('enabled_config',  -- 4 Enabled Config
            CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
            nextval('clients_schema.clients_rev'),
            NULL,
            '[{"title": "clause_title", "value": {}, "predicate": {"type": "true"}}]'::jsonb,
            '{"type": "true"}'::jsonb,
            'DESCRIPTION',
            True,
            'additionalProperties: true',
            TRUE,
            FALSE,
            'market')
;
