// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package madm is a generated GoMock package.
package madm

import (
	geobase "a.yandex-team.ru/library/go/yandex/geobase"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockgeoBase is a mock of geoBase interface.
type MockgeoBase struct {
	ctrl     *gomock.Controller
	recorder *MockgeoBaseMockRecorder
}

// MockgeoBaseMockRecorder is the mock recorder for MockgeoBase.
type MockgeoBaseMockRecorder struct {
	mock *MockgeoBase
}

// NewMockgeoBase creates a new mock instance.
func NewMockgeoBase(ctrl *gomock.Controller) *MockgeoBase {
	mock := &MockgeoBase{ctrl: ctrl}
	mock.recorder = &MockgeoBaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgeoBase) EXPECT() *MockgeoBaseMockRecorder {
	return m.recorder
}

// GetParentsIDsDef mocks base method.
func (m *MockgeoBase) GetParentsIDsDef(id geobase.ID) ([]geobase.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParentsIDsDef", id)
	ret0, _ := ret[0].([]geobase.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParentsIDsDef indicates an expected call of GetParentsIDsDef.
func (mr *MockgeoBaseMockRecorder) GetParentsIDsDef(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParentsIDsDef", reflect.TypeOf((*MockgeoBase)(nil).GetParentsIDsDef), id)
}
