#!/bin/bash

#echo "should run under morda"
# токен робота robot-morda-yt
yt_token=$(</etc/yandex/portal/morda/keys/ROBOT-MORDA-YT_OAUTH_RO)
YT_TOKEN=$yt_token yt2 read \
    '//home/antivir/prod/export/widgets/threats{mask}' \
    --proxy banach --format dsv > /opt/www/bases/infected_masks
sed -i 's/^mask=//' /opt/www/bases/infected_masks

/opt/www/morda/wadm/scripts/widgets_job.pl --action=fast-antivir
