#!/bin/sh

set -e


# Have you ever tried to remove old config file from previous version of deb package?
# Well, it took 4 people and a day of thinking and we came to conslusion that this is by far
# the easiest way to do it.
rm -f "/etc/yandex/taxi/first-unit/push-client-first-unit.production.yaml"
rm -f "/etc/yandex/taxi/first-unit/push-client-first-unit.testing.yaml"
rm -f "/etc/yandex/taxi/first-unit/push-client-first-unit.unstable.yaml"
rm -f "/etc/yandex/taxi/first-unit/push-client-first-unit.stress.yaml"
rm -f "/etc/yandex/taxi/first-unit/push-client-first-unit.testsuite.yaml"
rm -f "/etc/yandex/statbox-push-client/custom/first-unit.yaml"



#DEBHELPER#

exit 0
