insert into payouts.payout_batches (
    type_code,
    status_code,
    client_id,
    contract_id,
    contract_alias,
    contract_type,
    firm_id,
    person_id,
    amount_w_vat,
    currency,
    updated_at_utc
)
values
(
    'PAYOUT',
    'EXPORT_READY',
    '123456',
    '654321',
    '654321/123',
    'revenues',
     13,
    '111111',
    1234.56,
    'RUB',
	'2022-06-21 09:59:03.0676'
),
(
    'PAYOUT',
    'EXPORT_READY',
    '123457',
    '754321',
    '754321/123',
    'revenues',
    13,
    '222222',
    1234.57,
    'RUB',
	'2022-06-22 09:59:15.817547'
),
(
    'PAYOUT',
    'EXPORT_READY',
    '123458',
    '854321',
    '854321/123',
    'revenues',
    13,
    '333333',
    1234.58,
    'RUB',
    '2022-06-23 09:59:32.015871'
);

insert into payouts.batch_change_log (
    batch_id,
    batch_status_code,
    idempotency_key,
    created_at_utc
)
values
(
    1,
    'PAYOUT_READY',
    '1/PAYOUT_READY',
	'2022-06-22 10:00:45.257851'
),
(
    1,
    'EXPORT_READY',
    '1/EXPORT_READY',
	'2022-06-22 10:01:03.306299'
),
(
    2,
    'PAYOUT_READY',
    '2/PAYOUT_READY',
	'2022-06-22 10:00:45.257851'
),
(
    2,
    'EXPORT_READY',
    '2/EXPORT_READY',
	'2022-06-22 10:01:03.306299'
),
(
    3,
    'PAYOUT_READY',
    '3/PAYOUT_READY',
    '2022-06-23 10:00:07.302417'
),
(
    3,
    'EXPORT_READY',
    '3/EXPORT_READY',
    '2022-06-23 10:00:19.180674'
);

insert into export.consumer_cursors (
    cursor,
    consumer_id
)
values
(
    2,
    'billing_fin_payouts.crontasks.upload_export_batches_to_hahn'
);
