insert into export.consumer_cursors (
    cursor,
    consumer_id
)
values
(
    5,
    'billing_fin_payouts.crontasks.upload_interface_expenses_to_hahn'

),
(
    10,
    'billing_fin_payouts.crontasks.upload_interface_expenses_to_arnold'
),
(
    100,
    'billing_fin_payouts.crontasks.upload_interface_revenues_to_hahn'

),
(
    200,
    'billing_fin_payouts.crontasks.upload_interface_payments_to_hahn'
)
;
