#! /usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = "Zasimov Alexey"
__email__ = "zasimov-a@yandex-team.ru"


from wp7desktop.share.wp7 import Canvas, border
from wp7desktop.share.wp7.backing import WIDTH
from wp7desktop.share.wp7.padding import CroppingError
from wp7desktop.share.wp7.fonts import init_fonts, Font

if __name__ == "__main__":
    c = Canvas(border(5))


    init_fonts("fonts")
    font = Font("SegoeWP.ttf", 42.667, (1.0, 1.0, 1.0, 0.60))
    c.set_font(font)


    del c

    try:
        c = Canvas(border(WIDTH*2))
        print "cropping error"
        exit(1)
    except CroppingError:
        pass

    

