#! /usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = "Zasimov Alexey"
__email__ = "zasimov-a@yandex-team.ru"


from wp7desktop.share.wp7.fonts import init_fonts, Font


if __name__ == "__main__":
    init_fonts("fonts")
    stocks_value = Font("SegoeWP.ttf", 42.667, (1.0, 1.0, 1.0, 0.60))
