#!/bin/sh

GEO_LIB_VERSION='3.0.5'
DEST=/opt/www/bases/test/
mkdir -p $DEST
svn export svn+ssh://svn.yandex.ru/geobase/tags/stable/library-$GEO_LIB_VERSION/tests/geolocation_test_data ${DEST}geolocation_test_data
svn export svn+ssh://svn.yandex.ru/geobase/tags/stable/library-$GEO_LIB_VERSION/tests/geodata.bin ${DEST}geodata3.bin 


