CREATE_ON_DEMAND = """<root>
	<token>1111111111111111</token>
	<uniq>fP0fbpZ9Edzd3a1iw4gnMda1kGOnPw5Y</uniq>
	<hash>fP0fbpZ9Edzd3a1iw4gnMda1kGOnPw5Y</hash>
	<request type="createOrder">
		<order>
			<orderId>
				<yandexId>{request_id}</yandexId>
			</orderId>
			<locationFrom>
				<country>Россия</country>
				<region>Москва и Московская область</region>
				<locality>Москва</locality>
				<settlement>Москва</settlement>
				<street>улица Льва Толстого</street>
				<house>16</house>
				<zipCode>123412</zipCode>
				<lat>55.733969</lat>
				<lng>37.587093</lng>
				<locationId>213</locationId>
			</locationFrom>
			<warehouseFrom>
				<id>
					<yandexId>10000981168</yandexId>
					<deliveryId>53</deliveryId>
					<partnerId>53</partnerId>
				</id>
				<address>
					<country>Россия</country>
					<region>Москва и Московская область</region>
					<locality>Москва</locality>
					<settlement>Москва</settlement>
					<street>улица Льва Толстого</street>
					<house>16</house>
					<zipCode>123412</zipCode>
					<lat>55.733969</lat>
					<lng>37.587093</lng>
					<locationId>213</locationId>
				</address>
				<schedule>
					<workTime>
						<day>1</day>
						<periods>
							<timeInterval>09:00:00+03:00/23:59:00+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>2</day>
						<periods>
							<timeInterval>00:01:00+03:00/23:59:00+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>3</day>
						<periods>
							<timeInterval>09:00:00+03:00/21:00:00+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>4</day>
						<periods>
							<timeInterval>09:00:00+03:00/21:00:00+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>5</day>
						<periods>
							<timeInterval>09:00:00+03:00/21:00:00+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>6</day>
						<periods>
							<timeInterval>09:00:00+03:00/20:00:00+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>7</day>
						<periods>
							<timeInterval>09:00:00+03:00/21:00:00+03:00</timeInterval>
						</periods>
					</workTime>
				</schedule>
				<phones>
					<phone>
						<phoneNumber>+79151005429</phoneNumber>
					</phone>
				</phones>
				<instruction>идти прямо от метро</instruction>
			</warehouseFrom>
			<locationTo>
				<country>Россия</country>
				<federalDistrict>Центральный федеральный округ</federalDistrict>
				<region>Москва и Московская область</region>
				<locality>Москва</locality>
				<street>Льва Толстого</street>
				<house>16</house>
				<room>303</room>
				<zipCode>119021</zipCode>
				<intercom>007</intercom>
				<porch>404</porch>
				<floor>8</floor>
				<metro>Парк Культуры</metro>
				<lat>55.73397404565889</lat>
				<lng>37.587092522460836</lng>
				<locationId>213</locationId>
			</locationTo>
			<weight>1</weight>
			<length>12</length>
			<width>10</width>
			<height>11</height>
			<cargoType>0</cargoType>
			<cargoCost>890</cargoCost>
			<assessedCost>890</assessedCost>
			<paymentMethod>2</paymentMethod>
			<tariff>Такси и Лавки</tariff>
			<deliveryType>0</deliveryType>
			<deliveryCost>49</deliveryCost>
			<deliveryDate>{delivery_date}</deliveryDate>
            <deliveryInterval>18:00:00+03:00/19:00:00+03:00</deliveryInterval>
			<total>0</total>
			<amountPrepaid>939</amountPrepaid>
			<pickupPointId>
				<yandexId>10000981168</yandexId>
			</pickupPointId>
			<items>
				<item>
					<article>217172403.alisa3p</article>
					<name>Кукла Barbie Черно-белый твидовый костюм, 29 см, DWF54</name>
					<count>1</count>
					<price>890</price>
					<taxes>
						<tax>
							<type>VAT</type>
							<value>7</value>
						</tax>
					</taxes>
					<cargoTypes>
						<cargoType>980</cargoType>
						<cargoType>950</cargoType>
					</cargoTypes>
					<categoryName>Куклы и пупсы</categoryName>
					<korobyte>
						<width>10</width>
						<height>11</height>
						<length>12</length>
						<weightGross>1</weightGross>
					</korobyte>
					<unitId>
						<vendorId>10427354</vendorId>
						<article>217172403.alisa3p</article>
					</unitId>
					<supplier>
						<inn>3327123849</inn>
					</supplier>
				</item>
			</items>
			<recipient>
				<fio>
					<name>первоеимя</name>
					<surname>последнееимя</surname>
					<patronymic>среднееимя</patronymic>
				</fio>
				<phones>
					<phone>
						<phoneNumber>+78887776655</phoneNumber>
					</phone>
				</phones>
				<email>ymail@y.mail</email>
				<uid>851268023</uid>
			</recipient>
			<sender>
				<id>
					<yandexId>431782</yandexId>
				</id>
				<incorporation>ИП Саванеев Вячеслав Владимирович</incorporation>
				<phones>
					<phone>
						<phoneNumber>+74957392222</phoneNumber>
					</phone>
				</phones>
				<name>Яндекс.Маркет</name>
				<legalForm>2</legalForm>
				<inn>657145109813</inn>
				<taxation>1</taxation>
				<url>pokupki.market.yandex.ru</url>
				<ogrn>111111111111111</ogrn>
			</sender>
			<warehouse>
				<id>
					<yandexId>10000004403</yandexId>
					<deliveryId>172</deliveryId>
					<partnerId>172</partnerId>
				</id>
				<address>
					<country>Россия</country>
					<region>Московская область</region>
					<locality>Софьино</locality>
					<settlement>Софьино</settlement>
					<street>территория Логистический технопарк Софьино</street>
					<house>к1</house>
					<building></building>
					<housing></housing>
					<room></room>
					<zipCode>140126</zipCode>
					<lat>55.499346</lat>
					<lng>38.17672</lng>
					<locationId>120013</locationId>
				</address>
				<schedule>
					<workTime>
						<day>1</day>
						<periods>
							<timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>2</day>
						<periods>
							<timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>3</day>
						<periods>
							<timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>4</day>
						<periods>
							<timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>5</day>
						<periods>
							<timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>6</day>
						<periods>
							<timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>7</day>
						<periods>
							<timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
						</periods>
					</workTime>
				</schedule>
				<contact>
					<name>Антон</name>
					<surname>Сачков</surname>
				</contact>
				<phones>
					<phone>
						<phoneNumber>+79269900526</phoneNumber>
					</phone>
				</phones>
				<instruction>140126, Московская область, Раменский район, Софьинское сельское поселение, село Софьино, территория Логистический технопарк Софьино, к1</instruction>
			</warehouse>
			<services>
				<service>
					<code>
						<yandexId>CHECK</yandexId>
						<deliveryId>CHECK</deliveryId>
						<partnerId>CHECK</partnerId>
					</code>
					<isOptional>false</isOptional>
					<cost>0.0</cost>
				</service>
				<service>
					<code>
						<yandexId>DELIVERY</yandexId>
						<deliveryId>DELIVERY</deliveryId>
						<partnerId>DELIVERY</partnerId>
					</code>
					<isOptional>false</isOptional>
					<cost>0.0</cost>
					<taxes>
						<tax>
							<type>VAT</type>
							<value>7</value>
						</tax>
					</taxes>
				</service>
				<service>
					<code>
						<yandexId>INSURANCE</yandexId>
						<deliveryId>INSURANCE</deliveryId>
						<partnerId>INSURANCE</partnerId>
					</code>
					<isOptional>false</isOptional>
					<cost>0.0</cost>
				</service>
				<service>
					<code>
						<yandexId>RETURN_SORT</yandexId>
						<deliveryId>RETURN_SORT</deliveryId>
						<partnerId>RETURN_SORT</partnerId>
					</code>
					<isOptional>false</isOptional>
					<cost>0.0</cost>
				</service>
			</services>
			<comment>Оставить у двери</comment>
			<tags>
            <tag>ELECTRONIC_ACCEPTANCE_CERTIFICATE_REQUIRED</tag>
				<tag>ON_DEMAND</tag>
			</tags>
		</order>
		<restrictedData>
			<transferCodes>
				<inbound>
					<verification>96429</verification>
				</inbound>
			</transferCodes>
		</restrictedData>
	</request>
</root>"""

CREATE_EXPRESS = """<root>
	<token>1111111111111111</token>
	<uniq>8yxXkfZGekWJRv1phWJ3zMPAbFz0sSCd</uniq>
	<hash>8yxXkfZGekWJRv1phWJ3zMPAbFz0sSCd</hash>
	<request type="createOrder">
		<order>
			<orderId>
				<yandexId>{request_id}</yandexId>
			</orderId>
			<locationFrom>
				<country>Россия</country>
				<region>Москва и Московская область</region>
				<locality>Москва</locality>
				<settlement>Москва</settlement>
				<street>Проспект Мира</street>
				<house>12</house>
				<building></building>
				<housing></housing>
				<room></room>
				<zipCode>129085</zipCode>
				<lat>55.774532</lat>
				<lng>37.632745</lng>
				<locationId>213</locationId>
			</locationFrom>
			<warehouseFrom>
				<id>
					<yandexId>10000998614</yandexId>
					<deliveryId>bf1e96ac-83e6-4747-9f41-b969de51bec5</deliveryId>
					<partnerId>bf1e96ac-83e6-4747-9f41-b969de51bec5</partnerId>
				</id>
				<address>
					<country>Россия</country>
					<region>Москва и Московская область</region>
					<locality>Москва</locality>
					<settlement>Москва</settlement>
					<street>Проспект Мира</street>
					<house>12</house>
					<building></building>
					<housing></housing>
					<room></room>
					<zipCode>129085</zipCode>
					<lat>55.774532</lat>
					<lng>37.632745</lng>
					<locationId>213</locationId>
				</address>
				<schedule>
					<workTime>
						<day>1</day>
						<periods>
							<timeInterval>00:00:00+03:00/18:00:00+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>2</day>
						<periods>
							<timeInterval>00:00:00+03:00/23:00:00+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>3</day>
						<periods>
							<timeInterval>00:00:00+03:00/18:00:00+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>4</day>
						<periods>
							<timeInterval>00:00:00+03:00/18:00:00+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>5</day>
						<periods>
							<timeInterval>00:00:00+03:00/18:00:00+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>6</day>
						<periods>
							<timeInterval>00:00:00+03:00/18:00:00+03:00</timeInterval>
						</periods>
					</workTime>
				</schedule>
				<contact>
					<name>Дарья</name>
					<surname>Тимофеева</surname>
					<patronymic></patronymic>
				</contact>
				<phones>
					<phone>
						<phoneNumber>+79600577754</phoneNumber>
						<additional></additional>
					</phone>
				</phones>
				<instruction>Оставить у двери. Это доп.инструкции. В них смотрит курьер, и ему сразу все понятно</instruction>
			</warehouseFrom>
			<locationTo>
				<country>Россия</country>
				<federalDistrict>Центральный федеральный округ</federalDistrict>
				<region>Москва и Московская область</region>
				<locality>Москва</locality>
				<street>Сретенка</street>
				<house>14</house>
				<room>303</room>
				<zipCode>107045</zipCode>
				<intercom>007</intercom>
				<porch>404</porch>
				<floor>8</floor>
				<metro>Пражская</metro>
				<lat>55.76815715438623</lat>
				<lng>37.632232865487836</lng>
				<locationId>213</locationId>
			</locationTo>
			<weight>0.3</weight>
			<length>31</length>
			<width>11</width>
			<height>21</height>
			<cargoType>0</cargoType>
			<cargoCost>201</cargoCost>
			<assessedCost>201</assessedCost>
			<paymentMethod>2</paymentMethod>
			<tariff>Экспресс от дропшипов</tariff>
			<deliveryType>0</deliveryType>
			<deliveryCost>199</deliveryCost>
			<deliveryDate>{delivery_date}</deliveryDate>
			<deliveryInterval>19:00:00+03:00/20:00:00+03:00</deliveryInterval>
			<total>0</total>
			<amountPrepaid>400</amountPrepaid>
			<items>
				<item>
					<article>strundel.865.nk4</article>
					<name>Гель-смазка Биоритм Cosmo Vibro стимулирующий 25 г туба</name>
					<count>1</count>
					<price>201</price>
					<taxes>
						<tax>
							<type>VAT</type>
							<value>7</value>
						</tax>
					</taxes>
					<cargoTypes>
						<cargoType>490</cargoType>
						<cargoType>955</cargoType>
						<cargoType>440</cargoType>
					</cargoTypes>
					<categoryName>Интимные смазки</categoryName>
					<korobyte>
						<width>31</width>
						<height>21</height>
						<length>11</length>
						<weightGross>0.3</weightGross>
					</korobyte>
					<unitId>
						<vendorId>10782016</vendorId>
						<article>strundel.865.nk4</article>
					</unitId>
					<supplier>
						<inn>5401232103</inn>
					</supplier>
				</item>
			</items>
			<recipient>
				<fio>
					<name>первоеимя</name>
					<surname>последнееимя</surname>
					<patronymic>среднееимя</patronymic>
				</fio>
				<phones>
					<phone>
						<phoneNumber>+78887776655</phoneNumber>
					</phone>
				</phones>
				<email>ymail@y.mail</email>
			</recipient>
			<sender>
				<id>
					<yandexId>10782016</yandexId>
				</id>
				<incorporation>ООО Шакуров Дарья Дмитриевна</incorporation>
				<phones>
					<phone>
						<phoneNumber>+79600577754</phoneNumber>
					</phone>
				</phones>
				<name>Яндекс.Маркет</name>
				<legalForm>1</legalForm>
				<inn>5401232103</inn>
				<taxation>1</taxation>
				<url>pokupki.market.yandex.ru</url>
				<ogrn>1045400530647</ogrn>
			</sender>
			<warehouse>
				<id>
					<yandexId>10000998614</yandexId>
					<deliveryId>bf1e96ac-83e6-4747-9f41-b969de51bec5</deliveryId>
					<partnerId>bf1e96ac-83e6-4747-9f41-b969de51bec5</partnerId>
				</id>
				<address>
					<country>Россия</country>
					<region>Москва и Московская область</region>
					<locality>Москва</locality>
					<settlement>Москва</settlement>
					<street>Проспект Мира</street>
					<house>12</house>
					<building></building>
					<housing></housing>
					<room></room>
					<zipCode>129085</zipCode>
					<lat>55.774532</lat>
					<lng>37.632745</lng>
					<locationId>213</locationId>
				</address>
				<schedule>
					<workTime>
						<day>1</day>
						<periods>
							<timeInterval>00:00:00+03:00/18:00:00+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>2</day>
						<periods>
							<timeInterval>00:00:00+03:00/18:00:00+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>3</day>
						<periods>
							<timeInterval>00:00:00+03:00/18:00:00+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>4</day>
						<periods>
							<timeInterval>00:00:00+03:00/18:00:00+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>5</day>
						<periods>
							<timeInterval>00:00:00+03:00/18:00:00+03:00</timeInterval>
						</periods>
					</workTime>
					<workTime>
						<day>6</day>
						<periods>
							<timeInterval>00:00:00+03:00/18:00:00+03:00</timeInterval>
						</periods>
					</workTime>
				</schedule>
				<contact>
					<name>Дарья</name>
					<surname>Тимофеева</surname>
					<patronymic></patronymic>
				</contact>
				<phones>
					<phone>
						<phoneNumber>+79600577754</phoneNumber>
						<additional></additional>
					</phone>
				</phones>
				<instruction>Это доп.инструкции. В них смотрит курьер, и ему сразу все понятно</instruction>
			</warehouse>
			<services>
				<service>
					<code>
						<yandexId>CHECK</yandexId>
						<deliveryId>CHECK</deliveryId>
						<partnerId>CHECK</partnerId>
					</code>
					<isOptional>false</isOptional>
					<cost>0.0</cost>
				</service>
				<service>
					<code>
						<yandexId>DELIVERY</yandexId>
						<deliveryId>DELIVERY</deliveryId>
						<partnerId>DELIVERY</partnerId>
					</code>
					<isOptional>false</isOptional>
					<cost>0.0</cost>
					<taxes>
						<tax>
							<type>VAT</type>
							<value>7</value>
						</tax>
					</taxes>
				</service>
				<service>
					<code>
						<yandexId>INSURANCE</yandexId>
						<deliveryId>INSURANCE</deliveryId>
						<partnerId>INSURANCE</partnerId>
					</code>
					<isOptional>false</isOptional>
					<cost>0.0</cost>
				</service>
				<service>
					<code>
						<yandexId>RETURN_SORT</yandexId>
						<deliveryId>RETURN_SORT</deliveryId>
						<partnerId>RETURN_SORT</partnerId>
					</code>
					<isOptional>false</isOptional>
					<cost>0.0</cost>
				</service>
			</services>
			<comment>Оставить у двери</comment>
			<shipmentDate>2021-07-24T00:00:00+03:00</shipmentDate>
			<shipmentPointCode>bf1e96ac-83e6-4747-9f41-b969de51bec5</shipmentPointCode>
			<tags>
				<tag>ELECTRONIC_ACCEPTANCE_CERTIFICATE_REQUIRED</tag>
               <tag>EXPRESS</tag>
			</tags>
		</order>
	</request>
</root>"""


UPDATE_ORDER = """<root>
    <token>1111111111111111</token>
    <uniq>4nKodxg7DbpeHkMJGNspILr2MKbAle4o</uniq>
    <hash>4nKodxg7DbpeHkMJGNspILr2MKbAle4o</hash>
    <request type="updateOrder">
        <order>
            <orderId>
                  <yandexId>33889911</yandexId>
            <partnerId>{platform_request_id}</partnerId>
				<partnerId>bf1e96ac-83e6-4747-9f41-b969de51bec5</partnerId>
            </orderId>
            <locationFrom>
                <country>Россия</country>
                <region>Москва и Московская область</region>
                <locality>Москва</locality>
            </locationFrom>
            <locationTo>
                <country>Россия</country>
                <federalDistrict>Центральный федеральный округ</federalDistrict>
                <region>Москва и Московская область</region>
                <locality>Москва</locality>
                <street>Малые Каменщики</street>
                <house>4</house>
                <room>303</room>
                <zipCode>125047</zipCode>
                <intercom>007</intercom>
                <porch>404</porch>
                <floor>8</floor>
                <metro>Таганская</metro>
                    <lat>55.73711141054096</lat>
                    <lng>37.652103599572555</lng>
                    <locationId>213</locationId>
                </locationTo>
                <weight>1</weight>
                <length>13</length>
                <width>11</width>
                <height>12</height>
                <cargoType>0</cargoType>
                <cargoCost>1150</cargoCost>
                <assessedCost>1150</assessedCost>
                <paymentMethod>2</paymentMethod>
                <tariff>Такси и Лавки</tariff>
                <deliveryType>0</deliveryType>
                <deliveryCost>49</deliveryCost>
                <deliveryDate>2021-08-03T00:00:00+03:00</deliveryDate>
                <total>0</total>
                <amountPrepaid>1199</amountPrepaid>
                <items>
                    <item>
                        <article>217176139.alisa3p</article>
                        <name>Кукла Barbie с набором одежды, 29 см, DTF02</name>
                        <count>1</count>
                        <price>1150</price>
                        <taxes>
                            <tax>
                                <type>VAT</type>
                                <value>7</value>
                            </tax>
                        </taxes>
                        <cargoTypes>
                            <cargoType>950</cargoType>
                        </cargoTypes>
                        <categoryName>Куклы и пупсы</categoryName>
                        <korobyte>
                            <width>11</width>
                            <height>12</height>
                            <length>13</length>
                            <weightGross>1</weightGross>
                        </korobyte>
                        <unitId>
                            <vendorId>10427354</vendorId>
                            <article>217176139.alisa3p</article>
                        </unitId>
                        <supplier>
                            <inn>3327123849</inn>
                        </supplier>
                    </item>
                </items>
                <recipient>
                    <fio>
                        <name>первоеимя</name>
                        <surname>последнееимя</surname>
                        <patronymic>среднееимя</patronymic>
                    </fio>
                    <phones>
                        <phone>
                            <phoneNumber>+78887776655</phoneNumber>
                        </phone>
                    </phones>
                    <email>ymail@y.mail</email>
                    <uid>851268023</uid>
                </recipient>
                <sender>
                    <id>
                        <yandexId>431782</yandexId>
                    </id>
                    <incorporation>ООО Яндекс.Маркет</incorporation>
                    <phones>
                        <phone>
                            <phoneNumber>+74957392222</phoneNumber>
                        </phone>
                    </phones>
                    <name>Яндекс.Маркет</name>
                    <legalForm>1</legalForm>
                    <inn>7715805253</inn>
                    <taxation>1</taxation>
                    <url>pokupki.market.yandex.ru</url>
                    <ogrn>1167746491395</ogrn>
                </sender>
                <warehouse>
                    <id>
                        <yandexId>10000004403</yandexId>
                        <deliveryId>172</deliveryId>
                        <partnerId>172</partnerId>
                    </id>
                    <address>
                        <country>Россия</country>
                        <region>Московская область</region>
                        <locality>Софьино</locality>
                        <settlement>Софьино</settlement>
                        <street>территория Логистический технопарк Софьино</street>
                        <house>к1</house>
                        <building></building>
                        <housing></housing>
                        <room></room>
                        <zipCode>140126</zipCode>
                        <lat>55.499346</lat>
                        <lng>38.17672</lng>
                        <locationId>120013</locationId>
                    </address>
                    <schedule><workTime>
                        <day>1</day>
                        <periods>
                            <timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>2</day>
                        <periods>
                            <timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>3</day>
                        <periods>
                            <timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>5</day>
                        <periods>
                            <timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>6</day>
                        <periods>
                            <timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>7</day>
                        <periods>
                            <timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
                        </periods>
                    </workTime>
                </schedule>
                <contact>
                    <name>Антон</name>
                    <surname>Сачков</surname>
                </contact>
                <phones>
                    <phone>
                        <phoneNumber>+79269900526</phoneNumber>
                    </phone>
                </phones>
                <instruction>140126, Московская область, Раменский район, Софьинское сельское поселение, село Софьино, территория Логистический технопарк Софьино, к1</instruction>
            </warehouse>
            <services>
                <service>
                    <code>
                        <yandexId>CHECK</yandexId>
                        <deliveryId>CHECK</deliveryId>
                        <partnerId>CHECK</partnerId>
                    </code>
                    <isOptional>false</isOptional>
                    <cost>0.0</cost>
                </service>
                <service>
                    <code>
                        <yandexId>DELIVERY</yandexId>
                        <deliveryId>DELIVERY</deliveryId>
                        <partnerId>DELIVERY</partnerId>
                    </code>
                    <isOptional>false</isOptional>
                    <cost>0.0</cost>
                    <taxes>
                        <tax>
                            <type>VAT</type>
                            <value>7</value>
                        </tax>
                    </taxes>
                </service><service>
                <code>
                    <yandexId>INSURANCE</yandexId>
                    <deliveryId>INSURANCE</deliveryId>
                    <partnerId>INSURANCE</partnerId>
                </code>
                <isOptional>false</isOptional>
                <cost>0.0</cost>
            </service>
            <service>
                <code>
                    <yandexId>RETURN_SORT</yandexId>
                    <deliveryId>RETURN_SORT</deliveryId>
                    <partnerId>RETURN_SORT</partnerId>
                </code>
                <isOptional>false</isOptional>
                <cost>0.0</cost>
            </service>
        </services>
        <shipmentDate>2021-07-24T00:00:00+03:00</shipmentDate>
        <tags>
				<tag>ELECTRONIC_ACCEPTANCE_CERTIFICATE_REQUIRED</tag>
			</tags>
        <places>
            <place>
                <placeId>
                    <yandexId>527717</yandexId>
                    <deliveryId>32821094_KOROBKA1</deliveryId>
                    <partnerId>32821094_KOROBKA1</partnerId>
                </placeId>
                <korobyte>
                    <width>2</width>
                    <height>2</height>
                    <length>2</length>
                    <weightGross>2</weightGross>
                </korobyte>
                <partnerCodes>
                    <partnerCode>
                        <partnerId>171</partnerId>
                        <partnerCodeValue>32821094_KOROBKA1</partnerCodeValue>
                    </partnerCode>
                </partnerCodes>
            </place>
        </places>
    </order>
</request>
</root>"""

UPDATE_ONDEMAND_ORDER = """<root>
    <token>1111111111111111</token>
    <uniq>4nKodxg7DbpeHkMJGNspILr2MKbAle4o</uniq>
    <hash>4nKodxg7DbpeHkMJGNspILr2MKbAle4o</hash>
    <request type="updateOrder">
        <order>
            <orderId>
                  <yandexId>33889911</yandexId>
            <partnerId>{platform_request_id}</partnerId>
				<partnerId>bf1e96ac-83e6-4747-9f41-b969de51bec5</partnerId>
            </orderId>
            <locationFrom>
                <country>Россия</country>
                <region>Москва и Московская область</region>
                <locality>Москва</locality>
            </locationFrom>
            <locationTo>
                <country>Россия</country>
                <federalDistrict>Центральный федеральный округ</federalDistrict>
                <region>Москва и Московская область</region>
                <locality>Москва</locality>
                <street>Малые Каменщики</street>
                <house>4</house>
                <room>303</room>
                <zipCode>125047</zipCode>
                <intercom>007</intercom>
                <porch>404</porch>
                <floor>8</floor>
                <metro>Таганская</metro>
                    <lat>55.73711141054096</lat>
                    <lng>37.652103599572555</lng>
                    <locationId>213</locationId>
                </locationTo>
                <weight>1</weight>
                <length>13</length>
                <width>11</width>
                <height>12</height>
                <cargoType>0</cargoType>
                <cargoCost>1150</cargoCost>
                <assessedCost>1150</assessedCost>
                <paymentMethod>2</paymentMethod>
                <tariff>Такси и Лавки</tariff>
                <deliveryType>0</deliveryType>
                <deliveryCost>49</deliveryCost>
                <deliveryDate>2021-08-03T00:00:00+03:00</deliveryDate>
                <total>0</total>
                <amountPrepaid>1199</amountPrepaid>
                <items>
                    <item>
                        <article>217176139.alisa3p</article>
                        <name>Кукла Barbie с набором одежды, 29 см, DTF02</name>
                        <count>1</count>
                        <price>1150</price>
                        <taxes>
                            <tax>
                                <type>VAT</type>
                                <value>7</value>
                            </tax>
                        </taxes>
                        <cargoTypes>
                            <cargoType>950</cargoType>
                        </cargoTypes>
                        <categoryName>Куклы и пупсы</categoryName>
                        <korobyte>
                            <width>11</width>
                            <height>12</height>
                            <length>13</length>
                            <weightGross>1</weightGross>
                        </korobyte>
                        <unitId>
                            <vendorId>10427354</vendorId>
                            <article>217176139.alisa3p</article>
                        </unitId>
                        <supplier>
                            <inn>3327123849</inn>
                        </supplier>
                    </item>
                </items>
                <recipient>
                    <fio>
                        <name>первоеимя</name>
                        <surname>последнееимя</surname>
                        <patronymic>среднееимя</patronymic>
                    </fio>
                    <phones>
                        <phone>
                            <phoneNumber>+78887776655</phoneNumber>
                        </phone>
                    </phones>
                    <email>ymail@y.mail</email>
                    <uid>851268023</uid>
                </recipient>
                <sender>
                    <id>
                        <yandexId>431782</yandexId>
                    </id>
                    <incorporation>ООО Яндекс.Маркет</incorporation>
                    <phones>
                        <phone>
                            <phoneNumber>+74957392222</phoneNumber>
                        </phone>
                    </phones>
                    <name>Яндекс.Маркет</name>
                    <legalForm>1</legalForm>
                    <inn>7715805253</inn>
                    <taxation>1</taxation>
                    <url>pokupki.market.yandex.ru</url>
                    <ogrn>1167746491395</ogrn>
                </sender>
                <warehouse>
                    <id>
                        <yandexId>10000004403</yandexId>
                        <deliveryId>172</deliveryId>
                        <partnerId>172</partnerId>
                    </id>
                    <address>
                        <country>Россия</country>
                        <region>Московская область</region>
                        <locality>Софьино</locality>
                        <settlement>Софьино</settlement>
                        <street>территория Логистический технопарк Софьино</street>
                        <house>к1</house>
                        <building></building>
                        <housing></housing>
                        <room></room>
                        <zipCode>140126</zipCode>
                        <lat>55.499346</lat>
                        <lng>38.17672</lng>
                        <locationId>120013</locationId>
                    </address>
                    <schedule><workTime>
                        <day>1</day>
                        <periods>
                            <timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>2</day>
                        <periods>
                            <timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>3</day>
                        <periods>
                            <timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>5</day>
                        <periods>
                            <timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>6</day>
                        <periods>
                            <timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>7</day>
                        <periods>
                            <timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
                        </periods>
                    </workTime>
                </schedule>
                <contact>
                    <name>Антон</name>
                    <surname>Сачков</surname>
                </contact>
                <phones>
                    <phone>
                        <phoneNumber>+79269900526</phoneNumber>
                    </phone>
                </phones>
                <instruction>140126, Московская область, Раменский район, Софьинское сельское поселение, село Софьино, территория Логистический технопарк Софьино, к1</instruction>
            </warehouse>
            <services>
                <service>
                    <code>
                        <yandexId>CHECK</yandexId>
                        <deliveryId>CHECK</deliveryId>
                        <partnerId>CHECK</partnerId>
                    </code>
                    <isOptional>false</isOptional>
                    <cost>0.0</cost>
                </service>
                <service>
                    <code>
                        <yandexId>DELIVERY</yandexId>
                        <deliveryId>DELIVERY</deliveryId>
                        <partnerId>DELIVERY</partnerId>
                    </code>
                    <isOptional>false</isOptional>
                    <cost>0.0</cost>
                    <taxes>
                        <tax>
                            <type>VAT</type>
                            <value>7</value>
                        </tax>
                    </taxes>
                </service><service>
                <code>
                    <yandexId>INSURANCE</yandexId>
                    <deliveryId>INSURANCE</deliveryId>
                    <partnerId>INSURANCE</partnerId>
                </code>
                <isOptional>false</isOptional>
                <cost>0.0</cost>
            </service>
            <service>
                <code>
                    <yandexId>RETURN_SORT</yandexId>
                    <deliveryId>RETURN_SORT</deliveryId>
                    <partnerId>RETURN_SORT</partnerId>
                </code>
                <isOptional>false</isOptional>
                <cost>0.0</cost>
            </service>
        </services>
        <shipmentDate>2021-07-24T00:00:00+03:00</shipmentDate>
        <tags>
				<tag>ELECTRONIC_ACCEPTANCE_CERTIFICATE_REQUIRED</tag>
				    <tag>ON_DEMAND</tag>
			</tags>
        <places>
            <place>
                <placeId>
                    <yandexId>527717</yandexId>
                    <deliveryId>32821094_KOROBKA1</deliveryId>
                    <partnerId>32821094_KOROBKA1</partnerId>
                </placeId>
                <korobyte>
                    <width>2</width>
                    <height>2</height>
                    <length>2</length>
                    <weightGross>2</weightGross>
                </korobyte>
                <partnerCodes>
                    <partnerCode>
                        <partnerId>171</partnerId>
                        <partnerCodeValue>32821094_KOROBKA1</partnerCodeValue>
                    </partnerCode>
                </partnerCodes>
            </place>
        </places>
    </order>
</request>
</root>"""

CALL_COURIER = """<root>
    <token>1111111111111111</token>
    <uniq>4nKodxg7DbpeHkMJGNspILr2MKbAle4o</uniq>
    <hash>4nKodxg7DbpeHkMJGNspILr2MKbAle4o</hash>
    <request type="callCourier">
        <orderId>
  			<yandexId>32786_25</yandexId>
            <partnerId>{platform_request_id}</partnerId>
        </orderId>
        <waitingTime>1800</waitingTime>
    </request>
</root>"""

DEFERRED_COURIER = """<root>
	<token>1111111111111111</token>
	<uniq>Z8bR0kNZsTPG60a9gTXyNwz8Mf2cihJg</uniq>
	<hash>Z8bR0kNZsTPG60a9gTXyNwz8Mf2cihJg</hash>
	<request type="createOrder">
        <order>
            <orderId>
                <yandexId>{request_id}</yandexId>
            </orderId>
            <locationFrom>
                <country>Россия</country>
                <region>Москва и Московская область</region>
                <locality>Москва</locality>
                <settlement>Москва</settlement>
                <street>Кооперативная улица</street>
                <house>2к14</house>
                <lat>55.724987</lat>
                <lng>37.568081</lng>
                <locationId>213</locationId>
            </locationFrom>
            <warehouseFrom>
                <id>
                    <yandexId>10000995271</yandexId>
                    <deliveryId>53c00eb0-93fe-4371-9909-027206fead40</deliveryId>
                    <partnerId>53c00eb0-93fe-4371-9909-027206fead40</partnerId>
                </id>
                <address>
                    <country>Россия</country>
                    <region>Москва и Московская область</region>
                    <locality>Москва</locality>
                    <settlement>Москва</settlement>
                    <street>Кооперативная улица</street>
                    <house>2к14</house>
                    <lat>55.724987</lat>
                    <lng>37.568081</lng>
                    <locationId>213</locationId>
                </address>
                <schedule>
                    <workTime>
                        <day>1</day>
                        <periods>
                            <timeInterval>04:00:00+03:00/05:00:00+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>2</day>
                        <periods>
                            <timeInterval>04:00:00+03:00/05:00:00+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>3</day>
                        <periods>
                            <timeInterval>04:00:00+03:00/05:00:00+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>4</day>
                        <periods>
                            <timeInterval>04:00:00+03:00/05:00:00+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>5</day>
                        <periods>
                            <timeInterval>04:00:00+03:00/05:00:00+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>6</day>
                        <periods>
                            <timeInterval>04:00:00+03:00/05:00:00+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>7</day>
                        <periods>
                            <timeInterval>04:00:00+03:00/05:00:00+03:00</timeInterval>
                        </periods>
                    </workTime>
                </schedule>
                <contact>
                    <name>185</name>
                    <surname>Кашапов</surname>
                    <patronymic>185</patronymic>
                </contact>
                <phones>
                    <phone>
                        <phoneNumber>+79263719604</phoneNumber>
                    </phone>
                </phones>
                <instruction>Вход со стороны улицы Кооперативная. Вход слева от аптеки Горздрав. На двери вывеска
                    Яндекс.Лавка.
                </instruction>
            </warehouseFrom>
            <locationTo>
                <country>Россия</country>
                <federalDistrict>Центральный федеральный округ</federalDistrict>
                <region>Москва и Московская область</region>
                <locality>Москва</locality>
                <street>Кооперативная</street>
                <house>2</house>
                <room>1</room>
                <zipCode>119048</zipCode>
                <intercom>1</intercom>
                <porch>1</porch>
                <floor>1</floor>
                <lat>55.72533104447162</lat>
                <lng>37.56706009162497</lng>
                <locationId>213</locationId>
            </locationTo>
            <weight>1</weight>
            <length>12</length>
            <width>10</width>
            <height>11</height>
            <cargoType>0</cargoType>
            <cargoCost>890</cargoCost>
            <assessedCost>890</assessedCost>
            <paymentMethod>2</paymentMethod>
            <tariff>Тариф МК Тарный 2</tariff>
            <deliveryType>0</deliveryType>
            <deliveryCost>49</deliveryCost>
            <deliveryDate>{delivery_date}</deliveryDate>
            <deliveryInterval>14:00:00+03:00/15:00:00+03:00</deliveryInterval>
            <total>0</total>
            <amountPrepaid>939</amountPrepaid>
            <items>
                <item>
                    <article>217172403.alisa3p</article>
                    <name>Кукла Barbie Черно-белый твидовый костюм, 29 см, DWF54</name>
                    <count>1</count>
                    <price>890</price>
                    <taxes>
                        <tax>
                            <type>VAT</type>
                            <value>7</value>
                        </tax>
                    </taxes>
                    <cargoTypes>
                        <cargoType>950</cargoType>
                        <cargoType>980</cargoType>
                    </cargoTypes>
                    <categoryName>Куклы и пупсы</categoryName>
                    <korobyte>
                        <width>10</width>
                        <height>11</height>
                        <length>12</length>
                        <weightGross>1</weightGross>
                    </korobyte>
                    <unitId>
                        <vendorId>10427354</vendorId>
                        <article>217172403.alisa3p</article>
                    </unitId>
                    <supplier>
                        <inn>3327123849</inn>
                    </supplier>
                </item>
            </items>
            <recipient>
                <fio>
                    <name>первоеимя</name>
                    <surname>последнееимя</surname>
                    <patronymic>среднееимя</patronymic>
                </fio>
                <phones>
                    <phone>
                        <phoneNumber>+78887776655</phoneNumber>
                    </phone>
                </phones>
                <email>ymail@y.mail</email>
                <uid>851268023</uid>
            </recipient>
            <sender>
                <id>
                    <yandexId>431782</yandexId>
                </id>
                <incorporation>ИП Саванеев Вячеслав Владимирович</incorporation>
                <phones>
                    <phone>
                        <phoneNumber>+74957392222</phoneNumber>
                    </phone>
                </phones>
                <name>Яндекс.Маркет</name>
                <legalForm>2</legalForm>
                <inn>657145109813</inn>
                <taxation>1</taxation>
                <url>pokupki.market.yandex.ru</url>
                <ogrn>111111111111111</ogrn>
            </sender>
            <warehouse>
                <id>
                    <yandexId>10000004403</yandexId>
                    <deliveryId>172</deliveryId>
                    <partnerId>172</partnerId>
                </id>
                <address>
                    <country>Россия</country>
                    <region>Московская область</region>
                    <locality>Софьино</locality>
                    <settlement>Софьино</settlement>
                    <street>территория Логистический технопарк Софьино</street>
                    <house>к1</house>
                    <building></building>
                    <housing></housing>
                    <room></room>
                    <zipCode>140126</zipCode>
                    <lat>55.499346</lat>
                    <lng>38.17672</lng>
                    <locationId>120013</locationId>
                </address>
                <schedule>
                    <workTime>
                        <day>1</day>
                        <periods>
                            <timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>2</day>
                        <periods>
                            <timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>3</day>
                        <periods>
                            <timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>4</day>
                        <periods>
                            <timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>5</day>
                        <periods>
                            <timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>6</day>
                        <periods>
                            <timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
                        </periods>
                    </workTime>
                    <workTime>
                        <day>7</day>
                        <periods>
                            <timeInterval>00:00:00+03:00/23:59:59+03:00</timeInterval>
                        </periods>
                    </workTime>
                </schedule>
                <contact>
                    <name>Антон</name>
                    <surname>Сачков</surname>
                </contact>
                <phones>
                    <phone>
                        <phoneNumber>+79269900526</phoneNumber>
                    </phone>
                </phones>
                <instruction>140126, Московская область, Раменский район, Софьинское сельское поселение, село Софьино,
                    территория Логистический технопарк Софьино, к1
                </instruction>
            </warehouse>
            <services>
                <service>
                    <code>
                        <yandexId>CHECK</yandexId>
                        <deliveryId>CHECK</deliveryId>
                        <partnerId>CHECK</partnerId>
                    </code>
                    <isOptional>false</isOptional>
                    <cost>0.0</cost>
                </service>
                <service>
                    <code>
                        <yandexId>DELIVERY</yandexId>
                        <deliveryId>DELIVERY</deliveryId>
                        <partnerId>DELIVERY</partnerId>
                    </code>
                    <isOptional>false</isOptional>
                    <cost>0.0</cost>
                    <taxes>
                        <tax>
                            <type>VAT</type>
                            <value>7</value>
                        </tax>
                    </taxes>
                </service>
                <service>
                    <code>
                        <yandexId>INSURANCE</yandexId>
                        <deliveryId>INSURANCE</deliveryId>
                        <partnerId>INSURANCE</partnerId>
                    </code>
                    <isOptional>false</isOptional>
                    <cost>0.0</cost>
                </service>
                <service>
                    <code>
                        <yandexId>RETURN_SORT</yandexId>
                        <deliveryId>RETURN_SORT</deliveryId>
                        <partnerId>RETURN_SORT</partnerId>
                    </code>
                    <isOptional>false</isOptional>
                    <cost>0.0</cost>
                </service>
            </services>
            <shipmentDate>2021-09-15T00:00:00+03:00</shipmentDate>
            <tags>
                <tag>DEFERRED_COURIER</tag>
            </tags>
        </order>
        <restrictedData>
            <promise>test-go-offer-id</promise>
        </restrictedData>
    </request>"""
