insert into interface.expenses(
    transaction_id,
    row_index,
    accounting_date,
    client_id,
    status_code,
    dry_run,
    payment_processor
) values
('1', 1, '2022-02-01', '12345', 'IN_PROC', False, 'OEBS'),
('2', 2, '2022-02-01', '12345', 'WITHOUT_NETTING', False, 'OEBS');

insert into interface.revenues(
    transaction_id,
    row_index,
    accounting_date,
    client_id,
    status_code,
    dry_run,
    payment_processor
) values
('1', 1, '2022-02-01', '12346', 'IN_PROC', False, 'OEBS'),
('2', 2, '2022-02-01', '12346', 'WITH_NETTING', False, 'OEBS'),
('3', 3, '2022-02-01', '12347', 'SKIP_PAYOUT', False, 'OEBS');

insert into interface.payments(
    transaction_id,
    row_index,
    accounting_date,
    client_id,
    status_code,
    dry_run,
    payment_processor
) values
('1', 1, '2022-02-01', '12345', 'WITH_NETTING', True, 'YA_BANK'),
('2', 2, '2022-02-01', '12346', 'WITH_NETTING', True, 'YA_BANK');


insert into payouts.payout_batches(
    batch_id,
    type_code,
    status_code,
    client_id,
    contract_id,
    updated_at_utc,
    dry_run,
    payment_processor
) values
('1', 'PAYOUT', 'OPEN', '12348', '48', '2022-02-07T00:00:00.000000+00:00', False, 'OEBS'),
('2', 'PAYOUT', 'EXPORT_READY', '12349', '49', '2022-02-07T00:00:00.000000+00:00', False, 'OEBS'),
('3', 'DRAFT', 'OPEN', '12350', '50', '2022-02-07T00:00:00.000000+00:00', False, 'OEBS');
