#! /usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = "Zasimov Alexey"
__email__ = "zasimov-a@yandex-team.ru"

u""" Убеждаемся, что валидные файлы разбираются нормально, а
невалидные выплевывают ошибку.
"""

from wp7desktop.share.xml import parse
from wp7desktop.share.xml.parse import etree

if __name__ == "__main__":
    parse("tests-data/exports/stocks/10000.xml")
    parse("tests-data/exports/weather/10.xml")
    parse("tests-data/exports/traffic/stat.xml")
    try:
        parse("tests-data/invalid.xml")
        print "Normal result for invalid xml."
        exit(1)
    except etree.XMLSyntaxError:
        pass
