import pytest

import atlas_backend.domain.anomaly as _anomalies
from atlas_backend.internal.anomalies import change_history


@pytest.mark.parametrize(
    'anomaly_dct, old_anomaly_dct, expected_result',
    [
        (
            {
                '_id': '5e00b661954de74d8a6af7c7',
                'author': 'omnipotent_user',
                'created': 1593173520,
                'description': 'new description',
                'duty_task': 'https://st.yandex-team.ru/ATLASBACK-1527',
                'end_ts': 1593186537,
                'level': 'major',
                'losses': {'orders': -38},
                'notifications': {},
                'source': 'all',
                'start_ts': 1593181520,
                'status': 'rejected',
            },
            {
                '_id': '5e00b661954de74d8a6af7c7',
                'author': 'omnipotent_user',
                'created': 1593173520,
                'description': 'new description',
                'duty_task': 'https://st.yandex-team.ru/ATLASBACK-1527',
                'end_ts': 1593186537,
                'level': 'major',
                'losses': {'orders': -38},
                'notifications': {},
                'source': 'all',
                'start_ts': 1593181520,
                'status': 'rejected',
            },
            False,
        ),
        (
            {
                'author': 'omnipotent_user',
                'description': 'new description',
                'duty_task': 'https://st.yandex-team.ru/ATLASBACK-1527',
                'end_ts': 1593186537,
                'level': 'major',
                'source': 'all',
                'start_ts': 1593181520,
                'status': 'rejected',
            },
            {
                '_id': '5e00b661954de74d8a6af7c7',
                'author': 'omnipotent_user',
                'created': 1593173520,
                'description': 'new description',
                'duty_task': 'https://st.yandex-team.ru/ATLASBACK-1527',
                'end_ts': 1593186537,
                'level': 'major',
                'losses': {'orders': -38},
                'notifications': {},
                'source': 'all',
                'start_ts': 1593181520,
                'status': 'rejected',
            },
            False,
        ),
        (
            {
                'author': 'omnipotent_user',
                'end_ts': 1593186537,
                'level': 'major',
                'source': 'all',
                'start_ts': 1593181520,
                'status': 'rejected',
            },
            {
                '_id': '5e00b661954de74d8a6af7c7',
                'author': 'omnipotent_user',
                'created': 1593173520,
                'end_ts': 1593186537,
                'level': 'major',
                'losses': {'orders': -38},
                'notifications': {},
                'source': 'all',
                'start_ts': 1593181520,
                'status': 'rejected',
            },
            False,
        ),
        (
            {
                'author': 'omnipotent_user',
                'description': 'new description 2',
                'duty_task': 'https://st.yandex-team.ru/ATLASBACK-1527',
                'end_ts': 1593186537,
                'level': 'major',
                'source': 'all',
                'start_ts': 1593181520,
                'status': 'rejected',
            },
            {
                '_id': '5e00b661954de74d8a6af7c7',
                'author': 'omnipotent_user',
                'created': 1593173520,
                'description': 'new description',
                'duty_task': 'https://st.yandex-team.ru/ATLASBACK-1527',
                'end_ts': 1593186537,
                'level': 'major',
                'losses': {'orders': -38},
                'notifications': {},
                'source': 'all',
                'start_ts': 1593181520,
                'status': 'rejected',
            },
            True,
        ),
        (
            {
                'author': 'omnipotent_user',
                'description': 'new description',
                'end_ts': 1593186537,
                'level': 'major',
                'source': 'all',
                'start_ts': 1593181520,
                'status': 'rejected',
            },
            {
                '_id': '5e00b661954de74d8a6af7c7',
                'author': 'omnipotent_user',
                'created': 1593173520,
                'description': 'new description',
                'duty_task': 'https://st.yandex-team.ru/ATLASBACK-1527',
                'end_ts': 1593186537,
                'level': 'major',
                'losses': {'orders': -38},
                'notifications': {},
                'source': 'all',
                'start_ts': 1593181520,
                'status': 'rejected',
            },
            True,
        ),
        (
            {
                'author': 'omnipotent_user',
                'description': 'new description',
                'end_ts': 1593186537,
                'level': 'minor',
                'source': 'yango',
                'start_ts': 1593181520,
                'status': 'confirmed',
            },
            {
                '_id': '5e00b661954de74d8a6af7c7',
                'author': 'omnipotent_user',
                'created': 1593173520,
                'description': 'new description',
                'end_ts': 1593186537,
                'level': 'major',
                'losses': {'orders': -38},
                'notifications': {},
                'source': 'all',
                'start_ts': 1593181520,
                'status': 'rejected',
            },
            True,
        ),
        (
            {
                'author': 'omnipotent_user',
                'description': 'new description',
                'duty_task': 'https://st.yandex-team.ru/ATLASBACK-1527',
                'end_ts': 1593186537,
                'level': 'major',
                'source': 'lavka',
                'start_ts': 1593181520,
                'status': 'confirmed',
            },
            {
                '_id': '5e00b661954de74d8a6af7c7',
                'author': 'omnipotent_user',
                'created': 1593173520,
                'description': 'new description',
                'end_ts': 1593186537,
                'level': 'major',
                'losses': {'orders': -38},
                'notifications': {},
                'source': 'lavka',
                'start_ts': 1593181520,
                'status': 'confirmed',
            },
            True,
        ),
        (
            {
                'author': 'omnipotent_user',
                'description': 'new description',
                'duty_task': 'https://st.yandex-team.ru/ATLASBACK-1527',
                'end_ts': 1593186537,
                'start_ts': 1593181520,
                'status': 'rejected',
            },
            {
                '_id': '5e00b661954de74d8a6af7c7',
                'author': 'omnipotent_user',
                'created': 1593173520,
                'description': 'new description',
                'duty_task': 'https://st.yandex-team.ru/ATLASBACK-1527',
                'end_ts': 1593186537,
                'level': 'major',
                'losses': {'orders': -38},
                'notifications': {},
                'source': 'all',
                'start_ts': 1593181520,
                'status': 'rejected',
            },
            True,
        ),
    ],
)
def test_has_anomaly_not_changed(
        anomaly_dct, old_anomaly_dct, expected_result,
):
    anomaly = _anomalies.Anomaly.from_dict(anomaly_dct)
    old_anomaly = _anomalies.Anomaly.from_dict(old_anomaly_dct)
    result = change_history.has_anomaly_changed(
        anomaly,
        old_anomaly,
        skip_fields=['created'],
        extra_fields=['severity_level', 'order_source'],
    )
    assert result is expected_result
