INSERT INTO crm_hub.batch_sending
(
    id,
    campaign_id,
    group_id,
    filter,
    yt_table,
    yt_test_table,
    pg_table,
    state,
    processing_chunk_size,
    use_policy,
    entity_type,
    group_type,
    channel,
    channel_info,
    extra_data,
    subfilters,
    created_at,
    updated_at
)
VALUES
(
    '00000000000000000000000000000001',
    1,
    1,
    'group_1',
    '//home/segment_table',
    '//home/verification_table',
    'batch_1_1',
    'NEW',
    0,
    false,
    'driver',
    'testing',
    'legacywall',
    ('{
        "title": "wall {ext1} title",
        "text": "wall {ext2} message",
        "url": "wall {ext3} url",
        "teaser": "wall {ext3} teaser",
        "type": "newsletter",
        "format": "raw",
        "application": "taximeter",
        "channel_name": "driver_legacywall",
        "url_open_mode": "webview"
    }')::jsonb,
    ('{
        "column": "city",
         "values": [
            {"key": "city_1", "values": [{"key": "ext1", "value": "11"}, {"key": "ext2", "value": "12"}, {"key": "ext3", "value": "13"}]},
            {"key": "city_2", "values": [{"key": "ext1", "value": "21"}, {"key": "ext2", "value": "22"}, {"key": "ext3", "value": "23"}]},
            {"key": "city_3", "values": [{"key": "ext1", "value": "31"}, {"key": "ext2", "value": "32"}, {"key": "ext3", "value": "33"}]}        ]
    }')::jsonb,
    null,
    now(),
    now()
),
(
    '00000000000000000000000000000002',
    1,
    2,
    'group_2',
    '//home/segment_table',
    '//home/verification_table',
    'batch_1_2',
    'NEW',
    0,
    false,
    'driver',
    'testing',
    'push',
    ('{
        "ttl": 100,
        "code": 1300,
        "content": "push {ext1} test",
        "deeplink": "push {ext2} deeplink",
        "deeplink_title": "push {ext3} title",
        "channel_name": "driver_push",
        "collapse_key": "collapse_key"
    }')::jsonb,
    ('{
        "column": "city",
         "values": [
            {"key": "city_1", "values": [{"key": "ext1", "value": "11"}, {"key": "ext2", "value": "12"}, {"key": "ext3", "value": "13"}]},
            {"key": "city_2", "values": [{"key": "ext1", "value": "21"}, {"key": "ext2", "value": "22"}, {"key": "ext3", "value": "23"}]},
            {"key": "city_3", "values": [{"key": "ext1", "value": "31"}, {"key": "ext2", "value": "32"}, {"key": "ext3", "value": "33"}]}
        ]
    }')::jsonb,
    null,
    now(),
    now()
),
(
    '00000000000000000000000000000003',
    1,
    3,
    'group_3',
    '//home/segment_table',
    '//home/verification_table',
    'batch_1_3',
    'NEW',
    0,
    false,
    'driver',
    'testing',
    'sms',
    ('{
        "intent": "taxicrm_drivers",
        "sender": "go",
        "content": "sms {ext1} {ext2} text",
        "channel_name": "user_sms"
    }')::jsonb,
    ('{
        "column": "city",
         "values": [
            {"key": "city_1", "values": [{"key": "ext1", "value": "11"}, {"key": "ext2", "value": "12"}]},
            {"key": "city_2", "values": [{"key": "ext1", "value": "21"}, {"key": "ext2", "value": "22"}]},
            {"key": "city_3", "values": [{"key": "ext1", "value": "31"}, {"key": "ext2", "value": "32"}]}
        ]
    }')::jsonb,
    null,
    now(),
    now()
),
(
    '00000000000000000000000000000004',
    1,
    4,
    'group_4',
    '//home/segment_table',
    '//home/verification_table',
    'batch_1_4',
    'NEW',
    0,
    false,
    'driver',
    'testing',
    'sms',
    ('{
        "intent": "taxicrm_drivers",
        "sender": "go",
        "content": "sms {ext1} {ext2} text",
        "channel_name": "user_sms"
    }')::jsonb,
    ('{
        "column": "city",
         "values": [
            {"key": "city_1", "values": [{"key": "ext1", "value": "11"}, {"key": "ext2", "value": "12"}]},
            {"key": "city_2", "values": [{"key": "ext1", "value": "21"}, {"key": "ext2", "value": "22"}]},
            {"key": "city_3", "values": [{"key": "ext1", "value": "31"}, {"key": "ext2", "value": "32"}]}
        ]
    }')::jsonb,
    null,
    now(),
    now()
),
(
    '00000000000000000000000000000005',
    2,
    1,
    'group_1',
    '//home/segment_table',
    '//home/verification_table',
    'batch_2_1_testing',
    'NEW',
    0,
    false,
    'driver',
    'testing',
    'sms',
    ('{
        "intent": "taxicrm_drivers",
        "sender": "go",
        "content": "sms text",
        "channel_name": "user_sms"
    }')::jsonb,
    ('{}')::jsonb,
    null,
    now(),
    now()
),
(
    '00000000000000000000000000000006',
    2,
    1,
    'group_1',
    '//home/segment_table',
    '//home/verification_table',
    'batch_2_1_local_testing',
    'NEW',
    0,
    false,
    'driver',
    'local_testing',
    'sms',
    ('{
        "intent": "taxicrm_drivers",
        "sender": "go",
        "content": "sms text",
        "channel_name": "user_sms"
    }')::jsonb,
    ('{}')::jsonb,
    null,
    now(),
    now()
),
(
    '00000000000000000000000000000007',
    2,
    1,
    'group_1',
    '//home/segment_table',
    '//home/verification_table',
    'batch_2_1_control',
    'NEW',
    0,
    false,
    'driver',
    'control',
    'sms',
    ('{
        "intent": "taxicrm_drivers",
        "sender": "go",
        "content": "sms text",
        "channel_name": "user_sms"
    }')::jsonb,
    ('{}')::jsonb,
    null,
    now(),
    now()
),
(
    '00000000000000000000000000000008',
    2,
    1,
    'group_1',
    '//home/segment_table',
    '//home/verification_table',
    'batch_2_1_local_control',
    'NEW',
    0,
    false,
    'driver',
    'local_control',
    'sms',
    ('{
        "intent": "taxicrm_drivers",
        "sender": "go",
        "content": "sms text",
        "channel_name": "user_sms"
    }')::jsonb,
    ('{}')::jsonb,
    null,
    now(),
    now()
),
(
    '00000000000000000000000000000009',
    2,
    1,
    'group_1',
    '//home/segment_table',
    '//home/verification_table',
    'batch_2_1_global_control',
    'NEW',
    0,
    false,
    'driver',
    'global_control',
    'sms',
    ('{
        "intent": "taxicrm_drivers",
        "sender": "go",
        "content": "sms text",
        "channel_name": "user_sms"
    }')::jsonb,
    ('{}')::jsonb,
    null,
    now(),
    now()
),
(
    '00000000000000000000000000000011',
    3,
    1,
    'group_1',
    '//home/segment_table',
    '//home/verification_table',
    'batch_3_1_testing',
    'NEW',
    0,
    false,
    'user',
    'testing',
    'push',
    ('{
        "channel_name": "user_push",
        "deeplink": "push_deeplink",
        "content": "push_text"
    }')::jsonb,
    ('{}')::jsonb,
    null,
    now(),
    now()
),
(
    '00000000000000000000000000000012',
    3,
    1,
    'group_1',
    '//home/segment_table',
    '//home/verification_table',
    'batch_3_1_testing',
    'NEW',
    0,
    false,
    'user',
    'testing',
    'promo',
    ('{
        "channel_name": "user_promo", "content": "promo_id"
    }')::jsonb,
    ('{}')::jsonb,
    null,
    now(),
    now()
),
(
    '00000000000000000000000000000013',
    3,
    1,
    'group_1',
    '//home/segment_table',
    '//home/verification_table',
    'batch_3_1_testing',
    'NEW',
    0,
    false,
    'user',
    'testing',
    'sms',
    ('{
        "channel_name": "user_sms", "content": "sms_text"
    }')::jsonb,
    ('{}')::jsonb,
    null,
    now(),
    now()
),
(
    '00000000000000000000000000000014',
    4,
    1,
    'group_1',
    '//home/segment_table',
    '//home/verification_table',
    'batch_4_1',
    'NEW',
    0,
    false,
    'user',
    'testing',
    'push',
    ('{
        "channel_name": "user_push",
        "deeplink": "push_deeplink",
        "content": "push_text"
    }')::jsonb,
    ('{}')::jsonb,
    ('[{"column": "efficiency", "value": "1"}]')::jsonb,
    now(),
    now()
),
(
    '00000000000000000000000000000015',
    4,
    1,
    'group_1',
    '//home/segment_table',
    '//home/verification_table',
    'batch_4_1',
    'NEW',
    0,
    false,
    'user',
    'testing',
    'push',
    ('{
        "channel_name": "user_push",
        "deeplink": "push_deeplink",
        "content": "push_text"
    }')::jsonb,
    ('{}')::jsonb,
    ('[{"column": "efficiency", "value": "0"}]')::jsonb,
    now(),
    now()
),
(
    '00000000000000000000000000000016',
    4,
    1,
    'group_1',
    '//home/segment_table',
    '//home/verification_table',
    'batch_4_1',
    'NEW',
    0,
    false,
    'user',
    'testing',
    'push',
    ('{
        "channel_name": "user_push",
        "deeplink": "push_deeplink",
        "content": "push_text"
    }')::jsonb,
    ('{}')::jsonb,
    ('[]')::jsonb,
    now(),
    now()
),
(
    '00000000000000000000000000000017',
    5,
    1,
    'group_1',
    '//home/segment_table',
    '//home/verification_table',
    'batch_5_1',
    'NEW',
    0,
    false,
    'driver',
    'testing',
    'sms',
    ('{
        "intent": "taxicrm_drivers",
        "sender": "go",
        "content": "sms text",
        "channel_name": "driver_sms"
    }')::jsonb,
    ('{}')::jsonb,
    ('[{"column": "efficiency", "value": "1"}]')::jsonb,
    now(),
    now()
),
(
    '00000000000000000000000000000018',
    5,
    1,
    'group_1',
    '//home/segment_table',
    '//home/verification_table',
    'batch_5_1',
    'NEW',
    0,
    false,
    'driver',
    'testing',
    'sms',
    ('{
        "intent": "taxicrm_drivers",
        "sender": "go",
        "content": "sms text",
        "channel_name": "driver_sms"
    }')::jsonb,
    ('{}')::jsonb,
    ('[{"column": "efficiency", "value": "0"}]')::jsonb,
    now(),
    now()
),
(
    '00000000000000000000000000000019',
    5,
    1,
    'group_1',
    '//home/segment_table',
    '//home/verification_table',
    'batch_5_1',
    'NEW',
    0,
    false,
    'driver',
    'testing',
    'sms',
    ('{
        "intent": "taxicrm_drivers",
        "sender": "go",
        "content": "sms text",
        "channel_name": "driver_sms"
    }')::jsonb,
    ('{}')::jsonb,
    ('[]')::jsonb,
    now(),
    now()
);
