# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/maps/proto/common2/geo_object.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import geometry_pb2 as yandex_dot_maps_dot_proto_dot_common2_dot_geometry__pb2
from . import metadata_pb2 as yandex_dot_maps_dot_proto_dot_common2_dot_metadata__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yandex/maps/proto/common2/geo_object.proto',
  package='yandex.maps.proto.common2.geo_object',
  syntax='proto2',
  serialized_pb=_b('\n*yandex/maps/proto/common2/geo_object.proto\x12$yandex.maps.proto.common2.geo_object\x1a(yandex/maps/proto/common2/geometry.proto\x1a(yandex/maps/proto/common2/metadata.proto\"\xc6\x02\n\tGeoObject\x12>\n\x08metadata\x18\x01 \x03(\x0b\x32,.yandex.maps.proto.common2.metadata.Metadata\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x43\n\nbounded_by\x18\x04 \x01(\x0b\x32/.yandex.maps.proto.common2.geometry.BoundingBox\x12>\n\x08geometry\x18\x05 \x03(\x0b\x32,.yandex.maps.proto.common2.geometry.Geometry\x12\x43\n\ngeo_object\x18\x06 \x03(\x0b\x32/.yandex.maps.proto.common2.geo_object.GeoObject\x12\x0c\n\x04\x61ref\x18\x07 \x03(\t')
  ,
  dependencies=[yandex_dot_maps_dot_proto_dot_common2_dot_geometry__pb2.DESCRIPTOR,yandex_dot_maps_dot_proto_dot_common2_dot_metadata__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GEOOBJECT = _descriptor.Descriptor(
  name='GeoObject',
  full_name='yandex.maps.proto.common2.geo_object.GeoObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='yandex.maps.proto.common2.geo_object.GeoObject.metadata', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='yandex.maps.proto.common2.geo_object.GeoObject.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='yandex.maps.proto.common2.geo_object.GeoObject.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bounded_by', full_name='yandex.maps.proto.common2.geo_object.GeoObject.bounded_by', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='geometry', full_name='yandex.maps.proto.common2.geo_object.GeoObject.geometry', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='geo_object', full_name='yandex.maps.proto.common2.geo_object.GeoObject.geo_object', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aref', full_name='yandex.maps.proto.common2.geo_object.GeoObject.aref', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=495,
)

_GEOOBJECT.fields_by_name['metadata'].message_type = yandex_dot_maps_dot_proto_dot_common2_dot_metadata__pb2._METADATA
_GEOOBJECT.fields_by_name['bounded_by'].message_type = yandex_dot_maps_dot_proto_dot_common2_dot_geometry__pb2._BOUNDINGBOX
_GEOOBJECT.fields_by_name['geometry'].message_type = yandex_dot_maps_dot_proto_dot_common2_dot_geometry__pb2._GEOMETRY
_GEOOBJECT.fields_by_name['geo_object'].message_type = _GEOOBJECT
DESCRIPTOR.message_types_by_name['GeoObject'] = _GEOOBJECT

GeoObject = _reflection.GeneratedProtocolMessageType('GeoObject', (_message.Message,), dict(
  DESCRIPTOR = _GEOOBJECT,
  __module__ = 'yandex.maps.proto.common2.geo_object_pb2'
  # @@protoc_insertion_point(class_scope:yandex.maps.proto.common2.geo_object.GeoObject)
  ))
_sym_db.RegisterMessage(GeoObject)


# @@protoc_insertion_point(module_scope)
