# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/maps/proto/common2/i18n.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yandex/maps/proto/common2/i18n.proto',
  package='yandex.maps.proto.common2.i18n',
  syntax='proto2',
  serialized_pb=_b('\n$yandex/maps/proto/common2/i18n.proto\x12\x1eyandex.maps.proto.common2.i18n\"-\n\x0eLocalizedValue\x12\r\n\x05value\x18\x01 \x02(\x01\x12\x0c\n\x04text\x18\x02 \x02(\t\"9\n\x04Time\x12\r\n\x05value\x18\x01 \x02(\x03\x12\x14\n\ttz_offset\x18\x02 \x02(\x11:\x01\x30\x12\x0c\n\x04text\x18\x03 \x02(\t\"6\n\x05Money\x12\r\n\x05value\x18\x01 \x02(\x01\x12\x0c\n\x04text\x18\x02 \x02(\t\x12\x10\n\x08\x63urrency\x18\x03 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOCALIZEDVALUE = _descriptor.Descriptor(
  name='LocalizedValue',
  full_name='yandex.maps.proto.common2.i18n.LocalizedValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='yandex.maps.proto.common2.i18n.LocalizedValue.value', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='yandex.maps.proto.common2.i18n.LocalizedValue.text', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=117,
)


_TIME = _descriptor.Descriptor(
  name='Time',
  full_name='yandex.maps.proto.common2.i18n.Time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='yandex.maps.proto.common2.i18n.Time.value', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tz_offset', full_name='yandex.maps.proto.common2.i18n.Time.tz_offset', index=1,
      number=2, type=17, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='yandex.maps.proto.common2.i18n.Time.text', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=176,
)


_MONEY = _descriptor.Descriptor(
  name='Money',
  full_name='yandex.maps.proto.common2.i18n.Money',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='yandex.maps.proto.common2.i18n.Money.value', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='yandex.maps.proto.common2.i18n.Money.text', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currency', full_name='yandex.maps.proto.common2.i18n.Money.currency', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=232,
)

DESCRIPTOR.message_types_by_name['LocalizedValue'] = _LOCALIZEDVALUE
DESCRIPTOR.message_types_by_name['Time'] = _TIME
DESCRIPTOR.message_types_by_name['Money'] = _MONEY

LocalizedValue = _reflection.GeneratedProtocolMessageType('LocalizedValue', (_message.Message,), dict(
  DESCRIPTOR = _LOCALIZEDVALUE,
  __module__ = 'yandex.maps.proto.common2.i18n_pb2'
  # @@protoc_insertion_point(class_scope:yandex.maps.proto.common2.i18n.LocalizedValue)
  ))
_sym_db.RegisterMessage(LocalizedValue)

Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), dict(
  DESCRIPTOR = _TIME,
  __module__ = 'yandex.maps.proto.common2.i18n_pb2'
  # @@protoc_insertion_point(class_scope:yandex.maps.proto.common2.i18n.Time)
  ))
_sym_db.RegisterMessage(Time)

Money = _reflection.GeneratedProtocolMessageType('Money', (_message.Message,), dict(
  DESCRIPTOR = _MONEY,
  __module__ = 'yandex.maps.proto.common2.i18n_pb2'
  # @@protoc_insertion_point(class_scope:yandex.maps.proto.common2.i18n.Money)
  ))
_sym_db.RegisterMessage(Money)


# @@protoc_insertion_point(module_scope)
