INSERT INTO dispatch_buffer.dispatch_meta
    (
    id,
    user_id,
    offer_id,
    order_id,
    created,
    zone_id,
    agglomeration,
    service,
    dispatch_status,
    classes,
    first_dispatch_run,
    last_dispatch_run
    )
VALUES
    (
        1,
        'user_id_1',
        'offer_id_1',
        'order_id_1',
        NOW() - '3 minute'::interval,
        'example',
        'example_agglomeration',
        'taxi',
        'dispatched',
        '{"econom"}',
        NOW() - '30 seconds'::interval,
        NOW()
    ),
    (
        2,
        'user_id_1',
        'offer_id_2',
        'order_id_2',
        NOW() - '3 minute'::interval,
        'example',
        'example_agglomeration',
        'taxi',
        'dispatched',
        '{"econom"}',
        NOW() - '30 seconds'::interval,
        NOW()
    ),
    (
        3,
        'user_id_1',
        'offer_id_3',
        'order_id_3',
        NOW() - '3 minute'::interval,
        'example',
        'example_agglomeration',
        'taxi',
        'dispatched',
        '{"econom"}',
        NOW() - '30 seconds'::interval,
        NOW()
    ),
    (
        4,
        'user_id_1',
        'offer_id_4',
        'order_id_4',
        NOW() - '3 minute'::interval,
        'example',
        'example_agglomeration',
        'taxi',
        'dispatched',
        '{"econom"}',
        NOW() - '50 seconds'::interval,
        NOW()
    ),
    (
        5,
        'user_id_1',
        'offer_id_5',
        'order_id_5',
        NOW() - '3 minute'::interval,
        'example',
        'example_agglomeration',
        'taxi',
        'dispatched',
        '{"econom"}',
        NOW() - '50 seconds'::interval,
        NOW()
    ),
    (
        6,
        'user_id_1',
        'offer_id_6',
        'order_id_6',
        NOW() - '3 minute'::interval,
        'example',
        'example_agglomeration',
        'taxi',
        'dispatched',
        '{"econom"}',
        NOW() - '55 seconds'::interval,
        NOW()
    ),
    (
        7,
        'user_id_1',
        'offer_id_7',
        'order_id_7',
        NOW() - '3 minute'::interval,
        'example',
        'example_agglomeration',
        'taxi',
        'dispatched',
        '{"econom"}',
        NOW() - '60 seconds'::interval,
        NOW()
    ),
    (
        8,
        'user_id_1',
        'offer_id_8',
        'order_id_8',
        NOW() - '3 minute'::interval,
        'example',
        'example_agglomeration',
        'taxi',
        'dispatched',
        '{"econom"}',
        NOW() - '90 seconds'::interval,
        NOW()
    ),
    (
        9,
        'user_id_1',
        'offer_id_9',
        'order_id_9',
        NOW() - '3 minute'::interval,
        'example',
        'example_agglomeration',
        'taxi',
        'dispatched',
        '{"econom"}',
        NOW() - '90 seconds'::interval,
        NOW()
    ),
    (
        10,
        'user_id_1',
        'offer_id_10',
        'order_id_10',
        NOW() - '3 minute'::interval,
        'example',
        'example_agglomeration',
        'taxi',
        'dispatched',
        '{"econom"}',
        NOW() - '100 seconds'::interval,
        NOW()
    ),
    (
        11,
        'user_id_1',
        'offer_id_11',
        'order_id_11',
        NOW() - '3 minute'::interval,
        'example',
        'example_agglomeration',
        'taxi',
        'dispatched',
        '{"econom"}',
        NOW() - '30 seconds'::interval,
        NOW()
    );

INSERT INTO dispatch_buffer.order_meta (
    id, order_meta
) VALUES (1, '{}'::jsonb),
         (2, '{}'::jsonb),
         (3, '{}'::jsonb),
         (4, '{}'::jsonb),
         (5, '{}'::jsonb),
         (6, '{}'::jsonb),
         (7, '{}'::jsonb),
         (8, '{}'::jsonb),
         (9, '{}'::jsonb),
         (10, '{}'::jsonb),
         (11, '{}'::jsonb);
