INSERT INTO eats_orders_tracking.waybills(waybill_ref, performer_info, points, order_nrs, chained_previous_waybill_ref, waybill_revision, cargo_waybill_created_at, is_actual_waybill, waybill_resolution, created_at, updated_at)
VALUES ('waybill_ref_1',
        '{"driver_id":"driver_1", "park_id": "park_1", "name": "Super", "raw_type": "pedestrian", "type": "pedestrian", "is_hard_of_hearing": false, "car_model": "xxx", "car_number": "xxx", "personal_phone_id": "pd_123"}'::jsonb,
        '[{"id":1, "claim_id": "123", "address":{"coordinates":[1.0, 1.0]}, "type": "source", "visit_order": 1, "visit_status": "visited", "corp_client_id": "corp_111", "external_order_id":"order_1"}, {"id":2, "claim_id": "123", "address":{"coordinates":[1.0, 1.0]}, "type": "destination", "visit_order": 3, "visit_status": "pending", "corp_client_id": "corp_111", "external_order_id":"order_1"}, {"id":3, "claim_id": "456", "address":{"coordinates":[1.0, 1.0]}, "type": "source", "visit_order": 2, "visit_status": "pending", "corp_client_id": "corp_111", "external_order_id":"order_2"}, {"id":4, "claim_id": "456", "address":{"coordinates":[1.0, 1.0]}, "type": "destination", "visit_order": 4, "visit_status": "pending", "corp_client_id": "corp_111", "external_order_id":"order_2"}]'::jsonb,
        array['order_1', 'order_2']::text[],
        null, 1, '2020-10-28T00:00:00.00+00:00', TRUE, 'complete', '2020-10-27T00:00:00.00+00:00', '2020-10-27T00:00:00.00+00:00'),
       ('waybill_ref_2',
        '{"driver_id":"driver_1", "park_id": "park_1", "name": "Super", "raw_type": "pedestrian", "type": "pedestrian", "is_hard_of_hearing": false, "car_model": "xxx", "car_number": "xxx", "personal_phone_id": "pd_123"}'::jsonb,
        '[{"id":3, "claim_id": "789", "address":{"coordinates":[1.0, 1.0]}, "type": "source", "visit_order": 2, "visit_status": "pending", "corp_client_id": "corp_111", "external_order_id":"order_3"},{"id":4, "claim_id": "789", "address":{"coordinates":[1.0, 1.0]}, "type": "destination", "visit_order": 4, "visit_status": "pending", "corp_client_id": "corp_111", "external_order_id":"order_3"}]'::jsonb,
        array['order_3']::text[], 'waybill_ref_1', 1, '2020-10-28T00:00:00.00+00:00', TRUE, 'complete', '2020-10-27T12:00:00.00+00:00', '2020-10-27T12:00:00.00+00:00');
