INSERT INTO taxi_db_postgres_atlas_backend.geo_presets (ru_name,
                                                        en_name,
                                                        ru_description,
                                                        en_description,
                                                        hierarchy_type,
                                                        node_ids,
                                                        default_agg_method,
                                                        preset_type,
                                                        created_by,
                                                        created_at,
                                                        changed_by,
                                                        changed_at)
VALUES ( -- preset_id = 1
           'Тестовый пресет 1',
           'Test preset 1',
           'Некое подробное описание',
           'Detailed description',
           'br',
           ARRAY ['br_kolpino', 'br_saintpetersburg'],
           'agglomeration',
           'private',
           'test_user1',
           '2022-05-10 10:12:13',
           'test_user1',
           '2022-05-10 10:12:13'),
       ( -- preset_id = 2
           'Тестовый пресет 2',
           'Test preset 2',
           'Некое подробное описание',
           'Detailed description',
           'br',
           ARRAY ['br_kolpino'],
           'agglomeration',
           'private',
           'test_user2',
           '2022-05-10 10:15:07',
           'test_user2',
           '2022-05-10 10:15:07'),
       ( -- preset_id = 3
           'Тестовый пресет 3',
           'Test preset 3',
           'Некое подробное описание',
           'Detailed description',
           'br',
           ARRAY ['br_kolpino'],
           'agglomeration',
           'public',
           'omnipotent_user',
           '2022-05-10 10:17:42',
           'omnipotent_user',
           '2022-05-10 10:17:42'),
       ( -- preset_id = 4
           'Тестовый пресет 4',
           'Test preset 4',
           'Некое подробное описание',
           'Detailed description',
           'br',
           ARRAY ['br_moscow', 'br_leningradskaja_obl'],
           'agglomeration',
           'public',
           'omnipotent_user',
           '2022-05-10 10:26:23',
           'omnipotent_user',
           '2022-05-10 10:26:23')
;
