INSERT INTO driver_work_rules.work_rules (
    park_id,
    id,
    idempotency_token,
    commission_for_driver_fix_percent,
    commission_for_subvention_percent,
    commission_for_workshift_percent,
    is_archived,
    is_commission_if_platform_commission_is_null_enabled,
    is_commission_for_orders_cancelled_by_client_enabled,
    is_default,
    is_driver_fix_enabled,
    is_dynamic_platform_commission_enabled,
    is_enabled,
    is_workshift_enabled,
    name,
    type,
    created_at,
    updated_at
)
VALUES
(
    'park_id1',
    'work_rule_id1',
    NULL,
    12.35,
    3.21,
    14.3,
    false,
    true,
    true,
    false,
    false,
    true,
    true,
    true,
    'Name',
    'park',
    '2019-02-14 11:48:33.644361',
    '2020-02-14 11:48:33.644361'
), (
    'park_id1',
    'work_rule_id_without_calc_entries',
    NULL,
    12.35,
    3.21,
    14.3,
    false,
    true,
    true,
    false,
    false,
    true,
    true,
    true,
    'Name',
    'park',
    '2019-02-14 11:48:33.644361',
    '2020-02-14 11:48:33.644361'
);
