INSERT INTO bank_applications.applications (application_id,
                                            user_id_type,
                                            user_id,
                                            type,
                                            status,
                                            reason,
                                            multiple_success_status_allowed,
                                            initiator,
                                            additional_params)
VALUES ('7948e3a9-623c-4524-1111-9e4264d27a01',
        'BUID',
        'buid_1',
        'CHANGE_PHONE',
        'PROCESSING',
        '',
        FALSE,
        '{}'::jsonb,
        '{
          "core_request_id": "some_core_request_id"
        }'::jsonb),
       ('7948e3a9-623c-4524-1111-9e4264d27a02',
        'BUID',
        'buid_2',
        'CHANGE_PHONE',
        'PROCESSING',
        '',
        FALSE,
        '{}'::jsonb,
        NULL);

INSERT INTO bank_applications.change_phone_applications (application_id,
                                                         buid,
                                                         new_phone_id,
                                                         old_phone_id,
                                                         status,
                                                         validation_type,
                                                         chatterbox_id,
                                                         comment,
                                                         initiator,
                                                         create_idempotency_token,
                                                         submitted_form,
                                                         new_phone_track_id,
                                                         old_phone_track_id,
                                                         operation_type)
VALUES ('7948e3a9-623c-4524-1111-9e4264d27a01',
        'buid_1',
        'phone_id_2',
        'phone_id_1',
        'PROCESSING',
        'REGULAR',
        'FTB-1313',
        '',
        '{"initiator_id": "previous_support", "initiator_type": "SUPPORT"}'::jsonb,
        'cc5b512c-72ee-4cce-a460-9248ab3791e1',
        '{"buid": "67754336-d4d1-43c1-aadb-cabd06674ea6",
          "new_phone": "+79995556677",
          "reason": "REGULAR"}'::jsonb,
        '',
        '',
        'INSERT'
       ),
       ('7948e3a9-623c-4524-1111-9e4264d27a02',
        'buid_2',
        'phone_id_2',
        'phone_id_1',
        'PROCESSING',
        'REGULAR',
        'FTB-1313',
        '',
        '{"initiator_id": "support-abc", "initiator_type": "SUPPORT"}'::jsonb,
        'cc5b512c-72ee-4cce-a460-9248ab3791e1',
        '{"buid": "67754336-d4d1-43c1-aadb-cabd06674ea6",
          "new_phone": "+79995556677",
          "reason": "REGULAR"}'::jsonb,
        '',
        '',
        'INSERT'
       )
