DATA(
    arcadia/smart_devices/platforms/jbl_link/music/data/launch.json
    arcadia/smart_devices/platforms/jbl_link/portable/data/launch.json
    arcadia/smart_devices/platforms/saturn/data/launch.json
    arcadia/smart_devices/platforms/yandexmini/data/launch.json
    arcadia/smart_devices/platforms/yandexstation/data/launch.json
    arcadia/smart_devices/platforms/yandexstation_2/data/launch.json
)
