#!/usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = "Zasimov Alexey"
__email__ = "zasimov-a@yandex-team.ru"

u"""
с
"""

from wp7desktop.share.graphics.cairo import image, set_font
import os
import tempfile


if __name__ == "__main__":
    fd, tmp = tempfile.mkstemp()
    try:
        os.close(fd)
        i, ctx = image(2000, 2000)
        ctx.move_to(10, 500)
        set_font(ctx, "fonts/SegoeWP-Light.ttf", 72)
        ctx.show_text("This is sample SegoeWP-Light.")
        set_font(ctx, "fonts/SegoeWP.ttf", 72)
        ctx.show_text("This is sample SegoeWP.")
        ctx.move_to(10, 1000)
        set_font(ctx, "fonts/SegoeWP-Light.ttf", 92)
        ctx.show_text("This is sample SegoeWP-Light.")
        set_font(ctx, "fonts/SegoeWP.ttf", 92)
        ctx.show_text("This is sample SegoeWP.")
        i.write_to_png(tmp)
        #os.system("open %s" % tmp)
    finally:
        os.unlink(tmp)
