#!/usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = "Zasimov Alexey"
__email__ = "zasimov-a@yandex-team.ru"

u"""
Тестируем все нужные нам cairo-операции.
"""

from wp7desktop.share.graphics.cairo import image, set_font

if __name__ == "__main__":
    i, ctx = image(500, 500)
    set_font(ctx, "fonts/SegoeWP.ttf", 72)
    ctx.move_to(10, 10)
    ctx.line_to(40, 40)
    ctx.set_source_rgba(1.0, 1.0, 0.0, 0.0)
    ctx.rectangle (5, 5, 10, 10)
    ctx.show_text("This is good.")
    del i
    del ctx

