#!/usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = "Zasimov Alexey"
__email__ = "zasimov-a@yandex-team.ru"

u"""
Картинки должны создаваться! Проверяем, что это так.
"""

from wp7desktop.share.graphics.cairo import image
import os
import tempfile


if __name__ == "__main__":
    fd, tmp = tempfile.mkstemp()
    try:
        os.close(fd)
        i, ctx = image(1, 1)
        i.write_to_png(tmp)
        i, ctx = image(100, 100)
        i.write_to_png(tmp)
        i, ctx = image(2000, 2000)
        i.write_to_png(tmp)
    finally:
        os.unlink(tmp)

