INSERT INTO price_modifications.rules
  (rule_id, name, source_code, policy, author, approvals_id, ast)
VALUES
  (1, 'return_time',         'return concat({metadata=["dummy": 42]}, ride.price * (trip.time / *ride.price));', 'both_side', '200ok',   16, 'E("dummy",42);CR(boarding=B(B(B(B(trip,.,F(time)),/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(boarding)),distance=B(B(B(B(trip,.,F(time)),/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(distance)),time=B(B(B(B(trip,.,F(time)),/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(time)),waiting=B(B(B(B(trip,.,F(time)),/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(waiting)),requirements=B(B(B(B(trip,.,F(time)),/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(requirements)),transit_waiting=B(B(B(B(trip,.,F(time)),/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(transit_waiting)),destination_waiting=B(B(B(B(trip,.,F(time)),/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(destination_waiting)))'),
  (2, 'return_price',        'return ride.price;', 'both_side', '200ok',   17, 'CR(boarding=B(B(ride,.,F(price)),.,F(boarding)),distance=B(B(ride,.,F(price)),.,F(distance)),time=B(B(ride,.,F(price)),.,F(time)),waiting=B(B(ride,.,F(price)),.,F(waiting)),requirements=B(B(ride,.,F(price)),.,F(requirements)),transit_waiting=B(B(ride,.,F(price)),.,F(transit_waiting)),destination_waiting=B(B(ride,.,F(price)),.,F(destination_waiting)))'),
  (3, 'base_price_discount', 'if (fix.base_price_discount as bpd) { if (bpd.boarding_discount >= 0 && bpd.boarding_discount <= 1 && bpd.distance_discount >= 0 && bpd.distance_discount <= 1 && bpd.time_discount >= 0 && bpd.time_discount <= 1) { return { boarding = ride.price.boarding * (1 - bpd.boarding_discount), distance = ride.price.distance * (1 - bpd.distance_discount), time = ride.price.time * (1 - bpd.time_discount) }; } } return ride.price;', 'both_side', 'ioann-v', 18, 'IF(U(?,B(fix,.,F(base_price_discount))),CR(boarding=B(B(B(ride,.,F(price)),.,F(boarding)),*,B(1.000000,-,B(U(*,B(fix,.,F(base_price_discount))),.,F(boarding_discount)))),distance=B(B(B(ride,.,F(price)),.,F(distance)),*,B(1.000000,-,B(U(*,B(fix,.,F(base_price_discount))),.,F(distance_discount)))),time=B(B(B(ride,.,F(price)),.,F(time)),*,B(1.000000,-,B(U(*,B(fix,.,F(base_price_discount))),.,F(time_discount))))));CR(boarding=B(B(ride,.,F(price)),.,F(boarding)),distance=B(B(ride,.,F(price)),.,F(distance)),time=B(B(ride,.,F(price)),.,F(time)),waiting=B(B(ride,.,F(price)),.,F(waiting)),requirements=B(B(ride,.,F(price)),.,F(requirements)),transit_waiting=B(B(ride,.,F(price)),.,F(transit_waiting)),destination_waiting=B(B(ride,.,F(price)),.,F(destination_waiting)))')
;


INSERT INTO price_modifications.rules_drafts
  (rule_id, name, source_code, policy, author, ast, evaluate_on_prestable, prestable_evaluation_begin_time)
VALUES
  (4, 'run_on_pre_draft', 'return concat({metadata=["dummy": 42]}, ride.price * (trip.time / *ride.price));', 'both_side', '200ok', 'E("dummy",42);CR(boarding=B(B(B(B(trip,.,F(time)),/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(boarding)),distance=B(B(B(B(trip,.,F(time)),/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(distance)),time=B(B(B(B(trip,.,F(time)),/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(time)),waiting=B(B(B(B(trip,.,F(time)),/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(waiting)),requirements=B(B(B(B(trip,.,F(time)),/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(requirements)),transit_waiting=B(B(B(B(trip,.,F(time)),/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(transit_waiting)),destination_waiting=B(B(B(B(trip,.,F(time)),/,U(*,B(ride,.,F(price)))),*,B(ride,.,F(price))),.,F(destination_waiting)))', true, null)
;
