import datetime

import pytest


@pytest.mark.parametrize(
    ['client_id', 'put_data', 'expected_result', 'status_code'],
    [
        pytest.param(
            'trial',
            {
                'company_name': 'can change it',
                'country': 'rus',
                'city': 'Москва',
                'contact_name': 'will not change',
                'contact_phone': '+7 (901) 111-11-11',
                'contact_emails': ['example@yandex.ru'],
                'contract_by_proxy': False,
                'enterprise_name_full': 'example',
                'enterprise_name_short': 'example',
                'legal_address': 'Москва;115222;Москворечье;2к2',
                'legal_address_info': {
                    'city': 'Москва',
                    'post_index': '115222',
                    'street': 'Москворечье',
                    'house': '2к2',
                },
                'mailing_address': 'Москва;115222;Москворечье;2к2',
                'mailing_address_info': {
                    'city': 'Москва',
                    'post_index': '115222',
                    'street': 'Москворечье',
                    'house': '2к2',
                },
                'company_tin': '500100732259',
                'bank_bic': '044525225',
                'bank_name': 'Банк',
                'yandex_login': 'example',
                'processing_agreement': True,
                'offer_agreement': True,
                'promo_id': 'I\'m google click ID',
                'signer_gender': 'female',
                'client_id': 'not_allowed',
                'blah': 'blah1',
                'company_registration_date': None,  # erasing field
                'bank_account_number': None,  # erasing field
                'autofilled_fields': ['lol', 'kek'],
                'references': {},
                'services': ['taxi', 'eats2', 'drive', 'tanker'],
                'is_without_vat_allowed': True,
            },
            {
                '_id': 'draft',
                'country': 'rus',
                'contact_name': 'trial_name',
                'company_name': 'can change it',
                'contact_phone': '+79011111111',
                'contact_emails': ['example@yandex.ru'],
                'contact_emails_ids': ['example_email_pd_id'],
                'contact_phone_id': 'phone_pd_id_1',
                'yandex_login': 'trial_login2',
                'yandex_login_id': 'trial_login_id2',
                'client_id': 'trial',
                'bank_bic': '044525225',
                'bank_name': 'Банк',
                'city': 'Москва',
                'company_tin': '500100732259',
                'company_tin_id': 'tin_pd_id',
                'contract_by_proxy': False,
                'enterprise_name_full': 'example',
                'enterprise_name_short': 'example',
                'legal_address': 'Москва;115222;Москворечье;2к2',
                'legal_address_info': {
                    'city': 'Москва',
                    'post_index': '115222',
                    'street': 'Москворечье',
                    'house': '2к2',
                },
                'mailing_address': 'Москва;115222;Москворечье;2к2',
                'mailing_address_info': {
                    'city': 'Москва',
                    'post_index': '115222',
                    'street': 'Москворечье',
                    'house': '2к2',
                },
                'processing_agreement': True,
                'offer_agreement': True,
                'promo_id': 'I\'m google click ID',
                'signer_gender': 'female',
                'autofilled_fields': ['lol', 'kek'],
                'references': {'utm': 'val'},
                'contract_type': 'taxi',
                'enterprise_name': '',
                'legal_form': '',
                'signer_name': '',
                'signer_position': '',
                'bank_account_number': '',
                'company_cio': '',
                'proxy_scan': '',
                'services': ['taxi', 'eats2', 'drive', 'tanker'],
                'without_vat_contract': False,
                'is_without_vat_allowed': True,
            },
            200,
            id='1',
        ),
        pytest.param(
            'trial',
            {
                'country': 'rus',
                'city': 'Москва',
                'contact_name': 'will not change',
                'contact_phone': '+7 (901) 111-11-11',
                'contact_emails': ['example@yandex.ru'],
                'contract_by_proxy': True,
                'company_name': 'trial_company',
                'bank_account_number': '40702810638050013199',
                'proxy_scan': 'string_to_be_decoded_using_base_64',
                'without_vat_contract': True,
            },
            {
                '_id': 'draft',
                'country': 'rus',
                'city': 'Москва',
                'contact_name': 'trial_name',
                'company_name': 'trial_company',
                'contact_phone': '+79011111111',
                'contact_emails': ['example@yandex.ru'],
                'contact_emails_ids': ['example_email_pd_id'],
                'contact_phone_id': 'phone_pd_id_1',
                'yandex_login': 'trial_login2',
                'yandex_login_id': 'trial_login_id2',
                'client_id': 'trial',
                'contract_by_proxy': True,
                'proxy_scan': 'key',
                'bank_account_number': '40702810638050013199',
                'references': {'utm': 'val'},
                'contract_type': 'without_vat',
                'enterprise_name': '',
                'enterprise_name_full': '',
                'enterprise_name_short': '',
                'legal_form': '',
                'signer_name': '',
                'signer_position': '',
                'bank_bic': '',
                'bank_name': '',
                'company_cio': '',
                'company_tin': '',
                'legal_address': '',
                'mailing_address': '',
                'promo_id': '',
                'draft_status': 'filled',
                'without_vat_contract': True,
            },
            200,
            id='proxy_scan draft',
        ),
        pytest.param(
            'triax',
            {
                'company_name': 'name',
                'country': 'rus',
                'contact_name': 'will not change',
                'contact_phone': '+7 (901) 111-11-11',
                'contact_emails': ['example@yandex.ru'],
                'contract_by_proxy': False,
                'proxy_scan': None,
                'city': None,
            },
            {
                '_id': 'bzdraft',
                'country': 'rus',
                'contact_name': 'mr.Anderson Jr.',
                'company_name': 'name',
                'contact_phone': '+79011111111',
                'contact_emails_ids': ['example_email_pd_id'],
                'contact_phone_id': 'phone_pd_id_1',
                'yandex_login': 'bzdraft_login',
                'yandex_login_id': 'bzdraft_login_id',
                'client_id': 'triax',
                'contract_by_proxy': False,
                'city': '',
                'enterprise_name': '',
                'enterprise_name_full': '',
                'enterprise_name_short': '',
                'legal_form': '',
                'signer_name': '',
                'signer_position': '',
                'bank_account_number': '',
                'bank_bic': '',
                'bank_name': '',
                'company_cio': '',
                'company_tin': '',
                'legal_address': '',
                'mailing_address': '',
                'promo_id': '',
                'proxy_scan': '',
                'draft_status': 'filled',
                'without_vat_contract': False,
            },
            200,
            id='erase fields',
        ),
        pytest.param(
            'incomplete_isr_draft',
            {
                'client_id': 'incomplete_isr_draft',
                'autofilled_fields': ['enterprise_name_full'],
                'references': {},
                'city': 'Тель Авив',
                'company_name': 'Isr company_name',
                'contract_type': 'taxi',
                'contact_emails': ['engineer@yandex-team.ru'],
                'contact_name': 'Василий',
                'contact_phone': '+79263452242',
                'country': 'isr',
                'legal_address_info': {
                    'city': 'Tel Aviv',
                    'house': '1',
                    'post_index': '12345',
                    'street': 'street1',
                },
                'enterprise_name_full': 'UPDATED',
                'registration_number': '502901001',
                'company_tin': '559017555',
                'yandex_login': 'incomplete_isr_draft',
                'services': ['taxi'],
                'created': '2019-11-12T11:49:33.368000+03:00',
                'updated': '2019-11-12T11:49:33.368000+03:00',
            },
            {
                '_id': 'incomplete_isr_draft',
                'city': 'Тель Авив',
                'client_id': 'incomplete_isr_draft',
                'company_name': 'Isr company_name',
                'company_tin': '559017555',
                'company_tin_id': 'full_isr_draft_tin_id',
                'contact_emails': ['engineer@yandex-team.ru'],
                'contact_emails_ids': ['engineer_id'],
                'autofilled_fields': ['enterprise_name_full'],
                'contact_name': 'Василий',
                'contact_phone': '+79263452242',
                'contact_phone_id': 'pd_id1',
                'contract_type': 'taxi',
                'country': 'isr',
                'enterprise_name_full': 'UPDATED',
                'legal_address_info': {
                    'city': 'Tel Aviv',
                    'house': '1',
                    'post_index': '12345',
                    'street': 'street1',
                },
                'references': {},
                'registration_number': '502901001',
                'yandex_login': 'incomplete_isr_draft',
                'yandex_login_id': 'incomplete_isr_draft_id',
                'enterprise_name_short': '',
                'legal_form': '',
                'signer_name': '',
                'signer_position': '',
                'services': ['taxi'],
            },
            200,
            id='isr update',
        ),
    ],
)
@pytest.mark.config(TVM_RULES=[{'dst': 'personal', 'src': 'corp-requests'}])
async def test_client_put_client_request_draft(
        mock_mds,
        mock_personal,
        web_app_client,
        db,
        client_id,
        put_data,
        expected_result,
        status_code,
):
    response = await web_app_client.put(
        '/v1/client-request-draft',
        params={'client_id': client_id},
        json=put_data,
    )
    assert response.status == status_code
    response_json = await response.json()
    assert response_json == {}

    draft = await db.corp_client_request_drafts.find_one(
        {'client_id': client_id},
    )
    assert isinstance(draft.get('created'), datetime.datetime)
    assert isinstance(draft.get('updated'), datetime.datetime)
    assert draft['updated'] >= draft['created']

    del draft['updated']
    del draft['created']
    reg_date = draft.pop('company_registration_date', None)
    if reg_date:
        assert isinstance(reg_date, datetime.datetime)

    assert draft == expected_result


@pytest.mark.parametrize(
    ['client_id', 'result', 'status_code', 'test_pd_retrieve'],
    [
        pytest.param(
            'triad',
            {
                'client_id': 'triad',
                'contact_name': 'mr.Anderson Jr.',
                'country': 'rus',
                'contact_phone': '+79263452243',
                'yandex_login': 'sraft_login',
                'bank_account_number': '40702810638050013199',
                'bank_bic': '044525225',
                'bank_name': 'Банк',
                'city': 'Москва',
                'company_cio': '770501001',
                'company_name': 'name',
                'company_ogrn': '1027717009275',
                'company_tin': '500100732259',
                'contact_emails': ['example@yandex.ru'],
                'contract_by_proxy': False,
                'enterprise_name': 'ООО "ЯНДЕКС.ТАКСИ"',
                'enterprise_name_full': 'example',
                'enterprise_name_short': 'example',
                'legal_address': 'Москва;115222;Москворечье;2к2',
                'legal_address_info': {
                    'city': 'Москва',
                    'post_index': '115222',
                    'street': 'Москворечье',
                    'house': '2к2',
                },
                'legal_form': 'Общество с ограниченной ответственностью',
                'mailing_address': 'Москва;115222;Москворечье;2к2',
                'mailing_address_info': {
                    'city': 'Москва',
                    'post_index': '115222',
                    'street': 'Москворечье',
                    'house': '2к2',
                },
                'offer_agreement': True,
                'processing_agreement': True,
                'signer_name': 'Шулейко Даниил Владимирович',
                'signer_position': 'ГЕНЕРАЛЬНЫЙ ДИРЕКТОР',
                'signer_gender': 'male',
                'proxy_scan': (
                    'http://mds.yandex.net/get-taxi/group/key?sign=sign'
                ),
                'references': {'utm': 'utm_val', 'promo_id': 'click ID'},
                'company_registration_date': (
                    '2010-01-01T15:20:09.160000+03:00'
                ),
                'contract_type': 'taxi',
                'autofilled_fields': [
                    'legal_address',
                    'signer_name',
                    'signer_position',
                    'company_tin',
                    'company_cio',
                    'company_ogrn',
                    'legal_form',
                    'company_registration_date',
                    'enterprise_name',
                ],
                'services_to_show': ['taxi'],
                'created': '2018-04-11T15:20:09.160000+03:00',
                'updated': '2018-04-12T15:20:09.160000+03:00',
                'promo_id': '',
                'services': ['taxi', 'eats2', 'drive', 'tanker'],
                'without_vat_contract': False,
            },
            200,
            False,
        ),
        pytest.param(
            'bzdrial',
            {
                'client_id': 'bzdrial',
                'country': 'rus',
                'contract_type': 'taxi',
                'contact_phone': '+79011111111',
                'contact_emails': ['lol@yandex.ru'],
                'contact_name': 'trial_name',
                'company_name': 'trial_company',
                'yandex_login': 'trial_login',
                'created': '2018-04-19T15:20:09.160000+03:00',
                'updated': '2018-04-20T15:20:09.160000+03:00',
                'references': {},
                'autofilled_fields': [],
                'bank_account_number': '',
                'bank_bic': '',
                'bank_name': '',
                'city': '',
                'company_cio': '',
                'company_tin': '',
                'enterprise_name': '',
                'enterprise_name_full': '',
                'enterprise_name_short': '',
                'legal_address': '',
                'legal_form': '',
                'mailing_address': '',
                'promo_id': '',
                'proxy_scan': '',
                'services_to_show': ['taxi'],
                'signer_position': '',
                'signer_name': '',
                'without_vat_contract': False,
            },
            200,
            True,
        ),
        pytest.param(
            'full_isr_draft',
            {
                'client_id': 'full_isr_draft',
                'autofilled_fields': [],
                'references': {},
                'legal_form': 'isr-legal-form',
                'city': 'Тель Авив',
                'company_name': 'Isr company_name',
                'contract_type': 'taxi',
                'contact_emails': ['engineer@yandex-team.ru'],
                'contact_name': 'Василий',
                'contact_phone': '+79263452242',
                'country': 'isr',
                'enterprise_name_short': 'example_short',
                'enterprise_name_full': 'example',
                'legal_address_info': {
                    'city': 'Tel Aviv',
                    'house': '1',
                    'post_index': '12345',
                    'street': 'street1',
                },
                'mailing_address_info': {
                    'city': 'Tel Aviv',
                    'house': '1',
                    'post_index': '12345',
                    'street': 'street2',
                },
                'registration_number': '502901001',
                'offer_agreement': True,
                'processing_agreement': True,
                'company_tin': '559017555',
                'yandex_login': 'full_isr_draft',
                'services_to_show': ['taxi'],
                'signer_name': 'signer_name_isr',
                'signer_position': 'signer_position_isr',
                'signer_gender': 'female',
                'created': '2019-11-12T11:49:33.368000+03:00',
                'updated': '2019-11-12T11:49:33.368000+03:00',
                'draft_status': 'filled',
                'services': ['taxi'],
            },
            200,
            True,
        ),
        pytest.param(
            'incomplete_isr_draft',
            {
                'client_id': 'incomplete_isr_draft',
                'autofilled_fields': [],
                'references': {},
                'city': 'Тель Авив',
                'company_name': 'Isr company_name',
                'contract_type': 'taxi',
                'contact_emails': ['engineer@yandex-team.ru'],
                'contact_name': 'Василий',
                'contact_phone': '+79263452242',
                'country': 'isr',
                'legal_address_info': {
                    'city': 'Tel Aviv',
                    'house': '1',
                    'post_index': '12345',
                    'street': 'street1',
                },
                'registration_number': '502901001',
                'company_tin': '1503009017',
                'yandex_login': 'incomplete_isr_draft',
                'created': '2019-11-12T11:49:33.368000+03:00',
                'updated': '2019-11-12T11:49:33.368000+03:00',
                'enterprise_name_short': '',
                'legal_form': '',
                'services_to_show': ['taxi'],
                'signer_name': '',
                'signer_position': '',
                'enterprise_name_full': '',
            },
            200,
            True,
        ),
        pytest.param(
            'multi_isr_draft',
            {
                'client_id': 'multi_isr_draft',
                'autofilled_fields': [],
                'references': {},
                'legal_form': 'isr-legal-form',
                'city': 'Тель Авив',
                'company_name': 'Isr company_name',
                'contract_type': 'multi',
                'contact_emails': ['engineer@yandex-team.ru'],
                'contact_name': 'Василий',
                'contact_phone': '+79263452242',
                'country': 'isr',
                'enterprise_name_short': 'example_short',
                'enterprise_name_full': 'example',
                'legal_address_info': {
                    'city': 'Tel Aviv',
                    'house': '1',
                    'post_index': '12345',
                    'street': 'street1',
                },
                'mailing_address_info': {
                    'city': 'Tel Aviv',
                    'house': '1',
                    'post_index': '12345',
                    'street': 'street2',
                },
                'registration_number': '502901001',
                'offer_agreement': True,
                'processing_agreement': True,
                'company_tin': '559017555',
                'yandex_login': 'multi_isr_draft',
                'services_to_show': ['taxi', 'cargo'],
                'signer_name': 'signer_name_isr',
                'signer_position': 'signer_position_isr',
                'signer_gender': 'female',
                'created': '2019-11-12T11:49:33.368000+03:00',
                'updated': '2019-11-12T11:49:33.368000+03:00',
                'draft_status': 'filled',
                'services': ['taxi'],
            },
            200,
            True,
        ),
    ],
)
@pytest.mark.config(CORP_READ_PD_CONDITION='kek')
@pytest.mark.config(TVM_RULES=[{'dst': 'personal', 'src': 'corp-requests'}])
async def test_client_get_client_request_draft(
        client_id,
        mock_mds,
        mock_personal,
        web_app_client,
        db,
        result,
        status_code,
        test_pd_retrieve,
):
    response = await web_app_client.get(
        '/v1/client-request-draft', params={'client_id': client_id},
    )
    assert response.status == status_code
    response_json = await response.json()
    assert response_json == result
